### PR TITLE
Feature Request : I Created a small PCL java wrapper using swig‏

### PR DESCRIPTION
**Pull request by RemonComputer**
- Open this link to Know the details
  http://www.pcl-developers.org/I-Created-a-small-PCL-java-wrapper-using-swig-td5709158.html
- I only Added Java folder
- what is my next step ? [I know i will continue  developing the wrapper , Is there any Github steps or any other steps ?]

### CODE REVIEW

**Comment by RemonComputer** [comment]
well it's a very long time since you replied,
Sorry for my late reply,
I didn't have the intention to support that for along time (for the time being),
My intention was to make a prototype and the PCL community may continue the work after me.

**Comment by osblinnikov** [comment]
Too bad because I also think that would be great to have.

**Comment by jspricke** [comment]
Hey Oleg, maybe you want to help maintaining it?

**Comment by osblinnikov** [comment]
Probably. I need to sleep over with it. )

**Comment by taketwo** [comment]
As far as I can see, this wrapper requires no modifications to the PCL itself and is well localized in a separate "java" folder. In my opinion, this qualifies it to be a stand-alone project with it's own repository. Therefore, anyone interested can create and maintain it. If it gains momentum and we see people using it, we can always adopt it under PointCloudLibrary organization.

**Pull request closed without merging**
