### PR TITLE
Moves UniformSampling to filters, it's not a Keypoint

### PR DESCRIPTION
**Pull request by fran6co**
Fixes https://github.com/PointCloudLibrary/pcl/issues/1404

### CODE REVIEW

**Comment by gedikli** [comment]
There is a reason why we did the single pass Mean and Covar estimation -> speed.
If the double pass is required, use those methods directly or call the single-pass with Eigen::Matrix3d matrices, which uses double as accumulator. That should also increase the accuracy.

**Comment by fran6co** [comment]
Not sure how that relates to the UniformSampling move to filter. Did you meant to post it here => https://github.com/PointCloudLibrary/pcl/pull/1407 ?

**Comment by taketwo** [comment]
LGTM
Regarding API break, I think we should keep the old header file, otherwise those who use this class won't be able to compile their code and will have no clue what happened and why the file just disappeared. So maybe wipe the old file, insert a warning macro with a descriptive message and include the file from it's new location?

**Comment by fran6co** [comment]
Is it ok like this?

**Comment by taketwo** [comment]
:+1: but we'll need a yes from @jspricke

**Comment by mpflueger** [comment]
With this change some tutorials now require pcl 1.8 (I'm looking at correspondence_grouping, but there may be others), but the ubuntu PPA is still at 1.7.  Perhaps the website needs a dropdown to select your pcl version when looking at a tutorial?  Or at least a warning and link to the repo to find old versions?

**Pull request merged**
