### PR TITLE
Fixes for incorrect VTK library dependencies

### PR DESCRIPTION
**Pull request by themightyoarfish**
So I'm not sure if anyone beside me has had this issue … I'm on homebrew's vtk 8.2, and these changes here were necessary to build everything for me.
As for the apps, I only built point_cloud_editor, so I do not know if the others have any more problems. I did build all component PCL libs though.

### CODE REVIEW

**Comment by larshg** [comment]
I think you need to rebase your branch on master, to remove the old commits from the retina PR.

Also, you need to add some ifs, so you don't just add/remove libraries that are not required by other versions of VTK 😄

**Comment by mvieth** [comment]
@themightyoarfish Are you going to continue this pull request? Currently, several CIs are failing, and, as Lars mentioned, there are some old commits.
Out of interest: Why are you using `vtk@8.2`, not plain `vtk` (which is version 9.1)? As I understand it, `vtk@8.2` is deprecated

**Comment by themightyoarfish** [comment]
Probably if no one else observed these issues, this can be closed, i opened this more to document the fix in case someone is googling or searching for this problem. 

On December 29, 2021 11:43:40 AM GMT+01:00, Markus Vieth ***@***.***> wrote:
***@***.*** Are you going to continue this pull request? Currently, several CIs are failing, and, as Lars mentioned, there are some old commits.

**Comment by mvieth** [comment]
If you do not intend to bring this pull request in a merge-able state, I currently see no reason to leave it open. I am not aware that anyone else uses PCL with VTK 8, and it seems unlikely to me because:
- Ubuntu does not offer VTK 8 over apt, only VTK 6, 7, and 9
- homebrew offers VTK 8.2, but that version is marked deprecated, and the standard VTK version is VTK 9.1
- On VCPKG, VTK is at version 9.0.3

**Comment by themightyoarfish** [comment]
I'm revisiting this right now and as i've found in https://github.com/PointCloudLibrary/pcl/issues/3370#issuecomment-1004910758, VTK 9.0 creates problems when embedding a PCL visualizer into a Qt widget. Therefore it would be great if PCL remained backwards compatible to 8.2, which necessitates fixes like these here.

**Comment by mvieth** [comment]
Feel free to continue this pull request whenever you like (tell me if you want me to reopen it)

**Pull request closed without merging**
