### PR TITLE
Updated narf_keypoint_extraction.rst

### PR DESCRIPTION
**Pull request by rahulchhabra07**
Added hyperlink to a tutorial referred.

### CODE REVIEW

**Comment by VictorLamoine** [comment]
:+1:

**Comment by rahulchhabra07** [comment]
Hey,

The merging of this pull request seems to have failed.
Could you please let me know the possible reasons and any changes that I should make.

Thanks.

**Comment by SergioRAgostinho** [comment]
@rahulchhabra07 Nothing related to the changes you did.

**Comment by taketwo** [comment]
I think we should use RST commands instead of explicit urls:

```rst
:ref:`range_image_visualization`
```

**Comment by rahulchhabra07** [comment]
Yeah, that sounds better.

Will make another commit for that.

Let me know if you have any more suggestions. I am planning to add references for the entire documentation wherever necessary. 

Thanks.

**Comment by taketwo** [comment]
That would be a great contribution, thanks in advance!

**Pull request merged**
