### PR TITLE
reformatting include/pcl/registration/impl

### PR DESCRIPTION
**Pull request by JStech**
This is the first of three PRs to incorporate the `registration` module into `make format`.

### CODE REVIEW

**Review by larshg — CHANGES_REQUESTED** [review]
Resolve conflicts and it should be ready to :rocket:

**Comment by JStech** [comment]
OK, I rebased

**Review by kunaltyagi — APPROVED** [review]
Does it make sense to add `registration/include/pcl/registration/impl` to the format file?

**Comment by JStech** [comment]
I didn't add these piecemeal changes to the format file--instead I just added the whole module in #4450. I don't expect to have this PR or #4449 merged without (eventually) merging #4450 also. Honestly, I didn't bother to figure out how to specify subdirectories in the formatting script.

**Review by larshg — APPROVED** [review]

**Pull request merged**
