### PR TITLE
Remove KinFu

### LINKED ISSUE #1546: Remove KinFu
KinFu code is old, deprecated and [Nerei/kinfu_remake](https://github.com/Nerei/kinfu_remake) is **much** better.

What about deleting the code/application in PCL?

### PR DESCRIPTION
**Pull request by VictorLamoine**
Fixes #1546

### CODE REVIEW

**Comment by SergioRAgostinho** [comment]
Once this is merged I think we should make a post to pcd-devs and pcl-users, to notify people of the removal as well as explaining the reasons for it and links for the current alternatives. Basically aggregate all previous discussions we had about this, on a single post.

**Comment by taketwo** [comment]
:+1:

**Comment by SergioRAgostinho** [comment]
So we had an interesting conversation about this at the hackfest. @fedassa proposed to keep it since it's pretty popular and try to recruit some help in the next GSOC to maintain this and improve it.  Not sure how realistic this is, since the only additional help we had (excluding the website migration) since then was @stefanbuettner :x

**Comment by VictorLamoine** [comment]
It was never part of a release, KinFu remake is already a better version, those GSOC people really should work on KinFu remake instead of this old/deprecated version, they would be loosing their time otherwise.

**Comment by caomw** [comment]
I hold that KinFu module is very useful for many practical applications, thus, it should be kept !

**Comment by taketwo** [comment]
@caomw Out of curiosity, why don't you use any of these better maintained open-source systems:
* [kinfu_remake](https://github.com/Nerei/kinfu_remake)
* [Kintinious](https://github.com/mp3guy/Kintinuous)
* [InfiniTAM](https://github.com/victorprad/InfiniTAM)

**Comment by caomw** [comment]
@taketwo 
Thank you for your response.
To the best of our knowledge, some existing systems are based on kinfu_large_scale module, for example Elastic Reconstructio and SceneNN, etc.

**Comment by SergioRAgostinho** [comment]
@caomw  That's not exactly an answer to the question made. 

A really hypothetical answer, not exactly valid, but still addressing the question, would be for instance: 
> "I don't use kinfu_remake because the author doesn't like vim, Elastic Reconstruction because it's hard to understand and SceneNN because I don't want want a dependency on Caffee"

But don't get me wrong, even if it's not maintained properly now, I like to have it around. We never know what happens in the future. We just keep it eternally tagged as unstable and experimental.

**Comment by caomw** [comment]
@SergioRAgostinho 
Thank you very much !

**Comment by VictorLamoine** [comment]
Then I'm closing!

**Pull request closed without merging**
