### PR TITLE
Solve issues with failing filter tests

### PR DESCRIPTION
**Pull request by SergioRAgostinho**
We had three failing tests:
1. `RiftEstimation`
2. `CPPFEstimation`
3. `FPFHEstimation`

## 1. and 2.

Both these classes have not been touched in 6 to 7 years yet they will start failing once we move out of trusty. This implies is being caused by a third party. Since they both "only" depend on `search::KdTree` from a 3rd party standpoint, I'm inclined to point FLANN as the culprit. Nevertheless, the "solution" is to simply update the values with the new versions. If FLANN is not the culprit, I'll later test with Eigen and then both.

## 3. 

For the `FPFHEstimationOMP` failing test, I noticed the thresholds were more strict than the ones used for the non-OMP version. I decided eliminate the double standard and they're submitted to the exact same test written for `FPFHEstimation`.

### CODE REVIEW

**Comment by taketwo** [comment]
I tried your changes on my machine (Ubuntu 16.04, FLANN 1.8.4).
1. `RiftEstimation` did not fail before and still does not fail with your changes.
2. `CPPFEstimation` failed before and still fails with your changes.
3. `FPFHEstimation`failed before and still fails with your changes.

Let's tackle them one by one. Here is my output for `CPPFEstimation`:

```
[ RUN      ] PCL.CPPFEstimation
/home/sergey/Workspace/Libraries/pcl/test/features/test_cppf_estimation.cpp:110: Failure
The difference between feature_cloud->points[2572].f1 and 0.0669282 is 0.0019496153528213434, which exceeds 1e-4, where
feature_cloud->points[2572].f1 evaluates to 0.06497858464717865,
0.0669282 evaluates to 0.066928199999999993, and
1e-4 evaluates to 0.0001.
/home/sergey/Workspace/Libraries/pcl/test/features/test_cppf_estimation.cpp:111: Failure
The difference between feature_cloud->points[2572].f2 and -0.1988939 is 0.0014384733806609984, which exceeds 1e-4, where
feature_cloud->points[2572].f2 evaluates to -0.20033237338066101,
-0.1988939 evaluates to -0.19889390000000001, and
1e-4 evaluates to 0.0001.
/home/sergey/Workspace/Libraries/pcl/test/features/test_cppf_estimation.cpp:112: Failure
The difference between feature_cloud->points[2572].f3 and 0.7856042 is 0.0024019864852905526, which exceeds 1e-4, where
feature_cloud->points[2572].f3 evaluates to 0.78800618648529053,
0.7856042 evaluates to 0.78560419999999997, and
1e-4 evaluates to 0.0001.
/home/sergey/Workspace/Libraries/pcl/test/features/test_cppf_estimation.cpp:120: Failure
The difference between feature_cloud->points[2572].alpha_m and -1.852997 is 0.00074833132934570834, which exceeds 1e-4, where
feature_cloud->points[2572].alpha_m evaluates to -1.8522486686706543,
-1.852997 evaluates to -1.852997, and
1e-4 evaluates to 0.0001.
[  FAILED  ] PCL.CPPFEstimation (228 ms)
```

I noticed that your conditional code is for FLANN strictly higher than 1.8.4, which I have on my machine. So I tried to change the condition to greater or equal and got the following output:

```
[ RUN      ] PCL.CPPFEstimation
/home/sergey/Workspace/Libraries/pcl/test/features/test_cppf_estimation.cpp:96: Failure
The difference between feature_cloud->points[2572].f1 and 0.0568356 is 0.0081429846471786499, which exceeds 1e-4, where
feature_cloud->points[2572].f1 evaluates to 0.06497858464717865,
0.0568356 evaluates to 0.0568356, and
1e-4 evaluates to 0.0001.
/home/sergey/Workspace/Libraries/pcl/test/features/test_cppf_estimation.cpp:97: Failure
The difference between feature_cloud->points[2572].f2 and -0.1988939 is 0.0014384733806609984, which exceeds 1e-4, where
feature_cloud->points[2572].f2 evaluates to -0.20033237338066101,
-0.1988939 evaluates to -0.19889390000000001, and
1e-4 evaluates to 0.0001.
/home/sergey/Workspace/Libraries/pcl/test/features/test_cppf_estimation.cpp:98: Failure
The difference between feature_cloud->points[2572].f3 and 0.7854938 is 0.0025123864852905076, which exceeds 1e-4, where
feature_cloud->points[2572].f3 evaluates to 0.78800618648529053,
0.7854938 evaluates to 0.78549380000000002, and
1e-4 evaluates to 0.0001.
/home/sergey/Workspace/Libraries/pcl/test/features/test_cppf_estimation.cpp:106: Failure
The difference between feature_cloud->points[2572].alpha_m and -1.847514 is 0.0047346686706541963, which exceeds 1e-4, where
feature_cloud->points[2572].alpha_m evaluates to -1.8522486686706543,
-1.847514 evaluates to -1.8475140000000001, and
1e-4 evaluates to 0.0001.
[  FAILED  ] PCL.CPPFEstimation (227 ms)
```

Here are the numbers without prose:

my results | old expected | old diff | new expected | new diff
-- | -- | -- | -- | --
0.0649785 | 0.0669281 | 0.0019 |  0.0568356 | 0.0081
-0.2003323 | -0.1988939 | 0.0014 | -0.1988939 | 0.0014
0.7880061 | 0.7856042 | 0.0024 | 0.7854938 | 0.0025
-1.8522486 | -1.852997 | 0.0007 | -1.847514 | 0.0047

So clearly my results don't match old expectation, but they are even more off from the ones...

**Comment by SergioRAgostinho** [comment]
Then this is something else... I believe this class is only making use of FLANN and EIGEN as a 3rd party. This is my current environment with respect to third parties.

**OS X**
Eigen: 3.3.4
Flann: 1.9.1

Another idea is to actually look into changes into the KdTree class, but I believe I did this and got nothing suspicious.

**Comment by taketwo** [comment]
Regarding `CPPFEstimation`, as far as I can see, it does not use KdTree explicitly, but depends on the normals (which are estimated using KdTree). This is clearly a flaw in the unit test design to compute normals within test instead of providing them as an input.

I think the most reasonable way is to pre-compute normals and incorporate them into `colored_cloud.pcd` file. Drop normal estimation from the test, so that it indeed becomes a _unit test_ (not integration test). After that we can check if the CPPF results are still different on Travis and our machines.

**Comment by SergioRAgostinho** [comment]
I just reverted `test_cppf_estimation` to its original test state. I cleaned up the file of useless code and provided a new `colored_cloud_with_normals.pcd` file. I thought about simply overwriting the original  `colored_cloud.pcd` but was slightly scared of breaking things for other tests. We can always overwrite it before the merge to see what happens. 

I'm getting the following expectation failures
```
[ RUN      ] PCL.CPPFEstimation
/Users/neglective/Development/3rdparty/pcl/test/features/test_cppf_estimation.cpp:74: Failure
The difference between feature_cloud->points[2572].f1 and 0.0669282 is 0.0100925858551979, which exceeds 1e-4, where
feature_cloud->points[2572].f1 evaluates to 0.056835614144802094,
0.0669282 evaluates to 0.066928199999999993, and
1e-4 evaluates to 0.0001.
/Users/neglective/Development/3rdparty/pcl/test/features/test_cppf_estimation.cpp:76: Failure
The difference between feature_cloud->points[2572].f3 and 0.7856042 is 0.00011034929199216226, which exceeds 1e-4, where
feature_cloud->points[2572].f3 evaluates to 0.78549385070800781,
0.7856042 evaluates to 0.78560419999999997, and
1e-4 evaluates to 0.0001.
/Users/neglective/Development/3rdparty/pcl/test/features/test_cppf_estimation.cpp:84: Failure
The difference between feature_cloud->points[2572].alpha_m and -1.852997 is 0.0054822514266967826, which exceeds 1e-4, where
feature_cloud->points[2572].alpha_m evaluates to -1.8475147485733032,
-1.852997 evaluates to -1.852997, and
1e-4 evaluates to 0.0001.
[  FAILED  ] PCL.CPPFEstimation (37308 ms)
```
Let's compare. :)

**Comment by SergioRAgostinho** [comment]
> Looks the same. For the record, I have Eigen 3.3-beta installed. **Edit:** and the same results on Travis.

That is awesome. So the normal estimation is responsible for the differences. I would say we update the reference values for this test and proceed with the next one, RIFT. I'll have a look at the test later.

> (I wonder why your test time is sooo long?)

It's a debug build. On release it reduces to 127ms. The power of optimizations is impressive.

**Comment by taketwo** [comment]
> I thought about simply overwriting the original colored_cloud.pcd but was slightly scared of breaking things for other tests. We can always overwrite it before the merge to see what happens.

It's used only in one other test (`test_segmentation`). I think as long as the XYZ coordinates stay the same there is no reason for anything to break.

> proceed with the next one, RIFT. I'll have a look at the test later.

RIFT uses KdTree internally, so your approach of having different expected values is the best we can do. And as I wrote, the test passes for me on Ubuntu 16.04, so everything is alright.

**Comment by SergioRAgostinho** [comment]
> It's used only in one other test (`test_segmentation`). I think as long as the XYZ coordinates stay the same there is no reason for anything to break.

The double checked the ASCII version and it was. I'll overwrite it then.

> RIFT uses KdTree internally, so your approach of having different expected values is the best we can do. And as I wrote, the test passes for me on Ubuntu 16.04, so everything is alright.

Yeah, that leaves me slightly restless but ok. 

<hr>

`FPFHEstimation` - hopefully what was failing before with the non OMP version is failing now on both. What's your error dump for this one?

**Comment by taketwo** [comment]
For me both standard and OMP versions fail with the same results, so I'm only posting the first one:

```
[ RUN      ] FPFHTest/0.Estimation
/home/sergey/Workspace/Libraries/pcl/test/features/test_pfh_estimation.cpp:430: Failure
The difference between fpfhs->points[0].histogram[14] and 9.37615 is 0.010728967285155377, which exceeds 1e-2, where
fpfhs->points[0].histogram[14] evaluates to 9.3868789672851562,
9.37615 evaluates to 9.3761500000000009, and
1e-2 evaluates to 0.01.
/home/sergey/Workspace/Libraries/pcl/test/features/test_pfh_estimation.cpp:431: Failure
The difference between fpfhs->points[0].histogram[15] and 17.963 is 0.011408508300782216, which exceeds 1e-2, where
fpfhs->points[0].histogram[15] evaluates to 17.951591491699219,
17.963 evaluates to 17.963000000000001, and
1e-2 evaluates to 0.01.
[  FAILED  ] FPFHTest/0.Estimation, where TypeParam = pcl::FPFHEstimation<pcl::PointXYZ, pcl::Normal, pcl::FPFHSignature33> (205 ms)
```

It's kind of close, but above the threshold. For this passes?

**Comment by SergioRAgostinho** [comment]
> For this passes?

I'm sorry. I can't figure what you're asking here. :/

**Comment by taketwo** [comment]
> I'm sorry. I can't figure what you're asking here. :/

It's broken English sentence with a missing word :laughing: I meant to ask "For you this passes?"

> Give it a try now. Maybe now it will be close enough to also pass in your build.

Yep, it is!

**Comment by SergioRAgostinho** [comment]
Great! :) I'll let you review the changes. 

I originally intended to squash this last commit, but after looking at the commit list, it seems ok on it's own.

**Comment by taketwo** [comment]
There is a problem on Travis:

```
/home/travis/build/PointCloudLibrary/pcl/test/features/test_pfh_estimation.cpp:159: undefined reference to `pcl::PFHEstimation<pcl::PointNormal, pcl::PointNormal, pcl::PFHSignature125>::computePairFeatures(pcl::PointCloud<pcl::PointNormal> const&, pcl::PointCloud<pcl::PointNormal> const&, int, int, float&, float&, float&, float&)'
/home/travis/build/PointCloudLibrary/pcl/test/features/test_pfh_estimation.cpp:168: undefined reference to `pcl::PFHEstimation<pcl::PointNormal, pcl::PointNormal, pcl::PFHSignature125>::computePointPFHSignature(pcl::PointCloud<pcl::PointNormal> const&, pcl::PointCloud<pcl::PointNormal> const&, std::vector<int, std::allocator<int> > const&, int, Eigen::Matrix<float, -1, 1, 0, -1, 1>&)'
CMakeFiles/test_pfh_estimation.dir/test_pfh_estimation.cpp.o:(.rodata._ZTVN3pcl13PFHEstimationINS_11PointNormalES1_NS_15PFHSignature125EEE[_ZTVN3pcl13PFHEstimationINS_11PointNormalES1_NS_15PFHSignature125EEE]+0x58): undefined reference to `pcl::PFHEstimation<pcl::PointNormal, pcl::PointNormal, pcl::PFHSignature125>::computeFeature(pcl::PointCloud<pcl::PFHSignature125>&)'
collect2: error: ld returned 1 exit status
```

`PFHEstimation` is not instantiated for `PointNormal` type when the library is built with only core point types. We should either include the "hpp" header or convert the loaded cloud to a `Normal` cloud before supplying to the algorithm.

**Comment by SergioRAgostinho** [comment]
errrr..... this happened

```
git push -d origin features
```
instead of
```
git push -f origin features
```

The `f` is next to the `d`.  I think I need to open another one now 😅

**Comment by jspricke** [comment]
You could have pushed it again ;)

**Comment by SergioRAgostinho** [comment]
I did. It did not allow to reopen the issue. :/ The new PR uses exactly the same branch.

**Comment by jspricke** [comment]
Not sure, I think if you reopen the request first and then push it maybe work. So if you want to try, you could delete first, then reopen, then push.

**Comment by SergioRAgostinho** [comment]
screen shot 2018-10-11 at 15 12 23

The reopen part seems to be impossible.

**Comment by SergioRAgostinho** [comment]
screen shot 2018-10-11 at 15 14 20

 I forgot to push before

**Pull request closed without merging**
