### PR TITLE
Include <limits> which is missing in a VTK 9.0.x header

### PR DESCRIPTION
**Pull request by mvieth**

### CODE REVIEW

**Review by larshg — DISMISSED** [review]

**Comment by mvieth** [comment]
@SunBlack If this looks good to you, I would merge it

**Comment by SunBlack** [comment]
From the code it looks good. I'm just thinking about the position, if we really want the `#if` inside the VTK include block and not just in front of it.

**Comment by mvieth** [comment]
> From the code it looks good. I'm just thinking about the position, if we really want the `#if` inside the VTK include block and not just in front of it.

It kind of has to be inside the VTK include block, at least it must come after `#include <vtkVersion.h>` so that `VTK_MAJOR_VERSION` and `VTK_MINOR_VERSION` are defined. For pcl_plotter.cpp, I could move it further up, so that the if-block comes right after `#include <vtkVersion.h>`, if you like that better?

**Comment by SunBlack** [comment]
Ahh well, to have this always after `vtkVersion.h` is a good idea.

**Comment by mvieth** [comment]
So should I change the order in pcl_plotter.cpp to look like this?
```cpp
#include <vtkVersion.h>
#if VTK_MAJOR_VERSION == 9 && VTK_MINOR_VERSION == 0
#include <limits> // This must be included before vtkDoubleArray.h
#endif
#include <vtkDoubleArray.h>
// then the rest of the vtk includes
```

**Review by larshg — APPROVED** [review]

**Pull request merged**
