### PR TITLE
Update required boost

### PR DESCRIPTION
**Pull request by larshg**
Update required boost.

### CODE REVIEW

**Review by kunaltyagi — DISMISSED** [review]

**Comment by mvieth** [comment]
I quickly skimmed through https://bugreports.qt.io/browse/QTBUG-22829 and https://bugreports.qt.io/browse/QTBUG-29331, but it is not clear to me yet why this can be removed. I didn't read anywhere that this problem only appears with Boost versions < 1.65.0?

**Comment by larshg** [comment]
> I quickly skimmed through https://bugreports.qt.io/browse/QTBUG-22829 and https://bugreports.qt.io/browse/QTBUG-29331, but it is not clear to me yet why this can be removed. I didn't read anywhere that this problem only appears with Boost versions < 1.65.0?

Indeed its a bit mismatching about it being in the boost minimum required patch. As I read the two bugs its for Qt4 and <qt 5.4, where we  are at qt 5.9.5 on Ubuntu 18.04, so I should maybe move those to a minimum required Qt PR.

**Review by kunaltyagi — APPROVED** [review]
Approved, with same logic as the FLANN PR. If we end up deciding against changing the min version there, please revoke my approval here :)

**Review by mvieth — APPROVED** [review]
As a side idea, we could change our Dockerfile to enable us to install any of the two available Boost versions, something like `libboost-date-time${BOOST_VERSION}-dev`, where `BOOST_VERSION` could e.g. be 1.62, 1.65, or empty for default (on Ubuntu 18.04). But that's not a must.
(also for reference: the FLANN PR is #4766 if anyone else is looking for it)

**Pull request merged**
