### PR TITLE
Fix typo in mls.h and mls.hpp

### PR DESCRIPTION
**Pull request by keineahnung2345**

### CODE REVIEW

**Comment by keineahnung2345** [comment]
In mls.hpp, "principle curvature" is also a typo for "principal curvature", I'd like to fix it. But it will change the APIs, don't know if it will be accepted or not?

**Review by JStech — APPROVED** [review]
LGTM. I support fixing the principle/principal error, although it'd probably be easier to do it in another PR and have the discussion there.

**Comment by keineahnung2345** [comment]
@JStech OK, I will open another PR.

**Review by kunaltyagi — APPROVED** [review]

**Review by mvieth — APPROVED** [review]
Thanks!

**Pull request merged**
