### PR TITLE
Switch latest Ubuntu to C++17

### PR DESCRIPTION
**Pull request by cybaol**

### CODE REVIEW

**Comment by larshg** [comment]
Should we also set CMAKE_CUDA_STANDARD to 17?

**Comment by cybaol** [comment]
@larshg If so, should we also set `PCL_CXX_COMPILE_FEATURES` to `cxx_std_17`?

**Comment by larshg** [comment]
> @larshg If so, should we also set `PCL_CXX_COMPILE_FEATURES` to `cxx_std_17`?

I don't think its necessary, since it just set the minimum required, whereas the CMAKE_CXX_STANDARD sets it as a hard requirement.
See https://cmake.org/cmake/help/latest/manual/cmake-compile-features.7.html#requiring-language-standards

**Comment by cybaol** [comment]
> > @larshg If so, should we also set `PCL_CXX_COMPILE_FEATURES` to `cxx_std_17`?
> 
> I don't think its necessary, since it just set the minimum required, whereas the CMAKE_CXX_STANDARD sets it as a hard requirement. See https://cmake.org/cmake/help/latest/manual/cmake-compile-features.7.html#requiring-language-standards

I see.

**Review by mvieth — APPROVED** [review]

**Review by kangzixiang — APPROVED** [review]

**Pull request merged**
