### PR TITLE
Fix issues describled in #1324 (Color offset problem and wrong variable used)

### PR DESCRIPTION
**Pull request by the-glu**
As described in #1324 that fix : 

* Wrong offset used for colors, that produce wrong colors in visualiser
* Wrong variable used

### CODE REVIEW

**Comment by taketwo** [comment]
Could you actually put `fields[rgba_index].offset` into a variable so that it's not evaluated on every iteration? Just in case a compiler is not smart enough to optimize this.

Please don't make a second commit in this PR, just fixup the existing one. Thanks!

**Comment by the-glu** [comment]
Fixed, in a single commit :)

Just wondering, why don't add a second commit ? I had to push-force the new commit and that doesn't feel right :P

**Comment by taketwo** [comment]
I think you forgot `.offset` :)

**Comment by the-glu** [comment]
Yes sorry, fixed ^^'

**Comment by taketwo** [comment]
Push force (and history rewriting) is fine as long as we don't do it to the `master` branch (or any other "public" branch for that matter).

It's nicer to have a single commit for related changes. The history looks cleaner, `git blame` becomes more useful. Less objects in the repository and therefore less space used and faster clone.

Of course, when a bug is already in master, we have no way other than to put a new fix commit on top. But if a new bug and a fix for it are still in a feature branch, then why not squashing them before final merge.

**Pull request merged**
