### PR TITLE
Prefer C++ method std::log over C method log

### PR DESCRIPTION
**Pull request by SunBlack**

### CODE REVIEW

**Comment by taketwo** [comment]
Yeah, osx fails most of the times lately...

**Comment by SergioRAgostinho** [comment]
I'll try to reserve some time during the weekend to see if I can replicate it.

**Comment by SergioRAgostinho** [comment]
Just gave it a test and master build without issues. My next conjecture is that the agent/VM might be running out of memory.

**Comment by taketwo** [comment]
Couple of observations:
* All osx jobs starting from August have failed in the same way:
  * at approximately the same time (40 or 41 minute into the build)
  * at the same percentage (35%) after completing `pcl_surface` target
* Before August osx jobs occasionally failed, but with "communication lost" error
* Before August in succeeding jobs `pcl_surface` target was at 36% of the build

I also checked updates that happened to Azure osx image recently ([week 29](https://github.com/microsoft/azure-pipelines-image-generation/pull/1093), [week 30](https://github.com/microsoft/azure-pipelines-image-generation/pull/1147)), but there is nothing significant that can affect us. The only somewhat remotely related change is a tiny bump in homebrew version.

**Comment by taketwo** [comment]
Our Ubuntu job has been failing lately as well. Coincidentally during compilation of examples for the surface module:

```
[ 41%] Building CXX object examples/surface/CMakeFiles/pcl_example_nurbs_fitting_closed_curve.dir/example_nurbs_fitting_closed_curve.cpp.o
/__w/1/s/examples/surface/example_nurbs_fitting_closed_curve.cpp:1:55: fatal error: pcl/surface/on_nurbs/fitting_curve_2d_pdm.h: No such file or directory
compilation terminated.
examples/surface/CMakeFiles/pcl_example_nurbs_fitting_closed_curve.dir/build.make:62: recipe for target 'examples/surface/CMakeFiles/pcl_example_nurbs_fitting_closed_curve.dir/example_nurbs_fitting_closed_curve.cpp.o' failed
make[2]: *** [examples/surface/CMakeFiles/pcl_example_nurbs_fitting_closed_curve.dir/example_nurbs_fitting_closed_curve.cpp.o] Error 1
make[1]: *** [examples/surface/CMakeFiles/pcl_example_nurbs_fitting_closed_curve.dir/all] Error 2
```

I can not reproduce on my 16.04 machine.

**Comment by SergioRAgostinho** [comment]
Ok, I didn't build nurbs code before. Just the standard surface module. I'll have another look to see if something pops out.

**Comment by SunBlack** [comment]
> I can not reproduce on my 16.04 machine.

Neither on 18.04 with clang (as usual: full build)

**Pull request merged**
