### PR TITLE
fix linemod binindex wrong range bug in surface normal modality

### PR DESCRIPTION
**Pull request by RunqiuBao**
In linemod, binindex in surface normal modality should be within [1, 8] (0 represents invalid points), but in current master it is [0, 7] ( only one angle 360deg gives binindex 8).

### CODE REVIEW

**Comment by mvieth** [comment]
Thank you for finding this bug! Two things:
- We are using C++14, so `std::clamp` is not an option. You could use `bin_index = (bin_index < 1) ? 1 : (8 < bin_index) ? 8 : bin_index;` instead
- I am not very familiar with this class and linemod, I am wondering whether 11.25 is the correct value. To my understanding the angle should be divided into 8 bins, so each bin is 360/8=45 degrees wide. Also, 0 should be in the middle of the bin, meaning the bin contains values between -22.5 and 22.5. The next bin then contains values between 22.5 and 67.5 (with 45 in the middle). So shouldn't it actually be 22.5 instead of 11.25, or am I missing something?

**Comment by RunqiuBao** [comment]
> Thank you for finding this bug! Two things:
> 
> * We are using C++14, so `std::clamp` is not an option. You could use `bin_index = (bin_index < 1) ? 1 : (8 < bin_index) ? 8 : bin_index;` instead
> * I am not very familiar with this class and linemod, I am wondering whether 11.25 is the correct value. To my understanding the angle should be divided into 8 bins, so each bin is 360/8=45 degrees wide. Also, 0 should be in the middle of the bin, meaning the bin contains values between -22.5 and 22.5. The next bin then contains values between 22.5 and 67.5 (with 45 in the middle). So shouldn't it actually be 22.5 instead of 11.25, or am I missing something?

Hi, 
- I changed according to your suggestion and pushed.
- In my understanding, this magic number **11.25f** here is just a bias for the bin boundaries. In this case, the first bin contains values between -11.25~33.75, instead of -22.5~22.5

**Comment by mvieth** [comment]
> In my understanding, this magic number **11.25f** here is just a bias for the bin boundaries. In this case, the first bin contains values between -11.25 ~ 33.75, instead of -22.5 ~ 22.5

But why should the bin be asymmetric, instead of 0 being in the middle of the bin? My first intuition would have been that the bin was supposed to be from -22.5 to 22.5, but the person who originally wrote this code made a mistake by writing 11.25 instead of 22.5 ?

**Comment by RunqiuBao** [comment]
> > In my understanding, this magic number **11.25f** here is just a bias for the bin boundaries. In this case, the first bin contains values between -11.25 ~ 33.75, instead of -22.5 ~ 22.5
> 
> But why should the bin be asymmetric, instead of 0 being in the middle of the bin? My first intuition would have been that the bin was supposed to be from -22.5 to 22.5, but the person who originally wrote this code made a mistake by writing 11.25 instead of 22.5 ?

Hi. 
I am not sure if the original author wrote **11.25f** conciously or unconsciously. But why must 0 be the middle of the first bin? If 0 here means the normal is right pointing to the x direction, why is this direction special? In real life point cloud data, normals distribute uniformly, doesn't it?

**Comment by mvieth** [comment]
Yes, that's true.
There are two similar computations in the same file (line 682 and line 901). Please check if these also need this fix. One of these uses 22.5 instead of 11.25. I would say that at least all three computations should use the same value (11.25 or 22.5), what do you think?

**Comment by RunqiuBao** [comment]
> Yes, that's true. There are two similar computations in the same file (line 681 and line 900). Please check if these also need this fix. One of these uses 22.5 instead of 11.25. I would say that at least all three computations should use the same value (11.25 or 22.5), what do you think?

Hi, thanks for the notice!
I fixed the other two places, according to my understanding. However I do not have tests for verifying them. Please test it if you have any.

As for the bin boundaries issue, since it is not related to the issue in this PR, I created another PR to fix it: [pull/5464](https://github.com/PointCloudLibrary/pcl/pull/5464)

**Review by mvieth — APPROVED** [review]
Thank you! Looks correct now

**Pull request merged**
