### PR TITLE
[tools] Replace std::stringstream by std::string

### PR DESCRIPTION
**Pull request by SunBlack**
As far as I read this transition doesn't really has a big negative performance impact and it increases the readability as `.str ()` is not anymore necessary and we can add `const` qualifier.

Only one left, which I can't replace as there is no already implemented way from `PointXYZ` to `std::string`
https://github.com/PointCloudLibrary/pcl/blob/eebd3018e54a522cb71dd8ff517d9f82a880252f/tools/pcd_viewer.cpp#L184-L191

### CODE REVIEW

**Comment by SunBlack** [comment]
Sometimes I love C++. I saw that I could simplify parts of the code by using Boost.

Now I'm getting a compile error:

image

When I apply the suggested change I'm getting

image

Now I'm confused

**Comment by kunaltyagi** [comment]
I'd check if CMake finds the filesystem component of Boost

**Review by kunaltyagi — APPROVED** [review]
I see that I commented on the wrong PR

**Comment by SunBlack** [comment]
> I'd check if CMake finds the filesystem component of Boost (is the problem exists. CI is green right now)

The error was just a missing include, even the erro message doesn't sound so ;-)

**Review by mvieth — APPROVED** [review]

**Comment by mvieth** [comment]
@SunBlack I think I am going to squash all three commits into one and merge, or do you want to reorganize the changes into more than one commit?

**Comment by SunBlack** [comment]
I think we should keep the first two commits as this are different changes. Last one I could squash into the other.

**Comment by mvieth** [comment]
> I think we should keep the first two commits as this are different changes. Last one I could squash into the other.

Makes sense :+1:

**Pull request merged**
