### PR TITLE
Add Ubuntu16.04 based build on Azure Pipelines

### PR DESCRIPTION
**Pull request by taketwo**
This PR adds a new job that builds PCL in the Ubuntu 16.04 based image. It also switches the documentation job to use a dedicated "doc" image with Doxygen and other necessary tools.

I've created a new [organization](https://hub.docker.com/r/pointcloudlibrary/) on Docker Hub to host "environment" images where all PCL dependencies are pre-installed. The images from this organization will be used for containerized builds on Azure Pipelines. For the time being I created these images locally and pushed to the registry. In future we may commit their respective Dockerfiles to the main PCL repository (or a supplementary one) and setup a separate pipeline to rebuild and push them to the registry automatically.

### CODE REVIEW

**Comment by SergioRAgostinho** [comment]
@taketwo Read this https://docs.microsoft.com/en-us/azure/devops/pipelines/process/phases?view=vsts&tabs=yaml#timeouts

You need to set the timeout explicitly to 0. A maximum limit still exists and it is 6 hours.

**Comment by taketwo** [comment]
Thanks for the tip! With timeout set to zero the job succeeded (on my private account, [log here](https://dev.azure.com/u7p11/pcl/_build/results?buildId=35&view=logs)). It took 3 hours to build the library though, really long. That was without passing `-j` option to _make_, so I've also tried to set `-j2` and `-j3`. This leads to faster build progress, however inevitably ends up in a failure at some late stage of the build. I restarted the pipeline multiple times, but it always eventually failed. Here is an [example](https://dev.azure.com/PointCloudLibrary/pcl/_build/results?buildId=22&view=logs) of such failure. Unfortunately, Azure is not informative about the problem and refuses to provide a complete log of the step up until the failure, so we can not check at which exact point during the build it failed. I suspect it's some sort of out of memory error, we had similar a similar problem in the early days on Travis. The hacky solution was to build the memory-heavy targets with a single thread, and the rest of the targets with multiple threads. I'll try to use the same technique here.

**Comment by SergioRAgostinho** [comment]
>  Unfortunately, Azure is not informative about the problem and refuses to provide a complete log of the step up until the failure, so we can not check at which exact point during the build it failed.

It doesn't allow me to download to the log of the failed build :/

> I suspect it's some sort of out of memory error, we had similar a similar problem in the early days on Travis. 

That would also be my intuition. Did you know the "resource limits" of their VMs? In Travis we were not able to compile with `-j2` in the container infrastructure and that was a reason to move to their sudo enabled builds. It provided slightly more memory.

> The hacky solution was to build the memory-heavy targets with a single thread, and the rest of the targets with multiple threads. I'll try to use the same technique here.

We never really get rid of the highly involved CI pipelines.

**Comment by taketwo** [comment]
Done.

**Pull request merged**
