### PR TITLE
Publish test results to Azure Pipelines

### PR DESCRIPTION
**Pull request by vagisha-nidhi**
This PR is related to the issue [https://github.com/PointCloudLibrary/pcl/issues/2947](https://github.com/PointCloudLibrary/pcl/issues/2947)
The PR helps to publish test results for reporting in Azure Pipelines.

Azure Pipelines provides excellent reporting capabilities that can be leveraged by this PR.
An example report is shown in the image below.
image
image

### CODE REVIEW

**Comment by taketwo** [comment]
Hi, thanks for the PR. Is test results publishing also supported on Ubuntu/MacOS?

**Comment by vagisha-nidhi** [comment]
@taketwo Please find test results published here [https://dev.azure.com/PointCloudLibrary/pcl/_build/results?buildId=2724&view=ms.vss-test-web.build-test-results-tab](https://dev.azure.com/PointCloudLibrary/pcl/_build/results?buildId=2724&view=ms.vss-test-web.build-test-results-tab).
Also, CTest generates a ctest results file on adding the argument **`-T Test`** which is read to publish the results.

**Comment by vagisha-nidhi** [comment]
> Hi, thanks for the PR. Is test results publishing also supported on Ubuntu/MacOS?
> 
> As far as I can see, the publishing step currently exits with warning:
> 
> > ##[warning]No test result files matching *_/Test_.xml were found.

@taketwo This is supported in Ubuntu/MacOs as well. I have modified the PR to publish results in Ubuntu and MacOs. Please visit the build page see the published results.
Thanks.

**Comment by jasjuang** [comment]
@vagisha-nidhi Can you let us know how to run CUDA unit tests on Azure pipelines? We had a discussion at https://github.com/PointCloudLibrary/pcl/pull/3100. Personally I am also trying to make it work for my own project as well.

**Pull request merged**
