### PR TITLE
Optimised pcl

### PR DESCRIPTION
**Pull request by MMiknis**
Sorry about a messy pull request this is my first one and I messed it up a bit. The commits should be fine.
I have used PCL for my research and found quite  a few ways at speeding it up as the performance was quite slow to be used for real time tasks.

### CODE REVIEW

**Comment by VictorLamoine** [comment]
Please use the PCL style guide. You can find it [here](http://pointclouds.org/documentation/advanced/pcl_style_guide.php).
There is an [Eclipse formatter file](https://github.com/PointCloudLibrary/pcl/blob/master/doc/advanced/content/files/PCL_eclipse_profile.xml) if you want to auto-format your code.

**Comment by MMiknis** [comment]
I've updated the code using the style guide link provided and synced it, I am just not sure if the commits went through. Sorry for being a nuisance, still new to all of this :(

**Comment by jspricke** [comment]
I'm not sure about this optimizations. Which compiler and optimization flags did you use?

**Comment by MMiknis** [comment]
I used the default compiler that comes with Visual studio 2013 (no optimisation flags enabled) and saw same results on Linux mint machine and raspberry pi 2.

Well it's much faster than the stock code as pushback is too slow as well as vector access and dereferencing uses up too much of the CPU time. I have attached an image to show this:
opti

**Comment by jspricke** [comment]
@MMiknis can you try #1343 instead?

**Comment by MMiknis** [comment]
Yeah sure I will test the #1343 on all 3 machines and report back

**Comment by fran6co** [comment]
This is related to => https://github.com/PointCloudLibrary/pcl/issues/1306

**Comment by MMiknis** [comment]
OK I have done the tests and the #1343 is faster than stock code but still not as fast as #1340.
Here are some of the results including the frame-rates as well:
comparison

As you can see #1340 has 3 times better frame-rate than #1343 on average and overall CPU ussage. And #1340 can still be faster as I only committed part of the optimizations that I have done, as #1340 is being held back by depth calculation access:
opti

With depth calculation optimised I can achieve 42fps on average:
opti 2

**Comment by jspricke** [comment]
Is this again with optimization disabled? Can you do it with optimization turned on?

**Comment by MMiknis** [comment]
Well I did run through the test with maximum optimization flags on and off and here are the results:
results

Optimization flags did make quite a big difference

**Comment by MMiknis** [comment]
I am not sure what to do next. Should I try to submit the other optimisations that I have done for other PCL modules or wait to see what happens with this?

**Comment by jspricke** [comment]
Thanks for the ping. I would prefer to merge something along the lines of #1343. @taketwo what do you think?

**Comment by MMiknis** [comment]
If you want I can do #1343 along with depth optimisation performance test? So it wouldn't be too big of a change of code style but still provide a better performance.

**Comment by jspricke** [comment]
We have the rule not to merge our own patches, so let's wait for taketwo to look over this. I would prefer to have the rest of the changes in a separate pull request.

**Comment by MMiknis** [comment]
Yeah sure, that's fine :)

**Comment by taketwo** [comment]
I'm much in favor of #1343. Perhaps we can speed it up even further if we get rid of this legacy trick with float casts.

```cpp
// Define point color
                  uint32_t rgb = (static_cast<uint32_t>(pixel_r) << 16
                                | static_cast<uint32_t>(pixel_g) << 8
                                | static_cast<uint32_t>(pixel_b));
                  newPoint.rgb = *reinterpret_cast<float*>(&rgb);
```

**Comment by MMiknis** [comment]
The float casting is quite fast, my results showed that it only took up 1.4% of the CPU cycles. The vector pushback was by far the slowest part.

**Comment by taketwo** [comment]
Well, nevertheless. Points now have `rgba` field, which is a 32 bit unsigned integer. So we can put bytes directly into it.

**Comment by taketwo** [comment]
But that's just my two cents. We can merge that request as is, it's already a huge improvement.

**Comment by MMiknis** [comment]
I see, so as @jspricke mentioned he can't merge #1343 himself does that mean that I need to make the change as do a new pull request?

**Comment by jspricke** [comment]
ok, seems like we are really getting into it now. Let's wait for @fran6co to finish, maybe :).

**Comment by taketwo** [comment]
@fran6co Do you want us to merge #1343, or will it be a part of your PR?

**Comment by taketwo** [comment]
OK, sorry. I see that it is a part of the PR already.
Closing this and the other one as they are superseded by Francisco's request.

**Pull request closed without merging**
