### PR TITLE
[WIP] Surround secure env with quotes

### PR DESCRIPTION
**Pull request by taketwo**
Just to test if this will solve problems with doc job: https://travis-ci.com/PointCloudLibrary/pcl/jobs/151400719.

### CODE REVIEW

**Comment by taketwo** [comment]
This did solve the errors while exporting the variables: https://travis-ci.com/PointCloudLibrary/pcl/jobs/151424950

However we won't know whether GitHub will accept pushes from Travis without merging this.

**Comment by SergioRAgostinho** [comment]
What if you disable the PR check that is done here
https://github.com/PointCloudLibrary/pcl/blob/ce416739f44156828aee8b41ee89bac4aa5f5987/.travis.sh#L96-L98

 Would that work?

**Comment by taketwo** [comment]
Your question made me think about whether the exporting errors are actually solved or not. Secret environment variables are not supposed to be available for pull requests or forks. Most likely Travis completely ignored this section and did not export anything. Hence no errors.

**Comment by taketwo** [comment]
I'd propose to use [encrypted files](https://docs.travis-ci.com/user/encrypting-files/) instead of environment variables. Then the `id_rsa` with the key for our documentation repository can be stored in encrypted form in PCL repository under `.github` subdirectory. This will allow to avoid this juggling:

https://github.com/PointCloudLibrary/pcl/blob/ce416739f44156828aee8b41ee89bac4aa5f5987/.travis.sh#L102-L107

**Comment by SergioRAgostinho** [comment]
I agree 👍

**Comment by jspricke** [comment]
I would propose to use `-t ed25519`, see https://blog.g3rt.nl/upgrade-your-ssh-keys.html (if Travis is new enough ;) ).

**Comment by SergioRAgostinho** [comment]
We might also want to make use of the deployment feature of Travis. It honestly feels semantically more correct given what we're trying to achieve.

https://docs.travis-ci.com/user/deployment/script/

**Comment by taketwo** [comment]
The blog post claims that Ubuntu 14.04+ has software support for Ed25519, so we are covered.

I created a keypair using `ssh-keygen -o -t ed25519 -C documentation@pointclouds.org` and then tried to encrypt it as described in the Travis article I referred to before. I logged in with Travis CLI and `--com` option, but the encryption failed with the following output:

```
$ travis encrypt-file id_ed25519
Detected repository as PointCloudLibrary/pcl, is this correct? |yes|
encrypting id_ed25519 for PointCloudLibrary/pcl
storing result as id_ed25519.enc
storing secure env variables for decryption
not logged in - try running travis login --org
```

I'm not sure about this one. I did not try with `--org`, because we are supposedly switching to `--com`, so need to encode with it. Could it be that I don't have permissions? Also, I think I wouldn't be able to add the generated public key to our organization anyway. @jspricke perhaps you will be the best person to handle this?

**Comment by taketwo** [comment]
Obsoleted by #2604.

**Pull request closed without merging**
