### PR TITLE
Added virtual dtor for PointCloud

### PR DESCRIPTION
**Pull request by erdustiggen**
As requested in #3470, a virtual destructor was readded to the PointCloud class.

### CODE REVIEW

**Comment by taketwo** [comment]
To resolve this warning indeed only `pcl::RangeImage` needs a virtual destructor.

However, as we have now found out, `pcl::PointCloud` serves as a base class. It's a good practice to mark destructors of every base class as virutal ([ref](https://stackoverflow.com/a/461237/1525865)).

**Comment by taketwo** [comment]
I agree with your first point. Perhaps we should even evaluate a possibility of "un-deriving" `RangeImage` from `PointCloud`.

**Comment by SergioRAgostinho** [comment]
I just had a look at the public interface of RangeImage and it looks messy. I wish we could write it from scratch. 
- The base container as a `Eigen::Matrix`/`Eigen::Array`
- Most of the public methods actually feel like they should be free functions of static factory methods.
- Not derived from `PointCloud`.

**Comment by taketwo** [comment]
So maybe we pretend that `RangeImage` is not derived from `PointCloud` -> nothing is derived from `PointCloud` -> `PointCloud` is not supposed to be a base class -> `PointCloud` does not need a virtual destructor. And `RangeImage` gets a virtual destructor since we pretend it's at the root of a class hierarchy?

**Comment by kunaltyagi** [comment]
> PointCloud is not supposed to be a base class 

Maybe add [final](https://en.cppreference.com/w/cpp/language/final) specifier to `PointCloud` in that case?

**Pull request closed without merging**
