### PR TITLE
[CI win] Add VTK and remove buildtrees

### PR DESCRIPTION
**Pull request by larshg**
remove buildtrees.

### CODE REVIEW

**Comment by kunaltyagi** [comment]
The installation takes 1 hour and 20 minutes (a huge jump), up from 5 minutes.

This might require some more DevOps (a separate job which creates the base "installed" artifacts and runs once a day/week)

**Comment by larshg** [comment]
Yes. its crazy :/

I'm trying to make a docker image with dependencies prebuild like ubuntu has it. You think its viable way to go?

**Comment by kunaltyagi** [comment]
Docker dependency for Windows? I didn't know you can containerize Windows. If so, that'd be the best way to go.

[But apparently you can. Crazy times to live in](https://docs.microsoft.com/en-us/virtualization/windowscontainers/quick-start/building-sample-app)

**Comment by kunaltyagi** [comment]
Visualization tests fails (for Windows)

**Comment by larshg** [comment]
I'll look into it when I got the container windows running. I'm not that familiar with docker/azure integration.

**Comment by kunaltyagi** [comment]
Sure take your time. I just posted to note an issue on CI because the CI removes old logs after a while.

> when I got the container windows running

I'd be interested in looking at that dockerfile 😄 

> I'm not that familiar with docker/azure integration

Right now, you'd need to create a docker image youself, and use the ubuntu-based CI for hints on how to pull and use the right image.

**Comment by taketwo** [comment]
Does "remove buildtrees" buys us something in terms of space? IIRC one of the windows jobs fails occasionally with "out of space" error, so maybe makes sense to fast-track this change without waiting for VTK/windocker?

**Comment by larshg** [comment]
Yes, all the intermediate obj files and a version of each dll, pdb and lib file would be present.

However it's only for 3 relatively small libraries, so it's not that much I guess.

**Comment by larshg** [comment]
Closing in favor of the docker versions.

**Comment by kunaltyagi** [comment]
#3917 for reference

**Pull request closed without merging**
