### PR TITLE
Added modernize-return-braced-init-list to clang-tidy checks

### PR DESCRIPTION
**Pull request by gnawme**
Added the [`modernize-return-braced-init-list`](https://clang.llvm.org/extra/clang-tidy/checks/modernize/return-braced-init-list.html) `clang-tidy` check

### CODE REVIEW

**Comment by mvieth** [comment]
I don't like all the formatting changes in openni2_grabber.cpp. Please undo them, they have nothing to do with the clang-tidy check and make this PR unnecessarily large.

**Comment by gnawme** [comment]
> I don't like all the formatting changes in openni2_grabber.cpp. Please undo them, they have nothing to do with the clang-tidy check and make this PR unnecessarily large.

I think these resulted from running `make format`, not sure why they were so extensive in this file

**Comment by larshg** [comment]
the format changes in `openni2_grabber.cpp` is still there 😄

**Review by mvieth — APPROVED** [review]
Thanks!

**Review by larshg — APPROVED** [review]

**Pull request merged**
