### PR TITLE
fix build with CUDA

### PR DESCRIPTION
**Pull request by daizhirui**
`CUDA_TOOLKIT_INCLUDE` is not set when `find_package(CUDAToolkit)` is called with `cmake >= 3.17`, which causes error 
```
gpu/utils/include/pcl/gpu/utils/safe_call.hpp:40:10: fatal error: cuda_runtime_api.h: No such file or directory
```

### CODE REVIEW

**Comment by larshg** [comment]
Which library/app are you building - I can't reproduce it and I'm using Cmake 3.28.
But thanks for notifying so quickly :grin:

**Comment by daizhirui** [comment]
Here is the command I use:
```
cmake .. -DCMAKE_INSTALL_PREFIX=/usr \
		-DCMAKE_CXX_FLAGS="${CXXFLAGS} -fPIC" \
		-DCMAKE_SHARED_LINKER_FLAGS="${LDFLAGS} -Wl,--as-needed" \
		-DCMAKE_EXE_LINKER_FLAGS="${LDFLAGS} -Wl,--as-needed" \
		-DCMAKE_CUDA_ARCHITECTURES="52;60;60;62;70;72;75;80;86;86-virtual" \
		-DBUILD_apps=ON \
		-DBUILD_apps_cloud_composer=ON \
		-DBUILD_apps_in_hand_scanner=ON \
		-DBUILD_apps_modeler=ON \
		-DBUILD_apps_point_cloud_editor=ON \
		-DBUILD_examples=ON \
		-DBUILD_global_tests=OFF \
		-DBUILD_surface_on_nurbs=ON \
		-DBUILD_CUDA=ON \
		-DBUILD_cuda_io=ON \
		-DBUILD_cuda_apps=ON \
		-DBUILD_GPU=ON \
		-DBUILD_gpu_kinfu=OFF \
		-DBUILD_gpu_kinfu_large_scale=OFF \
		-DBUILD_gpu_surface=ON \
		-DBUILD_gpu_tracking=ON \
		-DBUILD_simulation=ON \
		-DCMAKE_CUDA_COMPILER=/opt/cuda/bin/nvcc \
		-DCMAKE_MODULE_PATH=/usr/lib/cmake/OpenVDB \
		-DWITH_QT=QT6
cmake --build . --target all
```

The error occurs:
```
[  3%] Built target pcl_common
[  3%] Building CUDA object cuda/segmentation/CMakeFiles/pcl_cuda_segmentation.dir/src/connected_components.cu.o
[  3%] Building CXX object examples/common/CMakeFiles/pcl_example_scope_time.dir/example_scope_time.cpp.o
[  4%] Building CXX object examples/geometry/CMakeFiles/pcl_example_half_edge_mesh.dir/example_half_edge_mesh.cpp.o
[  4%] Building CXX object stereo/CMakeFiles/pcl_stereo.dir/src/stereo_grabber.cpp.o
[  4%] Building CXX object examples/common/CMakeFiles/pcl_example_organized_point_cloud.dir/example_organized_point_cloud.cpp.o
[  4%] Building CUDA object gpu/containers/CMakeFiles/pcl_gpu_containers.dir/src/device_memory.cpp.o
[  4%] Building CXX object gpu/containers/CMakeFiles/pcl_gpu_containers.dir/src/error.cpp.o
[  4%] Building CUDA object cuda/features/CMakeFiles/pcl_cuda_features.dir/src/normal_3d.cu.o
[  4%] Building CXX object ml/CMakeFiles/pcl_ml.dir/src/point_xy_32i.cpp.o
[  4%] Building CXX object sample_consensus/CMakeFiles/pcl_sample_consensus.dir/src/sac.cpp.o
[  4%] Building CXX object sample_consensus/CMakeFiles/pcl_sample_consensus.dir/src/sac_model_circle.cpp.o
[  4%] Building CXX object ml/CMakeFiles/pcl_ml.dir/src/point_xy_32f.cpp.o
[  4%] Building CXX object examples/common/CMakeFiles/pcl_example_check_if_point_is_valid.dir/example_check_if_point_is_valid.cpp.o
[  4%] Building CXX object io/CMakeFiles/pcl_io_ply.dir/src/ply/ply_parser.cpp.o
[  4%] Building CXX object examples/common/CMakeFiles/pcl_example_copy_point_cloud.dir/example_copy_point_cloud.cpp.o
[  4%] Building CXX object gpu/containers/CMakeFiles/pcl_gpu_containers.dir/src/initialization.cpp.o
[  4%] Building CXX object octree/CMakeFiles/pcl_octree.dir/src/octree_inst.cpp.o
[  4%] Building CXX object kdtree/CMakeFiles/pcl_kdtree.dir/src/kdtree_flann.cpp.o
In file included from /home/daizhirui/.cache/paru/clone/pcl-git/src/pcl/gpu/containers/src/initialization.cpp:38:
/home/daizhirui/.cache/paru/clone/pcl-git/src/pcl/gpu/utils/include/pcl/gpu/utils/safe_call.hpp:40:10: fatal error: cuda_runtime_api.h: No such file or directory
   40 | #include <cuda_runtime_api.h>
      |          ^~~~~~~~~~~~~~~~~~~~
compilation terminated.
make[2]: *** [gpu/containers/CMakeFiles/pcl_gpu_containers.dir/build.make:105: gpu/containers/CMakeFiles/pcl_gpu_containers.dir/src/initialization.cpp.o] Error 1
make[2]: *** Waiting for unfinished jobs....
[  4%] Building CXX object ml/CMakeFiles/pcl_ml.dir/src/densecrf.cpp.o
[  4%] Building CXX object ml/CMakeFiles/pcl_ml.dir/src/pairwise_potential.cpp.o
[  4%] Building CXX object ml/CMakeFiles/pcl_ml.dir/src/permutohedral.cpp.o
[  4%] Building CXX object ml/CMakeFiles/pcl_ml.dir/src/svm_wrapper.cpp.o
[  4%] Linking CXX executable ../../bin/pcl_example_scope_time
```

**Review by larshg — APPROVED** [review]

**Comment by larshg** [comment]
It is indeed not set, but builds on the CI's. I wonder if you have a specific cmake, which falls wrongly through the ifs :smile:

**Comment by daizhirui** [comment]
I use cmake 3.28.3 and cuda 12.4

**Comment by mvieth** [comment]
Shouldn't this line be added directly after `find_package(CUDAToolkit QUIET)`? Otherwise it would overwrite the value set by `find_package(CUDA 9.0)` if CMake < 3.17, no?

**Review by larshg — CHANGES_REQUESTED** [review]
Move the line as per @mvieth

**Comment by daizhirui** [comment]
Done. Thanks for pointing it out.

**Review by mvieth — APPROVED** [review]
Thanks!

**Comment by larshg** [comment]
@daizhirui Can you build octree and surface? Or do you also get errors about thrust::tuple get method?

**Review by larshg — DISMISSED** [review]

**Comment by daizhirui** [comment]
My previous build succeeded because it is actually CUDA 12.3. The NVIDIA driver reports CUDA 12.4 but it turns out it is 12.3. I tried another build with CUDA 12.4 and got the same error as yours @larshg.
I already fix it. Now I am sure that it works with CUDA 12.4.

**Comment by larshg** [comment]
> My previous build succeeded because it was actually CUDA 12.3. The NVIDIA driver reports CUDA 12.4 but it turned out it was 12.3. I tried another build with CUDA 12.4 and got the same error as yours @larshg. I already fix it. Now I am sure that it works with CUDA 12.4.

Nice, however I think we might need to add some #ifdefs if CUDA 9.0 doesn't support the newer thrust::get API. But lets see what the CI says. Think the oldest we build with is 10.x

**Comment by larshg** [comment]
Opened an issue https://github.com/NVIDIA/cccl/issues/1519, as according to documentation it should be possible to use get member functions:
https://nvidia.github.io/cccl/thrust/api/groups/group__tuple.html

**Review by mvieth — APPROVED** [review]
Thank you!

**Pull request merged**
