### PR TITLE
pcl::ISSKeypoint3D: Fixed segfault with search surface enabled.

### PR DESCRIPTION
**Pull request by ghost**
Changed to index `surface_` with search query results, intead of `input_`.

Prevents segfault when `surface_` is set with `setSearchSurface`.

### CODE REVIEW

**Comment by mvieth** [comment]
I don't fully understand the problem yet, especially how your last comment relates to the changes you have made. Considering that `searchForNeighbors` [searches in `input_`](https://github.com/PointCloudLibrary/pcl/blob/master/keypoints/include/pcl/keypoints/keypoint.h#L159), isn't it correct that `nn_indices` is used with `input_`? Ideally, you would add a simple test in test/keypoints/test_iss_3d.cpp that fails without the fix, but passes with the fix.

**Comment by mvieth** [comment]
Ah yes, you are right, `searchForNeighbors` is [searching in `surface_`](https://github.com/PointCloudLibrary/pcl/blob/master/keypoints/include/pcl/keypoints/impl/keypoint.hpp#L70). So your change in line 194 looks correct to me.
But the problem in lines 431, 440, ... you are describing, is a separate problem, not related to the change you made in `getScatterMatrix`, right?

**Comment by pmdifran** [comment]
I think that these assumptions really limit the ISSKeypoint detection. 

What if I want to ensure that keypoints are a minimum distance from each other? 

It doesn't make sense to compute them at the full cloud resolution, and then apply a voxel filter - if we could alternatively filter `input_` from the start (and save ourselves from a bunch of unnecessary computations).

To fix segfault at Line 440, could we:
- check if `surface_ == input_`
- if they differ, construct a KdTree for `input_`, with the same type as `KdTreePtr`
- Use this KdTree to search for input neighbors within the `non_max_radius_` (i.e. Line 431 above)

**Comment by mvieth** [comment]
Could you add a test in test_iss_3d.cpp to verify that your changes are correct?

**Comment by pmdifran** [comment]
Added some tests.

If you're happy with this - I can add the `input_search_tree_` as an `ISSKeypoints3D` member, and set it up during `initCompute`. 

Adding it to the class prevents us from constructing the KdTree in two separate function calls (`getBoundaryPoints` and `detectKeypoints`).

**Pull request closed without merging**
