### PR TITLE
Invalid cast to LeafNode* in OctreePointCloudVoxelCentroid

### PR DESCRIPTION
**Pull request by SergioRAgostinho**
Closes #960. Credits to @ThomasGuerneve for the original PR.

### CODE REVIEW

**Comment by SergioRAgostinho** [comment]
The build failed. Let me have a look at it.

**Comment by taketwo** [comment]
It's unrelated. IIRC the failing test is due to random nature of the algorithm being tested (KFPCS).

**Comment by SergioRAgostinho** [comment]
That's why RNGesus created seeds :) Just ran the test 5 times on my env and it's passing. I assume it might be failing sporadically then. I'll try to see if I can make the test consistent. 

Nevertheless, can you give it a try on your linuv env as well? Just want to be sure this is an rng issue and not some something related to platform difference.

**Comment by taketwo** [comment]
Succeeded 10 times in a row on my machine.

**Comment by SergioRAgostinho** [comment]
> (Are we in 0.01% today? :) )

Hahaha. (buys lottery ticket)

Thanks for the tests. I just figured out I won't be able to do much without doing changes to the api because the seed is reset to `srand (time (NULL))` in some of the methods.

**Pull request merged**
