### PR TITLE
Replace deprecated random shuffle with shuffle

### PR DESCRIPTION
**Pull request by al-tu**
`std::random_shuffle` is deprecated in C++14. replaced with `std::shuffle`

### CODE REVIEW

**Review by mvieth — APPROVED** [review]
Seems good. Metslib is technically 3rd party and has a custom license, but replacing deprecated functions like here should be fine.

**Comment by SunBlack** [comment]
Wouldn't it better to remove metslib from core and use [this](https://github.com/coin-or/metslib) instead (there may be more fixes)?

**Comment by larshg** [comment]
> Wouldn't it better to remove metslib from core and use [this](https://github.com/coin-or/metslib) instead (there may be more fixes)?

I think the author has changed its License, so its now GPL or Common Public License 1.0. Not BSD as PCL is.

**Comment by SunBlack** [comment]
> I think the author has changed its License, so its now GPL or Common Public License 1.0. Not BSD as PCL is.

[Interesting](https://github.com/PointCloudLibrary/pcl/blob/master/recognition/include/pcl/recognition/3rdparty/metslib/README.md), even I can't find the mentioned commit.

**Comment by mvieth** [comment]
> > I think the author has changed its License, so its now GPL or Common Public License 1.0. Not BSD as PCL is.
> 
> [Interesting](https://github.com/PointCloudLibrary/pcl/blob/master/recognition/include/pcl/recognition/3rdparty/metslib/README.md), even I can't find the mentioned commit.

Here is the commit: https://github.com/PointCloudLibrary/pcl/commit/e4d6501af048215ce84b4ee436ff0e18dba2d30d

**Review by kunaltyagi — APPROVED** [review]

**Pull request merged**
