### PR TITLE
Fixed compile error related to example projects

### PR DESCRIPTION
**Pull request by simbaforrest**
Related issues:

https://github.com/PointCloudLibrary/pcl/issues/1313

https://github.com/PointCloudLibrary/pcl/issues/1314

### CODE REVIEW

**Comment by taketwo** [comment]
Can you please explain the first fix (in "example_difference_of_normals.cpp")? Everything else looks good.

**Comment by simbaforrest** [comment]
Without the change, the [line 206 ](https://github.com/simbaforrest/pcl/blob/master/examples/features/example_difference_of_normals.cpp#L206)

and the [line 114](https://github.com/simbaforrest/pcl/blob/master/examples/features/example_difference_of_normals.cpp#L114)

will lead to unresolved external symbols since only core point types were instantiated in the pcl's dll.

**Comment by taketwo** [comment]
This is strange, I'll need to test this. But anyway, we should not manipulate `PCL_NO_PRECOMPILE` inside source files, this is something that is set by _CMake_ when configuring the project.

**Comment by simbaforrest** [comment]
I guess then the other way is to add
```C++
#include <pcl/features/impl/normal_3d_omp.hpp>
```
below [line 19](https://github.com/simbaforrest/pcl/blob/master/examples/features/example_difference_of_normals.cpp#L19)

and add
```C++
#include <pcl/segmentation/impl/extract_clusters.hpp>
```
below [line 22](https://github.com/simbaforrest/pcl/blob/master/examples/features/example_difference_of_normals.cpp#L22)

since without this "PCL_NO_PRECOMPILE", this two hpp files will not be included and in the example project, the types
```C++
typedef pcl::PointNormal PointNT;
typedef pcl::PointNormal PointOutT;
```
will leave some functions of
```C++
pcl::NormalEstimationOMP<PointT, PointNT> ne;
```
and
```C++
pcl::EuclideanClusterExtraction<PointOutT> ec;
```
undefined.

**Comment by taketwo** [comment]
How about other example programs though? Shouldn't the same problem manifest in them as well?

**Comment by simbaforrest** [comment]
Other examples are built just fine. I guess by they don't use any non-default point types.

BTW, just want to note that I built with the PCL_NO_PRECOMPILE off. So maybe this example project should add some compile time switch...

**Comment by taketwo** [comment]
Ok, I also get the error with `PCL_NO_PRECOMPILE=OFF` and `PCL_ONLY_CORE_POINT_TYPES=ON`.

I think the right way to solve this is to include the corresponding headers from `impl/` as you suggested. However I would wrap them in `#ifdef PCL_ONLY_CORE_POINT_TYPES`.

**Comment by simbaforrest** [comment]
Sure, I'll update and submit another pull request then.

**Comment by taketwo** [comment]
You don't need to make another PR. Just rewrite your last commit locally and push with `--force` flag.

**Comment by taketwo** [comment]
Can you actually join both `#ifdef`s so we have cleaner code? And one last thing will be to squash the commits in this pull request so that we do not pollute the history.

```
git rebase -i HEAD~2
```

Mark the second commit as "fixup", save and exit. Once rebasing is done, `git push --force`, and this PR will be automatically updated. Thank you!

**Comment by simbaforrest** [comment]
This will be cleaned up code
```C++
#include <string>

#include <pcl/point_types.h>
#include <pcl/io/pcd_io.h>
#include <pcl/kdtree/kdtree_flann.h>
#include <pcl/common/point_operators.h>
#include <pcl/common/io.h>
#include <pcl/search/organized.h>
#include <pcl/search/octree.h>
#include <pcl/search/kdtree.h>
#include <pcl/features/normal_3d_omp.h>
#include <pcl/filters/conditional_removal.h>
#include <pcl/segmentation/sac_segmentation.h>
#include <pcl/segmentation/extract_clusters.h>
#include <pcl/io/vtk_io.h>
#include <pcl/filters/voxel_grid.h>

#include <pcl/features/don.h>

#ifdef PCL_ONLY_CORE_POINT_TYPES
#include <pcl/features/impl/normal_3d_omp.hpp>
#include <pcl/segmentation/impl/extract_clusters.hpp>
#endif
```

Sorry I'm not that familiar with git rebase, I tried "git rebase -i HEAD~2" but nothing seems to happen. Should I do this after this new commit or before?

**Comment by simbaforrest** [comment]
Got it, since with the interactive rebase, I have to setup my git to work with my notepad++ like [this](http://stackoverflow.com/questions/4513387/git-problem-with-interactive-rebase)...

**Comment by taketwo** [comment]
Apparently working with terminal Git is a bit more complicated on Windows :D
Sorry again, but could you please squash these two commits into a single one? Then I'll merge.

**Comment by simbaforrest** [comment]
Now there should be only one commit :)

**Comment by taketwo** [comment]
Perfect! Thank you.

**Pull request merged**
