### PR TITLE
Update logo

### PR DESCRIPTION
**Pull request by jspricke**

### CODE REVIEW

**Comment by SergioRAgostinho** [comment]
:+1: We already have #2535 addressing the same problem.

**Comment by jspricke** [comment]
I would still go with this one as it uses a logo from the repo instead of getting one externally ;).

**Comment by SergioRAgostinho** [comment]
I prefer the other logo in terms of looks. Would you mind pushing it to the repo as well so we have it locally?

**Comment by jspricke** [comment]
both are fine with me.. updated.

**Pull request merged**
