### PR TITLE
[ci] Hotfix for Azure's weirdness with Alpine image

### PR DESCRIPTION
**Pull request by kunaltyagi**

### CODE REVIEW

**Comment by kunaltyagi** [comment]
Original command
```bash
/usr/bin/docker create --name fmt_pointcloudlibraryfmt_4d62b1 --label 0085e0 --network vsts_network_763f3d5f187b439290109a4c8aaebd9e  -v "/var/run/docker.sock":"/var/run/docker.sock" -v "/home/vsts/work/1":"/__w/1" -v "/home/vsts/work/_temp":"/__w/_temp" -v "/home/vsts/work/_tasks":"/__w/_tasks" -v "/opt/hostedtoolcache":"/__t" -v "/home/vsts/agents/2.166.4/externals":"/__a/externals":ro -v "/home/vsts/work/.taskkey":"/__w/.taskkey" pointcloudlibrary/fmt "/__a/externals/node/bin/node" -e "setInterval(function(){}, 24 * 60 * 60 * 1000);"
```

Relevant sections only:
```bash
docker create \
  --name fmt_pointcloudlibraryfmt \
  -v "/home/vsts/agents/2.166.4/externals":"/__a/externals":ro \
  pointcloudlibrary/fmt \
  "/__a/externals/node/bin/node" -e "setInterval(function(){}, 24 * 60 * 60 * 1000);"
```

Clearly, the `node` is unable to function in alpine.

Searching gave this: [Azure's dependencies for non-glibc containers](https://github.com/microsoft/azure-pipelines-agent/blob/master/docs/design/non-glibc-containers.md)

I'm working on this now

**Comment by taketwo** [comment]
Unfortunately the latest `node:alpine` has clang 9.

**Comment by kunaltyagi** [comment]
Working on it... I think I got it 😄

**Comment by kunaltyagi** [comment]
Please merge ASAP. CI is green for formatting

**Comment by taketwo** [comment]
Already on Dockerhub.

**Comment by kunaltyagi** [comment]
Pushed new version without my image

**Comment by kunaltyagi** [comment]
CI green with official image

**Pull request merged**
