### PR TITLE
Use system-installed cJSON, if available

### PR DESCRIPTION
**Pull request by mvieth**
Fixes https://github.com/PointCloudLibrary/pcl/issues/6080

### CODE REVIEW

**Comment by larshg** [comment]
Shouldn't we deprecate the use of the bundled cjson. If it expose a risk with no updates?

**Comment by mvieth** [comment]
> Shouldn't we deprecate the use of the bundled cjson. If it expose a risk with no updates?

I could add a CMake warning if no system cJSON is found, something like "It is recommended to install an up-to-date version of cJSON on your system. PCL contains an older version of cJSON, which may pose a risk and may be removed in a future PCL release." What do you think?

**Review by larshg — APPROVED** [review]

**Comment by larshg** [comment]
Doesn't seem to find cJSON on 20.04 - https://dev.azure.com/PointCloudLibrary/pcl/_build/results?buildId=24611&view=logs&j=149f4e41-9368-548e-d6d4-ff21d16f0ace&t=419be3d8-25a4-545d-da3e-1be8b204b16c&l=118 ?

**Comment by larshg** [comment]
No, I don't think so. Just wanted to mention it. I guess we should keep one of our CI's running with the bundled one, until we remove it.

**Comment by mvieth** [comment]
> I guess we should keep one of our CI's running with the bundled one, until we remove it.

As long as 20.04 is still running on the CI, we have one. After that, we could consider making the "ubuntu-variety" CI choose at random between system-installed cJSON and bundled one.

**Pull request merged**
