### PR TITLE
bugfixes for fpcs pairwise matching

### PR DESCRIPTION
**Pull request by theilerp**
This pull requests solves two minor bugs in the 4PCS matching method

(a) early termination using score threshold corrected: the threshold is automatically set to 1-approx_overlap_, but the case when this should happend (namely when no threshold is set) was wrong  --> corrected

(b) problem of openmp and rand usage solved: the standard rand method to generate random numbers is not thread save, thus each thread used in the method was based on the same random numbers and did thus produce the same results --> corrected by setting the random seed inside the parallel session

Anything I missed?

### CODE REVIEW

**Comment by taketwo** [comment]
Could you please look at the error Travis gives in "test" build?

**Comment by theilerp** [comment]
Forgot to place the new definition of the rng seed inside an openmp ifdef section. Didn't realize the error, because I always have activated openmp.

**Comment by taketwo** [comment]
Please squash and I'll merge.

**Comment by theilerp** [comment]
squashed and thanks

**Pull request merged**
