### PR TITLE
fix ply parsing comment and eof, fixes #3487

### LINKED ISSUE #3487: PLYReader fails to read without extra line at the end nor comment
## Your Environment
* Operating System and version: Ubuntu 18.04
* Compiler: GCC 7 
* PCL Version: Latest master

## Context
PLYReader fails to read ply file in a few simple scenarios.

## Code to Reproduce
```
int main(){
  pcl::PointCloud<pcl::PointXYZRGB> cld;

  pcl::PLYReader Reader;
  Reader.read("test1.ply", cld); // success
  // Reader.read("test2.ply", cld); // fail
  // Reader.read("test3.ply", cld); // fail
  // Reader.read("test4.ply", cld); // fail

  return 0;
}
```

test1.ply is the only scenario that it will read successfully
```
ply
format ascii 1.0
comment PCL generated
element vertex 3
property float x
property float y
property float z
property uchar red
property uchar green
property uchar blue
element camera 1
property float view_px
property float view_py
property float view_pz
property float x_axisx
property float x_axisy
property float x_axisz
property float y_axisx
property float y_axisy
property float y_axisz
property float z_axisx
property float z_axisy
property float z_axisz
property float focal
property float scalex
property float scaley
property float centerx
property float centery
property int viewportx
property int viewporty
property float k1
property float k2
end_header
127.97639 -267.0896 -900.87177 66 107 172
128.3494 -267.11069 -900.89008 65 103 172
128.06009 -267.20074 -901.63428 68 120 175
0 0 0 1 0 0 0 1 0 0 0 1 0 0 0 0 0 3 1 0 0

```

If we simply delete the last empty line from test1.ply to become test2.ply it fails
```
ply
format ascii 1.0
comment PCL generated
element vertex 3
property float x
property float y
property float z
property uchar red
property uchar green
property uchar blue
element camera 1
property float view_px
property float view_py
property float view_pz
property float x_axisx
property float x_axisy
property float x_axisz
property float y_axisx
property float y_axisy
property float y_axisz
property float z_axisx
property float z_axisy
property float z_axisz
property float focal
property float scalex
property float scaley
property float centerx
property float centery
property int viewportx
property int viewporty
property float k1
property float k2
end_header
127.97639 -267.0896 -900.87177 66 107 172
128.3494 -267.11069 -900.89008 65 103 172
128.06009 -267.20074 -901.63428 68 120 175
0 0 0 1 0 0 0 1 0 0 0 1 0 0 0 0 0 3 1 0 0
```

If we add a comment at the end as shown in test3.ply it also fails
```
ply
format ascii 1.0
comment PCL generated
element vertex 3
property float x
property float y
property float z
property uchar red
property uchar green
property uchar blue
element camera 1
property float view_px
property float view_py
property float view_pz
property float x_axisx
property float x_axisy
property float x_axisz
property float y_axisx
property float y_axisy
property float y_axisz
property float z_axisx
property float z_axisy
property float z_axisz
property float focal
property float scalex
property float scaley
property float centerx
property float centery
property int viewportx
property int viewporty
property float k1
property float k2
end_header
127.97639 -267.0896 -900.87177 66 107 172
128.3494 -267.11069 -900.89008 65 103 172
128.06009 -267.20074 -901.63428 68 120 175
0 0 0 1 0 0 0 1 0 0 0 1 0 0 0 0 0 3 1 0 0
comment test
```

Even if we add another empty line after the comment it still fails as shown in test4.ply
```
ply
format ascii 1.0
comment PCL generated
element vertex 3
property float x
property float y
property float z
property uchar red
property uchar green
property uchar blue
element camera 1
property float view_px
property float view_py
property float view_pz
property float x_axisx
property float x_axisy
property float x_axisz
property float y_axisx
property float y_axisy
property float y_axisz
property float z_axisx
property float z_axisy
property float z_axisz
property float focal
property float scalex
property float scaley
property float centerx
property float centery
property int viewportx
property int viewporty
property float k1
property float k2
end_header
127.97639 -267.0896 -900.87177 66 107 172
128.3494 -267.11069 -900.89008 65 103 172
128.06009 -267.20074 -901.63428 68 120 175
0 0 0 1 0 0 0 1 0 0 0 1 0 0 0 0 0 3 1 0 0
comment test

```

I can open all 4 scenarios without a problem in meshlab, and I think it should be reasonable to expect PCL to be able to handle this. For the 3 failure cases, the error message is all the same as below

```
[pcl::PLYReader] /home/jasjuang/test2.ply:37: parse error
[pcl::PLYReader::read] problem parsing header!
[pcl::PLYReader::read] problem parsing header!
```

When I look into the source code [here](https://github.com/PointCloudLibrary/pcl/blob/a2bedc96e0b7d1a19a6e92ca9292afe009251ae5/io/src/ply/ply_parser.cpp), there are multiple places that will trigger "parse error", can someone give me pointers on where should I look into in order to fix this problem?

### PR DESCRIPTION
**Pull request by jasjuang**
This PR fixes the problem as indicated in #3487. The fix from #3353 is also included here.

Fixes #3353 by superseding it

### CODE REVIEW

**Comment by kunaltyagi** [comment]
Can we add the failing case to PLY test suite such that master fails the test and this PR resolves it?

**Comment by jasjuang** [comment]
@kunaltyagi Can you give me a pointer on where in the codebase can I add the test?

**Comment by kunaltyagi** [comment]
Sure, the existing tests are in [test/io/test_ply_io.cpp](https://github.com/PointCloudLibrary/pcl/blob/master/test/io/test_ply_io.cpp)

**Comment by jasjuang** [comment]
@kunaltyagi It looks like gtest but for some reason, I couldn't find the test executable in my build folder. I checked the test folder, io folder, bin folder but it looks like none of them has it. Can you let me know how to invoke the test?

**Comment by kunaltyagi** [comment]
I have the following extra in my CMake invocation: `-DBUILD_global_tests=ON -DGTEST_SRC_DIR=/repo/googletest/googletest -DGTEST_INCLUDE_DIR=/repo/googletest/googletest/include/`

**Comment by jasjuang** [comment]
@kunaltyagi got it, my `BUILD_global_tests` was off by default. As for the detection of gtest, I suppose we should update it at some point. I use gtest for my own downstream project, and using it is as simple as:

```
find_package(GTest CONFIG REQUIRED)

add_executable(myTest ${MY_SRCS} ${MY_INCS})

target_link_libraries(myTest GTest::gtest_main)
```

There shouldn't be a need to specify the path for gtest.

**Comment by jasjuang** [comment]
@kunaltyagi I just realized that there doesn't seem to be a way to make pcl work with installed gtest... it requires a freshly cloned gtest source. We should definitely fix this at some point.

**Comment by kunaltyagi** [comment]
> my BUILD_global_tests was off by default

I figured. 😄 

> using it is as simple as: `find_package(GTest CONFIG REQUIRED)`

I don't have it installed globally. Don't want to do that really. Moreover, PCL uses it's own GTest finder, not the one supplied by CMake (that happened recently, well compared to PCL's usage)

**Comment by kunaltyagi** [comment]
> We should definitely fix this at some point.

I agree, but I don't have a lot of CMake Wizardry experience. Feel free to create a PR (or at least an issue) though 😆

**Comment by jasjuang** [comment]
@kunaltyagi what's the main reason for not wanting to install gtest globally? All of your other external dependencies like vtk, flann is installed globally, right?

**Comment by kunaltyagi** [comment]
> what's the main reason for not wanting to install gtest globally?

Different projects using different versions. I don't really have global installs. FLANN is global, but not VTK. I have 2 VTK (one for paraview, one for vtk, since both supply common files and aren't compatible with each other, but I need both)

**Comment by jasjuang** [comment]
Ok, I will try to finish adding the test first, for the gtest PR, do we want to fully migrate to using installed gtest and remove the current way of discovering gtest? I find it weird to have to refer to a 3rd party source repo for its build. Even referencing to a locally installed 3rd party library makes more sense to me. For your case, I am sure you are referring to locally installed VTK, instead of the VTK source.

**Comment by kunaltyagi** [comment]
> I find it weird to have to refer to a 3rd party source repo for its build

Not really. A lot of CMake works so that you can have one source, and multiple projects using it with their own flags. That's not common for people, but for "package managers" this is quite common.

> do we want to fully migrate to using installed gtest and remove the current way of discovering gtest

I was thinking more on the lines of letting CMake discover it on its own, but I don't know if it works with source or only an install.

**Comment by jasjuang** [comment]
@kunaltyagi added the tests as requested

**Comment by jasjuang** [comment]
I am not exactly sure how to make cmake auto-detect whether it should pick gtest source or installed gtest. I will just file an issue for now.

**Comment by taketwo** [comment]
@kunaltyagi what's your opinion about this https://github.com/PointCloudLibrary/pcl/pull/3353#issuecomment-534549336?

**Comment by kunaltyagi** [comment]
Regarding the bad-parse, it might be possible to do both:

* inform that there was a bad-parse
* try to return something usable in case of error

Usual assumptions for UI is to attempt to work (eg: corrupted documents in OpenOffice). On the other hand, I don't like libraries returning half-baked outputs without any signal to the user. There might be a middle ground but I don't know if this requires more extensive changes.

Give me tomorrow and I will have a better answer than this hand-waving

**Comment by kunaltyagi** [comment]
The `eof` check could just be made to return true at the end (see my PR) and there's no need to do that check inside the element read loop which might return true despite there being lesser elements. Didn't add the test but this PR would return true for a file with truncated elements. There's a `fail` check, and I don't know if I should remove that.

**Pull request closed without merging**
