### PR TITLE
Compatibility reports generation script

### PR DESCRIPTION
**Pull request by SergioRAgostinho**
A new useful script to generate the ABI compatibility reports scripts in a single go 💯

One more step in speeding up releases. I'm crunching the reports now and I'll upload them later.

### CODE REVIEW

**Comment by SergioRAgostinho** [comment]
Here they are. 
[abi_reports.zip](https://github.com/PointCloudLibrary/pcl/files/2342552/abi_reports.zip)

**Comment by SergioRAgostinho** [comment]
# Comment Reports

Some of them are spot on. I think this version of the tool still has some minor problems.

## Common

- We added an number of const qualifiers to `parse.cpp` functions.

## Features

- We removed a member `negative_` from `StatisticalOutlierRemoval<PCLPointCloud2>`.
- Weirdly enough, it's also reporting changes in SAC headers for a number of symbols.

## IO

- Removed members from `HDLGrabber`.
- Changed types on some methods from `HDLGrabber`.

## Octree

- We renamed some iterator names. I think we typedefed things. It appears as low severity.
- We modified the type of `Iterator::depth_`

## Recognition

- Reporting broken symbols from SAC and Registration.

## Registration

- We added some attributes to `Registration` and they won't be initialized unless people recompile.

## Sample Consensus

- We added `const` qualifier on a number of methods.

## Segmentation

- It complains with `getPointCloudDifference` for having removed the parameters although in theory we deprecated it. This one is strange.

## Surface

- The `MovingLeastSquares` class suffered profound changes.
- `MarchingCubes` had some members removed.

## Visualization

- We removed the `PCLVisualizer::addCoordinateSystem()` method apparently, although we actually didn't.

**Comment by SergioRAgostinho** [comment]
[abi-reports.tar.gz](https://github.com/PointCloudLibrary/pcl/files/2377189/abi-reports.tar.gz)

**Comment by SergioRAgostinho** [comment]
[compat_reports.zip](https://github.com/PointCloudLibrary/pcl/files/2428310/compat_reports.zip)

Latest version of the compatibility reports. I think this script is good to go for now.  It is missing proper error checking and abortion routines when things fail but we can tweak those later.

**Comment by taketwo** [comment]
The script looks good and we don't have any bash coding standards anyway. However I haven't tried to use it myself. Do you think it's needed? Or OK to merge as is?

**Comment by SergioRAgostinho** [comment]
> Do you think it's needed? Or OK to merge as is?

Well… to be fully honest, the first time you run things and don’t have all the required tools things can get ver criptic until you realize what is actually missing. It’s kinda half-baked, so probably not gonna be a good idea to merge it if we expect our users to use it. 

The challenge now is recreating a bare environment without any of these tools. I have to figure out if chroot is enough to solve this problem or if something more advanced is required.

**Comment by taketwo** [comment]
I've tried this on my not-so-bare Ubuntu 16.04 environment and the only packages that I was missing are `abi-dumper` and `abi-compliance-checker`.

**Comment by taketwo** [comment]
Add something like this on top?

```bash
if ! hash abi-dumper2 2>/dev/null || ! hash abi-compliance-checker 2>/dev/null; then
  echo "This script requires abi-dumper and abi-compliance-checker"
  echo "On Ubuntu: apt-get install abi-dumper abi-compliance-checker"
  exit 1
fi
```

**Comment by jspricke** [comment]
Just for reference, PCL ABI is tracked here as well: https://abi-laboratory.pro/index.php?view=timeline&l=pcl

**Comment by taketwo** [comment]
Yeah, we have this link in our README actually. However it's not up to date, the latest status is reported for some random point in time in May.

**Comment by SergioRAgostinho** [comment]
Latest reports 

[compat_reports.zip](https://github.com/PointCloudLibrary/pcl/files/2472562/compat_reports.zip)

**Comment by taketwo** [comment]
Sorry that I bring this up now, what about rename `generate_reports.sh` -> `generate_abi_reports.sh`? And probably squash everything into a single commit?

**Pull request merged**
