### PR TITLE
Add Link zlib Library

### PR DESCRIPTION
**Pull request by UnaNancyOwen**
Fail build when enable the WITH_PNG option, because libpng required zlib.
Resolved this issue by add zlib to additional dependencies.

### CODE REVIEW

**Comment by VictorLamoine** [comment]
PCL builds fine on my side without the fix.

```cmake
//Path to a library.
PNG_LIBRARY_DEBUG:FILEPATH=PNG_LIBRARY_DEBUG-NOTFOUND

//Path to a library.
PNG_LIBRARY_RELEASE:FILEPATH=/usr/lib/x86_64-linux-gnu/libpng.so

//Path to a file.
PNG_PNG_INCLUDE_DIR:PATH=/usr/include

//PNG file support
WITH_PNG:BOOL=ON
```

**Comment by UnaNancyOwen** [comment]
Hi Victor Lamoine,

Sorry, I have tried on the MSVC.
Might be no problem in other environments (Linux, Mac).
Fixed to be valid only on the MSVC.

**Comment by VictorLamoine** [comment]
Oh ok; I can't test for MSVC.
Please squash your commits.

**Comment by UnaNancyOwen** [comment]
Sorry, I don't know well how to squash.
I close the this pull request, and will again pull request.
(to not pollute the git history.)
Is this OK?

**Comment by VictorLamoine** [comment]
Hey, it's quite simple actually, you don't have to close pull request to update them (now it's too late).
Considering you have two remotes:
origin: your fork
upstream: pcl repository

```
git rebase -i upstream/master
```

This will open a text editor, replace `pick` by `s` (or `squash`) and then save the editor.
After that, an other windows open with the commit message, edit it as you like and save.

It's a good pratice to verify you have done nothing wrong by checking `git log --oneline | head -n10`
When you are done, just push again the modifications with `git push -f`, the pull request will update automatically.

**Comment by UnaNancyOwen** [comment]
Sorry, I had already finished send of the [pull request](https://github.com/PointCloudLibrary/pcl/pull/1250) again.
I am deeply sorry for any trouble that I have caused.

**Comment by VictorLamoine** [comment]
No problem! For the future, try the commands that I sent and don't hesitate to ask if you have any problem (just don't close the pull request, its cleaner)

**Pull request closed without merging**
