### PR TITLE
Refactor AgastDetector5_8_computeCornerScore

### PR DESCRIPTION
**Pull request by SunBlack**
I splittet changes into multiple commits, hopefully you can follow all changes. I used [this code](https://github.com/PointCloudLibrary/pcl/pull/2657#issuecomment-442884061) to verify I didn't changed behavior.

### CODE REVIEW

**Comment by taketwo** [comment]
Oh God! I hope you had fun at least :)

I appreciate how you partitioned this into well-explained commits, but I got lost nevertheless. Will have to trust your verification code again. By the way, how much time your verification code takes to run?

This refactoring reminded me of a project that I had to do in my Bachelors studies for Discrete Mathematics course. We were given a huge table describing a binary function with multiple parameters. The task was to write it as a single logical expression. And the catch was that only few (two?) operations were allowed, e.g. NAND and NOT. (This was supposed to show us how to design simple circuits with a limited set of logical gates.)  Of course we had to do all this by hand. Royal pain in the ass.

**Comment by SunBlack** [comment]
> Oh God! I hope you had fun at least :)

The fun will start with `AgastDetector7_12s_computeCornerScore` 😆 . Not sure if I'll optimize the other functions like this as well (If you wish to train your brain: reorder the conditions xD). Was something thinking about to write a program to rewrite the code (build a truth table and then work with it) - but wasn't sure if this will be faster than manual rewrite.

> I appreciate how you partitioned this into well-explained commits, but I got lost nevertheless.

I believe you got lost at reordering commits?

> Will have to trust your verification code again. By the way, how much time your verification code takes to run?

I was happy that I had this code. Sometimes I did a mistaken (no idea why a test failed on Mac) ;). The code is fast enough, so it is not important (6.5ms if I use cpp.sh)

> This refactoring reminded me of a project that I had to do in my Bachelors studies for Discrete Mathematics course. We were given a huge table describing a binary function with multiple parameters. The task was to write it as a single logical expression. And the catch was that only few (two?) operations were allowed, e.g. NAND and NOT. (This was supposed to show us how to design simple circuits with a limited set of logical gates.) Of course we had to do all this by hand. Royal pain in the ass.

😆 I've been thinking about cutting everything into one query, but believed it will be unreadable after this as before - just in another way.

**Comment by SergioRAgostinho** [comment]
Sir, you are a masochist.

**Comment by SunBlack** [comment]
> Sir, you are a masochist.

😆 I just don't want to lose any more hair by thinking about there is still code using `goto` (the PCL has enough examples of bad code or ugly coding style)

**Comment by SergioRAgostinho** [comment]
You have my kudos for the commit strategy and messages. This review would be impossible otherwise. I have a Mac platform so I can try to bisect the offending commit which broke the tests. I stopped at the reordering commits for now (no surprise), I'll have to continue from that later.

**Comment by SunBlack** [comment]
I found the issue in my test code and fixed the test.

**Comment by SergioRAgostinho** [comment]
I'm very inclined to merge this PR as is, no squashing, agreed? Otherwise, other "victims" who decide to traverse the commit history won't have the commit messages as anchor points.

**Pull request merged**
