### PR TITLE
Add `MSVC_MP` CMake option to adjust number of parallel build jobs

### PR DESCRIPTION
**Pull request by SunBlack**

### CODE REVIEW

**Comment by SunBlack** [comment]
> Are you sure you can remove that version check on `MSVC`

See https://github.com/PointCloudLibrary/pcl/pull/2690#issuecomment-445224381. Since C++14 is now necessary we require at least VS 2015 (MSVC_VERSION 1900) now.

I will check you suggestion. Looks indeed better :).

**Comment by SunBlack** [comment]
Tested it: And it works :).

Side node: MSVC seems to ignore passed process count and only differ between with and without `/MP`. But I'm not sure if it is a UI error of VS or not. But [documentation](https://docs.microsoft.com/en-us/previous-versions/bb385193(v=vs.140)) says we can pass processor count...

**Comment by SunBlack** [comment]
> After reading the documentation I noticed that one can pass `/MP1` which makes the `elseif()` useless.

I was thinking about it, too. But I there was a decision: Add a useless flag (`MP1`) or add two more CMake lines and prevent useless flag ;).

> Also I'm questioning if `USE_MSVC_MP` is the best name to use here, since it gives the idea that is a binary var from the name. Maybe remove the prefix `USE_`?

I added `USE_` before so it is in same group like `USE_PROJECT_FOLDERS`. But we could also start a group `MSVC`.

> Finally, our CI might blow-up out of memory if we don't tweak the number of compilations processes running, but we can tweak that later.

I didn't changed behavior to the state of pre-PR.

**Comment by SergioRAgostinho** [comment]
> I was thinking about it, too. But I there was a decision: Add a useless flag (`MP1`) or add two more CMake lines and prevent useless flag ;). And I didn't tried what happens in case someone enters `-1` (if it will be ignored then or cause a compiler issue)

Makes sense. With the current logic, it will be ignored.

> I added `USE_` before so it is in same group like `USE_PROJECT_FOLDERS`. But we could also start a group `MSVC`.

In this case better go with the `MSVC` group. `USE_blah` should be binary in my opinion.

> I didn't changed behavior to the state of pre-PR.

From the logic it seems that by default it will always try to use the number if gets from `ProcessorCount()`. Everything went ok, so it is not a problem.

**Comment by SunBlack** [comment]
> > I added `USE_` before so it is in same group like `USE_PROJECT_FOLDERS`. But we could also start a group `MSVC`.
> 
> In this case better go with the `MSVC` group. `USE_blah` should be binary in my opinion.

What do you prefer as new name `MSVC_MP`, `MSVC_simultaneously_compilers` or whatever?
 
> From the logic it seems that by default it will always try to use the number if gets from `ProcessorCount()`. Everything went ok, so it is not a problem.

As before ;)

**Comment by SergioRAgostinho** [comment]
`MSVC_MP` works for me. The docstring is pretty clear.

> As before ;)

Oh, true.

**Comment by taketwo** [comment]
LGTM, but I'm not a MSVC user.

**Pull request merged**
