### PR TITLE
Bug fix in estimation of the min/max elements/vectors in pcl::eigen33 

### PR DESCRIPTION
**Pull request by lamouski**
**Maintainer Edit**: See https://github.com/PointCloudLibrary/pcl/pull/3057#issuecomment-491711126

### CODE REVIEW

**Comment by SergioRAgostinho** [comment]
Thank you for contributing this. Would you mind writing a unit test which exposes the problem you just fixed?

**Comment by lamouski** [comment]
> Thank you for contributing this. Would you mind writing a unit test which exposes the problem you just fixed?
Yes, Sure. I need some time for this.

**Comment by taketwo** [comment]
What about pulling these lines out of the `if-else` construct? Would be no bug if this was implemented this way from the beginning:

```cpp
min_el = mmax[0] <= mmax[min_el] ? 0 : min_el;
max_el = mmax[0] > mmax[max_el] ? 0 : max_el;
```

**Comment by lamouski** [comment]
> What about pulling these lines out of the `if-else` construct? Would be no bug if this was implemented this way from the beginning:

Its sounds reasonable. It is nessusary then also correct another case:

`min_el = mmax[1] <= mmax[min_el] ? 1 : min_el;
max_el = mmax[1] > mmax[max_el] ? 1 : max_el;`

I'll try it.

**Comment by taketwo** [comment]
@jpsml are you still around? We have this pending bugfix for `eigen33()`. It seems to affect your GASD descriptor and consistently fail respective unit test (please see CI results). Since the unit test compares with hard-coded numbers which you generated, it's hard for us to decide what to do about it. Should we just update the numbers to match the current output?

**Comment by lamouski** [comment]
I want to add some background information.
Main effect of this "bug" is that the direction of the eigenvectors can be inversed in the case if the max element is estimated not correctly. 
Actually i had anothe problem. Namely the normal of the plane was computed incorrect if huge amount of points were used. The problem was in the float-type covariance matrix for eigen vector estimation. This matrix seem to be bad conditioned in case of huge amount of points because the low float accuracy. 
During the code investigation i have found the inconsistency in the eigen33 function. The correction of that inconsistency was  then issued as this bug fix.

**Comment by taketwo** [comment]
@lamouski thanks for the explanation. In fact, I was about to request you to separate the precision fix into a separate PR because these two things are independent.

**Comment by jpsml** [comment]
@taketwo, yes, I believe that the best thing to do is to just update the numbers to match the current output.

**Comment by lamouski** [comment]
@jpsml, thanks. I will do it.

**Comment by lamouski** [comment]
As i told, I just found the inconsistency in the code during solwing of enother problem. I have already prepared some portion of the test code. I am not 100% sure in it because the theoretical background is not completly clear for me. But I comit it in order to give more information.

**Comment by SergioRAgostinho** [comment]
Please do. If you're not sure if it relevant to this PR, commit it first on a separate branch of your fork and post the url for me to have a look at. My plan is to grab your data, supply it to Eigen or numpy and compare vs what eigen33 is returning. Hopefully this exhibit the problem.

**Pull request closed without merging**
