### PR TITLE
Hotfix for multiple declarations in 1.12

### LINKED ISSUE #4882: [pcl 1.12 /surface] duplicate definition of plc::mlsresult::calculatePrincipalCurvatures (const double u, const double v) const;
My code works fine with pcl.1.11.1, however when i update to the pcl 1.12, "duplicate definition of plc::mlsresult::calculatePrincipalCurvatures (const double u, const double v) const;" happens.
I think the name of function calculatePrincipalCurvatures is changed,  corrected from Principle? #4505

**To Reproduce**

include<pcl/surface/mls.h> or include <pcl/surface/impl/mls.hpp>
 "duplicate definition of plc::mlsresult::calculatePrincipalCurvatures (const double u, const double v) const;" is showed at link time.

**Your Environment (please complete the following information):**

 - OS: [e.g. Ubuntu 20.04]
 - Compiler: [ GCC 8.1]
 - PCL Version [1.12, and latest from git]

**Possible Solution**

this commit may related with this bug
https://github.com/PointCloudLibrary/pcl/commit/a3a4ee918094b94c8ef10dc360d1aeb2803da36f

**Additional context**

### PR DESCRIPTION
**Pull request by kunaltyagi**
Fixes #4882

### CODE REVIEW

**Review by cdb0y511 — APPROVED** [review]
Hotfix for multiple declarations in 1.12.

**Review by cdb0y511 — APPROVED** [review]

**Comment by mvieth** [comment]
If I remember correctly, we tried to make `calculatePrincipalCurvatures` inline in the original pull request, but it failed to build there as well, so we decided against that. Two options I see:
1. Make `calculatePrincipalCurvatures` inline and actually move the implementation from mls.hpp to mls.h, then it should compile and no duplicate-definition-error should occur. Disadvantage: more code in the header file
2. Make `calculatePrincipalCurvatures` inline and keep the implementation code in mls.hpp, but move the implementation of `calculatePrincipleCurvatures` from mls.h to mls.hpp. Disadvantage: two places to consider when removing `calculatePrincipleCurvatures`, but that should be manageable.

**Comment by larshg** [comment]
I guess solution 2 would be best. Just add a reminder that one need to remove the respectively places.

**Comment by mvieth** [comment]
I hope it is okay that I push to your branch, Kunal, otherwise feel free to remove my commits again :smile: I just want to see whether the solution works, so we can hopefully merge it soon

**Review by mvieth — APPROVED** [review]
I tested this and it fixes the duplicate definition error

**Review by larshg — APPROVED** [review]

**Comment by mvieth** [comment]
I thought a bit more about this, and it unfortunately breaks ABI by making `calculatePrincipalCurvatures` inline (previously, the compiled function was in the library and could be linked to, but when it is inline, it is not in the library, possibly leading to symbol-not-found errors). So we could delay this until 1.13.0, or we test another solution: Moving the implementation of `calculatePrincipalCurvatures` from mls.hpp to mls.cpp

**Comment by larshg** [comment]
Closing in favor of #5049.

**Pull request closed without merging**
