### PR TITLE
Fix registration unit tests

### PR DESCRIPTION
**Pull request by jspricke**

### CODE REVIEW

**Comment by taketwo** [comment]
I think it is `GeneralizedIterativeClosestPoint6D` test that segfaults...

**Comment by jspricke** [comment]
Let's see how this one goes. Interestingly I got completely different errors on my system, so I predict quite some new failing unit tests once we update the CI systems ;).

**Comment by jspricke** [comment]
This is ready from my side

**Comment by taketwo** [comment]
Amazing to see Travis green again! Thanks!

**Pull request merged**
