### PR TITLE
Fix of IterativeClosestPointWithNormals shared_ptr

### LINKED ISSUE #4416: [icp.h] IterativeClosestPointWithNormals shared_ptr is of type IterativeClosestPoint
**Describe the bug**
I try to pass a shared_ptr of different ICPs arround. With GICP this works like a charm. But with IterativeClosestPointWithNormals the pointer type always falls back to IterativeClosestPoint Class.
Therefore I can not `setUseSymmetricObjective(true)` on that shared_ptr.

**Context**

Pass IterativeClosestPointWithNormals as shared_ptr to a function.

**Expected behavior**

The expected behavior can be seen with GICP which is also based on IterativeClosestPoint but has its own shared_ptr definition.

**Current Behavior**

The IterativeClosestPointWithNormals::Ptr is of type IterativeClosestPoint.

**Screenshots/Code snippets**

```C++
template<typename PointType>
void parametrize(typename pcl::IterativeClosestPointWithNormals<PointType,PointType>::Ptr& icp) {

	std::cout << " class name " << icp->getClassName() << std::endl; // prints IterativeClosestPointWithNormals correctly
	icp->setUseSymmetricObjective(true); // compilation fails because of type IterativeClosestPoint
}

int main() {
pcl::IterativeClosestPointWithNormals<pcl::PointNormal,pcl::PointNormal>::Ptr icp_n (new pcl::IterativeClosestPointWithNormals<pcl::PointNormal,pcl::PointNormal>);
parametrize<pcl::PointNormal>(icp_n);
}
```

**Your Environment (please complete the following information):**

 - OS: [e.g. Ubuntu 20.04]
 - PCL Version [1.11]

**Possible Solution**

In icp.h starting with line 333:

```C++
      using Ptr = shared_ptr<IterativeClosestPoint<PointSource, PointTarget, Scalar> >;
      using ConstPtr = shared_ptr<const IterativeClosestPoint<PointSource, PointTarget, Scalar> >;

```
change to

```C++
      using Ptr = shared_ptr<IterativeClosestPointWithNormals<PointSource, PointTarget, Scalar> >;
      using ConstPtr = shared_ptr<const IterativeClosestPointWithNormals<PointSource, PointTarget, Scalar> >;

```
as GICP does in gicp.h line 99f.:
```C++
      using Ptr = shared_ptr< GeneralizedIterativeClosestPoint<PointSource, PointTarget> >;
      using ConstPtr = shared_ptr< const GeneralizedIterativeClosestPoint<PointSource, PointTarget> >;

```

### PR DESCRIPTION
**Pull request by PerceptMD**
Closes #4416

Recreated because I messed up my branches.

Futher enhancement by: https://github.com/PointCloudLibrary/pcl/pull/4421

### CODE REVIEW

**Comment by kunaltyagi** [comment]
Shall we focus on #4421 and merge that one directly?

**Comment by PerceptMD** [comment]
I would recommend to merge this here quickly as it is an error in the API of ICP with Normals.
Then do the refactoring of all ICP classes in a clean way when possible.

**Comment by larshg** [comment]
Well, it would only help those who build from source to get this merged fast. I would vote to just do #4421.

**Review by mvieth — APPROVED** [review]
Thanks!

**Pull request merged**
