### PR TITLE
[ci] Add UINT64 indices to release CI to check when 1.12 is "ready"

### PR DESCRIPTION
**Pull request by kunaltyagi**

### CODE REVIEW

**Comment by larshg** [comment]
Can we make the release pipeline run with this PR?

Anyways, it seems right. I'm not that familiar with azure piplines and --build-args though.

**Comment by kunaltyagi** [comment]
Yeah. I ran them on my personal CI: https://kunaltyagi.visualstudio.com/pcl/_build/results?buildId=689&view=results

**Comment by larshg** [comment]
Nice, so there are work to be done I can see.

**Comment by kunaltyagi** [comment]
This is just a PR to make sure we don't release before all modules that are traditionally shipped are ready

**Review by larshg — APPROVED** [review]

**Review by mvieth — APPROVED** [review]

**Pull request merged**
