### PR TITLE
Fix alpha channel in tests clouds

### PR DESCRIPTION
**Pull request by VictorLamoine**
All alpha values are now set to `255`
I also compressed `five_people.pcd` (12.7 Mb to 2.0 Mb)

See https://github.com/PointCloudLibrary/pcl/pull/1144#issuecomment-78879524

### CODE REVIEW

**Comment by VictorLamoine** [comment]
It seems like the new point clouds make PCL PLY reader crash.. :disappointed:

**Comment by taketwo** [comment]
Any update here? Do you have any idea what's the reason?

**Comment by VictorLamoine** [comment]
Well it's surely our issues with PLY format support again!

**Comment by VictorLamoine** [comment]
Ready to be merged, the recent PLY fixes makes these files ok now!

**Pull request merged**
