### PR TITLE
Added openni2 live stream compatability to kinfu

### PR DESCRIPTION
**Pull request by msalvato**

### CODE REVIEW

**Comment by jspricke** [comment]
+1

**Comment by taketwo** [comment]
The `source_cbXXX` functions seem to be the same except to image type. Perhaps it makes sense to just template them on the image type?

Also, can we add a short description of the new option to `print_cli_help ()`?

**Comment by PlayerUsr** [comment]
Added openni2 live stream compatability to kinfu : is not work because capteur.cpp is with grapper openni1 !!!

**Comment by msalvato** [comment]
Sorry everyone that I dropped the ball on this way back, glad someone else implemented the fix it looks like.

**Pull request closed without merging**
