### PR TITLE
Fix VTK path and version number in cmake file

### PR DESCRIPTION
**Pull request by UnaNancyOwen**
Fix difference path and version number by VTK version.
VTK6 : VTK/lib/**cmake**/vtk-6.x
VTK5 : VTK/lib/vtk-5.x

### CODE REVIEW

**Comment by jspricke** [comment]
Where do you take this paths from?

**Comment by UnaNancyOwen** [comment]
CMake files of VTK is included in under the directory (VTK_INSTALL_PACKAGE_DIR).
VTK6 : [CMakeLists.txt#L235](https://github.com/Kitware/VTK/blob/v6.3.0/CMakeLists.txt#L235)
VTK5 : [CMakeLists.txt#L233](https://github.com/Kitware/VTK/blob/v5.10.1/CMakeLists.txt#L233)

**Comment by jspricke** [comment]
But those are package installiert paths whereas the ones in the config are hints for the all in one installer which was especially prepared back then. Do you have a specific use case for them?

**Comment by UnaNancyOwen** [comment]
Yes, I generate and distributing the All-in-one Installer in [my blog](http://unanancyowen.com/?p=1255&lang=en). (because, All-in-one Installer that distributing at the official site is so old.)
This change is needed for generating project using CMake.

**Comment by taketwo** [comment]
BTW, we plan to release 1.8.0 soon. @UnaNancyOwen if you can take care of producing new installers, I think we will be happy to make them "official".

**Comment by UnaNancyOwen** [comment]
@taketwo That is excellent! > "release 1.8.0 soon"
I will cooperate for yours as much as I can.
BTW, Who is the PCL maintainer for Windows?

**Comment by jspricke** [comment]
Great initiative, would be awesome to have installers again.

**Comment by jspricke** [comment]
There is no Windows maintainer, do you want to step up?

**Comment by jspricke** [comment]
..let's discuss this on pcl-dev@, can you send a mail?

**Comment by UnaNancyOwen** [comment]
@jspricke I see, I will send an e-mail.

**Pull request merged**
