### PR TITLE
Remove redundant calls to std::string::c_str()

### PR DESCRIPTION
**Pull request by SunBlack**
Changes are done by: `run-clang-tidy -header-filter='.' -checks='-,readability-redundant-string-cstr' -fix`

### CODE REVIEW

**Comment by SunBlack** [comment]
> Should we have the clang-tidy checks part of the formatting CI?

Clang-Tidy has nothing to do with formatting. Nevertheless it would be nice if it would be part of the build CI. I just don't have the time to write an parser from Clang-Tidy output to Azure Tests results format.

**Comment by kunaltyagi** [comment]
Sorry, I meant "static analysis" tests, which currently only performs formatting check.

> I just don't have the time to write an parser from Clang-Tidy output to Azure Tests results format.

We don't need to parse the output, right? Simply following the current method of running the tool to fix, getting the diff (if non-empty) would be sufficient to detect an issue. The display of diff and other work is already done by @taketwo

**Comment by SunBlack** [comment]
> We don't need to parse the output, right? Simply following the current method of running the tool to fix, getting the diff (if non-empty) would be sufficient to detect an issue. The display of diff and other work is already done by @taketwo

A lot of checks doesn't have an automatic `-fix` option, so parsing output is the better way. Of course we could also check if the error log is empty as first step, but I believe a simple yml to xml skript is still better.

**Comment by kunaltyagi** [comment]
> I believe a simple yml to xml skript is still better.

Sure, that sounds simple enough... Maybe combining [PyYAML](https://pypi.org/project/PyYAML/) and [dict2xml](https://pypi.org/project/dict2xml/) will do the trick. I'll try something over the holidays maybe. Meanwhile, Happy Holidays and New Year 😄

**Comment by kunaltyagi** [comment]
@SunBlack I've been unable to use the `-export-fixes fixes.yml` option.  Do you have any insights?

I'm using `run-clang-tidy.py` from HEAD, and your command

**Comment by SunBlack** [comment]
A reverse seach in my terminal showed me `run-clang-tidy-8 -header-filter='.*' -checks='-*,misc-misplaced-const' -export-fixes=/media/sf_pcl/clang-tidy_result.yaml` as last time I used it.

But maybe try first if `run-clang-tidy` is really working, as I have usally some trouble at first becausing of missing python dependencies. You could e.g. test it via `run-clang-tidy -header-filter='.*' -checks='-*,modernize-use-override' -fix` as we don't use `override` for deconstructors in this framework, so clang-tidy will be definitely change something.

**Pull request merged**
