### PR TITLE
Fix cmake warnings

### PR DESCRIPTION
**Pull request by larshg**
LibUSB-1.0 warning:
```
CMake Warning (dev) at C:/Program Files/CMake/share/cmake-3.17/Modules/FindPackageHandleStandardArgs.cmake:272 (message):
  The package name passed to `find_package_handle_standard_args` (LIBUSB_1)
  does not match the name of the calling package (libusb-1.0).  This can lead
  to problems in calling code that expects `find_package` result variables
  (e.g., `_FOUND`) to follow a certain pattern.
Call Stack (most recent call first):
  cmake/Modules/Findlibusb-1.0.cmake:68 (find_package_handle_standard_args)
  C:/vcpkg/scripts/buildsystems/vcpkg.cmake:329 (_find_package)
  CMakeLists.txt:308 (find_package)
This warning is for project developers.  Use -Wno-dev to suppress it.
```
Ensenso warning:
```
CMake Warning (dev) at C:/Program Files/CMake/share/cmake-3.17/Modules/FindPackageHandleStandardArgs.cmake:272 (message):
  The package name passed to `find_package_handle_standard_args` (ENSENSO)
  does not match the name of the calling package (Ensenso).  This can lead to
  problems in calling code that expects `find_package` result variables
  (e.g., `_FOUND`) to follow a certain pattern.
Call Stack (most recent call first):
  cmake/Modules/FindEnsenso.cmake:41 (find_package_handle_standard_args)
  C:/vcpkg/scripts/buildsystems/vcpkg.cmake:329 (_find_package)
  cmake/pcl_targets.cmake:836 (find_package)
  CMakeLists.txt:317 (PCL_ADD_GRABBER_DEPENDENCY)
This warning is for project developers.  Use -Wno-dev to suppress it.
```

### CODE REVIEW

**Comment by larshg** [comment]
Just a quick question before I continue this journey. I'm trying to follow cmakes quidelines: https://cmake.org/cmake/help/v3.11/manual/cmake-developer.7.html#standard-variable-names

So instead of makine all names uppercase, they will be what they are defined in the filename, ie. 
* ClangFormat
* davidSDK
* DSSDK
* Eigen
* Ensenso
* FLANN
* GTestSource
* libusb-1.0
* OpenNI
* OpenNI2
* PCAP
* Qhull
* RSSDK
* RSSDK2
* Sphinx

Are there any suggestions to name changes?

libusb-1.0 -> usb-1.0 / usb10 etc.?
Qhull -> QHULL?

Should we make all UPPER CASE?

**Comment by kunaltyagi** [comment]
IMO, it's the difference between using the official project name (Qhull, OpenNI2, etc.) and names hard to misspell (QHULL: Qhull, QHull; OPENNI2: OpenNi2, OpenNI2, etc.)

Both are ok in the code, but the official names are a lot better for warnings, and messages. (I don't write or deal with CMake a lot, so take my comment with a cart of salt)

**Comment by SergioRAgostinho** [comment]
I don't recall exactly why the uppercase was needed in the first place (@taketwo  usually has that answer at the tip of his tongue) but I suspect our PCLConfig.cmake will need to be checked because it relies on that UPPERCASE assumption. 

I have no issues with the name changes but I suspect this is going to open a big can of worms which will require testing over a couple of release candidates.

**Comment by larshg** [comment]
>but I suspect our PCLConfig.cmake will need to be checked because it relies on that UPPERCASE assumption.

Indeed I have already made some changes - yet tutorials is not building yet, so I got more changes to do :)

> I have no issues with the name changes but I suspect this is going to open a big can of worms which will require testing over a couple of release candidates.

Yes, there are still changes to be done, missing optional dependencies etc. 

I'll try add all the name changes, without removing the TOUPPER, then the last switch will be to just remove all TOUPPER cases.

**Comment by larshg** [comment]
Its also possible to do this minimal change to avoid the warning, but it really doesn't fix the variables that will be defined with UPPERCASE, ie:

`find_package_handle_standard_args(LIBUSB_1 DEFAULT_MSG LIBUSB_1_LIBRARY LIBUSB_1_INCLUDE_DIR)`

to:

`find_package_handle_standard_args(libusb-1.0 DEFAULT_MSG LIBUSB_1_LIBRARY LIBUSB_1_INCLUDE_DIR)`

However, one searching for libusb-1.0 should be able to assume the variables libusb-1.0_INCLUDE_DIR would be set, but in PCLs findlibusb-1.0 it would end up being LIBUSB_1_INCLUDE_DIR etc.

So is it worth spending the time to do all the name changes? :smile:

**Comment by SergioRAgostinho** [comment]
I would say for this PR just focus on the minimal changes which suppress the warnings. 

> So is it worth spending the time to do all the name changes? 😄

It's not a priority for me at the moment. There's an additional discussion down the road which @shrijitsingh99 initiated, on how PCL is overriding find package scripts by exporting its own finder scripts when used in cmake downstream projects. I suspect that one will have a direct impact in the naming convention as well and I would rather bundle both points in the same discussion.

**Comment by larshg** [comment]
Closing this for another time another day 😄

**Pull request closed without merging**
