### PR TITLE
Format include/pcl/registration/*.h

### PR DESCRIPTION
**Pull request by JStech**
Follow-on to #4448, with all *.h headers included.

### CODE REVIEW

**Comment by kunaltyagi** [comment]
Running format on this modifies distances.h

**Comment by JStech** [comment]
So it does. Updated.

**Review by kunaltyagi — APPROVED** [review]

**Comment by larshg** [comment]
@JStech can you resolve conflicts :-)

**Review by larshg — APPROVED** [review]
I skimmed the majority of files, but I rely highly on the passed CI :)

**Comment by kunaltyagi** [comment]
I did a git diff with a local format copy, can confirm this works :)

**Pull request merged**
