### PR TITLE
Check for empty container via .empty() instead of with .size()

### PR DESCRIPTION
**Pull request by SunBlack**
Changes are done by `run-clang-tidy -header-filter='.*' -checks='-*,readability-container-size-empty' -fix`

### CODE REVIEW

**Comment by SunBlack** [comment]
> Would it be possible to perform a find-replace to change from `empty()` to `empty ()`. Because as it is, we are accepting a PR that breaks PCL's coding style with every change it introduced :/

Well if I replace all `.empty()` by `.empty ()`, this will be 389 changes. You really want this in this PR?

Btw: This is the part of the coding style that I really don't like at all. I don't have an idea until now, which benefit we got by a whitespace before a bracket (for me it decreases readability).

**Comment by SunBlack** [comment]
Ups wrong button, didnt' wanted to close this PR xD

**Comment by taketwo** [comment]
Yes, this whitespace was a notorious choice for the style guide. (Not made by any of us who are currently active in PCL.) I think when we finally adopt automatic code formatting tools we can change it. But we have to live with it, at least for now.

**Comment by SergioRAgostinho** [comment]
> Well if I replace all `.empty()` by `.empty ()`, this will be 389 changes. You really want this in this PR?

Thank you for the sanity check ^^ Once we get the formatting tool running on CI I'm open to discuss changes to the style guide.

**Pull request merged**
