### PR TITLE
Add TrajkovicKeypoint2D/3D to CMake build

### PR DESCRIPTION
**Pull request by ThorstenHarter**
The files which have been added to PCL in #409 are missing in the CMakeLists.txt of the keypoints module.

Fix Microsoft Visual Studio 2015 compile error: "trajkovic_3d.hpp(235): error C3016: 'i': index variable in OpenMP 'for' statement must have signed integral type" by changing index type from size_t to int.

### CODE REVIEW

**Comment by SergioRAgostinho** [comment]
Have a look at 

https://github.com/PointCloudLibrary/pcl/blob/master/common/include/pcl/pcl_macros.h#L44-L55
http://www.boost.org/doc/libs/1_55_0/boost/cstdint.hpp

The boost provided `intmax_t` might be the safest option in this scenario.

**Comment by ThorstenHarter** [comment]
You mean like this?
```
  for (intmax_t i = 0; i < indices.size (); ++i)
  {
    int idx = indices[i];
```
I automatically added the casts because we use -Wsign-conversion in our projects, but since this isn't activated in PCL, they are not mandatory.

**Comment by SergioRAgostinho** [comment]
You still need to cast `indices.size()` like you did before because of what of Wsign-comparison. It is active in PCL for clang (we do need to revise/unify our flags across different compilers). So please suppress all of those.

The point behind my comment was to make sure we use the highest range integer possible, that's available on each platform, to avoid potential overflows on very big `indices` vectors. `int` didn't ensure that but `intmax_t` seems to.

**Comment by ThorstenHarter** [comment]
So you're saying a PointCloud could have more than INT_MAX points?
Because only then the indices vector of the keypoints search could be bigger than that.

In that case the filters, features and keypoints algorithms won't work anyway, because the indices are always defined like this: `std::vector<int> indices`

In other words, I don't see the sense in changing the type of 'i' to intmax_t, while 'idx', 'indices' etc. are using the type int.

**Comment by SergioRAgostinho** [comment]
That's a valid point. I regret a little what our "big data" users deal with. Hopefully someone with those needs will have a look at things and decide to push some changes.

**Pull request merged**
