### PR TITLE
Modernize some CMake macros (Increases minimum required CMake version to 3.5)

### PR DESCRIPTION
**Pull request by SunBlack**
This is a preparation for another change, which I didn't got ready today. But I think it's already enough for a PR.

//Edit: Typical error source: Using to modern CMake commands. PCL now requires CMake 3.5, because `cmake_parse_arguments` was new in CMake core with CMake 3.5. Wanted already to use `PARSE_ARGV N`, but this was introduced in 3.7, so had to use old way.
//Edit2: We could keep CMake 3.1 compatibility by calling `include(CMakeParseArguments)` before. As far as I see we used `cmake_parse_arguments` already before this changes, but we didn't included module, so CMake script was already broken for 3.4 and below xD

### CODE REVIEW

**Comment by SergioRAgostinho** [comment]
Don't forget to update these documentations files
https://github.com/PointCloudLibrary/pcl/pull/2605/files

**Comment by SunBlack** [comment]
How you want to squash with master? The fixup fixes something which is already merged into master.

**Comment by SergioRAgostinho** [comment]
Ignore what I said then 😅 I reviewed the PR per commit and thought it was something added on some previous commit.

**Comment by SergioRAgostinho** [comment]
Heads up: I'm unable to successfully configure CMake on my OSX environment after this PR. Need to figure out what is different between me and the CI. 

Here's the log
```
CMake Error at cmake/pcl_targets.cmake:297 (install):
  install TARGETS given no RUNTIME DESTINATION for executable target
  "pcl_fs_face_detector".
Call Stack (most recent call first):
  apps/CMakeLists.txt:70 (PCL_ADD_EXECUTABLE)


CMake Error at cmake/pcl_targets.cmake:297 (install):
  install TARGETS given no RUNTIME DESTINATION for executable target
  "pcl_manual_registration".
Call Stack (most recent call first):
  apps/CMakeLists.txt:80 (PCL_ADD_EXECUTABLE)
```

It's being very clear about the reason. I'll dig into it to better understand what changed.

**Pull request merged**
