### PR TITLE
Disable SSE flags in AppVeyor.

### PR DESCRIPTION
**Pull request by SergioRAgostinho**
Just testing a theory.

### CODE REVIEW

**Comment by SergioRAgostinho** [comment]
Back when I was trying to set up travis for OS X, I had an issue with SSE flags as well. I don't recall the exact details but the unit tests were blowing with a segfault that I could traceback to a KVM problem with SSE flags. I'm now questioning if the same is happening for the Windows CI. Would you mind merging this and observe for a while the behavior of the windows CI over the next merges and PRs?

**Comment by taketwo** [comment]
To clarify, you expect that this may fix occasional failures of "a_recognition_cg_test" on x86 job?

**Comment by SergioRAgostinho** [comment]
That's my hypothesis yes.

**Comment by SergioRAgostinho** [comment]
Shall I revert this now or wait for the day we actually fix the `a_recognition_cg_test` bug?

**Comment by taketwo** [comment]
Or wait for the day we make some meaningful changes in AppVeyor config... I don't care really, seems all the same :)

**Pull request merged**
