### PR TITLE
Remove std::binary_function from Registration

### PR DESCRIPTION
**Pull request by greenbrettmichael**
Removed std::binary_function from Registration library to support C++17, this change should be reverse compatible

### CODE REVIEW

**Comment by taketwo** [comment]
Should be safe to include in 1.9.0 I think.

**Comment by SergioRAgostinho** [comment]
@taketwo safe to assume it breaks the ABI right?

**Comment by taketwo** [comment]
I don't think so, it was a pure meta-programming gizmo. Here is how `binary_function` looks like in standard library (7.3.0):

```cpp
template<typename _Arg1, typename _Arg2, typename _Result>
struct binary_function
{
/// @c first_argument_type is the type of the first argument
typedef _Arg1 →   first_argument_type;·
/// @c second_argument_type is the type of the second argument
typedef _Arg2 →   second_argument_type;
/// @c result_type is the return type
typedef _Result → result_type;
};
```

**Comment by SergioRAgostinho** [comment]
Thank you both

**Pull request merged**
