### PR TITLE
[WIP] Unit tests balancing

### PR DESCRIPTION
**Pull request by SergioRAgostinho**
This intends to prevent test-extended-1 in travis CI to time out.

Changes in bold

Core | Extended 1 | Extended 2
--- | --- | ---
common:	(io features) | io: octree (vtk) | filters: sample_consensus (io features segmentation)
geometry: common | registration: features (io) | segmentation: geometry features ml
octree: common	|  | people: visualization segmentation	
kdtree: common (io) |  | **visualization: io search geomtry (features) [moved from ext-1]**
search: kdtree octree (io) | | recognition: io registration ml
sample_consensus: search (io) | | **outofcore: io filters visualization [moved from ext-1]**
2d: io filters | | **surface: search (io features filters) [moved from ext-1]**
keypoints: features (io) | |
features: filters 2d (io keypoints) | |

The registration module is heavy.

### CODE REVIEW

**Comment by SergioRAgostinho** [comment]
I still need to see if I can there are modules which are not required to be built, still ensuring all tools are compiled.

**Comment by SergioRAgostinho** [comment]
Closing for now. No point fiddling with things this early.

**Comment by taketwo** [comment]
Does this give any improvement?

```
cache:
   apt: true
```

**Comment by SergioRAgostinho** [comment]
> Does this give any improvement?

No. I switched focus to using ccache. Have a look in #1888

**Pull request closed without merging**
