### PR TITLE
Fix docs on Travis CI.

### PR DESCRIPTION
**Pull request by SergioRAgostinho**

### CODE REVIEW

**Comment by SergioRAgostinho** [comment]
Jinja version is needs to be regressed to not use asyncio features since travis is runnings Python 3.4. 
There's also something wrong with sphinx.

**Comment by taketwo** [comment]
Thanks for investigating this! Travis is green, however since this is a PR the doc task did not run "for real". Do you think this is ready for merge?

**Comment by SergioRAgostinho** [comment]
I pushed the following to a branch of my fork 
- commit: https://github.com/SergioRAgostinho/pcl/compare/master...c23224af5b3f
- ci log: https://travis-ci.org/SergioRAgostinho/pcl/builds/427928638#L2570

**Comment by taketwo** [comment]
OK, looks good then.

**Pull request merged**
