### PR TITLE
[Cmake]Remove unused variables and fix cmake for tools

### PR DESCRIPTION
**Pull request by larshg**
Remove HAVE_VTK, guard simulation and gpu/people tools with BUILD_tools, add subsystem name for tools in io, outofcore, simulation and gpu/people.

### CODE REVIEW

**Comment by larshg** [comment]
[Cuda](https://github.com/PointCloudLibrary/pcl/blob/0bb69c0c795e852ddd731039cc1b0ac96b11d8ed/cuda/CMakeLists.txt#L5) and gpu modules are not added by default (its not set). But there is searched for CUDA by default.

Should I add Default to true to add CUDA subsystems?

**Comment by SergioRAgostinho** [comment]
> Should I set Default to true to add CUDA/GPU subsystems?

No, they are unstable modules :/

**Comment by kunaltyagi** [comment]
@larshg Could you edit the title so it can appear in the changelog nicely?

**Comment by larshg** [comment]
@kunaltyagi like this?

**Comment by larshg** [comment]
Found some more missing guards in gpu/people - should I just add a commit to this?

**Pull request merged**
