### PR TITLE
Pass values by reference

### PR DESCRIPTION
**Pull request by SunBlack**
Fixed all passedByValue hints by CppCheck 1.85

### CODE REVIEW

**Comment by jasjuang** [comment]
I believe pass vectors by reference makes sense but strings should be passed by value because of SSO.

Please see https://stackoverflow.com/a/10232761/3667089

**Comment by SergioRAgostinho** [comment]
@jasjuang What the article you pointed is saying is that if you need to create a copy of the string, inside the function, for any given reason, then you should definitely pass by value.

**Comment by SergioRAgostinho** [comment]
Nb: I'm not marking this as an ABI change because it is just targeted at apps and tools. Nothing on the main libs public interface.

**Comment by SergioRAgostinho** [comment]
If a string meets the SSO length criteria, then it is allocated on the stack. Great for constructors and move mechanics. It's good that it exists when we qualify for it, but I can only rely on the assumptions that my string is going to be small in a couple of controlled cases. This lenght criteria is implementation defined but for libc++ appears to be [3 words](https://stackoverflow.com/a/21710033/9458162), and according to the answer yields 10 chars on a 32 bit machine,  22 chars on a 64bit. So you're copying 24bytes vs a pointer (8 bytes) in the best case. 

The claimed benefit is that one doesn't need to care about it anymore because in most cases SSO will kick in and it's a minor stack copy, if the string is short. Also you don't have to write the extra `const` and `&`.

In the opposite case, you obviously write `const &` but what exactly is the downside of this approach?

**Comment by jasjuang** [comment]
If we can't assume the string to be small I agree `const &` is a better idea. Thanks for showing me the link. That was an interesting read!

**Pull request merged**
