### PR TITLE
Fix some CUDA 9 related errors

### PR DESCRIPTION
**Pull request by Robzz**
This PR fixes a couple of errors I'm encountering in CUDA code when compiling with CUDA 9.1:

* For some reason, `thrust::device_reference` does not seem to coerce to a reference anymore. The fix is to use `thrust::raw_reference_cast`.
* NPPi has been split into multiple libraries since CUDA 9, the fix is to look for the appropriate libraries depending on the detected CUDA version in the `people` module.

My setup is:

* PCL HEAD
* Windows 10
* Latest Visual Studio 2017 (using the VS2015 toolset)
* CMake 3.10.1 using the Ninja generator

Disclaimer: this compiles for me but I don't think I'm actually using any of this code, so it might be a good idea to test that I haven't broken functionality :) Someone should also probably try and get this to compile on Linux with both CUDA >= 9 and CUDA <= 8 since I don't have easy access to a Linux machine right now.

Tested with CUDA 9, I'm currently attempting a build with CUDA 8 but I don't expect any surprises, I'll update this PR in case I did break things for CUDA <= 8.

### CODE REVIEW

**Comment by taketwo** [comment]
I wanted to give it a try on my Ubuntu/CUDA9 laptop, but build fails even before sample consensus module with:

```cpp
/usr/local/cuda/include/thrust/system/cuda/detail/transform.h(118): error: no instance of function template "pcl::cuda::NormalDeviationKernel<Storage>::operator() [with Storage=pcl::cuda::Device]" matches the argument list
            argument types are: (thrust::detail::tuple_of_iterator_references<const pcl::cuda::PointXYZRGB &, float4 &, thrust::null_type, thrust::null_type, thrust::null_type, thrust::null_type, thrust::null_type, thrust::null_type, thrust::null_type, thrust::null_type>)
            object type is: pcl::cuda::NormalDeviationKernel<pcl::cuda::Device>

```

**Comment by Robzz** [comment]
Yeah unfortunately I don't expect it to work on Ubuntu or any other linux distro just yet, this MR just fixes issues I encountered with Windows, and there is some more work needed to get it to build on linux...

**Comment by taketwo** [comment]
>  I'm currently attempting a build with CUDA 8 but I don't expect any surprises, I'll update this PR in case I did break things for CUDA <= 8.

Since you did not comment about this, I assume this change did not break CUDA 8?

**Comment by SergioRAgostinho** [comment]
That one I can test later today. I’m running CUDA 8 on my dev machine.

**Comment by taketwo** [comment]
Great. If it's ok then I suggest we merge this.

**Comment by Robzz** [comment]
> Since you did not comment about this, I assume this change did not break CUDA 8?

No breakage that I could find but as I said, I don't think I'm using that code so I suggest you test something that does :)

**Comment by SergioRAgostinho** [comment]
So apparently my CUDA version is 7.5 but that's ok given the last sentence on the OP. `pcl_gpu_people` is not compiling and failing with the log below. I'll try to rebase to current master just to see if it goes through. From the error message it should be easy to correct.

```
$ make
-- Using CPU native flags for SSE optimization:  -march=native
-- -- GCC > 4.3 found, enabling -Wabi
-- Found OpenMP
-- Eigen found (include: /usr/include/eigen3, version: 3.2.92)
-- FLANN found (include: /usr/include, lib: optimized;/usr/lib/x86_64-linux-gnu/libflann_cpp.so;debug;/usr/lib/x86_64-linux-gnu/libflann_cpp.so)
-- OpenNI found (include: /usr/include/ni, lib: /usr/lib/libOpenNI.so)
-- OpenNI2 found (include: /usr/include/openni2, lib: /usr/lib/libOpenNI2.so)
-- Checking for module 'metslib'
--   No package 'metslib' found
-- QHULL found (include: /usr/include, lib: optimized;/usr/lib/x86_64-linux-gnu/libqhull.so;debug;/usr/lib/x86_64-linux-gnu/libqhull.so)
-- Found CUDA Toolkit v7.5
-- CUDA NVCC target flags: -gencode;arch=compute_20,code=sm_20;-gencode;arch=compute_20,code=sm_21;-gencode;arch=compute_30,code=sm_30;-gencode;arch=compute_35,code=sm_35;-gencode;arch=compute_50,code=sm_50;-gencode;arch=compute_52,code=sm_52
[... some warnings from VTK ...]
-- VTK_MAJOR_VERSION 5, rendering backend: OpenGL
-- VTK found (include: /usr/include/vtk-5.10;/usr/include, lib: /usr/lib/;/usr/lib)
-- Could NOT find PCAP (missing:  PCAP_LIBRARIES PCAP_INCLUDE_DIRS) 
-- Boost version: 1.58.0
-- Found the following Boost libraries:
--   system
--   filesystem
--   thread
--   date_time
--   iostreams
--   chrono
--   atomic
--   regex
-- VTK found (include: /usr/include/vtk-5.10;/usr/include, lib: /usr/lib/;/usr/lib)
-- DOXYGEN_FOUND 
-- HTML_HELP_COMPILER 
-- Found CPack generators: DEB
-- The following subsystems will be built:
--   common
--   kdtree
--   octree
--   search
--   sample_consensus
--   filters
--   2d
--   geometry
--   io
--   features
--   ml
--   segmentation
--   visualization
--   surface
--   registration
--   keypoints
--   tracking
--   recognition
--   stereo
--   cuda_common
--   cuda_io
--   cuda_features
--   cuda_segmentation
--   cuda_sample_consensus
--   cuda_apps
--   outofcore
--   gpu_containers
--   gpu_utils
--   gpu_octree
--   gpu_features
--   gpu_kinfu
--   gpu_kinfu_large_scale
--   gpu_people
--   gpu_segmentation
--   gpu_surface
--   gpu_tracking
--   people
--   tools
-- The following subsystems will not be built:
--   apps: No reason
--   examples: Code examples are disabled by default.
--   simulation: Disabled by default.
--   global_tests: No reason
-- Configuring done
-- Generating done
-- Build files have been written to: <path_to_pcl>/pcl/build
[  3%] Built target pcl_common
[  4%] Built target pcl_kdtree
[  4%] Built target pcl_octree
[  5%] Built target pcl_search
[  7%] Built target pcl_sample_consensus
[ 12%] Built target pcl_filters
[ 12%] Built target pcl_io_ply
[ 19%] Built target pcl_io
[ 19%] Built target pcl_pcd_convert_NaN_nan
[ 19%] Built target pcl_openni_pcd_recorder
[ 20%] Built target pcl_pcd_introduce_nan
[ 20%] Built target pcl_convert_pcd_ascii_binary
[ 21%] Built target pcl_openni_grabber_depth_example
[ 21%] Built target pcl_converter
[ 22%] Built target pcl_hdl_grabber
[ 22%] Built target pcl_openni_grabber_example
[ 22%] Built target pcl_plyheader
[ 22%] Built target pcl_ply2ply
[ 22%] Built target pcl_ply2raw
[ 22%] Built target pcl_ply2obj
[ 28%] Built target pcl_features
[ 29%] Built target pcl_ml
[ 32%] Built target pcl_segmentation
[ 35%] Built target pcl_visualization
[ 35%] Built target pcl_hdl_viewer_simple
[ 35%] Built target pcl_timed_trigger_test
[ 36%] Built target pcl_vlp_viewer
[ 36%] Built target pcl_oni_viewer
[ 36%] Built target pcl_openni_image
[ 36%] Built target pcl_viewer
[ 36%] Built target pcl_pcd_grabber_viewer
[ 36%] Built target pcl_image_grabber_saver
[ 36%] Built target pcl_openni2_viewer
[ 36%] Built target pcl_image_grabber_viewer
[ 36%] Built target pcl_pcd_image_viewer
[ 36%] Built target pcl_openni_viewer
[ 39%] Built target pcl_surface
[ 45%] Built target pcl_registration
[ 46%] Built target pcl_keypoints
[ 47%] Built target pcl_tracking
[ 50%] Built target pcl_recognition
[ 51%] Built target pcl_stereo
[ 51%] Linking CXX shared library ../../lib/libpcl_cuda_io.so
[ 52%] Built target pcl_cuda_io
[ 52%] Linking CXX shared library ../../lib/libpcl_cuda_features.so
[ 52%] Built target pcl_cuda_features
[ 52%] Linking CXX shared library ../../lib/libpcl_cuda_segmentation.so
[ 52%] Built target pcl_cuda_segmentation
[ 52%] Linking CXX shared library ../../lib/libpcl_cuda_sample_consensus.so
[ 53%] Built target pcl_cuda_sample_consensus
[ 53%] Linking CXX executable ../../bin/kinect_viewer_cuda
[ 53%] Built target kinect_viewer_cuda
[ 53%] Built target pcl_outofcore
[ 54%] Built target pcl_outofcore_viewer
[ 54%] Built target pcl_outofcore_print
[ 55%] Built target pcl_outofcore_process
[ 56%] Built target pcl_gpu_containers
[ 56%] Linking CXX shared library ../../lib/libpcl_gpu_utils.so
[ 57%] Built target pcl_gpu_utils
[ 57%] Linking CXX shared library ../../lib/libpcl_gpu_octree.so
[ 58%] Built target pcl_gpu_octree
[ 58%] Linking CXX shared library ../../lib/libpcl_gpu_features.so
[ 59%] Built target pcl_gpu_features
[ 59%] Linking CXX shared library ../../lib/libpcl_gpu_kinfu.so
[ 62%] Built target pcl_gpu_kinfu
[ 62%] Linking CXX executable ../../../bin/pcl_kinfu_app
[ 63%] Built target pcl_kinfu_app
[ 63%] Linking CXX executable ../../../bin/pcl_record_tsdfvolume
[ 63%] Built target pcl_record_tsdfvolume
[ 63%] Linking CXX shared library ../../lib/libpcl_gpu_kinfu_large_scale.so
[ 66%] Built target pcl_gpu_kinfu_large_scale
[ 66%] Linking CXX executable ../../../bin/pcl_record_kinect_maps_rgb
[ 66%] Built target pcl_record_kinect_maps_rgb
[ 66%] Linking CXX executable ../../../bin/pcl_kinfu_largeScale_mesh_output
[ 67%] Built target pcl_kinfu_largeScale_mesh_output
[ 67%] Linking CXX executable ../../../bin/pcl_kinfu_largeScale_texture_output
[ 67%] Built target pcl_kinfu_largeScale_texture_output
[ 67%] Linking CXX executable ../../../bin/pcl_kinfu_largeScale
[ 67%] Built target pcl_kinfu_largeScale
[ 67%] Linking CXX shared library ../../lib/libpcl_gpu_people.so
[ 70%] Built target pcl_gpu_people
[ 70%] Building CXX object gpu/people/tools/CMakeFiles/pcl_people_pcd_prob.dir/people_pcd_prob.cpp.o
<path_to_pcl>/pcl/gpu/people/tools/people_pcd_prob.cpp: In instantiation of ‘void savePNGFile(const string&, const pcl::PointCloud<PointT>&) [with T = pcl::PointXYZRGBA; std::__cxx11::string = std::__cxx11::basic_string<char>]’:
<path_to_pcl>/pcl/gpu/people/tools/people_pcd_prob.cpp:178:52:   required from here
<path_to_pcl>/pcl/gpu/people/tools/people_pcd_prob.cpp:111:23: error: no matching function for call to ‘savePNGFile(const string&, const pcl::PointCloud<pcl::PointXYZRGBA>&)’
   pcl::io::savePNGFile(filename, cloud);
                       ^
In file included from <path_to_pcl>/pcl/gpu/people/tools/people_pcd_prob.cpp:54:0:
<path_to_pcl>/pcl/io/include/pcl/io/png_io.h:93:5: note: candidate: void pcl::io::savePNGFile(const string&, const pcl::PointCloud<unsigned char>&)
     savePNGFile (const std::string& file_name, const pcl::PointCloud<unsigned char>& cloud);
     ^
<path_to_pcl>/pcl/io/include/pcl/io/png_io.h:93:5: note:   no known conversion for argument 2 from ‘const pcl::PointCloud<pcl::PointXYZRGBA>’ to ‘const pcl::PointCloud<unsigned char>&’
<path_to_pcl>/pcl/io/include/pcl/io/png_io.h:101:5: note: candidate: void pcl::io::savePNGFile(const string&, const pcl::PointCloud<short unsigned int>&)
     savePNGFile (const std::string& file_name, const pcl::PointCloud<unsigned short>& cloud);
     ^
<path_to_pcl>/pcl/io/include/pcl/io/png_io.h:101:5: note:   no known conversion for argument 2 from ‘const pcl::PointCloud<pcl::PointXYZRGBA>’ to ‘const pcl::PointCloud<short unsigned int>&’
<path_to_pcl>/pcl/io/include/pcl/io/png_io.h:110:5: note: candidate: void pcl::io::savePNGFile(const string&, const pcl::PCLImage&)
     savePNGFile (const std::string& file_name, const pcl::PCLImage& image);
     ^
<path_to_pcl>/pcl/io/include/pcl/io/png_io.h:110:5: note:   no known conversion for argument 2 from ‘const pcl::PointCloud<pcl::PointXYZRGBA>’ to ‘const pcl::PCLImage&’
<path_to_pcl>/pcl/io/include/pcl/io/png_io.h:119:5: note: candidate: template<class PointT> void pcl::io::savePNGFile(const string&, const pcl::PointCloud<PointT>&, const string&)
     savePNGFile (const std::string& file_name, const pcl::PointCloud<PointT>& cloud, const std::string& field_name)
     ^
<path_to_pcl>/pcl/io/include/pcl/io/png_io.h:119:5: note:   template argument deduction/substitution failed:
<path_to_pcl>/pcl/gpu/people/tools/people_pcd_prob.cpp:111:23: note:   candidate expects 3 arguments, 2 provided
   pcl::io::savePNGFile(filename, cloud);
                       ^
<path_to_pcl>/pcl/gpu/people/tools/people_pcd_prob.cpp: In instantiation of ‘void savePNGFile(const string&, const pcl::PointCloud<PointT>&) [with T = pcl::RGB; std::__cxx11::string = std::__cxx11::basic_string<char>]’:
<path_to_pcl>/pcl/gpu/people/tools/people_pcd_prob.cpp:179:50:   required from here
<path_to_pcl>/pcl/gpu/people/tools/people_pcd_prob.cpp:111:23: error: no matching function for call to ‘savePNGFile(const string&, const pcl::PointCloud<pcl::RGB>&)’
In file included from <path_to_pcl>/pcl/gpu/people/tools/people_pcd_prob.cpp:54:0:
<path_to_pcl>/pcl/io/include/pcl/io/png_io.h:93:5: note: candidate: void pcl::io::savePNGFile(const string&, const pcl::PointCloud<unsigned char>&)
     savePNGFile (const std::string& file_name, const pcl::PointCloud<unsigned char>& cloud);
     ^
<path_to_pcl>/pcl/io/include/pcl/io/png_io.h:93:5: note:   no known conversion for argument 2 from ‘const pcl::PointCloud<pcl::RGB>’ to ‘const pcl::PointCloud<unsigned char>&’
<path_to_pcl>/pcl/io/include/pcl/io/png_io.h:101:5: note: candidate: void pcl::io::savePNGFile(const string&, const pcl::PointCloud<short unsigned int>&)
     savePNGFile (const std::string& file_name, const pcl::PointCloud<unsigned short>& cloud);
     ^
<path_to_pcl>/pcl/io/include/pcl/io/png_io.h:101:5: note:   no known conversion for argument 2 from ‘const pcl::PointCloud<pcl::RGB>’ to ‘const pcl::PointCloud<short unsigned int>&’
<path_to_pcl>/pcl/io/include/pcl/io/png_io.h:110:5: note: candidate: void pcl::io::savePNGFile(const string&, const pcl::PCLImage&)
     savePNGFile (const std::string& file_name, const pcl::PCLImage& image);
     ^
<path_to_pcl>/pcl/io/include/pcl/io/png_io.h:110:5: note:   no known conversion for argument 2 from ‘const pcl::PointCloud<pcl::RGB>’ to ‘const pcl::PCLImage&’
<path_to_pcl>/pcl/io/include/pcl/io/png_io.h:119:5: note: candidate: template<class PointT> void pcl::io::savePNGFile(const string&, const pcl::PointCloud<PointT>&, const string&)
     savePNGFile (const std::string& file_name, const pcl::PointCloud<PointT>& cloud, const std::string& field_name)
     ^
<path_to_pcl>/pcl/io/include/pcl/io/png_io.h:119:5: note:   template argument deduction/substitution failed:
<path_to_pcl>/pcl/gpu/people/tools/people_pcd_prob.cpp:111:23: note:   candidate expects 3 arguments, 2 provided
   pcl::io::savePNGFile(filename, cloud);
                       ^
gpu/people/tools/CMakeFiles/pcl_people_pcd_prob.dir/build.make:62: recipe for target 'gpu/people/tools/CMakeFiles/pcl_people_pcd_prob.dir/people_pcd_prob.cpp.o' failed
make[2]: *** [gpu/people/tools/CMakeFiles/pcl_people_pcd_prob.dir/people_pcd_prob.cpp.o] Error 1
CMakeFiles/Makefile2:3709: recipe for target 'gpu/people/tools/CMakeFiles/pcl_people_pcd_prob.dir/all' failed
make[1]: *** [gpu/people/tools/CMakeFiles/pcl_people_pcd_prob.dir/all] Error 2
Makefile:160: recipe for target 'all' failed
make: *** [all] Error 2
```

**Comment by SergioRAgostinho** [comment]
Without being fully sure if this is the proper fix, these will get the compilation problem away.
```diff
diff --git a/gpu/people/tools/people_app.cpp b/gpu/people/tools/people_app.cpp
index be33ac0..0a9e021 100644
--- a/gpu/people/tools/people_app.cpp
+++ b/gpu/people/tools/people_app.cpp
@@ -129,7 +129,7 @@ savePNGFile(const std::string& filename, const pcl::gpu::DeviceArray2D<T>& arr)
 template <typename T> void
 savePNGFile (const std::string& filename, const pcl::PointCloud<T>& cloud)
 {
-  pcl::io::savePNGFile(filename, cloud);
+  pcl::io::savePNGFile(filename, cloud, "rgb");
 }
 
 ///////////////////////////////////////////////////////////////////////////////////////////////////////////////////
diff --git a/gpu/people/tools/people_pcd_prob.cpp b/gpu/people/tools/people_pcd_prob.cpp
index b5ef9c2..8fe5484 100644
--- a/gpu/people/tools/people_pcd_prob.cpp
+++ b/gpu/people/tools/people_pcd_prob.cpp
@@ -108,7 +108,7 @@ savePNGFile(const std::string& filename, const pcl::gpu::DeviceArray2D<T>& arr)
 template <typename T> void
 savePNGFile (const std::string& filename, const pcl::PointCloud<T>& cloud)
 {
-  pcl::io::savePNGFile(filename, cloud);
+  pcl::io::savePNGFile(filename, cloud, "rgb");
 }
 
 ///////////////////////////////////////////////////////////////////////////////////////////////////////////////////
```

But this is completely unrelated to your PR I would say.

**Comment by cmcmurrough** [comment]
I'm having the same issue as taketwo above on Ubuntu 16.04 / CUDA 9.1

**Pull request merged**
