### PR TITLE
New interface for LCCP

### PR DESCRIPTION
**Pull request by mschoeler**
Changed the interface of LCCP.
1. Added `setInputSupervoxels` method
2. Changed `segment` method to not return data.
3.  Made `mergeSmallSegments` protected (it is now called by `segment`)
4. Added `setMinSegmentSize (const uint32_t min_segment_size_arg)` as a public method
5. Sorted the definitions in lccp_segmentation.hpp by public first and protected second.

### CODE REVIEW

**Comment by VictorLamoine** [comment]
Just a suggestion: use `\ref` in your doxygen documentation every time a member function or member is named. It allows to easily navigate into the documentation and makes it more read-able.

Example : [pcl::EnsensoGrabber::storeEEPROMExtrinsicCalibration](http://docs.pointclouds.org/trunk/classpcl_1_1_ensenso_grabber.html#af304dc77f15a7403835a973d283008b5)

**Comment by taketwo** [comment]
Victor, AFAIK in most cases doxygen is smart enough to figure out that we are referring to a member function even without `\ref`. For example, check [this description](http://docs.pointclouds.org/trunk/group__segmentation.html#ga8ce6ea49099c7bf2de825f3f5ee61152) (paragraph starting with "Several overloads..."), and the source that produced it [here](https://github.com/PointCloudLibrary/pcl/blob/master/segmentation/include/pcl/segmentation/random_walker.h#L83). Magic!

Proposed changes LGTM, and since this has not been released yet, we are free to change the interface.

**Comment by mschoeler** [comment]
ok, added the \refs as well as some const to method variables.

**Comment by mschoeler** [comment]
do you have any more comments on this one or should we merge it? Than I would change the interface of CPC accordingly.
Bzw: I do not think the failed test (icp) comes from my changes.

**Comment by taketwo** [comment]
As I said, I'm fine with the changes. I thought that @jspricke might want to comment, but since he doesn't, I'll merge tomorrow.

**Comment by jspricke** [comment]
Sorry, had no time. Apart from the very minor rather big "Public Functions", I'm fine.

**Pull request merged**
