### PR TITLE
Add sync variants to CUDA vote functions to support PTX/ARCH >= 7.0

### LINKED ISSUE #2911: Compiling PCL with CUDA 10.1 (PTX ISA v6.4) fails
@jasjuang Following up on this pull request: I just updated CUDA to version 10.1 and I only managed to compile the PCL with that version once I explicitly limited the `CUDA_ARCH_BIN` cmake variable to architectures below 7.0. Otherwise I'm getting those compiler errors:

```
1>/pcl/gpu/octree/src/cuda/approx_nsearch.cu(144): warning : function "__ballot"
1>c:\program files\nvidia gpu computing toolkit\cuda\v10.1\include\sm_20_intrinsics.h(405): here was declared deprecated ("__ballot() is deprecated in favor of __ballot_sync() and may be removed in a future release (Use -Wno-deprecated-declarations to suppress this warning).")

1>/pcl/gpu/octree/src/cuda/approx_nsearch.cu(278): warning : function "__all"
1>c:\program files\nvidia gpu computing toolkit\cuda\v10.1\include\device_atomic_functions.h(179): here was declared deprecated ("__all() is deprecated in favor of __all_sync() and may be removed in a future release (Use -Wno-deprecated-declarations to suppress this warning).")

1>ptxas /AppData/Local/Temp/tmpxft_00005094_00000000-10_approx_nsearch.compute_61.ptx, line 60; warning : Instruction 'vote' without '.sync' is deprecated since PTX ISA version 6.0 and will be discontinued in a future PTX ISA version
1>ptxas /AppData/Local/Temp/tmpxft_00005094_00000000-10_approx_nsearch.compute_61.ptx, line 198; warning : Instruction 'vote' without '.sync' is deprecated since PTX ISA version 6.0 and will be discontinued in a future PTX ISA version
1>ptxas /AppData/Local/Temp/tmpxft_00005094_00000000-9_approx_nsearch.compute_70.ptx, line 60; error : Instruction 'vote' without '.sync' is not supported on .target sm_70 and higher from PTX ISA version 6.4
1>ptxas /AppData/Local/Temp/tmpxft_00005094_00000000-9_approx_nsearch.compute_70.ptx, line 198; error : Instruction 'vote' without '.sync' is not supported on .target sm_70 and higher from PTX ISA version 6.4

1>ptxas fatal   : Ptx assembly aborted due to errors
```

Did you encounter similar errors?

_Originally posted by @theche in https://github.com/PointCloudLibrary/pcl/pull/2883#issuecomment-471558833_

### PR DESCRIPTION
**Pull request by scottmudge**
This is needed in order to compile the CUDA modules with support for RTX/Turing cards.

Fixes #2911.

### CODE REVIEW

**Comment by taketwo** [comment]
@jasjuang could you also have a look, please?

**Comment by SergioRAgostinho** [comment]
It's probably a good idea to have @SunBlack testing this one as well.

**Comment by jasjuang** [comment]
I can confirm that this PR solves the compilation problem for CUDA 10.1. Please merge!

**Comment by SunBlack** [comment]
> It's probably a good idea to have @SunBlack testing this one as well.

Sorry, I currently didn't had CUDA 10.1 on my PC, because PCL wasn't compatible to it, so I couldn't test it. Typical example of the chicken or the egg causality dilemma ;).

**Pull request merged**
