### PR TITLE
Fix checks for user-provided CXX flags

### PR DESCRIPTION
**Pull request by taketwo**
This commit introduces `CMAKE_CXX_FLAGS_DEFAULT` with expected default flags (depends on compiler). This variable is used to check if the user explicitly provided different flags.

Fixes a problem reported here: https://github.com/PointCloudLibrary/pcl/pull/2100#issuecomment-431832974.

### CODE REVIEW

**Comment by claudiofantacci** [comment]
Thanks @taketwo, I'll test this PR on my Windows workstation tomorrow morning 👍 

Ok on macOS 👍

**Comment by claudiofantacci** [comment]
I'm compiling and testing now 😄

**Comment by claudiofantacci** [comment]
Unfortunately I get this in `Release`
```bash
Linking CXX shared library bin\pcl_surface_release.dll
FAILED: bin/pcl_surface_release.dll lib/pcl_surface_release.lib
cmd.exe /C "cd . && "C:\Program Files\CMake\bin\cmake.exe" -E vs_link_dll --intdir=surface\CMakeFiles\pcl_surface.dir --manifests  -- C:\PROGRA~2\MIB055~1\2017\Community\VC\Tools\MSVC\14.13.26128\bin\Hostx64\x64\link.exe /nologo @CMakeFiles\pcl_surface.rsp  /out:bin\pcl_surface_release.dll /implib:lib\pcl_surface_release.lib /pdb:bin\pcl_surface_release.pdb /dll /version:1.8 /machine:x64 /NODEFAULTLIB:LIBCMTD  /INCREMENTAL:NO /LTCG /OPT:REF /DELAYLOAD:VCOMP140.dll   && cd ."
LINK: command "C:\PROGRA~2\MIB055~1\2017\Community\VC\Tools\MSVC\14.13.26128\bin\Hostx64\x64\link.exe /nologo @CMakeFiles\pcl_surface.rsp /out:bin\pcl_surface_release.dll /implib:lib\pcl_surface_release.lib /pdb:bin\pcl_surface_release.pdb /dll /version:1.8 /machine:x64 /NODEFAULTLIB:LIBCMTD /INCREMENTAL:NO /LTCG /OPT:REF /DELAYLOAD:VCOMP140.dll /MANIFEST /MANIFESTFILE:bin\pcl_surface_release.dll.manifest" failed (exit code 1120) with the following output:
   Creating library lib\pcl_surface_release.lib and object lib\pcl_surface_release.exp
concave_hull.cpp.obj : error LNK2001: unresolved external symbol qh_qh
bin\pcl_surface_release.dll : fatal error LNK1120: 1 unresolved externals
```
and this in `Debug`
```bash
Linking CXX shared library bin\pcl_surface_debug.dll
FAILED: bin/pcl_surface_debug.dll lib/pcl_surface_debug.lib
cmd.exe /C "cd . && "C:\Program Files\CMake\bin\cmake.exe" -E vs_link_dll --intdir=surface\CMakeFiles\pcl_surface.dir --manifests  -- C:\PROGRA~2\MIB055~1\2017\Community\VC\Tools\MSVC\14.13.26128\bin\Hostx64\x64\link.exe /nologo @CMakeFiles\pcl_surface.rsp  /out:bin\pcl_surface_debug.dll /implib:lib\pcl_surface_debug.lib /pdb:bin\pcl_surface_debug.pdb /dll /version:1.8
/machine:x64 /NODEFAULTLIB:LIBCMTD  /debug /INCREMENTAL /DELAYLOAD:VCOMP140D.dll   && cd ."
LINK Pass 1: command "C:\PROGRA~2\MIB055~1\2017\Community\VC\Tools\MSVC\14.13.26128\bin\Hostx64\x64\link.exe /nologo @CMakeFiles\pcl_surface.rsp /out:bin\pcl_surface_debug.dll /implib:lib\pcl_surface_debug.lib /pdb:bin\pcl_surface_debug.pdb /dll /version:1.8 /machine:x64 /NODEFAULTLIB:LIBCMTD /debug /INCREMENTAL /DELAYLOAD:VCOMP140D.dll /MANIFEST /MANIFESTFILE:surface\CMakeFiles\pcl_surface.dir/intermediate.manifest surface\CMakeFiles\pcl_surface.dir/manifest.res" failed (exit code 1120) with the following output:
Creating library lib\pcl_surface_debug.lib and object lib\pcl_surface_debug.exp
concave_hull.cpp.obj : error LNK2001: unresolved external symbol qh_qh
convex_hull.cpp.obj : error LNK2001: unresolved external symbol qh_qh
bin\pcl_surface_debug.dll : fatal error LNK1120: 1 unresolved externals
```
I have all the options enabled to be able to run all tests as well.
I will investigate this linking issue.

**Comment by taketwo** [comment]
Thanks for testing. I do not entirely understand what's going on. Both your and AppVeyor runs have failures, but in different test cases, and fail in different ways. It seems like:
 * `double` transforms are at fault
 * point type / cloud density are not relevant
 * errors are related to transforms code optimized with SSE/AVX intrinsics (though which? do you compile with avx?)
 * AppVeyor fails with SEH, so something really nasty is going on, probably memory access related

**Comment by claudiofantacci** [comment]
As far as AppVeyor is concerned
 - builds are with VS2015 (my setup is VS2017, this may have some impact)
 - x86 fails at my same test, number 8, plust another one that throws SEH, which is a non-standard exception and I don't understand why that is happening.
 - x64 instead seems not to finish compilation and the build runs out of time

As far as your points are concerned:
>  errors are related to transforms code optimized with SSE/AVX intrinsics (though which? do you compile with avx?)

It seems the case indeed. I'm compiling with the following options derived from pcl `pcl_find_sse.cmake`
 - `CMAKE_CL_64`: 1
 - `SSE_FLAGS`: empty, and for x64 processor should be ok because SSE are activeted by default, while AVX needs a [separate activation](https://docs.microsoft.com/en-us/cpp/build/reference/arch-x64?view=vs-2017) that is not checked in PCL
 - `SSE_DEFINITIONS`:  `-D__SSSE3__` `-D__SSE2__` `-D__SSE__`

>     * AppVeyor fails with SEH, so something really nasty is going on, probably memory access related

See my previous reply regarding AppVeyor.

I'm now testing in `Debug` mode (even though there are problems that I'm trying to address) and Test 8 passes 🤣 🙈

**Comment by claudiofantacci** [comment]
In `Debug` mode the tests failing (aside the ones reported in https://github.com/PointCloudLibrary/pcl/issues/2399#issuecomment-429795482) are test 101 surface_convex_hull
```
test 101
    Start 101: surface_convex_hull

101: Test command: C:\Users\cfantacci\GitHub\pcl\buildd\bin\test_convex_hull.exe "C:/Users/cfantacci/GitHub/pcl/test/bun0.pcd"
101: Test timeout computed to be: 10000000
101: [==========] Running 6 tests from 1 test case.
101: [----------] Global test environment set-up.
101: [----------] 6 tests from PCL
101: [ RUN      ] PCL.ConvexHull_bunny
101: unknown file: error: SEH exception with code 0xc0000005 thrown in the test body.
101: [  FAILED  ] PCL.ConvexHull_bunny (6 ms)
101: [ RUN      ] PCL.ConvexHull_planar_bunny
101: unknown file: error: SEH exception with code 0xc0000005 thrown in the test body.
101: [  FAILED  ] PCL.ConvexHull_planar_bunny (5 ms)
101: [ RUN      ] PCL.ConvexHull_LTable
101: unknown file: error: SEH exception with code 0xc0000005 thrown in the test body.
101: [  FAILED  ] PCL.ConvexHull_LTable (1 ms)
101: [ RUN      ] PCL.ConvexHull_2dsquare
```
and test 102 surface_concave
```
test 102
    Start 102: surface_concave

102: Test command: C:\Users\cfantacci\GitHub\pcl\buildd\bin\test_concave_hull.exe "C:/Users/cfantacci/GitHub/pcl/test/bun0.pcd"
102: Test timeout computed to be: 10000000
102: [==========] Running 4 tests from 1 test case.
102: [----------] Global test environment set-up.
102: [----------] 4 tests from PCL
102: [ RUN      ] PCL.ConcaveHull_bunny
102: unknown file: error: SEH exception with code 0xc0000005 thrown in the test body.
102: [  FAILED  ] PCL.ConcaveHull_bunny (9 ms)
102: [ RUN      ] PCL.ConcaveHull_planar_bunny
102: unknown file: error: SEH exception with code 0xc0000005 thrown in the test body.
102: [  FAILED  ] PCL.ConcaveHull_planar_bunny (19 ms)
102: [ RUN      ] PCL.ConcaveHull_4points
102: unknown file: error: SEH exception with code 0xc0000005 thrown in the test body.
102: [  FAILED  ] PCL.ConcaveHull_4points (1 ms)
102: [ RUN      ] PCL.ConcaveHull_LTable
102: unknown file: error: SEH exception with code 0xc0000005 thrown in the test body.
102: [  FAILED  ] PCL.ConcaveHull_LTable (1 ms)
102: [----------] 4 tests from PCL (30 ms total)
102:
102: [----------] Global test environment tear-down
102: [==========] 4 tests from 1 test case ran. (30 ms total)
102: [  PASSED  ] 0 tests.
102: [  FAILED  ] 4 tests, listed below:
102: [  FAILED  ] PCL.ConcaveHull_bunny
102: [  FAILED  ] PCL.ConcaveHull_planar_bunny
102: [  FAILED  ] PCL.ConcaveHull_4points
102: [  FAILED  ] PCL.ConcaveHull_LTable
102:
102:  4 FAILED TESTS
1/1 Test #102: surface_concave ..................***Failed    0.33 sec
```

**Comment by taketwo** [comment]
Bravo, Claudio! How did you realize this? Also, how is this line parsed then, if it does not raise a compilation error?

**Comment by claudiofantacci** [comment]
> Bravo, Claudio!

🎉 Thanks! 🎉  

> How did you realize this?

I just compiled the test with MSVC and there was a **warning** about bad token at that line. At that point I found out that the code was _skipped_ altogether instead of being included in the compilation unit.

> Also, how is this line parsed then, if it does not raise a compilation error?

It does not indeed. This is probably (I'm unaware of this atm) something that can be added (or removed, it depend on the current PCL compiler options) as an option to the compiler to raise an error instead of a warning. With the current settings, an error in the macro results in the code surrounded by it to be ruled out from the compilation. As a result, I would say that this bug _affected all OSs_, not just Windows, unless you activated `AVX`.

Speaking about `AVX`, by having a look at [`pcl_find_sse.cmake`](https://github.com/PointCloudLibrary/pcl/blob/master/cmake/pcl_find_sse.cmake), there is no trace of `__AVX__` enabled anywhere for Windows or for target machine if you are crosscompiling.

To reason about the latter case, this line will enable `AVX` if corsscompilation is disabled for non-Windows machine 
https://github.com/PointCloudLibrary/pcl/blob/521a3acfcc24b19942fb4020ecd0729866b46a94/cmake/pcl_find_sse.cmake#L10

These lines
https://github.com/PointCloudLibrary/pcl/blob/521a3acfcc24b19942fb4020ecd0729866b46a94/cmake/pcl_find_sse.cmake#L184-L202
instead, does not activate `AVX` under windows.
For both [`x86`](https://docs.microsoft.com/en-us/cpp/build/reference/arch-x86?view=vs-2017) and [`x64`](https://docs.microsoft.com/en-us/cpp/build/reference/arch-x64?view=vs-2017) you need to set `/arch:[AVX|AVX2]` (that in turns activate the `__AVX[2]__` define).

For example, to test such compiler optimization we could use something like the following to minimal code used in OpenCV: [AVX](https://github.com/opencv/opencv/blob/master/cmake/checks/cpu_avx.cpp) and [AVX2](https://github.com/opencv/opencv/blob/master/cmake/checks/cpu_avx2.cpp).

This is just a proposal. I know we are approaching the release deadline. We can keep track of this in another issue and postpone it so that we can test it properly.

**Comment by claudiofantacci** [comment]
Travis tests failed because they went over the allowed time of 90 minutes.
Indeed, by fixing that line, there is much more optimization (and files) to compile.
We may ask @UnaNancyOwen to give it a shot and to run tests in `Release` 😄

**Comment by taketwo** [comment]
> As a result, I would say that this bug affected all OSs, not just Windows, unless you activated AVX.

Tests inside PCL don't cover non-AVX branches of code, however during development of these transform optimizations we had tests that covered all possible branches: https://github.com/taketwo/pcl-transforms on Linux.

> Speaking about AVX, by having a look at pcl_find_sse.cmake, there is no trace of __AVX__ enabled anywhere for Windows or for target machine if you are crosscompiling.

Yeah, AVX on Windows can definitely go into the CMake revamp TODO list.

**Comment by claudiofantacci** [comment]
> Tests inside PCL don't cover non-AVX branches of code, however during development of these transform optimizations we had tests that covered all possible branches: https://github.com/taketwo/pcl-transforms on Linux.

I don't understand this point. By my understanding in PCL tests (like in sample consensus one) SSE/SSE2 optimized transformation branches, that is non-AVX, are used. Am I wrong?

> Yeah, AVX on Windows can definitely go into the CMake revamp TODO list.

👍 

> I restarted the AppVeyor build, maybe we get lucky and it does not timeout this time.

🤞

**Comment by taketwo** [comment]
PCL tests will test the branch that you (implicitly) enabled at
configuration time. That is, if you build PCL with native on an AVX enabled
machine, then AVX branch will be tested. If you disabled SSE using CMake
option, then non-optimized branch will be tested. And so on...

**Comment by claudiofantacci** [comment]
> PCL tests will test the branch that you (implicitly) enabled at configuration time. That is, if you build PCL with native on an AVX enabled machine, then AVX branch will be tested. If you disabled SSE using CMake option, then non-optimized branch will be tested. And so on...

Yes I understand that. I was not understanding the implication to the fact that other OSs would have probably been affected by this bug. In this particular case, I was referring to the fact that in my local settings I have compiled and tested the code with SSE optimization capabilities 😄 

By  the way, all test passed 🎉

**Comment by SergioRAgostinho** [comment]
I'm going to merge this as well for 1.9.0. If problems appear because of it, I propose we release a patch version just to address this.

**Pull request merged**
