### PR TITLE
Change to minimum required c++ std, but don't force to lower.

### LINKED ISSUE #5457: [segmentation] SupervoxelClustering extract generates "double free or corruption (out)" in PCL 1.12.X
**Describe the bug**

When using an [`extract`](https://pointclouds.org/documentation/classpcl_1_1_supervoxel_clustering.html#a596335ad01c705d692462e1109363466) function from `SupervoxelClustering` the following error is presented `double free or corruption (out)`

**Context**

I'm trying to run the example code [_Clustering of Pointclouds into Supervoxels_](https://pcl.readthedocs.io/en/latest/supervoxel_clustering.html#supervoxel-clustering) for segmenting 3D point clouds in PCD format

**Expected behavior**

Extract the label map from the supervoxel structure

**Current Behavior**

When executing the extract method, it returns the error: `double free or corruption (out)`, similarly to the one reported by #2598

Example output:
```
$ ./supervoxel_clustering ../milk_cartoon_all_small_clorox.pcd --NT
PCL_VERSION: 101201
> Loading point cloud...
> Extracting supervoxels!
double free or corruption (out)
```

**To Reproduce**
1. Download the [`supervoxel_clustering.cpp`](https://pcl.readthedocs.io/en/latest/_downloads/5dcfd937b2f0e4061fa236fa6e47f6ce/supervoxel_clustering.cpp) exemple, [`CMakeLists.txt`](https://pcl.readthedocs.io/en/latest/_downloads/6fa7d213a5141569cba95305921a2aaf/CMakeLists.txt) and input point cloud [`milk_cartoon_all_small_clorox.pcd`](https://github.com/PointCloudLibrary/data/blob/master/tutorials/correspondence_grouping/milk_cartoon_all_small_clorox.pcd?raw=true)
2. Compile the `supervoxel_clustering.cpp` file
3. run `./supervoxel_clustering milk_cartoon_all_small_clorox.pcd --NT`

**Your Environment (please complete the following information):**

 - OS: Ubuntu 22.04
 - Compiler: GCC 11.2.0
 - PCL Version:  1.12.X and HEAD

**Additional context**

Although in #2598 it was reported that the problem was fixed in version 1.9.0, I am encountering the same problem in newer versions of the library (>=1.12.0).

### LINKED ISSUE #5644: [pcl::on_nurbs::Triangulation::convertSurface2PolygonMesh] double free or corrupt
**Describe the bug**

I am currently trying to run the bspline_fitting example and when it attempts to do the triangulation it runs into a "double free or corrupt" error. When debugging it is related to the shared_ptr_base.h

**Context**

I had previously done the same on a Ubuntu 20.4 and no error was identified

**Expected behavior**

It should run smoothly

**Current Behavior**

It breaks at that point due to the shared_ptr_base

**To Reproduce**

Nothing needed to reproduce as it is directly on the repository, it is an error due to Ubuntu version

**Your Environment (please complete the following information):**

 - OS: [Ubuntu 22.04]
 - Compiler: [GCC 11.3.0]
 - PCL Version [Latest, HEAD]

Thank you very much in advance

### LINKED ISSUE #5647: [moment_of_inertia.] double free or corruption (out)
running the tutorial code from Moment of inertia and eccentricity based descriptors gives the following error:

`double free or corruption (out)`

I am using colcon to build the tutorial code as a ROS 2 node. Please find the CmakeList content below:

```
`cmake_minimum_required(VERSION 3.8)
project(my_package)

if(CMAKE_COMPILER_IS_GNUCXX OR CMAKE_CXX_COMPILER_ID MATCHES "Clang")
  add_compile_options(-Wall -Wextra -Wpedantic)
endif()

# find dependencies
find_package(ament_cmake REQUIRED)
find_package(rclcpp REQUIRED)
find_package(std_msgs REQUIRED)
find_package(sensor_msgs REQUIRED)
find_package(pcl_conversions REQUIRED)
find_package(PCL 1.13 REQUIRED)
find_package(VTK REQUIRED)
find_package(pcl_ros)

find_package(rclcpp_components REQUIRED)
find_package(sensor_msgs REQUIRED)
find_package(geometry_msgs REQUIRED)
find_package(tf2 REQUIRED)
find_package(tf2_geometry_msgs REQUIRED)
find_package(tf2_ros REQUIRED)

set(dependencies
  pcl_conversions
  rclcpp
  rclcpp_components
  sensor_msgs
  geometry_msgs
  tf2
  tf2_geometry_msgs
  tf2_ros
  EIGEN3
  PCL
)
include_directories(${PCL_INCLUDE_DIRS} ${VTK_INCLUDE_DIRS} include)
link_directories(${PCL_LIBRARY_DIRS})
add_definitions(${PCL_DEFINITIONS})
add_executable(obb src/obb.cpp)
target_link_libraries(obb
$<BUILD_INTERFACE:${CMAKE_CURRENT_SOURCE_DIR}/include>
  $<INSTALL_INTERFACE:include>
  ${Boost_SYSTEM_LIBRARY}
  ${PCL_LIBRARIES}
  ${VTK_LIBRARIES})
target_include_directories(obb PUBLIC
  ${PCL_INCLUDE_DIRS})
ament_target_dependencies(obb
  rclcpp
  rclcpp_components
  sensor_msgs
  pcl_conversions)
target_compile_features(obb PUBLIC c_std_99 cxx_std_17)

install(TARGETS
  obb
  DESTINATION lib/${PROJECT_NAME})

if(BUILD_TESTING)
  find_package(ament_lint_auto REQUIRED)
  # the following line skips the linter which checks for copyrights
  # comment the line when a copyright and license is added to all source files
  set(ament_cmake_copyright_FOUND TRUE)
  # the following line skips cpplint (only works in a git repo)
  # comment the line when this package is in a git repo and when
  # a copyright and license is added to all source files
  set(ament_cmake_cpplint_FOUND TRUE)
  ament_lint_auto_find_test_dependencies()
endif()

ament_package()`
```

**Your Environment (please complete the following information):**

 - OS: Ubuntu 22.04
 - Compiler: gcc (Ubuntu 11.3.0-1ubuntu1~22.04) 11.3.0,  g++ (Ubuntu 11.3.0-1ubuntu1~22.04) 11.3.0
 - PCL Version: pcl 1.13

### PR DESCRIPTION
**Pull request by larshg**
Implements suggestion from #5457 

fixes #5457
fixes #5644 
fixes #5647

### CODE REVIEW

**Comment by mvieth** [comment]
I have thought about this and the situation is unfortunately quite complex:
1. I don't know if we should merge this PR before the 1.13.1 release, since then for some compilers (e.g. GCC 12), PCL will be compiled as C++17 instead of C++14 and I am not sure if that would be an ABI break
2. This PR does not fully solve the problem: Let's take GCC 12 as an example, the default is C++17 so PCL will be compiled with that standard. If someone compiles/forces their downstream project as C++14 (e.g. because older PCL version were compiled as C++14), they also get an error ("invalid read" in my tests). So this PR would "only" solve the problem for users who do not explicitly set the C++ standard for their downstream project and use a compiler for PCL and their downstream project that defaults to C++17 (e.g. GCC 11, GCC 12, Clang 16).
3. I may have found a solution that hopefully removes the dependency between the C++ standards used for PCL and the downstream project: using hidden visibility for symbols by default for gcc (and clang as well, I think). MSVC does this automatically, as far as I know (which is why this problem should not happen with MSVC). However, this is something I would not merge until after PCL 1.13.1 (definitely an ABI break).
4. A solution we could add for PCL 1.13.1 is a warning in pcl_config.h.in if the C++ standard (of the downstream project) is higher than C++14 (plus the option to silence the warning by defining a preprocessor symbol). On the other hand, this could often be a false alarm because in many cases, a C++14/C++17 mismatch does not seem to cause any trouble
5. Another option would be to not do anything in this matter until PCL 1.13.1 is released, be extra aware of this problem for all new issues, and to not wait too long with releasing PCL 1.14.0 where we fix the problem for good :slightly_smiling_face: 
6. For PCL 1.14.0, we could consider switching to C++17 anyway to have access to if constexpr, replace boost::filesystem, etc (if all relevant compilers support it)

**Comment by larshg** [comment]
Hmm.

According to [this SO post](https://stackoverflow.com/questions/46746878/is-it-safe-to-link-c17-c14-and-c11-objects) it shouldn't matter as long as it is the same compiler version used.

I guess it might be a preprocessor value that changes, which eigen doesn't like, or have you pinpointed exactly when and where it happends?

I have reasoned, that it happend if a pointcloud is constructed within a PCL method (C++14), but released in user code (c++17)?

**Comment by mvieth** [comment]
The problem is how Eigen creates aligned pointers, which changes between C++14 and C++17. We have to add the macro `EIGEN_MAKE_ALIGNED_OPERATOR_NEW` [under certain conditions](https://eigen.tuxfamily.org/dox/group__TopicStructHavingEigenMembers.html), for example for `PointCloud` it [is here](https://github.com/PointCloudLibrary/pcl/blob/master/common/include/pcl/point_cloud.h#L900). If I understood correctly, in C++14 and lower, the special new-operator allocates memory (unaligned pointer) and adds some bytes until it has a properly aligned pointer. When freeing the object, it must not call `free()` on the aligned pointer, but has to subtract the same number of bytes to get the original, unaligned pointer, and call `free()` on that one. Calling `free()` on the wrong pointer would lead exactly to the double-free-or-corruption errors. In C++17 these extra steps to get aligned pointers are not necessary any more, and no bytes will be added/subtracted.
In the three cases we have observed so far, the problem was not a point cloud constructed within PCL and destructed in user code. Instead, both construction and destruction happened within PCL code. For example, in the MomentOfInertiaEstimation case, [projected_cloud was created and destroyed in the same function](https://github.com/PointCloudLibrary/pcl/blob/master/features/include/pcl/features/impl/moment_of_inertia_estimation.hpp#L177-L183) The problem is that when the user code is compiled, a point cloud destructor (C++17) is created for a cloud in the user code, and during linking, this C++17 point cloud destructor is chosen to be called from within PCL code instead of the C++14 destructor from PCL. This is where my solution from point 3 from my last comment solves the problem: when using hidden visibility by default, the linker chooses the correct C++14 destructor.
Whether we can also have a problem when a point cloud is constructed within PCL and destructed in user code I am not sure, I will try to test this.

**Comment by larshg** [comment]
> In the three cases we have observed so far, the problem was not a point cloud constructed within PCL and destructed in user code.

Yeah, I somehow thought wrong about it, it is indeed when constructed and destructed within PCL.

Lets just inform users if they don't find existing issues already. And then focus on a solution for 1.14.

**Pull request closed without merging**
