### PR TITLE
Update README.md to include build instructions

### PR DESCRIPTION
**Pull request by aymanim**
This will allow easy access for contributors to refer to the official docs on building and compiling pcl from source.

### CODE REVIEW

**Comment by VictorLamoine** [comment]
Good idea but this tutorial covers only Linux.
The tutorial also needs to be updated (dependencies minimum versions for example).

**Comment by aymanim** [comment]
I agree, "Compiling from source" is a little out of date and while it does have a link to Mac OS and Windows instructions, they are scattered around on that page. How do you submit patches for that page? I didn't see anything in CONTRIBUTING.md regarding the documentation on the website.

**Comment by VictorLamoine** [comment]
The docs & tutorials are [here](https://github.com/PointCloudLibrary/pcl/tree/master/doc) but the tutorial you point out is not part of the automatic doc generation. It has to be edited by someone with credentials to the FTP.

**Comment by jspricke** [comment]
Moving it to the tutorials page (and probably merging it with the others) would actually be great :).

**Comment by VictorLamoine** [comment]
Done in #1107; when merged it would to point to this "new" tutorial.

**Comment by VictorLamoine** [comment]
The new tutorial is online [here](http://www.pointclouds.org/documentation/tutorials/compiling_pcl_posix.php#compiling-pcl-posix).
Can you update the link in your pull request?

I think the README.md should be more complete than it is right now, [how-to-write-a-good-readme](http://stackoverflow.com/questions/2304863/how-to-write-a-good-readme)

- I'd add a link the the [CONTRIBUTING.md](https://github.com/PointCloudLibrary/pcl/blob/master/CONTRIBUTING.md) file with a short description
- A link to [the documentation](http://docs.pointclouds.org/trunk/)
- A link to [the tutorials](http://www.pointclouds.org/documentation/tutorials/)

**Comment by VictorLamoine** [comment]
Done via https://github.com/PointCloudLibrary/pcl/pull/1540

**Pull request closed without merging**
