### PR TITLE
[features] Using arrays for brewity in vfh

### PR DESCRIPTION
**Pull request by kunaltyagi**

### CODE REVIEW

**Comment by kunaltyagi** [comment]
There's no ABI break, right? The internal structure is unmodified, `std::array` symbols are already present in PCL. No additional functions have been added/removed, etc.(I used [this document](https://community.kde.org/Policies/Binary_Compatibility_Issues_With_C%2B%2B))

**Comment by kunaltyagi** [comment]
PS: We create merge commits, right? I accidentally used the rebase and merge (I didn't notice since I prefer rebase)

**Comment by taketwo** [comment]
From your reference, last item in the "you cannot..." list:

> For non-static members:
>  change the type of the member, except for signedness

**Comment by kunaltyagi** [comment]
The type is unchanged (think of it as inserting a union of [array + 4 variables] instead). This is a private member (so no public symbols) and no size change.

**Comment by kunaltyagi** [comment]
I should look at getting the abi compliace setup working though

**Comment by taketwo** [comment]
Hmm, ok.

> I should look at getting the abi compliace setup working though

Add to GSoC ideas?

**Comment by kunaltyagi** [comment]
That's already there. ABI/API breakage

**Comment by kunaltyagi** [comment]
So, I did the ABI diff between master (pre-merge) and this branch.

Result: expected. the names are missing/changed, but doesn't matter (as long as the header is correct)



[libpcl_features_ 0.9 to 0.9.1 abi compatibility report.pdf](https://github.com/PointCloudLibrary/pcl/files/4102335/libpcl_features_.0.9.to.0.9.1.abi.compatibility.report.pdf)
[libpcl_features_ 0.9 to 0.9.1 api compatibility report.pdf](https://github.com/PointCloudLibrary/pcl/files/4102338/libpcl_features_.0.9.to.0.9.1.api.compatibility.report.pdf)

The process is much too slow and happens post compilation. I wonder if using a diff of libraries is better than parsing the libraries and then the diff of xml...

**Pull request merged**
