### PR TITLE
[GPU] Fixes compile error on MSVC by disabling Whole Program Optimization

### PR DESCRIPTION
**Pull request by larshg**
Temporarily avoids errors like:
#3951
#1113

presumable also this one:
#1418 (I have run the example with this patch)

According to [this](https://devblogs.microsoft.com/cppblog/quick-tips-on-using-whole-program-optimization/), it can possible impose a penality of 3-4% performance in normal libraries.

An alternative approach might be to parse different compilerflags to NVCC, instead of all Host flags - however I haven't looked into that just yet.

### CODE REVIEW

**Comment by SergioRAgostinho** [comment]
I'm not sure what to say here exactly. This is silently hiding an issue. Should we not provide instead an explicit work around that users need to be aware and activate, e.g. through a cache variable?

**Comment by larshg** [comment]
Can also print a warning when its get disabled due to people actively selecting to compile CUDA/GPU.

Since its difficult to know, that you have to set the WITH_GLOBALOPTIMIZATION_DISABLED, when compiling for CUDA/GPU on windows?

So one will probably end up compiling everything without the flag.
Experience a runtime error, spent time verifying own code.
Maybe search for similar errors, but many will probably just post an issue here, get told to set the flag and then recompile everything again.

If we just print a warning, the user does get a notice about Global optimization being disabled (can be hard to filter it between everything else), but at least things will work.

**Comment by SergioRAgostinho** [comment]
Sound argument. From my side proceed with adding the message then.

**Comment by SergioRAgostinho** [comment]
Was the CI error a fluke?
https://dev.azure.com/PointCloudLibrary/pcl/_build/results?buildId=16853&view=logs&j=b2e91478-826b-5668-35a1-2ffb6cc2ce81&t=22c5e2d5-98d8-5ead-0f8b-b95a043b17d5&l=4552

**Comment by larshg** [comment]
Yes, seems like a double unstable CI. But we can try it again :)

**Pull request merged**
