### PR TITLE
[I/O] Fix addition of Carriage Return to PCD files.

### LINKED ISSUE #4724: [custom] Question about PCD format
I'm trying to understand the proper format of a PCD file. The [documentation](https://pcl.readthedocs.io/projects/tutorials/en/latest/pcd_file_format.html) says that ASCII output and the PCD header is delimited by the newline character. However, when I run the [sample PCD program](https://pcl.readthedocs.io/projects/tutorials/en/latest/writing_pcd.html) on Windows, it generates output with the standard Windows line separators (CR + NL).

Is the documentation wrong? Is the code wrong?

If the code is correct, is *either* fine? Should I be able to transfer *any* PCD file from a UNIX-like system to a Windows system without worrying about the line separators?

### PR DESCRIPTION
**Pull request by larshg**
Fixes #4724.

### CODE REVIEW

**Review by kunaltyagi — APPROVED** [review]

**Comment by mvieth** [comment]
Has to be added [here](https://github.com/PointCloudLibrary/pcl/blob/master/io/include/pcl/io/impl/pcd_io.hpp#L733) and [here](https://github.com/PointCloudLibrary/pcl/blob/master/io/src/pcd_io.cpp#L1131) too, right?

**Comment by kunaltyagi** [comment]
Those are `writeASCII` versions. I wonder if opening in binary mode will affect the write operations for those (apart from just the whitespace)

**Comment by larshg** [comment]
I think your right @mvieth. Its also ASCII where I already changed. However, its still converting \n to \r\n. Unless its open in "binary" mode.
I'll update it.

**Review by kunaltyagi — APPROVED** [review]
Is there some io library to abstract this kind of difference between platforms?

**Review by mvieth — APPROVED** [review]

**Pull request merged**
