### PR TITLE
1 / x formatting common.

### PR DESCRIPTION
**Pull request by larshg**

### CODE REVIEW

**Comment by mvieth** [comment]
This may be problematic: if we merge this, then all other open pull requests that change something in common will have merge conflicts. Ideally we would only format modules where no corresponding open pull requests exist

**Comment by larshg** [comment]
> This may be problematic: if we merge this, then all other open pull requests that change something in common will have merge conflicts. Ideally we would only format modules where no corresponding open pull requests exist

I don't think we can manage to close all request for a given module. There seems to come new as fast as we can close them.
But if we merge PRs that help us to spent less time per PR (ie. Pointing out formatting errors) that will help us in the long run.
Yes, there are probably PRs that will need updates, but I think the majority needs that already. It is still unfortunate.

Is there even a simple way to check if a given file is modifed in any PR?

Generally I would opt for getting more things automated, at the cost of some PRs need rebasing/adjustments.

**Comment by mvieth** [comment]
> But if we merge PRs that help us to spent less time per PR (ie. Pointing out formatting errors) that will help us in the long run.

To be honest, I don't usually point out formatting errors in a PR (unless maybe they are very severe). Either the file is already formatted and checked by the CI, or it isn't formatted, then I don't see the point in making the PR author follow rules that not enforced in the rest of the file.

> Yes, there are probably PRs that will need updates, but I think the majority needs that already. It is still unfortunate.

Since the formatting touches most, if not all, lines in each file, the following merge conflicts will be so severe that it is close to impossible to resolve them. Usually the only option would be to open a new pull request with the same changes, but starting with the formatted file (which is time-consuming and not likely to happen for many PRs).

> Is there even a simple way to check if a given file is modifed in any PR?

Maybe through the GitHub API? Like our changelog generation script? If we could find out which files (maybe all files in a directory) are not modified by any PR, which we then can safely format, that would be a good way to circumvent this problem.

**Comment by larshg** [comment]
Yeah, I agree with your points. Maybe I was a bit overoptimistic about the merge conflict tools abilities 😄 

I actually went ahead as well and tried to put something together as well (with a bit of help from chatGPT for the fun of it):

Remember to change personal token to something actual.

Currently it queries all open PRs files and then you can check various inputs supplied in the terminal.

```

import requests

token = "INSERT_PERSONAL_TOKEN"

class GithubOpenPRsBot:

    def __init__(self, owner, repo) -> None:
        self.Owner = owner
        self.Repo = repo
        self.BaseURL = f"https://api.github.com/repos/{self.Owner}/{self.Repo}/pulls"
        self.headers = {"Authorization": f"Bearer {token}"}
        self.headers["Accept"] = "application/vnd.github.v3+json"
        
    def GetAllOpenPRs(self):
        pageCount = 1

        self.allPRs = []

        params = {"state": "open"}
        
        while True:
            params["page"] = str(pageCount)
            print(f'Quering page {pageCount}')
            response = requests.get(self.BaseURL, params=params, headers=self.headers)
            pull_requests = response.json()
            if len(pull_requests) == 0:
                break
            else:
                self.allPRs.append(pull_requests)
            pageCount += 1


    def GetAllModifiedFiles(self):
        for page in self.allPRs:
            for pr in page:
                pr_number = pr["number"]
                print("Queyring: " + str(pr_number))

                files_url = f"{self.BaseURL}/{pr_number}/files"
                files_response = requests.get(files_url, headers=self.headers)
                pr["files"] = files_response.json()

    def IsFileInOpenPRs(self,fileName):
        hasChanged = False
        for page in self.allPRs:
           for pr in page:
                for file in pr["files"]:
                    if fileName in file["filename"]:
                        pr_number = pr["number"]
                        pr_url = pr["html_url"]
                        hasChanged = True
                        print(f"The file '{fileName}' has been changed in PR #{pr_number} ({pr_url})")
        if not hasChanged:
            print(f"The file '{fileName}' has not been changed in any open PRs.")


# Example usage
owner = "PointCloudLibrary"
repo = "pcl"

gop = GithubOpenPRsBot(owner,repo)

gop.GetAllOpenPRs()
gop.GetAllModifiedFiles()

while(True)
    inputFromTerminal = input()
    files = inputFromTerminal.split(" ")

    for file in files:
        gop.IsFileInOpenPRs(file)

# eksample input: pcl/cloud_iterator.h common/bivariate_polynomial.h common/boost.h common/angles.h common/centroid.h common/colors.h common/common.h common/common_headers.h common/concatenate.h
```

**Comment by larshg** [comment]
Example output from the above, with the example input:

```
The file 'pcl/cloud_iterator.h' has been changed in PR #5725 (https://github.com/PointCloudLibrary/pcl/pull/5725)
The file 'pcl/cloud_iterator.h' has been changed in PR #4192 (https://github.com/PointCloudLibrary/pcl/pull/4192)
The file 'pcl/cloud_iterator.h' has been changed in PR #3545 (https://github.com/PointCloudLibrary/pcl/pull/3545)
The file 'common/bivariate_polynomial.h' has been changed in PR #5725 (https://github.com/PointCloudLibrary/pcl/pull/5725)
The file 'common/boost.h' has been changed in PR #5725 (https://github.com/PointCloudLibrary/pcl/pull/5725)
The file 'common/boost.h' has been changed in PR #3545 (https://github.com/PointCloudLibrary/pcl/pull/3545)
The file 'common/angles.h' has been changed in PR #5725 (https://github.com/PointCloudLibrary/pcl/pull/5725)
The file 'common/angles.h' has been changed in PR #3545 (https://github.com/PointCloudLibrary/pcl/pull/3545)
The file 'common/angles.h' has been changed in PR #1950 (https://github.com/PointCloudLibrary/pcl/pull/1950)
The file 'common/centroid.h' has been changed in PR #5725 (https://github.com/PointCloudLibrary/pcl/pull/5725)
The file 'common/centroid.h' has been changed in PR #5690 (https://github.com/PointCloudLibrary/pcl/pull/5690)
The file 'common/centroid.h' has been changed in PR #4870 (https://github.com/PointCloudLibrary/pcl/pull/4870)
The file 'common/centroid.h' has been changed in PR #4829 (https://github.com/PointCloudLibrary/pcl/pull/4829)
The file 'common/centroid.h' has been changed in PR #4192 (https://github.com/PointCloudLibrary/pcl/pull/4192)
The file 'common/centroid.h' has been changed in PR #1614 (https://github.com/PointCloudLibrary/pcl/pull/1614)
The file 'common/colors.h' has been changed in PR #5725 (https://github.com/PointCloudLibrary/pcl/pull/5725)
The file 'common/common.h' has been changed in PR #5725 (https://github.com/PointCloudLibrary/pcl/pull/5725)
The file 'common/common.h' has been changed in PR #1950 (https://github.com/PointCloudLibrary/pcl/pull/1950)
The file 'common/common.h' has been changed in PR #1907 (https://github.com/PointCloudLibrary/pcl/pull/1907)
The file 'common/common_headers.h' has been changed in PR #5725 (https://github.com/PointCloudLibrary/pcl/pull/5725)
The file 'common/concatenate.h' has been changed in PR #5725 (https://github.com/PointCloudLibrary/pcl/pull/5725)
The file 'common/concatenate.h' has been changed in PR #5525 (https://github.com/PointCloudLibrary/pcl/pull/5525)
```

**Comment by larshg** [comment]
There are quite a few that will be hit, but also some that probably never get merged, due to inactivity and so on.

**Pull request closed without merging**
