### PR TITLE
Run clang-tidy on optional PCL modules

### PR DESCRIPTION
**Pull request by gnawme**
Per @mvieth, configured `clang-tidy` to be run on optional PCL modules:

```
cmake -DCMAKE_EXPORT_COMPILE_COMMANDS=ON -DCMAKE_CXX_COMPILER=/usr/bin/clang-14 -DCMAKE_C_COMPILER=/usr/bin/clang-14 . \
      -DCMAKE_BUILD_TYPE="MinSizeRel" \
      -DPCL_ONLY_CORE_POINT_TYPES=ON \
      -DPCL_DISABLE_GPU_TESTS=ON \
      -DBUILD_simulation=ON \
      -DBUILD_surface_on_nurbs=ON \
      -DBUILD_global_tests=ON \
      -DBUILD_examples=ON \
      -DBUILD_apps_3d_rec_framework=ON \
      -DBUILD_apps_cloud_composer=ON \
      -DBUILD_apps_in_hand_scanner=ON \
      -DBUILD_apps_modeler=ON \
      -DBUILD_apps_point_cloud_editor=ON \
      -DBUILD_CUDA=$BUILD_GPU \
      -DBUILD_GPU=$BUILD_GPU \
      -DBUILD_cuda_io=$BUILD_GPU \
      -DBUILD_gpu_tracking=$BUILD_GPU \
      -DBUILD_gpu_surface=$BUILD_GPU \
      -DBUILD_gpu_people=$BUILD_GPU \
      -DBUILD_apps=ON \
      -DBUILD_tools=ON
```
`benchmark` could not be configured, and was omitted.

### CODE REVIEW

**Comment by gnawme** [comment]
Sorry, the rebase got a bit funky

**Comment by mvieth** [comment]
:cold_sweat: Over 9000 lines changed? Sorry, but we have to break this up into smaller pull requests. I may also have been unclear regarding the build options.
Modules so far not enabled in the Github action:
```
-- The following subsystems will not be built:
--   apps: Disabled by default
--   benchmarks: Disabled by default
--   examples: Code examples are disabled by default.
--   simulation: Disabled by default.
--   global_tests: Disabled by default
```
That would be the build options `-DBUILD_apps=ON -DBUILD_apps_3d_rec_framework=ON -DBUILD_apps_cloud_composer=ON -DBUILD_apps_in_hand_scanner=ON -DBUILD_apps_modeler=ON -DBUILD_apps_point_cloud_editor=ON -DBUILD_benchmarks=ON -DBUILD_examples=ON -DBUILD_simulation=ON -DBUILD_global_tests=ON`. I would prefer one pull request per enabled option.
I think we should leave surface_on_nurbs and everything related to CUDA and GPU OFF for now.

To build the benchmarks module, on Ubuntu the package `libbenchmark-dev` is needed.

**Comment by gnawme** [comment]
> Over 9000 lines changed? Sorry, but we have to break this up into smaller pull requests.

Sorry, I neglected to look at the LOC/files changed. Is there a LOC limit you would like observed per PR? Some of the build options don't raise any `clang-tidy` issues, so I grouped them as went along.

Just to clarify, should I add the build options to the `clang-tidy` Github action?

**Comment by mvieth** [comment]
> Sorry, I neglected to look at the LOC/files changed. Is there a LOC limit you would like observed per PR? Some of the build options don't raise any `clang-tidy` issues, so I grouped them as went along.

It's difficult to give a hard limit. In general, 200-300 changed lines are the upper limit in my opinion. The smaller the PR, the faster it will be merged. For easy changes (e.g. the same change applied in many places), it is okay to change more lines per PR than for complex changes. And you are right, if there are two or three build options that each only need a few code changes, it's fine to group them. So "one PR per option" is also not a strict rule :smile: 

> Just to clarify, should I add the build options to the `clang-tidy` Github action?

Yes, that would be nice. I will merge your other PR that adds the GitHub action soon, I just wanted to give the other maintainers a bit more time to review its current state

**Pull request closed without merging**
