### PR TITLE
[TRAVIS] Enable the build of apps.

### PR DESCRIPTION
**Pull request by frozar**
More tests in Travis CI.

### CODE REVIEW

**Comment by taketwo** [comment]
That was on the edge of 70 minutes!

**Comment by frozar** [comment]
Continous integration is definitely an issue for PCL. Rework has to be done as we know.

**Comment by SergioRAgostinho** [comment]
The first build failed on the merge with master 🤦‍♂️

**Comment by frozar** [comment]
For the non regression tests, everything should run without VTK, shouldn't they?

**Comment by frozar** [comment]
On my repository, I created the branch `travis_without_vtk` on top of `master`. I just use `-DWITH_VTK=OFF` to disable vtk. You can see the really promissing results of Travis CI there:  
https://travis-ci.org/frozar/pcl/builds/280901244

The build of `doc` failed (as usual on my repository) and the job `test-ext-1` failed also with this output:
```
95% tests passed, 1 tests failed out of 21

Total Test time (real) =  85.76 sec

The following tests FAILED:
	  4 - io_grabbers (Failed)
```

@taketwo, @SergioRAgostinho: What do you think about it?

**Comment by taketwo** [comment]
Can we disable "build-apps", or at least some of the apps? It's annoying that every time a build fails I need to open Travis and check "ah, ok, it's build-apps task timed out as usual, no problem".

**Comment by SergioRAgostinho** [comment]
Since we're on the edge, why not try to just disable those 4 or 5 I enable explicitly.

As a side comment, last time I checked, refactoring the apps target was a real pain.

**Pull request merged**
