### PR TITLE
remove unused boost headers includes

### PR DESCRIPTION
**Pull request by al-tu**

### CODE REVIEW

**Comment by mvieth** [comment]
@al-tu Are you still working on this? In the current state, it unfortunately does not compile ...

**Comment by al-tu** [comment]
> @al-tu Are you still working on this? In the current state, it unfortunately does not compile ...

yes, i think i'm close to finishing this one. i thought there is an opportunity to get rid of date_time incluclusion, but there's no easy way to do it. also `random` lib may probably be replaced (as discussed in some issues), but that is to be addressed in a separate PR

**Comment by al-tu** [comment]
> > i thought there is an opportunity to get rid of date_time incluclusion, but there's no easy way to do it
> 
> I think date_time is mostly needed for `to_iso_string` and `local_time`, to create a string representing the current time (for filenames etc), right? Maybe `std::strftime` or `std::put_time` can replace that? But that's just an idea, you don't have to do that. And if you do, I would suggest a new PR for that

i'll check out if there is a better option than basically copy-pasting those functions from boost (which doesn't seem to be a good idea). as for now, i've removed everything not used/forgotten/replaced with std::

**Comment by mvieth** [comment]
I don't fully understand some of the changes in `gpu`. Are they all a consequence of replacing the one `boost::array` with `std::array`?

**Review by mvieth — APPROVED** [review]
Thank you for your contribution!
In the interest of getting this merged now, I reverted some changes in the GPU module that seemed off-topic or where the reason behind the changes weren't clear to me. But feel free to open a new pull request with those changes if you think they are important, then we can discuss them again.

**Comment by al-tu** [comment]
> Thank you for your contribution! In the interest of getting this merged now, I reverted some changes in the GPU module that seemed off-topic or where the reason behind the changes weren't clear to me. But feel free to open a new pull request with those changes if you think they are important, then we can discuss them again.

thank you

**Pull request merged**
