### PR TITLE
Replace boost::bind with lambda

### PR DESCRIPTION
**Pull request by denix56**
Hi everybody,

I am currently working on replacement of boost::bind with lambdas. Work is not completed, but you can review what has already been done

**Maintainer Edit:** requires merge from #2878 first

### CODE REVIEW

**Comment by taketwo** [comment]
Thanks for starting to work on this.

I'm not sure if I understand/support the idea of replacing `boost::bind`ing of member functions with lambdas that capture `this` and call the functions. Can we just switch to `std::bind`?

Second important consideration is switching from `boost::function` to `std::function` in public APIs. It is similar to `shared_ptr` transition (which we haven't decided how to do yet), and we need to be very careful about this. I think it should be a two-step procedure. First we make sure that our APIs are not using "raw" types (i.e. we always provide typedefs for functions/callback types). Second we introduce a CMake option to choose which actual implementation (`boost` or `std`) is to be used.

**Comment by denix56** [comment]
@taketwo Lambdas are more efficient than std::bind and results in less and faster code. 
Also, Scott Meyers suggested to use lambdas for these reasons. Starting from c++14 there is no places where we cannot use lambdas instead of std::bind

**Comment by taketwo** [comment]
Did not know that. Can you give some references?

**Comment by denix56** [comment]
https://stackoverflow.com/questions/17363003/why-use-stdbind-over-lambdas-in-c14

**Comment by denix56** [comment]
https://stackoverflow.com/questions/17363003/why-use-stdbind-over-lambdas-in-c14

Effective Modern C++ (Scott Meyers):
The call to std::bind, however, passes a function pointer to setAlarm, and that
means that inside the function call operator for setSoundB (i.e., the function call
operator for the bind object), the call to setAlarm takes place through a function
pointer. Compilers are less likely to inline function calls through function pointers,
and that means that calls to setAlarm through setSoundB are less likely to be fully
inlined than those through setSoundL:
setSoundB(Sound::Siren); // body of setAlarm is less
 // likely to be inlined here
It’s thus possible that using lambdas generates faster code than using std::bind.

Compared to lambdas, then, code using std::bind is less readable, less expressive,
and possibly less efficient. In C++14, there are no reasonable use cases for
std::bind. In C++11, however, std::bind can be justified in two constrained situa‐
tions:

**Comment by denix56** [comment]
I have finally replaced all binds with lambdas as well as added typedefs to places where raw  ::function was used.

**Comment by SergioRAgostinho** [comment]
This PR is likely to be composed of a single commit and touching a combined total of 1300 lines of code. Once you get CI to run green please refactor it with over three separate PRs. My suggestion is to group up a couple of modules in separate PRs so that you try to aim at having no more than 500 lines of code touched.

**Comment by taketwo** [comment]
I back @SergioRAgostinho request, please split this over multiple PRs, otherwise we will choke at reviewing. On the first level I'd group by change type for trivial changes (e.g. `bind` -> lambda conversions). The rest could be grouped by module (e.g. there are a lot of things going on in `visualization`, can be in a single PR). Perhaps aim at even less than 500 lines.

**Comment by denix56** [comment]
I have split request in two (io module and all other modules) for lambda replacement. The other ones (boost::function -> std::function, replace raw ::function with typedefs etc.) will be done after merging current requests

**Comment by taketwo** [comment]
Superseded by a [set of PRs](https://github.com/PointCloudLibrary/pcl/pulls?utf8=%E2%9C%93&q=is%3Apr+is%3Aclosed+%22Prefer+lambdas%22).

**Pull request closed without merging**
