### PR TITLE
[cuda, gpu] Header fix for compilation

### PR DESCRIPTION
**Pull request by kunaltyagi**
Lack of CI. My apologies

### CODE REVIEW

**Comment by taketwo** [comment]
Hmm, I still get:

```
In file included from ../gpu/kinfu/tools/evaluation.cpp:37:0:
../gpu/kinfu/tools/evaluation.h:53:15: error: ‘shared_ptr’ does not name a type; did you mean ‘char16_t’?
   using Ptr = shared_ptr<Evaluation>;
               ^~~~~~~~~~
               char16_t
```

and a bunch of others in `gpu` module.

And more surprisingly:

```
[1/21] Building NVCC (Device) object cuda/segmentation/CMakeFiles/pcl_cuda_segmentation.dir/src/pcl_cuda_segmentation_generated_connected_components.cu.o
FAILED: cuda/segmentation/CMakeFiles/pcl_cuda_segmentation.dir/src/pcl_cuda_segmentation_generated_connected_components.cu.o
cd /home/sergey/Workspace/Libraries/pcl/build-1-10/cuda/segmentation/CMakeFiles/pcl_cuda_segmentation.dir/src && /usr/bin/cmake -E make_directory /home/sergey/Workspace/Libraries/pcl/build-1-10/cuda/segmentation/CMakeFiles/pcl_cuda_segmentation.dir/src/. && /usr/bin/cmake -D verbose:BOOL=OFF -D build_configuration:STRING=Release -D generated_file:STRING=/home/sergey/Workspace/Libraries/pcl/build-1-10/cuda/segmentation/CMakeFiles/pcl_cuda_segmentation.dir/src/./pcl_cuda_segmentation_generated_connected_components.cu.o -D generated_cubin_file:STRING=/home/sergey/Workspace/Libraries/pcl/build-1-10/cuda/segmentation/CMakeFiles/pcl_cuda_segmentation.dir/src/./pcl_cuda_segmentation_generated_connected_components.cu.o.cubin.txt -P /home/sergey/Workspace/Libraries/pcl/build-1-10/cuda/segmentation/CMakeFiles/pcl_cuda_segmentation.dir/src/pcl_cuda_segmentation_generated_connected_components.cu.o.Release.cmake
In file included from /home/sergey/Workspace/Libraries/pcl/common/include/pcl/pcl_macros.h:75:0,
                 from /home/sergey/Workspace/Libraries/pcl/common/include/pcl/point_traits.h:45,
                 from /home/sergey/Workspace/Libraries/pcl/common/include/pcl/make_shared.h:47,
                 from /home/sergey/Workspace/Libraries/pcl/cuda/common/include/pcl/cuda/point_cloud.h:42,
                 from /home/sergey/Workspace/Libraries/pcl/cuda/segmentation/src/connected_components.cu:40:
/usr/include/eigen3/Eigen/Core:42:14: fatal error: math_functions.hpp: No such file or directory
     #include <math_functions.hpp>
              ^~~~~~~~~~~~~~~~~~~~
compilation terminated.
```

**Comment by taketwo** [comment]
Sorry, did not notice the other PR (can we join them into one?) Still, after applying that patch I still get numerous errors in `gpu` module.

**Comment by kunaltyagi** [comment]
I'll apply those changes here. I can't compile gpu kinfu. CMake doesn't recognize my openni. The docker images will really help in this regard

**Comment by kunaltyagi** [comment]
PTAL

**Pull request merged**
