### PR TITLE
Improve shapes display by re-enabling lightning

### PR DESCRIPTION
**Pull request by VictorLamoine**
Before
---
before
After
---
after
Test project
---
[At your fingertips](https://gist.github.com/VictorLamoine/f0f59e660daa458d1ea5)

### CODE REVIEW

**Comment by jspricke** [comment]
Thanks Victor, it looks clearly like an improvement. Only, the lightning seems to be specifically disabled here: https://github.com/PointCloudLibrary/pcl/commit/d72d9b8d9494f20a50f94f64b0f71ebc67321e37 with a commit comment about wireframes. Can we disable it for wireframes maybe?

**Comment by VictorLamoine** [comment]
It's not a problem to enable lightning for shapes displayed as wireframe, I have just added
`viewer.setRepresentationToWireframeForAllActors();` before launching the viewer, here are the results:

Before
---
before_wireframe

After
---
after_wireframe

**Comment by jspricke** [comment]
You have to turn it around to see the the difference ;) (I've tried it over here).

**Comment by VictorLamoine** [comment]
I don't understand what you want to point; the wireframe lines are shaded.
Is there anything wrong with this?

**Comment by jspricke** [comment]
Run your test_shapes, press `w` turn model:
screenshot-1429188676

screenshot-1429188689

**Comment by VictorLamoine** [comment]
It happens because of the black background;
green_bg

I added a new commit that changes the `setRepresentationTo*ForAllActors ()` and the key `s` / `w`

**Comment by jspricke** [comment]
Thanks, LGTM.

**Pull request merged**
