### PR TITLE
Patch to fix clang-cl compiler compile time error(#5140)

### PR DESCRIPTION
**Pull request by KartikShrivastava**

### CODE REVIEW

**Review by larshg — APPROVED** [review]

**Comment by KartikShrivastava** [comment]
Hi, kindly wait for me to reproduce this error. As this patch was solely based on a suggestion of user and is not verified/reproduced yet.

**Comment by yuanchen-zhu** [comment]
Let me try it out

**Comment by yuanchen-zhu** [comment]
Yes, it works for my usage case. Sorry it took a while as I had to update vcpkg's port script to support pcl head. Note that is only for building pcl with msvc as usual (using vcpkg), and then consuming the built library in a project built using clang-cl.

**Review by mvieth — APPROVED** [review]
Thanks!

**Pull request merged**
