### PR TITLE
Move it to conditional state of rendering backend.

### LINKED ISSUE #5182: [compile error] Documentation doesn't compile (CI is red)
**Describe the error**

[CI compilation results/errors.](https://dev.azure.com/PointCloudLibrary/pcl/_build/results?buildId=20962&view=logs&j=e39aa7be-e494-54ce-b7c7-9d3a57135baa&t=7700d5f1-0838-52b6-ecbf-dfacd328c89d&l=71)

**Additional context**

Originates from #5160 
cc: @larshg

### PR DESCRIPTION
**Pull request by larshg**
Should hopefully fix #5182

### CODE REVIEW

**Comment by larshg** [comment]
Can we manually run the tutorial CI?

**Comment by mvieth** [comment]
> Can we manually run the tutorial CI?

I think the documentation CI runs for all PRs (see https://dev.azure.com/PointCloudLibrary/pcl/_build?definitionId=14, sometimes the runs are called `Merge <commit hash> into <commit hash>`, sometimes like the PRs), but it might take a bit to start.
Let me see if I can run the CI right now ...

**Comment by larshg** [comment]
Yeah, its just a bit late when it happens after its merged.

**Comment by larshg** [comment]
We do have a filter now that launches either the 6 standard builds or the doc/Tutorials build based on where there is changes. However we did talk about that it could good to run the tutorials build as a consumer of the other libraries.

**Comment by mvieth** [comment]
> We do have a filter now that launches either the 6 standard builds or the doc/Tutorials build based on where there is changes. However we did talk about that it could good to run the tutorials build as a consumer of the other libraries.

Agreed on the consumer thing, but I think the filter does not work the way we thought first: I think the documentation CI is run for every PR (before merge), but only linked to the PR on GitHub if the filter matches.
Anyway: I started the CI for this PR manually (note to future self: "Branch/tag" must be `refs/pull/5187/head`)

**Review by mvieth — APPROVED** [review]

**Pull request merged**
