### PR TITLE
Build only release for host-triplet

### PR DESCRIPTION
**Pull request by larshg**

### CODE REVIEW

**Comment by mvieth** [comment]
It seems like most of the time is spent building qt, and some packages appear twice, once with `x64-windows` and once with `x64-windows-rel`. Is that normal?

**Comment by larshg** [comment]
> It seems like most of the time is spent building qt, and some packages appear twice, once with `x64-windows` and once with `x64-windows-rel`. Is that normal?

I don't see any with only 'x64-windows' - only configuring. And then it builds for both release and debug, since release only is probably not supported for some reason.

Yeah, it takes time to build qt as well as vtk which is last.

**Comment by larshg** [comment]
Now I see what you meant, @mvieth, I have opened an [issue](https://github.com/microsoft/vcpkg/issues/29769)

**Review by mvieth — APPROVED** [review]
Is this something we should put into the install-PCL-via-VCPKG tutorial?

**Pull request merged**
