### PR TITLE
Fix for issue #681

### PR DESCRIPTION
**Pull request by vc-30**
Based on the discussion [here](https://github.com/PointCloudLibrary/pcl/issues/681#issuecomment-800952091) did the changes, please review it.

### CODE REVIEW

**Review by kunaltyagi — APPROVED** [review]
LGTM

**Comment by mvieth** [comment]
I am not very familiar with grabbers/devices in PCL yet. How do you know that it has to be an `ImageYUV422`, and not an `ImageBayerGRBG` or an `ImageRGB24`? Is that mentioned in some device manual?

**Comment by vc-30** [comment]
Hi @mvieth,

Thanks for the input, it appears there are two types of Xtion devices from ASUS 1. Xtion Pro and 2. Xtion Pro Live.

The Xtion Pro is just a depth sensor and details of it can be found in [Xtion Pro Specification](http://xtionprolive.com/asus-3d-depth-camera/asus%20xtion%20pro).
Similarly, Xtion Pro Live has the capability of producing RGB images as well as depth [Xtion Pro Live specification](http://xtionprolive.com/asus-3d-depth-camera/asus-xtion-pro-live).

Now I think based on [documentation](https://pointclouds.org/documentation/classopenni__wrapper_1_1_device_xtion_pro.html#details) in  io/include/pcl/io/openni_camera/openni_device_xtion.h it is referring to the Xtion Pro sensor (depth only). 

I am not sure based on that what would be the right datatype/object instance, that should be returned.

**Comment by mvieth** [comment]
If you are correct and that class is for the Xtion Pro (depth only), not for the Xtion Pro Live (depth+colour), then returning a null pointer might actually be correct, because (I think) `getCurrentImage` is for colour images. However, in that case which class is responsible for the Xtion Pro Live, maybe `DeviceONI`?
I might be able to make some experiments with the two devices in the next few days, will report back if a have results.

**Comment by mvieth** [comment]
I tried to do some tests but didn't get very far, and I probably won't be able to do more tests.
`DeviceONI` seems to read from ONI files, so unrelated to our discussion here.
I can't say for sure whether `DeviceXtionPro` is for the Xtion Pro Live as well, or whether the Xtion Pro Live is supported at all. So I am not sure which of the three image types is the right one, or whether the code should stay like it is (with null pointer). There is definitely more testing needed. You don't by chance have an Xtion Pro Live you can test with?

**Comment by vc-30** [comment]
Yes @mvieth, I don't have the respective hardware with which I can test, at least it is for sure the commit in this pull-request may not work as image is not of YUV422 type. Should we close this pull request and open a new one when we (or someone with hardware) can test it?

**Comment by mvieth** [comment]
> Yes @mvieth, I don't have the respective hardware with which I can test, at least it is for sure the commit in this pull-request may not work as image is not of YUV422 type. Should we close this pull request and open a new one when we (or someone with hardware) can test it?

I think that is a good idea, but I would also like to know @kunaltyagi 's opinion.

**Comment by kunaltyagi** [comment]
> I tried to do some tests but didn't get very far, and I probably won't be able to do more tests.

Issues with the hardware or PCL?

---
As always, this is a slight mess:
1. `DepthImage` is not a derived class of Image, and we can't create a depth image from a non-depth-metadata. So returning a depth image is a moot point (for depth only sensors)
2. `Image` for OpenNI doesn't mean DepthImage, but proper image only. The IO design in PCL also seems to reflect that, and that's another sign: don't return depth image

That means, our choices are restricted to returning either
* a nullptr, (current) or
* creating the image from whatever metadata is given (this PR)

The type of image comes into question (RGB or YUV) for the second case.

I favor the second (create the image and return), since the image is just a wrapper around the metadata, which contains the data as well. If it has no data, the image would be just... empty.

Between RGB24 and YUV422, I don't have a preference, since until hardware tests are done to determine which one is transmitted and captured, either one is fine till then.

**Comment by mvieth** [comment]
> > I tried to do some tests but didn't get very far, and I probably won't be able to do more tests.
> 
> Issues with the hardware or PCL?

Neither, I think. The message was something like "Could not open file", but it didn't seem to be a permission issue. I wasn't able to solve that because I had very little time with the hardware and I don't have any experience with PCL's grabbers (I received the point clouds as ROS messages so far).

@vc-30 Maybe you would like to have a look at [the other "good first issues"](https://github.com/PointCloudLibrary/pcl/issues?q=is%3Aissue+is%3Aopen+label%3A%22good+first+issue%22)?

**Comment by vc-30** [comment]
Sure @mvieth, will take a look. Thanks.

**Pull request closed without merging**
