### PR TITLE
Add a new "graph" module and point_cloud_graph class

### PR DESCRIPTION
**Pull request by taketwo**
This starts a series of pull requests to contribute the sources developed as a part of the past Toyota Code Sprint. The first few requests will be concerned with introduction of a new experimental module "graph". Later requests will add random walker based segmentation class. Finally, an example app and a tutorial will be submitted. The contribution is split into several pull requests to simplify reviewing process as the amount of code is quite large.

> **pcl_graph** is an experimental library that aims to provide a common toolbox to aid development of graph-based 3D processing algorithms within the PCL framework. The library has a strong influence from
> [Boost Graph Library](http://www.boost.org/doc/libs/1_55_0/libs/graph/doc/table_of_contents.html) and relies on the concepts, classes, and algorithms found there.
> 
> At the heart of the library lies the pcl::graph::point_cloud_graph class, which may be considered to be a blend of a PCL point cloud and [boost::adjacency_list](http://www.boost.org/doc/libs/1_55_0/libs/graph/doc/adjacency_list.html) (the most common graph representation in BGL). As such, this class may be used in PCL algorithms where a point cloud input is expected, as well as in BGL algorithms, where a graph is needed.

The `point_cloud_graph` class comes with a very extensive documentation, both in the form of doxygen comments for the end-users, and normal in-code comments explaining non-trivial sections.

A unit test with 30+ cases is also present.

### CODE REVIEW

**Comment by SergioRAgostinho** [comment]
Let's pick this up again for 1.9.0  (once we get there). 

(insert here usual paragraph about the tutorial)

**Comment by taketwo** [comment]
Not sure if this needs to go into the main PCL repo, I can not commit to supporting this.

**Comment by SergioRAgostinho** [comment]
What should we do with this? One idea would be to create a repo with experimental stuff like OpenCV has. This could go there as well as our `ml` module.

**Comment by taketwo** [comment]
On one hand, something like `pcl_contrib` is nice for trying out interfaces and adding experimental code. On the other hand, it increases maintenance burden. Not clear for contributors where to send pull requests. Not clear when stuff from there is migrated to the main repo...

**Comment by SergioRAgostinho** [comment]
I would say only new entire modules go there, or the ones which are clearly not production ready. My suggestion was on a per module base. Either a module is in the experimental repo or it's in the main one, and the contribution goes to where the corresponding module exists.

**Comment by taketwo** [comment]
I don't see much value in this, honestly. I can just put the code from this pull request into a separate Github repo and that's it. If anyone is ever interested, he can just clone and give a try, no need for ceremonies.

**Comment by SergioRAgostinho** [comment]
Fair enough. I'm also ok with that and we close this.

**Pull request closed without merging**
