### PR TITLE
Fix missing definition "boost::optional"

### PR DESCRIPTION
**Pull request by dongchenyu163**
Reported at issue #5209.

### CODE REVIEW

**Comment by mvieth** [comment]
Thanks! I am not sure why our CI jobs don't start, let me close and reopen this to hopefully trigger them ...

**Review by mvieth — APPROVED** [review]
Looks good to me, provided the CI checks pass

**Comment by larshg** [comment]
Maybe change it to [std::optinonal ](https://en.cppreference.com/w/cpp/utility/optional) ?

**Comment by mvieth** [comment]
> Maybe change it to [std::optinonal ](https://en.cppreference.com/w/cpp/utility/optional) ?

That's only available since C++17, we're still at C++14

**Comment by larshg** [comment]
> > Maybe change it to [std::optinonal ](https://en.cppreference.com/w/cpp/utility/optional) ?
> 
> That's only available since C++17, we're still at C++14

Ahh, right.

**Pull request merged**
