### PR TITLE
Misc. typos (cont. 2)

### PR DESCRIPTION
**Pull request by luzpaz**
Found via `codespell -q 3 -I ../pcl-whitelist.txt --skip="./surface/include/pcl/surface/3rdparty,./surface/src/3rdparty,./recognition/include/pcl/recognition/3rdparty"`  
Whitelist:
```
ang
childs
everytime
iff
indeces
isnt
ith
lod
metre
metres
mitre
nd
normaly
ot
resizeable
te
vertexes
```

### CODE REVIEW

**Comment by luzpaz** [comment]
Darn, I think i screwed this commit up. It shouldn't show that many files have been changed. I think it's because I branched this off of #2215 accidentally. I thought if I just rebased it off of master that it would reset it.

**Comment by SergioRAgostinho** [comment]
Did you force push after ? That's necessary

--

**Comment by luzpaz** [comment]
Closed in favor of #2217

**Comment by SergioRAgostinho** [comment]
> Is there a way I can eliminate the 3 previous commits and only keep: b3085a3 and
19c56e1 ?

Yes, using git's interactive rebasing functionality. You can drop out entire commits.

**Comment by luzpaz** [comment]
> Yes, using git's interactive rebasing functionality. You can drop out entire commits.

Never used it before. Thanks for the heads-up

**Pull request closed without merging**
