### PR TITLE
Discord bot to help maintainers discover issues and PR

### PR DESCRIPTION
**Pull request by kunaltyagi**
Bot is ready, CI not so much.

### CODE REVIEW

**Comment by kunaltyagi** [comment]
How does `PointCloudLibrary/meta` sound for stuff like this?

**Comment by SergioRAgostinho** [comment]
I would got for `PointCloudLibrary/discord-bot` or `PointCloudLibrary/discord`. There's no reason at this moment to create and umbrella repository this early.

@jspricke we need your powers to create a new repo once the name is agreed upon.

**Comment by kunaltyagi** [comment]
`discord-bot` it is then

**Comment by jspricke** [comment]
@kunaltyagi can you add some description to the commits what this is doing? Also, maybe squash the commits.
Can you also add some comments here what the new repo is about and who should have access?

**Comment by kunaltyagi** [comment]
The access rights will mirror the main pcl repo for now.

I'll reorganize the commits and send a PR on the repo once it is created.

I created a bot which helps to find issues and allow the community to make progress on random issues (to reduce the number of open issues). It also helps discover PR in the merge queue. The features might be added/removed based on future needs. Github search can't give random issues to close/add detail/work on and old or issues in middle will always languish.

**Comment by jspricke** [comment]
but how is that PCL related? Why should it be in the PointCloudLybrary organization? (Just asking)

**Comment by SergioRAgostinho** [comment]
It's currently being used on PCL's discord server to perform the functionalities Kunal mention. Discord is IM system we're endorsing to that users can reach out to us. It's also gonna be the chat/voice conference platform we're gonna be using to support this year's GSoC.

Does it need to be hosted on PCL's organization? Not really, but it was developed specifically with PCL's Discord in mind so it does fit the topic.

**Comment by jspricke** [comment]
Should be there now, ping me if you need more.

**Pull request closed without merging**
