### PR TITLE
Make Boost filesystem optional for C++17

### PR DESCRIPTION
**Pull request by cybaol**
#5881

### CODE REVIEW

**Comment by mvieth** [comment]
Additionally, `outofcore/CMakeLists.txt`, `recognition/CMakeLists.txt`, and `apps/3d_rec_framework/CMakeLists.txt` need to check whether the boost filesystem library was found, else disable building the modules.

**Comment by cybaol** [comment]
The `apps/CMakeLists.txt` depends on the `recognition` module. So I didn't change it.
And the extra dependency `boost_filesystem` seems not a correct name. I checked the name of the boost filesystem in the system, but the pcl still doesn't recognize it as its dependency. So I added an `if else`.

**Comment by mvieth** [comment]
To be honest, I think the previous version was better (before the "Simpler changes" commit). Now, the disabled modules are not mentioned at all in the CMake log, and no explanation why they are not built. Previously it said e.g. `recognition: Requires external library boost_filesystem`. Alternatively, you can do it like here: https://github.com/PointCloudLibrary/pcl/blob/master/gpu/kinfu/CMakeLists.txt#L5
Another thing: I noticed that `filesystem` is still listed here: https://github.com/PointCloudLibrary/pcl/blob/master/cmake/pcl_pclconfig.cmake#L88 It should be handled there like `serialization`. If you could change that as well, that would be great (important for projects using PCL)

**Review by mvieth — APPROVED** [review]
Thank you, it works nicely now :smile:

**Pull request merged**
