### PR TITLE
[tracking] made ParticleFilterTracker API user friendly

### PR DESCRIPTION
**Pull request by NehilDanis**
The solution for the issue defined [here](https://github.com/PointCloudLibrary/pcl/issues/4655). Used SFINAE in `setUseNormal` method. This way if users won't be able to set `use_normal_` variable to true, if they use pointcloud type which does not include normal.

### CODE REVIEW

**Comment by mvieth** [comment]
Thank you for working on this!
As an alternative to SFINAE, what do you think about using something like this in `setUseNormal`: `if(traits::has_normal_v<PointInT>)`? That would avoid the `ifdef DOXYGEN_ONLY` and the multiple definitions of `setUseNormal`. And, since the function is only called once, the if statement does not hurt the performance.

**Comment by NehilDanis** [comment]
> Thank you for working on this!
> As an alternative to SFINAE, what do you think about using something like this in `setUseNormal`: `if(traits::has_normal_v<PointInT>)`? That would avoid the `ifdef DOXYGEN_ONLY` and the multiple definitions of `setUseNormal`. And, since the function is only called once, the if statement does not hurt the performance.

Yes, that would be better, also we would prevent this unused variable as well. Thanks!

**Comment by mvieth** [comment]
Another (minor) thing: if a user calls `setUseNormal(false)` with a point type that does not have a normal, the warning would appear. It should only appear if the parameter is true.

**Review by mvieth — APPROVED** [review]
Thanks!

**Review by kunaltyagi — APPROVED** [review]

**Pull request merged**
