### PR TITLE
Fix PLYReader is_dense behavior

### PR DESCRIPTION
**Pull request by SergioRAgostinho**
Superseedes #1460 
Fixes: #1455

### CODE REVIEW

**Comment by taketwo** [comment]
Can you please rebase this?

**Comment by taketwo** [comment]
`PCL.Octree_Pointcloud_Adjacency` test failed on AppVeyor. Weird.

**Comment by SergioRAgostinho** [comment]
It's not triggering on Mac with the current master. I've rebased and I'll push again to check results. If it fails again it's better to have @UnaNancyOwen have a look to see if it fails also on his environment.

**Comment by SergioRAgostinho** [comment]
It went through :+1:

**Pull request merged**
