### PR TITLE
Update issue templates

### PR DESCRIPTION
**Pull request by kunaltyagi**
GitHub has new issue template, and the old one is expected to be deprecated

### CODE REVIEW

**Comment by taketwo** [comment]
I'm not sure I like compounding the title with module name, we have labels for that.

Speaking of labels though, we may need to revise our system. @kunaltyagi do you have any other open-source project in mind with a good label taxonomy? I find this one interesting: https://github.com/xmonad/xmonad/labels

**Comment by kunaltyagi** [comment]
That's lovely. It's like how people organize folders in email apps :smile: 

> we have labels for that

But reporters can't access them (AFAIK).

**Comment by taketwo** [comment]
> But reporters can't access them (AFAIK).

What does the `labels: ...` line do then?

**Comment by kunaltyagi** [comment]
It sets the label automatically. Good for having filters for triaging, etc. in larger organizations

**Comment by Morwenn** [comment]
I know that some big projects would use `[module_name]` in the title so that they can identify what askers are talking about, but would only use labels for the issue triaged by the project team. The rationale is that when you're sorting & filtering issues you want triaged issues and not for example things that users consider like bugs when they're actually incorrectly using a feature or asking for a new feature.

**Comment by kunaltyagi** [comment]
Much better worded. Thanks @Morwenn 

* Title: by user, for the team. Can have mislabeled data points 😛 
* Labels: by team, for the team. Better not have mislabeled data points 😆

**Comment by Morwenn** [comment]
Wouldn't it mean adding the "status: needs review" tag for PCL by default to identify the issues that stil haven't be triaged?

**Comment by taketwo** [comment]
I know this PR is about issue templates, but I feel it's so tightly connected with our triaging/labeling process that the discussion of the latter should happen here as well.

I think our label taxonomy is in relatively good shape. Most of our labels are clearly grouped (e.g. status, platform, module). Most of our labels are self-explanatory. Our labels seem to cover most of our needs. However, inspired by the [taxonomy in Xmonad project](https://github.com/xmonad/xmonad/labels?page=1&sort=name-asc), I see a number of ways we can improve.

Specifically, I think we may:

1. Add "skill" group
2. Add "effort" group
3. Rethink our "status" group, potentially split into "status" and "needs"
4. Group existing labels into "kind" group

What are your thoughts about this? I'll probably formalize my proposal into a table form. However, since my proposal will be heavily inspired by Xmonad, perhaps you can already share ideas/thoughts that that list provoked in you.

And by the way, in relation to this PR, @kunaltyagi is there some way to check how the templates will look like if the PR is merged?

**Comment by kunaltyagi** [comment]
>  is there some way to check how the templates will look like if the PR is merged?

AFAIK, no. We'll need to remove the current template too at some point. I don't know if the new templates take effect immediately or not. [Here's some more details](https://help.github.com/en/github/building-a-strong-community/about-issue-and-pull-request-templates)

Regarding taxonomy,
1. Skills as in level (low, mid, high) or area (if so, any proposed tags?)
2. Effort sounds good for bugs and feature-request issues. Doesn't make sense for PR :smile: 
3. :+1: 
4. I didn't get this. Did you mean the numbering trick used by xmonad?

**Comment by Morwenn** [comment]
Another example I like is Conan (see their [issue page](https://github.com/conan-io/conan/issues)): it's got complexity (low, medium, high), priority (low, medium, high), stage (triaging, queue, in-progress, needs review, etc.), type (bug, feature, etc.) and component (which part of the project it concerns). There is no difference between skill/effort/complexity though, so the Xmonad model seems more complete in that regard.

**Comment by kunaltyagi** [comment]
Label category comparison

| [Conan](https://github.com/conan-io/conan/labels) | [Xmonad](https://github.com/xmonad/xmonad/labels) | PCL (now) | PCL (proposed) |
|--|--|--|--|
| complexity | - |
| - | effort |
| - | skill |
| component | topic | module |
| priority | severity |
| stage | status | status |
| type | kind | misc |
| - | future-action/needs | status |
| misc | - | misc |
| - | - | changes |
| - | - | platform |

@taketwo Made a table for ya. Feel free to edit

**Comment by taketwo** [comment]
> Skills as in level (low, mid, high) or area (if so, any proposed tags?)

I thought about area; level is subjective, not informative, and may even feel dismissive. Examples are `cuda`, `cmake`, `openmp`. Though label set "module: cmake", "skill: cmake" looks redundant :confused:

> Effort sounds good for bugs and feature-request issues. Doesn't make sense for PR

Sure. Not all groups are expected to be applicable to both issues and PRs.

> I didn't get this. Did you mean the numbering trick used by xmonad?

No, I meant to add "kind: " prefix to some of our already existing labels like "proposal" or "bug".

> Another example I like is Conan (see their issue page):

Thanks for the link. Priority makes sense. On the other hand, in PCL I can confidently distinguish only critical vs. non-critical issues. Grading the latter is subjective and in the end, has limited utility. Also `stage: queue` is a bit mysterious to me.

> @taketwo Made a table for ya. Feel free to edit

Thanks! Don't you think "conan/complexity" is the same as "xmonad/effort"?

**Comment by Morwenn** [comment]
@taketwo `stage: queue` is a bit linked to priority: Conan has a paid team with a release schedule AFAIK and thus they release versions on a regular basis and have to put issues in and out of scope all the value. The "queue" stage basically means that the issue has been acknowledged and is on the list of things to do - most of the time those issues have passed the design stage.

**Comment by taketwo** [comment]
Here is a (work-in-progress) proposal, I still need to think through some things.

| Category | Label              | Applicable | Comment                                                |
|----------|--------------------|---------------|--------------------------------------------------------|
| kind     |                    | issue         |                                                        |
|          | bug                |               |                                                        |
|          | question           |               |                                                        |
|          | proposal           |               |                                                        |
|          | request            |               |                                                        |
| effort   |                    | issue         | Rough estimate of time needed to fix/implement/solve   |
|          | trivial            |               |                                                        |
|          | low                |               |                                                        |
|          | medium             |               |                                                        |
|          | high               |               |                                                        |
| skill    |                    | issue         | Skills/areas of expertise needed to tackle the issue   |
|          | good first issue   |               | Nothing in particular                                  |
|          | cmake              |               |                                                        |
|          | azure              |               |                                                        |
|          | openmp             |               |                                                        |
|          | meta-programming   |               |                                                        |
| module   | ...                | issue, pr     |                                                        |
| status   |                    | issue, pr     |                                                        |
|          | invalid            |               |                                                        |
|          | duplicate          |               |                                                        |
|          | work in progress   |               |                                                        |
|          | wontfix            |               |                                                        |
|          | stale              |               |                                                        |
|          | done               |               |                                                        |
| needs    |                    | issue, pr     | Specify why status can not be changed to "done"        |
|          | testing            |               |                                                        |
|          | review             |               |                                                        |
|          | decision           |               |                                                        |
|          | op feedback        |               |                                                        |
|          | community feedback |               | (?)                                                    |
|          | pr merge           |               |                                                        |
| log      |                    | pr            | Meta-information for changelog generation              |
|          | new feature        |               | Highlight addition of new feature or major enhancement |
|          | API break          |               |                                                        |
|          | ABI break          |               |                                                        |
|          | deprecation        |               |                                                        |
|          | removal            |               |                                                        |
|          | behavior change    |               |                                                        |
|          | exclude            |               | Exclude PR from changelog (for minor stuff)            |
| platform |                    | issue         | For platform specific issue (optional)                 |
|          | linux              |               |                                                        |
|          | windows            |               |                                                        |
|          | macos              |               |                                                        |

**Comment by kunaltyagi** [comment]
Maybe "needs: feedback: OP", "needs: feedback: community", "needs: feedback: maintainers" will clarify the diff name/overlapping area that you pointed out.

Labels now has a description field that can be used for the stuff in the comment column

**Comment by taketwo** [comment]
Thanks for the proposal. Two colons feels like too much for a single label though :)

I had a fresh look at the table above and realized that in some cases I created labels ony for the sake of creating labels. This is not how it's supposed to be; each category should serve a certain pragmatic purpose. Therefore, I tried to make a clear list of goals/problems that the label taxonomy has to solve:

1. Make it easier for potential contributors to orient among the miriads of open issues that need attention.

   "help needed" and "good first issue" are better than nothing, but not particularly informative. What kind of help is needed? Why is the issue good to be the first one? Because it does not require strong C++ skills or because it's low effort?

2. Automate changelog generation.

   Our "changes: x" and "module: x" labels already drive automated changelog generation. Some improvements are needed, however.

3. Automate monitoring/labeling of stale issues and PRs.

   We automatically label PRs as "stale" if certain condition holds. It would be nice to enable automatic labeling/closing of issues as well.

4. Support clear processes for dealing with PRs and various kinds of issues.

   The final state of each issue is to be closed and for each PR is to be merged. The labels should clearly indicate what prevents issue/pr from reaching its final state.

With these goals is mind, I came up with the following refined table:

| Category | Label              | Applicable | Comment                                                |
|----------|--------------------|------------|--------------------------------------------------------|
| -        | triage             | issue, pr  | Automatically assigned on creation                     |
| -        | stale              | issue, pr  | Automatically assigned by stalebot                     |
| kind     |                    | issue      |                                                        |
|          | bug                |            |                                                        |
|          | question           |            |                                                        |
|          | proposal           |            |                                                        |
|          | request            |            |                                                        |
|          | todo               |            |                                                        |
| effort   |                    | issue      | Rough estimate of time needed to fix/implement/solve   |
|          | trivial            |            |                                                        |
|          | low                |            |                                                        |
|          | medium             |            |                                                        |
|          | high               |            |                                                        |
| skill    |                    | issue      | Skills/areas of expertise needed to tackle the issue   |
|          | good first issue   |            | Nothing in particular                                  |
|          | cmake              |            |                                                        |
|          | azure              |            |                                                        |
|          | openmp             |            |                                                        |
|          | meta-programming   |            |                                                        |
| module   | ...                | issue, pr  |                                                        |
| needs    |                    | issue, pr  | Specify why not closed/merged yet                      |
|          | testing            |            |                                                        |
|          | review             |            |                                                        |
|          | author reply       |            |                                                        |
|          | community feedback |            |                                                        |
|          | pr merge           |            |                                                        |
| log      |                    | pr         | Meta-information for changelog generation              |
|          | new feature        |            | Highlight addition of new feature or major enhancement |
|          | API break          |            |                                                        |
|          | ABI break          |            |                                                        |
|          | deprecation        |            |                                                        |
|          | removal            |            |                                                        |
|          | behavior change    |            |                                                        |
|          | exclude            |            | Exclude PR from changelog (for minor stuff)            |
| platform |                    | issue      | For platform specific issue (optional)                 |
|          | linux              |            |                                                        |
|          | windows            |            |                                                        |
|          | macos              |            |                                                        |

Now let's talk processes.

## Issues

1. Each issue starts with the "triage" label.
2. Maintainer examines the issue and either assign a "kind: x" label, or asks follow-up questions until the kind can be determined.
3. Depending on the issue kind, "skill: x", "effort: x", and "platform: x" labels are assigned.
4. Depending on the issue kind, it stays open until:
   1. "kind: bug" - fixed
   2. "kind: question" - answered
   3. "kind: proposal" - rejected or accepted and converted into todo/pr
   4. "kind: request" - implemented
   5. "kind: todo" - implemented

Note that once at step 4 issue does not have to have a "needs: x" label. The kind implicitly decides what is needed. However, when we wait for author reply we should add "needs: author reply" label. This allows to keep track of stalled discussions and (potentially) automatically close issues that the author lost interest in.

## PRs

1. Each PR starts with the "triage" label.
2. Maintainer examines the PR and either merges it immediately, or initiates the "review - feedback - refinement" cycle.
3. During the cycle a label is added to clearly indicate where in this cycle we are and what is needed to move on. Options are:
   1. "needs: review" - author can not do anything, maintainer or community review is required
   2. "needs: author reply" - similar to when issues are triaged
   3. "needs: more work" - everything is clear, but more work is needed to finish off this PR
   4. "needs: testing" - someone with appropriate hardware/platform has to test changes since they are not or cannot be covered in CI
   5. "needs: pr merge"

Sometimes contributors go ahead to implement and submit a PR that has questionable relevance and/or value. In such cases "kind: proposal" label may be applicable to indicate that a discussion/decision is needed.

---

I feel like the taxonomy I came up with supports all the four goals that I have in mind. It's  major difference to the previous iteratino is removal of the "status" category. The only statuses that are still needed are "triage" and "stale". Since these are only two, I think they can live without an explicit category.

So... what do you think? Anything I missed?

**Comment by kunaltyagi** [comment]
Apart from status, there aren't any big changes, just refinement (for the people who want to compare the 2 table).

You did give it a lot of thought. I have a few follow-up questions

`needs: taketwo-feedback` 😛 

1. If person A can add only a few labels, but not all, what's the appropriate thing to do? Keep the triage label or add a label like 'effort: unspecified'?
2. > nice to enable automatic labeling/closing of issues as well

    How? Are there other bots like stale-bot? Or can that bot do multiple things? What label would you prefer? How is it different that what Github does with issues being closed by PRs?
3. Maybe rename log to changelog since then explanation isn't needed
3. In issues, I sometimes feel the need of a "needs: mcve" label. Dunno if this falls under "needs: author response" category
4. What's the difference between todo and request? Is todo for PR and request for issue or am I missing something?


Food for thought: If the number 2 needs a label for closed issues/PR, this adds 3 labels out of the earlier list of status. 'status: in-progress' is implicit. Then only wontfix and duplicate have been left out. Duplicate sounds like it might be good since a lot of issues regarding VTK and website are similar enough.

**Comment by taketwo** [comment]
> 1. If person A can add only a few labels, but not all, what's the appropriate thing to do? Keep the triage label or add a label like 'effort: unspecified'?

You are talking about maintainers, right? I think the only required label for issues in "kind: x" and for PRs is "needs: x". The application of other categories of labels is optional. And I don't think we need "effort: unspecified", it's implied if there is no "effort: x" label.

> > 2. nice to enable automatic labeling/closing of issues as well
>
> How? Are there other bots like stale-bot? Or can that bot do multiple things? What label would you prefer? How is it different that what Github does with issues being closed by PRs?

Stale-bot is [configurable](https://github.com/probot/stale). At the moment, it's set to label PRs that await author feedback for more than 60 days as "stale". The idea behind this is to a) bump the PR thread to encourage the author to finish the work; b) clearly mark abandoned PRs. We decided against automatically closing such PRs because sometimes, although unfinished, they contain nuggets of useful code that others may spot and potentially pick up.

The bot currently does not touch issues. With my proposed process/labels I think we can extend its configuration to bump *not triaged* issues that await authors feedback for 1-2 weeks and then automatically close them if there is still no reply in another 1-2 weeks.

> 3. Maybe rename log to changelog since then explanation isn't needed

:+1: if you think it's more clear.

> 4. In issues, I sometimes feel the need of a "needs: mcve" label. Dunno if this falls under "needs: author response" category

Yes, it does. My idea is to avoid having a vast set of specialized labels.  Nobody else but the author of the issue is supposed to come up with MCVE. So hypothetical "needs: mcve" would always imply "needs: author response". From maintainers perspective, whether an issue needs specifically MCVE or some other kind of author response does not really matter. We just forget about it until the author is back with the reply. And from the authors perspective, an explicit label also does not add much, a simple comment from maintainers requesting MCVE would do.

> 5. What's the difference between todo and request? Is todo for PR and request for issue or am I missing something?

Both are for issues. They are similar in that in order to close them something needs to be implemented. The difference, however, is in the origin and the "weight".

A "kind: request" comes from the community (e.g.: "Add implementation of new ICP objective function). Once triaged, we acknowledge that this is a valid request and contains enough information to be acted upon. However, it does not necessarily (actually, most likely not) go onto maintainers TODO list. We'd set expectations too high if we assign such a label.

A "kind: todo" comes from maintainers (e.g.: "Include PCL_VERSION in find_package output"). It skips triaging stage and directly ends up on our TODO. By definition, it's something we (maintainers) believe needs to be done. Maybe we can consider calling it "request" as well, but it's a bit strange to request ourselves to do something.

Maybe you can come up with some other label that is more neutral and can be applied to both kinds?

Regarding labels like "wontfix" and "duplicate". Again, I'd avoid having a vast set of specialized labels. When we close an issue that qualifies for such label,  we certainly post a comment explaining why we won't fix or which other issue this one is a duplicate of. And if we do so, then what's the pragmatic use of additionally attaching a label?

**Comment by kunaltyagi** [comment]
Got it,  makes sense. Thanks for the explanation 😄

**Comment by kunaltyagi** [comment]
Need decision to keep/rename/delete the following:
* enhancement
* modernization
* platform: android
* platform: ios
* status: in progress
* status: needs decision
* status: needs upstream fix
* different colors for `stale` and `triage`

Need more discussion on "special status" by GitHub labels:
* good first issue
* help wanted

My modifications:
* added `status:` to `triage` and `stale`
* added `kind: compile error` to highlight a large section of issues
* color changes to be more uniform

**Comment by taketwo** [comment]
> Need decision to keep/rename/delete the following

* `enhancement`: rename into `changelog: new feature`
* `modernization`: delete. This was a helper label to group gazillions of PRs in the changelog for 1.10. Generally, such grouping should instead be done through Projects.
* `platform: android` / `platform: ios`: no strong opinion. Probably delete since we don't really support these platforms?
* `status: in progress`: rename into `needs: more work`. If you have a better name in mind, let me know (Note that this label was missing from the table, but I discussed it in the running text. Added now to the table.)
* `status: needs decision`: implied by `kind: proposal`. Is it possible to merge labels? Then I'd merge with `kind: proposal`.
* `status: needs upstream fix`: it was needed like once or so

> My modifications:

* proposal: add `status:` to triage and stale. Not opposed. Dittor for different colors
* done: added `kind: compile error` to highlight a large section of issues. In my taxonomy this is a part of `kind: question`. The primary reason why I did not feel like separating is because I don't plan to treat these differently. Both are most likely gonna be closed with a redirect to StackOverflow. That said, you seem to be already troubleshooting (at least some) compile error issues. If having a label to highlight it helps, then why not. But just to make it clear, do you envision a different flow for dealing with `compile error` vs. `question`? If we have an open issue of type `compile error`, how do we close it?
* done: color changes to be more uniform :+1: great color choices!

> Need more discussion on "special status" by GitHub labels:

* good first issue: this maps to our `skill: good first issue`
* help wanted: I don't know what is meant by this. Whose help is wanted? By whom?

**Comment by taketwo** [comment]
And ooops, the stalebot wreaked havoc! Once we sort out the last label questions, we should update the config.

**Comment by Morwenn** [comment]
`enhancement` can be more than new features: a significant optimization or a more secure algorithm are both significant enhancements without being new features per se.

**Comment by kunaltyagi** [comment]
A compile error needs someone to replicate it, find the issue and resolve. Which is unlike a question since a question doesn't need to be replicated. If I know something is marked as windows, compile error, I really can't help on it. Saves some cognitive load from the people not interested in windows (aka me 😆 )

> Need more discussion on "special status" by GitHub labels:

Github will display the special labels above the issue/PR randomly. Us changing the labels might not reflect there.

> status: needs decision: implied by kind: proposal. Is it possible to merge labels? Then I'd merge with kind: proposal.

I don't think it's possible to merge labels. I wish I were better at JS to simply use the Gihub API to re-label the issues. I can, but in the same time as manual 🤣. Moreover, some "needs decision" are PR, not issues.

> stale-bot

Now we have `stale` and `status: stale`. Please delete one when you're done tinkering with the stale-bot. I'm afraid of messing it up now that I've seen it's avalanche.

**Comment by taketwo** [comment]
> enhancement can be more than new features: a significant optimization or a more secure algorithm are both significant enhancements without being new features per se

Sure, there is a difference. But note that the "changelog: x" labels are helpers for changelog generation and there is no distinction between "new feature" and "enhancement" in the changelog. I'm not sure we need to have it. What about a more general name like "changelog: noteworthy"?

> compile error

:+1: ok

> Github will display the special labels above the issue/PR randomly. Us changing the labels might not reflect there.

Is this a problem?

> Moreover, some "needs decision" are PR, not issues.

Yes, I mentioned this before. Authors of some questionable PRs skip the step of creating an issue with a proposal for discussion. In that case the PR thread becomes the place to discuss the proposal and thus "kind: proposal" is applicable.

> Please delete one when you're done tinkering with the stale-bot.

:+1:

**Comment by kunaltyagi** [comment]
Any changes needed in the issue template? Should I use sections `##` instead of bold `**`?

**Comment by kunaltyagi** [comment]
Added a change for multi-labels. Had to test this before using a short PR.

**Comment by SergioRAgostinho** [comment]
Is there any more work you want to perform here or can this be merged?

**Pull request merged**
