### PR TITLE
Enable Windows builds on Azure Pipelines

### PR DESCRIPTION
**Pull request by taketwo**

### CODE REVIEW

**Comment by UnaNancyOwen** [comment]
If Azure Pipelines has not time-limit of job, visualization (test_visualization) testing may be possible.
Please consider to add vcpkg install vtk.

**Comment by UnaNancyOwen** [comment]
tools may not be necessary for tests. (<code>-DBUILD_tools=OFF</code>)
surface_on_nurbus may be tests. (<code>-DBUILD_surface_on_nurbs=ON</code>)

**Comment by UnaNancyOwen** [comment]
I think CMake creates an x86 project by default under Windows.
It is need specify generator by target architecture.
```
# x86
cmake -G "Visual Studio 15 2017"
# x64
cmake -G "Visual Studio 15 2017 Win64"
```

**Comment by taketwo** [comment]
> If Azure Pipelines has not time-limit per job, visualization (test_visualization) testing may be possible.

It would be nice to enable visualization build as well. I'm concerned with the build time though. Yes, there is no limit on Azure, however we probably don't want our pipelines to take forever to build. There is no caching, so _vcpkg_ has to install everything from scratch every time. Right now (without `vtk`) it already takes 20 minutes to install the dependencies, plus another 2 hours for the library build. I'm afraid adding `vtk` can add another 30-40 minutes. But yeah, once the pipeline is working I'll give it a try to know the exact numbers and then we can decide if we enable it or not.

>  It is need specify generator by target architecture.

Thanks for the suggestion. This would explain why x64 build failed immediately.

The x86 build succeeded, however most tests failed with obscure `**Exception: Exit code 0xc0000135`. Do you have any idea what this could mean?

**Comment by SergioRAgostinho** [comment]
> Do you have any idea what this could mean?

Could it be that the path to the test files is somehow incorrect? If you notice, it's always tests which take files as command line arguments.

**Comment by UnaNancyOwen** [comment]
> There is no caching, so vcpkg has to install everything from scratch every time.

It is mean there is no cache feature in Azure Pipelines?
@kaylangan She may know good ideas and information.

**Comment by UnaNancyOwen** [comment]
> Do you have any idea what this could mean?

Please try to turn on VCPKG_APPLOCAL_DEPS. (<code>-DVCPKG_APPLOCAL_DEPS=ON</code>)

**Comment by taketwo** [comment]
> If you don't use ninja-build, it is unnecessary to specify them explicitly.

I tried without yesterday, but ended up with GCC 5 being picked up as a compiler. However, now I understand that it was because I did not set "Visual Studio 15 2017" as a generator.

> Please try to turn on `VCPKG_APPLOCAL_DEPS`

Will add with next commit.

**Comment by taketwo** [comment]
> Could it be that the path to the test files is somehow incorrect? If you notice, it's always tests which take files as command line arguments.

There is at least one test that uses files and succeeded: 

```
100: Test command: D:\a\build\bin\test_random_walker.exe "D:/a/1/s/test/segmentation/data"
```

Also there are lots of tests that don't load files but also failed.

**Comment by UnaNancyOwen** [comment]
The x86 tests seems to have failed, but the tests is running correctly.

**Comment by taketwo** [comment]
Just a single failing test on x86 build (due to precision), x64 finished with success. I wonder if we actually need x86 build at all. Does anyone use it anyway? Would it make more sense to rather have an additional VC2015-based x64 build?

In the meantime I've pushed a commit with `vtk` to check how much longer it will take.

By the way, Azure supports "release" builds that produce artifacts. @UnaNancyOwen do you think it makes sense to try to setup a pipeline that produces all-in-one installer automatically? I don't know how hard this would be, but can imagine it will reduce friction on releases even further.

**Comment by UnaNancyOwen** [comment]
> I wonder if we actually need x86 build at all. Does anyone use it anyway? Would it make more sense to rather have an additional VC2015-based x64 build?

(I think it is unnecessary, but) it seems that there is still demand because questions about that comes me still.
Fortunately, the Azure Pipelines processes jobs in parallel. It may be good to add job for VC2015.
(It is 10 parallels by default. Probably, We can increase number of parallels by asking MS.)

> @UnaNancyOwen do you think it makes sense to try to setup a pipeline that produces all-in-one installer automatically?

I think it is difficult. It requires some manual work (in my procedure).

**Comment by SergioRAgostinho** [comment]
I have the impression this particular test failure has occurred non deterministically in the past.

If the only the OMP version is failing we can first try to replicate the strategy we applied here 2bf4ae0e430b65ef6be3088547d48a015d05a8cd to ensure a single unified test in both classes. If only OMP fails than at least we're sure it's really the differences introduced in the OMP variant.

**Comment by UnaNancyOwen** [comment]
> I think we have to live without vtk for now. It took 1 hour to install dependencies with it, and the library failed to build because the agent ran out of space.

@kaylangan Could you give us additional storage space of agent?

**Comment by SergioRAgostinho** [comment]
As a workaround, we can also erase the build folder vcpkg uses halfway through the process. They're known to generate a lot of "compilation clutter". For more info see https://github.com/Microsoft/vcpkg/issues/248

**Comment by taketwo** [comment]
Could it be an option to install VTK from official package? These additional 40 minutes of compilation to the pipeline execution make me feel uneasy.

**Comment by SergioRAgostinho** [comment]
I think the best compromise we have is to use windows containers with the dependencies already set up, like you did for Ubuntu. For what I understand Azure Pipelines supports it. 

Till then I'm also against vtk on the windows CI.

**Comment by taketwo** [comment]
I did not realize there are containers with Windows inside nowadays! But from what I see they can not be created from a Linux host and I currently don't have access to Windows. Maybe at some later point. Or perhaps some other Windows user could create an image.

After merging #2636 both jobs succeeded, so either there was a discrepancy in the OMP and non-OMP tests, or it is a spurious failure and will show up later. Either way, I think this is good to go. I suppose we can drop Appveyor config now.

**Comment by kaylangan** [comment]
> It is mean there is no cache feature in Azure Pipelines?
> @kaylangan She may know good ideas and information.

We currently do not have a caching feature. We're in the process of designing it. You can see [initial plans here](https://github.com/Microsoft/azure-pipelines-yaml/blob/proposals/pipeline-caching/design/pipeline-caching.md).

**Comment by kaylangan** [comment]
> @kaylangan Could you give us additional storage space of agent?

Unfortunately, we cannot increase the storage space of agents since we're constrained by the specs of the VMs we use in our pools. We're planning on building a "bring your own server" feature where projects can bring their own, custom hardware, but I don't have an ETA for that.

**Comment by taketwo** [comment]
@kaylangan Thanks for sharing this information. Looking forward for the caching feature to be implemented!

**Pull request merged**
