### PR TITLE
Remove old issue template

### PR DESCRIPTION
**Pull request by kunaltyagi**
Old one made defunct by #3602

### CODE REVIEW

**Comment by taketwo** [comment]
It feels like we have a different interpretation of the `needs: pr merge` label. For me this indicates a dependency on some other PR, as in "this one can not be merged before some other PR is".

**Comment by SergioRAgostinho** [comment]
The was the classical one. Proposal to add a new label saying `needs: to be merged` and leave the old one with the same meaning.

**Comment by taketwo** [comment]
My idea was that the ultimate end state of each PR is "merged". Each PR that is not (yet) in that state should have a `needs: *` label that explains what prevents it from being merged. Following this logic, I don't see the use for `needs: to be merged` because it's not clear why don't we just merge.

**Comment by kunaltyagi** [comment]
> For me this indicates a dependency on some other PR, as in "this one can not be merged before some other PR is".

Got it. So the last label before merge should be `needs: review` or `needs: maintainer feedback`?

**Comment by taketwo** [comment]
Sort of, yes.

**Pull request merged**
