### PR TITLE
PLYReader: thread safe colors

### PR DESCRIPTION
**Pull request by mikhail-matrosov**
Bug fix: PLYReader would give corrupted colors if used in a parallel
code.

### CODE REVIEW

**Comment by SergioRAgostinho** [comment]
Thanks. Could you please follow 
http://pointclouds.org/documentation/advanced/pcl_style_guide.php#member-variables
http://pointclouds.org/documentation/advanced/pcl_style_guide.php#indentation-and-formatting

Also add, a comment explaining what those members are and initialize them properly in the class constructors.

**Comment by mikhail-matrosov** [comment]
Renamed and initialized variables in comply with pcl guidelines, corrected indentation. Sorry for the previous commit =)

**Comment by SergioRAgostinho** [comment]
Final comment. Could you please squash the commits into a single one.

**Comment by mikhail-matrosov** [comment]
Done

**Comment by VictorLamoine** [comment]
:+1:

**Comment by SergioRAgostinho** [comment]
:+1: thanks

**Comment by SergioRAgostinho** [comment]
Sorry to be picky once again, can you amend the commit message. You concatenated the message from the three commits you squashed.

**Comment by mikhail-matrosov** [comment]
No problem

**Comment by taketwo** [comment]
I'd say let's have a release candidate branch and revert it there?

**Comment by SergioRAgostinho** [comment]
But then can we properly tag the main branch?

**Comment by jspricke** [comment]
+1 for revert in release branch. (at tag is not associated with a branch ;) ).

**Comment by taketwo** [comment]
Yes, we work with a release branch, eventually tag it's tip, and then wipe the branch.

**Pull request merged**
