### PR TITLE
[WIP] Add copyright to all files

### LINKED ISSUE #946: [script] Add license to files without one, with correct copyright
The following files (from release 1.7.2) has NO license neither Copyright paragraph. Please add the needed information.

common/include/pcl/PolygonMesh.h
surface/include/pcl/surface/3rdparty/opennurbs/crc32.h
surface/include/pcl/surface/3rdparty/opennurbs/inffixed.h
surface/include/pcl/surface/3rdparty/opennurbs/opennurbs_dll_resource.h
apps/cloud_composer/src/cloud_browser.cpp
apps/cloud_composer/src/cloud_composer.cpp
apps/cloud_composer/src/cloud_view.cpp
apps/cloud_composer/src/cloud_viewer.cpp
apps/cloud_composer/src/commands.cpp
apps/cloud_composer/src/item_inspector.cpp
apps/cloud_composer/src/items/cloud_composer_item.cpp
apps/cloud_composer/src/items/cloud_item.cpp
apps/cloud_composer/src/items/fpfh_item.cpp
apps/cloud_composer/src/items/normals_item.cpp
apps/cloud_composer/src/main.cpp
apps/cloud_composer/src/merge_selection.cpp
apps/cloud_composer/src/point_selectors/click_trackball_interactor_style.cpp
apps/cloud_composer/src/point_selectors/interactor_style_switch.cpp
apps/cloud_composer/src/point_selectors/manipulation_event.cpp
apps/cloud_composer/src/point_selectors/rectangular_frustum_selector.cpp
apps/cloud_composer/src/point_selectors/selected_trackball_interactor_style.cpp
apps/cloud_composer/src/point_selectors/selection_event.cpp
apps/cloud_composer/src/project_model.cpp
apps/cloud_composer/src/properties_model.cpp
apps/cloud_composer/src/signal_multiplexer.cpp
apps/cloud_composer/src/tool_interface/abstract_tool.cpp
apps/cloud_composer/src/toolbox_model.cpp
apps/cloud_composer/src/transform_clouds.cpp
apps/cloud_composer/src/work_queue.cpp
apps/cloud_composer/tools/euclidean_clustering.cpp
apps/cloud_composer/tools/fpfh_estimation.cpp
apps/cloud_composer/tools/normal_estimation.cpp
apps/cloud_composer/tools/organized_segmentation.cpp
apps/cloud_composer/tools/sanitize_cloud.cpp
apps/cloud_composer/tools/statistical_outlier_removal.cpp
apps/cloud_composer/tools/supervoxels.cpp
apps/cloud_composer/tools/voxel_grid_downsample.cpp
apps/include/pcl/apps/face_detection/face_detection_apps_utils.h
apps/include/pcl/apps/face_detection/openni_frame_source.h
apps/include/pcl/apps/render_views_tesselated_sphere.h
apps/src/feature_matching.cpp
apps/src/grabcut_2d.cpp
apps/src/organized_segmentation_demo.cpp
apps/src/ppf_object_recognition.cpp
apps/src/pyramid_surface_matching.cpp
apps/src/render_views_tesselated_sphere.cpp
apps/src/surfel_smoothing_test.cpp
apps/src/test_search.cpp
cmake/custom_output.sh
cmake/merge_cmake_install.py
common/include/pcl/common/fft/kiss_fft.h
common/include/pcl/common/fft/kiss_fftr.h
common/include/pcl/common/impl/polynomial_calculations.hpp
common/include/pcl/ModelCoefficients.h
common/include/pcl/PCLHeader.h
common/include/pcl/PCLImage.h
common/include/pcl/PCLPointCloud2.h
common/include/pcl/PCLPointField.h
common/include/pcl/PointIndices.h
common/include/pcl/Vertices.h
doc/tutorials/content/sources/alignment_prerejective/alignment_prerejective.cpp
doc/tutorials/content/sources/bare_earth/bare_earth.cpp
doc/tutorials/content/sources/bspline_fitting/bspline_fitting.cpp
doc/tutorials/content/sources/cloud_viewer/cloud_viewer.cpp
doc/tutorials/content/sources/cluster_extraction/cluster_extraction.cpp
doc/tutorials/content/sources/concatenate_clouds/concatenate_clouds.cpp
doc/tutorials/content/sources/concatenate_fields/concatenate_fields.cpp
doc/tutorials/content/sources/concatenate_points/concatenate_points.cpp
doc/tutorials/content/sources/concave_hull_2d/concave_hull_2d.cpp
doc/tutorials/content/sources/conditional_euclidean_clustering/conditional_euclidean_clustering.cpp
doc/tutorials/content/sources/conditional_removal/conditional_removal.cpp
doc/tutorials/content/sources/convex_hull_2d/convex_hull_2d.cpp
doc/tutorials/content/sources/correspondence_grouping/correspondence_grouping.cpp
doc/tutorials/content/sources/cylinder_segmentation/cylinder_segmentation.cpp
doc/tutorials/content/sources/don_segmentation/don_segmentation.cpp
doc/tutorials/content/sources/extract_indices/extract_indices.cpp
doc/tutorials/content/sources/greedy_projection/greedy_projection.cpp
doc/tutorials/content/sources/iccv2011/include/feature_estimation.h
doc/tutorials/content/sources/iccv2011/include/filters.h
doc/tutorials/content/sources/iccv2011/include/load_clouds.h
doc/tutorials/content/sources/iccv2011/include/object_recognition.h
doc/tutorials/content/sources/iccv2011/include/openni_capture.h
doc/tutorials/content/sources/iccv2011/include/registration.h
doc/tutorials/content/sources/iccv2011/include/segmentation.h
doc/tutorials/content/sources/iccv2011/include/surface.h
doc/tutorials/content/sources/iccv2011/include/typedefs.h
doc/tutorials/content/sources/iccv2011/src/build_all_object_models.cpp
doc/tutorials/content/sources/iccv2011/src/build_object_model.cpp
doc/tutorials/content/sources/iccv2011/src/capture_tool.cpp
doc/tutorials/content/sources/iccv2011/src/correspondence_viewer.cpp
doc/tutorials/content/sources/iccv2011/src/openni_capture.cpp
doc/tutorials/content/sources/iccv2011/src/test_feature_estimation.cpp
doc/tutorials/content/sources/iccv2011/src/test_filters.cpp
doc/tutorials/content/sources/iccv2011/src/test_object_recognition.cpp
doc/tutorials/content/sources/iccv2011/src/test_registration.cpp
doc/tutorials/content/sources/iccv2011/src/test_segmentation.cpp
doc/tutorials/content/sources/iccv2011/src/test_surface.cpp
doc/tutorials/content/sources/iccv2011/src/tutorial.cpp
doc/tutorials/content/sources/implicit_shape_model/implicit_shape_model.cpp
doc/tutorials/content/sources/interactive_icp/interactive_icp.cpp
doc/tutorials/content/sources/iros2011/include/feature_estimation.h
doc/tutorials/content/sources/iros2011/include/filters.h
doc/tutorials/content/sources/iros2011/include/load_clouds.h
doc/tutorials/content/sources/iros2011/include/object_recognition.h
doc/tutorials/content/sources/iros2011/include/openni_capture.h
doc/tutorials/content/sources/iros2011/include/registration.h
doc/tutorials/content/sources/iros2011/include/segmentation.h
doc/tutorials/content/sources/iros2011/include/solution/feature_estimation.h
doc/tutorials/content/sources/iros2011/include/solution/filters.h
doc/tutorials/content/sources/iros2011/include/solution/object_recognition.h
doc/tutorials/content/sources/iros2011/include/solution/openni_capture.h
doc/tutorials/content/sources/iros2011/include/solution/registration.h
doc/tutorials/content/sources/iros2011/include/solution/segmentation.h
doc/tutorials/content/sources/iros2011/include/solution/surface.h
doc/tutorials/content/sources/iros2011/include/solution/typedefs.h
doc/tutorials/content/sources/iros2011/include/surface.h
doc/tutorials/content/sources/iros2011/include/typedefs.h
doc/tutorials/content/sources/iros2011/src/build_all_object_models.cpp
doc/tutorials/content/sources/iros2011/src/build_object_model.cpp
doc/tutorials/content/sources/iros2011/src/capture_tool.cpp
doc/tutorials/content/sources/iros2011/src/correspondence_viewer.cpp
doc/tutorials/content/sources/iros2011/src/openni_capture.cpp
doc/tutorials/content/sources/iros2011/src/test_feature_estimation.cpp
doc/tutorials/content/sources/iros2011/src/test_filters.cpp
doc/tutorials/content/sources/iros2011/src/test_object_recognition.cpp
doc/tutorials/content/sources/iros2011/src/test_registration.cpp
doc/tutorials/content/sources/iros2011/src/test_segmentation.cpp
doc/tutorials/content/sources/iros2011/src/test_surface.cpp
doc/tutorials/content/sources/iterative_closest_point/iterative_closest_point.cpp
doc/tutorials/content/sources/kdtree_search/kdtree_search.cpp
doc/tutorials/content/sources/matrix_transform/matrix_transform.cpp
doc/tutorials/content/sources/min_cut_segmentation/min_cut_segmentation.cpp
doc/tutorials/content/sources/model_outlier_removal/model_outlier_removal.cpp
doc/tutorials/content/sources/moment_of_inertia/moment_of_inertia.cpp
doc/tutorials/content/sources/narf_descriptor_visualization/narf_descriptor_visualization.cpp
doc/tutorials/content/sources/narf_feature_extraction/narf_feature_extraction.cpp
doc/tutorials/content/sources/narf_keypoint_extraction/narf_keypoint_extraction.cpp
doc/tutorials/content/sources/normal_distributions_transform/normal_distributions_transform.cpp
doc/tutorials/content/sources/normal_estimation_using_integral_images/normal_estimation_using_integral_images.cpp
doc/tutorials/content/sources/octree_change_detection/octree_change_detection.cpp
doc/tutorials/content/sources/octree_search/octree_search.cpp
doc/tutorials/content/sources/openni_grabber/openni_grabber.cpp
doc/tutorials/content/sources/openni_narf_keypoint_extraction/openni_narf_keypoint_extraction.cpp
doc/tutorials/content/sources/openni_range_image_visualization/openni_range_image_visualization.cpp
doc/tutorials/content/sources/passthrough/passthrough.cpp
doc/tutorials/content/sources/pcd_read/pcd_read.cpp
doc/tutorials/content/sources/pcd_write/pcd_write.cpp
doc/tutorials/content/sources/pcl_painter2D/pcl_painter2D_demo.cpp
doc/tutorials/content/sources/pcl_plotter/pcl_plotter_demo.cpp
doc/tutorials/content/sources/pcl_visualizer/pcl_visualizer_demo.cpp
doc/tutorials/content/sources/planar_segmentation/planar_segmentation.cpp
doc/tutorials/content/sources/point_cloud_compression/point_cloud_compression.cpp
doc/tutorials/content/sources/project_inliers/project_inliers.cpp
doc/tutorials/content/sources/qt_visualizer/main.cpp
doc/tutorials/content/sources/qt_visualizer/pclviewer.cpp
doc/tutorials/content/sources/qt_visualizer/pclviewer.h
doc/tutorials/content/sources/radius_outlier_removal/radius_outlier_removal.cpp
doc/tutorials/content/sources/random_sample_consensus/random_sample_consensus.cpp
doc/tutorials/content/sources/range_image_border_extraction/range_image_border_extraction.cpp
doc/tutorials/content/sources/range_image_creation/range_image_creation.cpp
doc/tutorials/content/sources/range_image_visualization/range_image_visualization.cpp
doc/tutorials/content/sources/region_growing_rgb_segmentation/region_growing_rgb_segmentation.cpp
doc/tutorials/content/sources/region_growing_segmentation/region_growing_segmentation.cpp
doc/tutorials/content/sources/registration_api/example1.cpp
doc/tutorials/content/sources/registration_api/example2.cpp
doc/tutorials/content/sources/remove_outliers/remove_outliers.cpp
doc/tutorials/content/sources/resampling/resampling.cpp
doc/tutorials/content/sources/rops_feature/rops_feature.cpp
doc/tutorials/content/sources/statistical_removal/statistical_removal.cpp
doc/tutorials/content/sources/stick_segmentation/stick_segmentation.cpp
doc/tutorials/content/sources/supervoxel_clustering/supervoxel_clustering.cpp
doc/tutorials/content/sources/template_alignment/template_alignment.cpp
doc/tutorials/content/sources/tracking/tracking_sample.cpp
doc/tutorials/content/sources/vfh_recognition/build_tree.cpp
doc/tutorials/content/sources/vfh_recognition/nearest_neighbors.cpp
doc/tutorials/content/sources/voxel_grid/voxel_grid.cpp
examples/common/example_get_max_min_coordinates.cpp
examples/features/example_difference_of_normals.cpp
examples/segmentation/example_supervoxels.cpp
examples/surface/example_nurbs_fitting_closed_curve.cpp
examples/surface/example_nurbs_fitting_closed_curve3d.cpp
examples/surface/example_nurbs_fitting_curve2d.cpp
examples/surface/example_nurbs_fitting_surface.cpp
examples/surface/example_nurbs_viewer_surface.cpp
examples/surface/test_nurbs_fitting_surface.cpp
io/src/openni_camera/openni_image_rgb24.cpp
io/tools/hdl_grabber_example.cpp
outofcore/include/pcl/outofcore/impl/lru_cache.hpp
outofcore/include/pcl/outofcore/impl/monitor_queue.hpp
outofcore/include/pcl/outofcore/visualization/axes.h
outofcore/include/pcl/outofcore/visualization/camera.h
outofcore/include/pcl/outofcore/visualization/common.h
outofcore/include/pcl/outofcore/visualization/geometry.h
outofcore/include/pcl/outofcore/visualization/grid.h
outofcore/include/pcl/outofcore/visualization/object.h
outofcore/include/pcl/outofcore/visualization/outofcore_cloud.h
outofcore/include/pcl/outofcore/visualization/scene.h
outofcore/include/pcl/outofcore/visualization/viewport.h
outofcore/src/visualization/camera.cpp
outofcore/src/visualization/common.cpp
outofcore/src/visualization/grid.cpp
outofcore/src/visualization/object.cpp
outofcore/src/visualization/outofcore_cloud.cpp
outofcore/src/visualization/scene.cpp
outofcore/src/visualization/viewport.cpp
recognition/include/pcl/recognition/auxiliary.h
recognition/include/pcl/recognition/bvh.h
recognition/include/pcl/recognition/crh_alignment.h
recognition/include/pcl/recognition/hv/hv_go.h
recognition/include/pcl/recognition/impl/ransac_based/simple_octree.hpp
recognition/include/pcl/recognition/model_library.h
recognition/include/pcl/recognition/obj_rec_ransac.h
recognition/include/pcl/recognition/orr_graph.h
recognition/include/pcl/recognition/orr_octree_zprojection.h
recognition/include/pcl/recognition/orr_octree.h
recognition/include/pcl/recognition/rigid_transform_space.h
recognition/include/pcl/recognition/simple_octree.h
recognition/include/pcl/recognition/trimmed_icp.h
recognition/include/pcl/recognition/voxel_structure.h
registration/include/pcl/registration/bfgs.h
surface/include/pcl/surface/3rdparty/opennurbs/examples_linking_pragmas.h
surface/include/pcl/surface/3rdparty/opennurbs/opennurbs_beam.h
surface/include/pcl/surface/3rdparty/opennurbs/opennurbs_hsort_template.h
surface/include/pcl/surface/3rdparty/opennurbs/opennurbs_qsort_template.h
surface/include/pcl/surface/3rdparty/opennurbs/trees.h
surface/include/pcl/surface/3rdparty/poisson4/hash.h
surface/src/3rdparty/opennurbs/opennurbs_beam.cpp
surface/src/3rdparty/opennurbs/opennurbs_box.cpp
surface/src/3rdparty/opennurbs/opennurbs_fsp.cpp
surface/src/3rdparty/opennurbs/opennurbs_mesh_ngon.cpp
surface/src/3rdparty/opennurbs/opennurbs_polyedgecurve.cpp
surface/src/3rdparty/opennurbs/opennurbs_sort.cpp
test/convert_image_to_point_cloud.py
test/io/test_grabbers.cpp
test/registration/test_registration_api_data.h
tools/linemod_detection.cpp
tracking/include/pcl/tracking/approx_nearest_pair_point_cloud_coherence.h
tracking/include/pcl/tracking/coherence.h
tracking/include/pcl/tracking/distance_coherence.h
tracking/include/pcl/tracking/hsv_color_coherence.h
tracking/include/pcl/tracking/impl/approx_nearest_pair_point_cloud_coherence.hpp
tracking/include/pcl/tracking/impl/coherence.hpp
tracking/include/pcl/tracking/impl/distance_coherence.hpp
tracking/include/pcl/tracking/impl/kld_adaptive_particle_filter_omp.hpp
tracking/include/pcl/tracking/impl/kld_adaptive_particle_filter.hpp
tracking/include/pcl/tracking/impl/nearest_pair_point_cloud_coherence.hpp
tracking/include/pcl/tracking/impl/normal_coherence.hpp
tracking/include/pcl/tracking/impl/particle_filter_omp.hpp
tracking/include/pcl/tracking/impl/particle_filter.hpp
tracking/include/pcl/tracking/impl/tracker.hpp
tracking/include/pcl/tracking/impl/tracking.hpp
tracking/include/pcl/tracking/kld_adaptive_particle_filter_omp.h
tracking/include/pcl/tracking/kld_adaptive_particle_filter.h
tracking/include/pcl/tracking/nearest_pair_point_cloud_coherence.h
tracking/include/pcl/tracking/normal_coherence.h
tracking/include/pcl/tracking/particle_filter_omp.h
tracking/include/pcl/tracking/particle_filter.h
visualization/include/pcl/visualization/simple_buffer_visualizer.h
visualization/test/test_geometry.cpp
visualization/test/test_shapes.cpp
visualization/test/test.cpp
visualization/tools/timed_trigger_test.cpp

### PR DESCRIPTION
**Pull request by VictorLamoine**
Fixes #946

I used this simple script:

```
#!/bin/sh

FILES="common/include/pcl/PolygonMesh.h
surface/include/pcl/surface/3rdparty/opennurbs/crc32.h
.......... truncated list ..........
visualization/tools/timed_trigger_test.cpp"
for f in $FILES
do
    cat ~/copyright.txt $f >tmp.txt
    rm $f
    mv tmp.txt $f
    echo "Processed $f"
done
```

where `copyright.txt` is:

```
/*
 * Software License Agreement (BSD License)
 *
 *  Point Cloud Library (PCL) - www.pointclouds.org
 *  Copyright (c) 2014-, Open Perception, Inc.
 *
 *  All rights reserved.
 *
 *  Redistribution and use in source and binary forms, with or without
 *  modification, are permitted provided that the following conditions
 *  are met:
 *
 *   * Redistributions of source code must retain the above copyright
 *     notice, this list of conditions and the following disclaimer.
 *   * Redistributions in binary form must reproduce the above
 *     copyright notice, this list of conditions and the following
 *     disclaimer in the documentation and/or other materials provided
 *     with the distribution.
 *   * Neither the name of the copyright holder(s) nor the names of its
 *     contributors may be used to endorse or promote products derived
 *     from this software without specific prior written permission.
 *
 *  THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
 *  "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
 *  LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS
 *  FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE
 *  COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT,
 *  INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING,
 *  BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
 *  LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
 *  CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
 *  LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN
 *  ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
 *  POSSIBILITY OF SUCH DAMAGE.
 *
 */

```

### CODE REVIEW

**Comment by VictorLamoine** [comment]
I updated the list to associate git usernames with emails; only Anatoly Barksheev doesn't have a valid email but he his still active on GitHub so should be able to contact him directly.

I'm not sure what the message/email should say, ideas?

**Comment by SergioRAgostinho** [comment]
Here's my two cents and let's build from this.

>Hey Anatoly, 
>
>I'm Victor, a maintainer for PCL. We've been recently requested to add a copyright notice on a bunch of files, some of whom you are the author of. We would like to know if you would like to claim your copyrights over them or if you'll wave them to Open Perception?
>
> Bye 
> Victor

Notice how I preserved your trademark farewell ;)

**Comment by VictorLamoine** [comment]
If someone is willing to continue this tidy work please go on. I don't have time for it :smile:

**Comment by taketwo** [comment]
:smile: haha ok. Anyway, glad to hear you're alive ;)

**Comment by VictorLamoine** [comment]
If someone wants to take over feel free to re-use what I have done

**Pull request closed without merging**
