### PR TITLE
Revert "Added optional polygon line width to visualizer"

### PR DESCRIPTION
**Pull request by VictorLamoine**
Reverts PointCloudLibrary/pcl#1112

### CODE REVIEW

**Comment by taketwo** [comment]
I think we can just put another one on top, no need to revert...

**Comment by VictorLamoine** [comment]
I thought we could re-open the same pull request but it does not seem to be possible.

**Comment by mschoeler** [comment]
I can just submit a new one

**Comment by taketwo** [comment]
No, that one is already done :)
The thing is, revert is not like removing a commit, it is rather adding a "mirror" commit (that undoes changes) on top. Since we know there will be a new patch, this does not make much sense. But this is not a problem of course.

**Comment by VictorLamoine** [comment]
Ok so that just adds a useless commit to the history, got that.

**Comment by mschoeler** [comment]
ok, almost done. Need to change some function calls in other parts of PCL, since the interface changed now. Is that a problem? People using this function would need to adapt it. This is why I had it as a last paramter.

**Pull request merged**
