### PR TITLE
Testing with smaller cache size

### PR DESCRIPTION
**Pull request by kunaltyagi**
Iterating on the Max Compiler Cache size

### CODE REVIEW

**Comment by kunaltyagi** [comment]
> Seem like it solved the problem

No. It didn't solve the problem. It reduced memory usage but with large compile times. I've gutted out the ccache 😢  for now.

> revert back to the original key before merging

I'd have needed to. But no need now

**Comment by kunaltyagi** [comment]
The issue wit tweaking is that the cache issues are hard to find out with CI. Local experiments don't match CI and dummy CI setup (like the commit which added ccache for CI) don't really imply a stable behavior in future. I'd drop this for now for CI

**Comment by SergioRAgostinho** [comment]
:+1: No opposition from my side.

**Comment by taketwo** [comment]
It's a pity, but indeed green CI is better than fast CI.

**Pull request merged**
