### PR TITLE
Switch to command line tools in MacOS CI (Broken by 2020 Apr 24 update)

### PR DESCRIPTION
**Pull request by SergioRAgostinho**

### CODE REVIEW

**Comment by SergioRAgostinho** [comment]
Worth having a try https://github.com/PointCloudLibrary/pcl/issues/2601#issuecomment-621889211

**Comment by SergioRAgostinho** [comment]
Look at it happily going!

**Comment by kunaltyagi** [comment]
Error:
```bash
test/common/test_io.cpp:134:9: error: unknown pragma ignored [-Werror,-Wunknown-pragmas]
#pragma warning(push)
        ^
```

**Comment by SergioRAgostinho** [comment]
:zero: - ifdef our way around it
:one: - disable warnings from unknown pragmas
?

**Comment by kunaltyagi** [comment]
🤦 I prefer local warning settings than global, but it appears that we might have to set pragma warning disable globally for clang and msvc

**Comment by kunaltyagi** [comment]
Merge at your leisure 🚀

**Pull request merged**
