### PR TITLE
replace deprecated boost filesystem extension

### PR DESCRIPTION
**Pull request by cybaol**
Task 2 of #5881

### CODE REVIEW

**Review by larshg — DISMISSED** [review]

**Comment by mvieth** [comment]
I found three instances of `fs::extension` in gpu/kinfu_large_scale/tools/kinfuLS_app.cpp, gpu/people/tools/people_app.cpp, and gpu/kinfu/tools/kinfu_app.cpp. Could you replace those as well, please?

**Comment by cybaol** [comment]
> I found three instances of `fs::extension` in gpu/kinfu_large_scale/tools/kinfuLS_app.cpp, gpu/people/tools/people_app.cpp, and gpu/kinfu/tools/kinfu_app.cpp. Could you replace those as well, please?

The clang-tidy error seems not related ?

**Comment by cybaol** [comment]
https://github.com/PointCloudLibrary/pcl/pull/5899/commits/b52465df3bc084ad52fbbe1c8c3c798f70633739

**Review by mvieth — APPROVED** [review]
No, the clang-tidy errors are not your fault.
Thanks for replacing boost::filesystem::extension!

**Pull request merged**
