### PR TITLE
Release 1.10.1

### LINKED ISSUE #3675: Minor Release 1.10.1
## Context
There should be a release 1.10.1 to fix some compilation issues in PCL 1.10 (which are visible because those modules aren't distributed, but they remain issue nonetheless)

## Next step
Compile PCL and test against a selection of packages, open and closed source.

### PR DESCRIPTION
**Pull request by taketwo**
This PR adds changelog to CHANGES.md and bumps version to 1.10.1.

Closes #3675.

### CODE REVIEW

**Comment by taketwo** [comment]
No, CMake config directory has `pcl-major.minor` format, so patch bump does not influence its location.

**Comment by SergioRAgostinho** [comment]
According to the change log, we're removing things from the API in this release. Did the old policy of not touching the API between 1.x.0 and 1.x.1 change?

**Comment by taketwo** [comment]
Actually it's an overstatement that we remove API. Please have a look at #3690; we simply abolish `#ifdef`/`#error` pragmas:

```cpp
#ifdef USE_ROS
   #error USE_ROS setup requires PCL to compile against ROS message headers, #endif 
```

Perhaps we should exclude this PR from the changelog. It's absolutely safe to assume that a) nobody has this macro set; b) nobody cares about it.

**Comment by SergioRAgostinho** [comment]
I ran ABI checker and only `features` came out with a warning because fiddled with protected variables inside a class. 

[features.zip](https://github.com/PointCloudLibrary/pcl/files/4351568/features.zip)

**Pull request merged**
