### PR TITLE
Replace std::bind by lambda expression to fix compile issue

### PR DESCRIPTION
**Pull request by SunBlack**

### CODE REVIEW

**Comment by taketwo** [comment]
What compiler error did you get? I built master (including CUDA apps) just yesterday with GCC7 and got no errors.

Speaking about the lambda, @SergioRAgostinho I think you usually capture `this` explicitly, right?

**Comment by SergioRAgostinho** [comment]
> Speaking about the lambda, @SergioRAgostinho I think you usually capture `this` explicitly, right?

Yes. In my dev environment, `this` always needs to be explicitly captured.

**Comment by SunBlack** [comment]
> What compiler error did you get? I built master (including CUDA apps) just yesterday with GCC7 and got no errors.

See referenced PR:
```
/media/sf_pcl/cuda/apps/src/kinect_viewer_cuda.cpp:80:9: error: no viable conversion from 'typename _Bind_helper<__is_socketlike<void (KinectViewerCuda::*)(const shared_ptr<Image> &, const shared_ptr<DepthImage> &, float)>::value, void (KinectViewerCuda::*)(const shared_ptr<Image> &, const shared_ptr<DepthImage> &, float), KinectViewerCuda *, const arg<1> &, const arg<2> &, const arg<3> &>::type' (aka '_Bind<void (KinectViewerCuda::*(KinectViewerCuda *, boost::arg<1>, boost::arg<2>, boost::arg<3>))(const boost::shared_ptr<openni_wrapper::Image> &, const boost::shared_ptr<openni_wrapper::DepthImage> &, float)>') to 'std::function<void (const boost::shared_ptr<openni_wrapper::Image> &, const boost::shared_ptr<openni_wrapper::DepthImage> &, float)>'
        f = std::bind (&KinectViewerCuda::cloud_cb_, this, _1, _2, _3);
```
I believe the issue is, that clang 6 is using `boost::arg<1>` instead of `std::arg<1>` for `_1` .

> Speaking about the lambda, @SergioRAgostinho I think you usually capture `this` explicitly, right?

Good to know, didn't followed all transitions in last time, so I didn't knew this convention.

General question: Why #3249 changed `boost::bind` to `std::bind` during there are a lot of PRs with `Prefer lambdas over binds`?

**Comment by SergioRAgostinho** [comment]
> I believe the issue is, that clang 6 is using `boost::arg<1>` instead of `std::arg<1>` for `_1` .

That would make sense. There's no `using` clause exposing the `std::placeholders` namespace.

**Pull request merged**
