### PR TITLE
Allow compilation with Boost 1.79

### PR DESCRIPTION
**Pull request by mvieth**
@UnaNancyOwen FYI
Related: issue #5261

### CODE REVIEW

**Review by UnaNancyOwen — APPROVED** [review]
Thanks! :+1:

**Comment by fxcoudert** [comment]
Weirdly enough, if we take pcl and add that commit https://github.com/PointCloudLibrary/pcl/commit/e964409b4accfd9070093dbc3c9cf5fb216cd877, we still see a build error:

```
-- Could NOT find Boost: Found unsuitable version "1.79.0", but required is exact version "1.78.0" (found /usr/local/include, )
  -- Could not find the VTK package due to a missing dependency: Boost
  -- Could NOT find Boost: Found unsuitable version "1.79.0", but required is exact version "1.78.0" (found /usr/local/include, found components: serialization)
```

This is with cmake 3.23.2. I do not understand where the `required is exact version "1.78.0"` is coming from…

**Comment by mvieth** [comment]
@fxcoudert I don't see a reason that this could come from PCL. PCL works with many Boost versions and does not require 1.78.0 exactly. In which system/build configuration do you get this error? Is this from https://github.com/Homebrew/homebrew-core/pull/101577 ? In the latest logs there, I see a different kind of build error, but I don't have enough experience with homebrew to say why that happens

**Comment by fxcoudert** [comment]
I have no idea where this is coming from either 😢 

The full output is this:

```
$ cmake .. -DCMAKE_INSTALL_PREFIX=/opt/homebrew/Cellar/pcl/1.12.1_3 -DCMAKE_INSTALL_LIBDIR=lib -DCMAKE_BUILD_TYPE=Release -DCMAKE_FIND_FRAMEWORK=LAST -DCMAKE_VERBOSE_MAKEFILE=ON -Wno-dev -DBUILD_TESTING=OFF -DCMAKE_OSX_SYSROOT=/Library/Developer/CommandLineTools/SDKs/MacOSX12.sdk -DBUILD_SHARED_LIBS:BOOL=ON -DBUILD_apps=AUTO_OFF -DBUILD_apps_3d_rec_framework=AUTO_OFF -DBUILD_apps_cloud_composer=AUTO_OFF -DBUILD_apps_in_hand_scanner=AUTO_OFF -DBUILD_apps_point_cloud_editor=AUTO_OFF -DBUILD_examples:BOOL=OFF -DBUILD_global_tests:BOOL=OFF -DBUILD_outofcore:BOOL=AUTO_OFF -DBUILD_people:BOOL=AUTO_OFF -DBUILD_simulation:BOOL=ON -DWITH_CUDA:BOOL=OFF -DWITH_DOCS:BOOL=OFF -DWITH_TUTORIALS:BOOL=OFF -DBUILD_apps_modeler:BOOL=OFF
-- Could NOT find ClangFormat (missing: ClangFormat_EXECUTABLE ClangFormat_VERSION) (Required is at least version "10")
-- Found OpenMP, spec date 201811
-- Eigen found (include: /opt/homebrew/include/eigen3, version: 3.4.0)
-- FLANN found (include: /opt/homebrew/include, lib: /opt/homebrew/lib/libflann_cpp.dylib)
-- Checking for module 'metslib'
--   No package 'metslib' found
-- Found Qhull version 8.0.2
-- Could NOT find Boost: Found unsuitable version "1.79.0", but required is exact version "1.78.0" (found /opt/homebrew/include, )
-- Could not find the VTK package due to a missing dependency: Boost
-- Could NOT find Boost: Found unsuitable version "1.79.0", but required is exact version "1.78.0" (found /opt/homebrew/include, found components: serialization)
-- Could not find the VTK package due to a missing dependency: Boost
-- VTK version: 9.1.0
-- VTK rendering backend: OpenGL2
-- VTK Qt support: YES
-- VTK libs: VTK::WrappingTools;VTK::ViewsQt;VTK::ViewsInfovis;VTK::CommonColor;VTK::ViewsContext2D;VTK::loguru;VTK::TestingRendering;VTK::TestingCore;VTK::vtksys;VTK::RenderingQt;VTK::PythonContext2D;VTK::RenderingVolumeOpenGL2;VTK::glew;VTK::opengl;VTK::PythonInterpreter;VTK::Python;VTK::RenderingLabel;VTK::octree;VTK::RenderingLOD;VTK::RenderingImage;VTK::RenderingFreeTypeFontConfig;VTK::RenderingContextOpenGL2;VTK::IOVeraOut;VTK::hdf5;VTK::IOTecplotTable;VTK::IOSegY;VTK::IOParallelXML;VTK::IOPLY;VTK::IOOggTheora;VTK::theora;VTK::ogg;VTK::IONetCDF;VTK::netcdf;VTK::IOMotionFX;VTK::pegtl;VTK::IOParallel;VTK::jsoncpp;VTK::IOMINC;VTK::IOLSDyna;VTK::IOInfovis;VTK::libxml2;VTK::zlib;VTK::IOImport;VTK::IOIOSS;VTK::ioss;VTK::exodusII;VTK::cgns;VTK::IOHDF;VTK::IOVideo;VTK::IOMovie;VTK::IOExportPDF;VTK::libharu;VTK::IOExportGL2PS;VTK::RenderingGL2PSOpenGL2;VTK::gl2ps;VTK::png;VTK::IOExport;VTK::RenderingVtkJS;VTK::IOGeometry;VTK::RenderingSceneGraph;VTK::IOExodus;VTK::IOEnSight;VTK::IOCityGML;VTK::pugixml;VTK::IOChemistry;VTK::IOCONVERGECFD;VTK::IOCGNSReader;VTK::IOAsynchronous;VTK::IOAMR;VTK::InteractionImage;VTK::InfovisBoostGraphAlgorithms;VTK::InfovisBoost;VTK::ImagingStencil;VTK::ImagingStatistics;VTK::ImagingMorphological;VTK::ImagingMath;VTK::ImagingFourier;VTK::GUISupportQtSQL;VTK::IOSQL;VTK::sqlite;VTK::GUISupportQtQuick;VTK::GUISupportQt;VTK::GeovisCore;VTK::libproj;VTK::InfovisLayout;VTK::ViewsCore;VTK::InteractionWidgets;VTK::RenderingVolume;VTK::RenderingAnnotation;VTK::ImagingHybrid;VTK::ImagingColor;VTK::InteractionStyle;VTK::FiltersTopology;VTK::FiltersSelection;VTK::FiltersSMP;VTK::FiltersPython;VTK::FiltersProgrammable;VTK::FiltersPoints;VTK::FiltersVerdict;VTK::verdict;VTK::FiltersParallelImaging;VTK::FiltersImaging;VTK::ImagingGeneral;VTK::FiltersHyperTree;VTK::FiltersGeneric;VTK::FiltersFlowPaths;VTK::eigen;VTK::FiltersAMR;VTK::FiltersParallel;VTK::FiltersTexture;VTK::FiltersModeling;VTK::FiltersHybrid;VTK::DomainsChemistryOpenGL2;VTK::RenderingOpenGL2;VTK::RenderingUI;VTK::DomainsChemistry;VTK::CommonPython;VTK::WrappingPythonCore;VTK::ChartsCore;VTK::InfovisCore;VTK::FiltersExtraction;VTK::ParallelDIY;VTK::diy2;VTK::IOXML;VTK::IOXMLParser;VTK::expat;VTK::ParallelCore;VTK::IOLegacy;VTK::IOCore;VTK::doubleconversion;VTK::lz4;VTK::lzma;VTK::utf8;VTK::FiltersStatistics;VTK::ImagingSources;VTK::IOImage;VTK::DICOMParser;VTK::jpeg;VTK::metaio;VTK::tiff;VTK::RenderingContext2D;VTK::RenderingFreeType;VTK::freetype;VTK::kwiml;VTK::RenderingCore;VTK::FiltersSources;VTK::ImagingCore;VTK::FiltersGeometry;VTK::FiltersGeneral;VTK::fmt;VTK::CommonComputationalGeometry;VTK::FiltersCore;VTK::CommonExecutionModel;VTK::CommonDataModel;VTK::CommonSystem;VTK::CommonMisc;VTK::exprtk;VTK::CommonTransforms;VTK::CommonMath;VTK::kissfft;VTK::CommonCore
-- Qt version: 5.15.3
-- Checking for module 'glut'
--   No package 'glut' found
CMake Error at /opt/homebrew/lib/cmake/Boost-1.79.0/BoostConfig.cmake:141 (find_package):
  Found package configuration file:

    /opt/homebrew/lib/cmake/boost_filesystem-1.79.0/boost_filesystem-config.cmake

  but it set boost_filesystem_FOUND to FALSE so package "boost_filesystem" is
  considered to be NOT FOUND.  Reason given by package:

  No suitable build variant has been found.

  The following variants have been tried and rejected:

  * libboost_filesystem-mt.dylib (release runtime,
  Boost_USE_DEBUG_RUNTIME=TRUE)

  * libboost_filesystem-mt.a (static, default is shared, set
  Boost_USE_STATIC_LIBS=ON to override)

  * libboost_filesystem.dylib (release runtime, Boost_USE_DEBUG_RUNTIME=TRUE)

  * libboost_filesystem.a (static, default is shared, set
  Boost_USE_STATIC_LIBS=ON to override)

Call Stack (most recent call first):
  /opt/homebrew/lib/cmake/Boost-1.79.0/BoostConfig.cmake:262 (boost_find_component)
  /opt/homebrew/Cellar/cmake/3.23.2/share/cmake/Modules/FindBoost.cmake:594 (find_package)
  cmake/pcl_find_boost.cmake:29 (find_package)
  CMakeLists.txt:399 (include)


-- Configuring incomplete, errors occurred!
See also "/tmp/pcl-20220601-66738-ju7752/pcl-pcl-1.12.1/build/CMakeFiles/CMakeOutput.log".
See also "/tmp/pcl-20220601-66738-ju7752/pcl-pcl-1.12.1/build/CMakeFiles/CMakeError.log".
```

**Comment by fxcoudert** [comment]
Hum the version error is a red herring, the issue is that it does not like out boost_filesystem. Fixed by passing `-DBoost_USE_DEBUG_RUNTIME:BOOL=OFF` (not sure why it is needed, though).

**Pull request merged**
