### PR TITLE
Increase threshold for expected value in test_non_linear

### LINKED ISSUE #2288: Segmentation test fails on ppc64le during build on Alpine
On Alpine 3.7 building PCL version 1.8.1 using compiler g++-6.4.0-r7 the package builds successfully however during the "make tests" the following test fails: 
Test 32 failing
32: Test command: /home/buildozer/aports/testing/pcl/src/pcl-pcl-1.8.1/build/test/segmentation/test_non_linear "/home/buildozer/aports/testing/pcl/src/pcl-pcl-1.8.1/test/noisy_slice_displaced.pcd"
32: Test timeout computed to be: 10000000
32: [==========] Running 1 test from 1 test case.
32: [----------] Global test environment set-up.
32: [----------] 1 test from SACSegmentation
32: [ RUN      ] SACSegmentation.Segmentation
32: /home/buildozer/aports/testing/pcl/src/pcl-pcl-1.8.1/test/segmentation/test_non_linear.cpp:76: Failure
32: The difference between static_cast<int> (inliers->indices.size ()) and 3516 is 11, which exceeds 10, where
32: static_cast<int> (inliers->indices.size ()) evaluates to 3505,
32: 3516 evaluates to 3516, and
32: 10 evaluates to 10.
32: [  FAILED  ] SACSegmentation.Segmentation (4 ms)
32: [----------] 1 test from SACSegmentation (4 ms total)
32:
32: [----------] Global test environment tear-down
32: [==========] 1 test from 1 test case ran. (4 ms total)
32: [  PASSED  ] 0 tests.
32: [  FAILED  ] 1 test, listed below:
32: [  FAILED  ] SACSegmentation.Segmentation          

It fails in the same way for both the ppc64le and aarch64 architectures.

### PR DESCRIPTION
**Pull request by taketwo**
Fixes #2288.

### CODE REVIEW

**Comment by SergioRAgostinho** [comment]
Quick debate: I'm questioning removing that check entirely? It's not useful.

**Comment by taketwo** [comment]
I think we need to verify that the call to `segment()` returns at least some inliers.

**Comment by taketwo** [comment]
Though we may relax the threshold even more to avoid problems in future.

**Comment by SergioRAgostinho** [comment]
I assumed so and its a valid approach. Alternatively I was thinking if setting a random seed before if would also prevent problems.

**Comment by taketwo** [comment]
Fixing the seed is a good approach, but I don't think it's possible here. `SampleConsensus` class has a private member variable `rng_` containing the random generator and we don't have access to it to set the seed.

**Pull request merged**
