### PR TITLE
fix /MP option not generated for Visual Studio.

### LINKED ISSUE #2030: /MP not added to CMAKE_CXX_FLAGS for Visual Studio
In commit 1355b98269b460c48ad626e68c2931aaca665a56 `CMAKE_CXX_FLAGS` is compared against a *default* value, however, the *default* value starts with a space which is not what you have when you run cmake to generate project files for visual studio. 

## Your Environment

* Operating System and version: Windows 10
* Compiler: VS2013
* PCL Version: 1.8.1, 1.8.0
* CMake: 3.8.1

## Expected Behavior
When `CMAKE_CXX_FLAGS` is not specified explicitly from cmake, the `/MP` option should be added for Visual Studio to enable parallel compile.

Remove the leading space in that commit, and the `/MP` option is added as expected.

## Possible Solution
`- if("${CMAKE_CXX_FLAGS}" STREQUAL " /DWIN32 /D_WINDOWS /W3 /GR /EHsc")	## Check against default flags`
`+ if("${CMAKE_CXX_FLAGS}" STREQUAL "/DWIN32 /D_WINDOWS /W3 /GR /EHsc")	## Check against default flags`

### PR DESCRIPTION
**Pull request by kaikai2**
This is to fix #2030

### CODE REVIEW

**Comment by UnaNancyOwen** [comment]
What is this commit 52d14ee?
If it is unnecessary, Please drop 52d14ee from this pull request.

**Comment by kaikai2** [comment]
@UnaNancyOwen Sorry, I did not aware pull request keeps pulling the latest branch. I've reverted the commit 52d14ee.

**Comment by kaikai2** [comment]
@taketwo Thanks for the note.

**Comment by kaikai2** [comment]
@taketwo I did a force push just now for a try, and this pull request updates with the unwanted 2 commits removed swiftly. Since it is done after the approval, will this change cause a problem?

**Comment by taketwo** [comment]
Great, thanks! No need to do squash on merge for us anymore :)

No, this is not a problem. This approval thing is just for our convenience to formalize comments like "LGTM" or "+1". It has no influence on "mergeability" of the pull request.

**Comment by UnaNancyOwen** [comment]
LGTM

**Comment by kaikai2** [comment]
OK. Cool! Thanks for clarifying that to me.

**Pull request merged**
