### PR TITLE
Adopt for failing tests on i386

### PR DESCRIPTION
**Pull request by jspricke**

### CODE REVIEW

**Comment by jspricke** [comment]
This is partly a draft so if someone wants to pick up ignored failures, that would be great.

**Comment by larshg** [comment]
@jspricke do you have a link to build/run output to see what values it calculates. Is it "just" due to numerical issues?

**Comment by jspricke** [comment]
https://buildd.debian.org/status/fetch.php?pkg=pcl&arch=i386&ver=1.13.0%2Bdfsg-1&stamp=1672966686&raw=0

**Review by mvieth — COMMENTED** [review]
Just two suggestions. No idea what is going on with the convolution test, but I don't have time to investigate that currently, so I am okay with disabling it for i386

**Review by mvieth — APPROVED** [review]

**Pull request merged**
