### PR TITLE
set QVTK library in release and debug mode

### PR DESCRIPTION
**Pull request by Tonsty**
for demands that need to link libraries in debug mode

### CODE REVIEW

**Comment by jspricke** [comment]
+1

**Comment by VictorLamoine** [comment]
`cmake ../src -DBUILD_apps=ON`
```
 CMake Error: The following variables are used in this project, but they are set to NOTFOUND.
 Please set them or make sure they are set and tested correctly in the CMake files:
 QVTK_LIBRARY_DEBUG
     linked by target "pcl_manual_registration" in directory /home/victor/pcl/src/apps
     linked by target "pcl_openni_passthrough" in directory /home/victor/pcl/src/apps
     linked by target "pcl_organized_segmentation_demo" in directory /home/victor/pcl/src/apps
     linked by target "pcl_pcd_video_player" in directory /home/victor/pcl/src/apps
 QVTK_LIBRARY_RELEASE
     linked by target "pcl_manual_registration" in directory /home/victor/pcl/src/apps
     linked by target "pcl_openni_passthrough" in directory /home/victor/pcl/src/apps
     linked by target "pcl_organized_segmentation_demo" in directory /home/victor/pcl/src/apps
     linked by target "pcl_pcd_video_player" in directory /home/victor/pcl/src/apps
```

**Comment by taketwo** [comment]
Hmm, in my case there are no errors. But these apps are silently ignored, i.e. after configuring with _CMake_ these particular targets do not appear in the makefile.

**Comment by Tonsty** [comment]
@VictorLamoine 
Yes, I forgot to take the apps into consideration.
I will fix this problem as soon as possible

**Comment by VictorLamoine** [comment]
How is this supposed to work? I always end up with:
`-- QVTK_LIBRARY optimized;QVTK_LIBRARY_RELEASE-NOTFOUND;debug;QVTK_LIBRARY_DEBUG-NOTFOUND`

Using `find_package(QVTK)` is ok:
`QVTK_LIBRARY /usr/lib/libQVTK.so`

**Comment by Tonsty** [comment]
I add this because I want to let the vtk lib can be linked in debug mode.

find_package(QVTK) can only link vtk in release mode

**Comment by VictorLamoine** [comment]
Ok, I don't think it is the right way to do this, I think we should rather modify the `FindQVTK.cmake` file.

[This FindQVTK.cmake](https://github.com/JoakimSoderberg/cmake-modules/blob/master/FindQVTK.cmake) should help us complete [our FindQVTK.cmake](https://github.com/PointCloudLibrary/pcl/blob/master/cmake/Modules/FindQVTK.cmake).

**Comment by Tobias-Fischer** [comment]
So is all what's needed appending ```PATH_SUFFIXES Release Debug```? to ```find_library```? At least for VTK 5.x? I think for VTK 6.x the correct version (Release/Debug) is automatically chosen: http://www.vtk.org/Wiki/VTK/Build_System_Migration

**Comment by VictorLamoine** [comment]
This is what understood too, however I did not test it.

**Pull request merged**
