### PR TITLE
Fixes for VTK 6.2.0

### PR DESCRIPTION
**Pull request by fran6co**
This is related to https://github.com/PointCloudLibrary/pcl/issues/712, they finally merged the patch https://github.com/Kitware/VTK/commit/a3e9fc90d95d2379618d6e6f0e630377dbe034ad mentioned by @asmaloney.

### CODE REVIEW

**Comment by fran6co** [comment]
Uhm... It doesn't work like this...

**Comment by jspricke** [comment]
Wasn't that tagget work in progress and not needed anymore?

**Comment by taketwo** [comment]
"[WIP]" was already removed from the title. The fix is not needed from 6.2.0 and up, so this commit adds `ifdef`s to not apply it.

**Comment by jspricke** [comment]
Oups, got it :).

**Pull request merged**
