### PR TITLE
Improvements for sample consensus

### PR DESCRIPTION
**Pull request by mvieth**
Please see commit messages.

### CODE REVIEW

**Comment by mvieth** [comment]
Hm, does anyone by chance have an idea why the `refineModel` is not found? I'm a bit stumped right now. It seems to be correctly instantiated and linked, no? If not, I can remove that commit.

**Comment by larshg** [comment]
I can see that at least for ubuntu and MacOS the `PCL_ONLY_CORE_POINT_TYPES` is set to ON and its complaining its missing this: `pcl::SampleConsensus<pcl::PointXYZINormal>`.

So you need to add the `PointXYZINormal` to the instantiated types.

For Windows you might also need to add the PCL_EXPORT macro.

But shouldn't the implementation be placed in a .hpp file?

**Comment by SergioRAgostinho** [comment]
> Hm, does anyone by chance have an idea why the `refineModel` is not found? I'm a bit stumped right now. It seems to be correctly instantiated and linked, no? If not, I can remove that commit.

There's a remote change that this is an issue with pcl_config.h not being visible to some file which requires the definition of `PCL_NO_PRECOMPILE` to exist.

**Comment by mvieth** [comment]
I added pcl_config includes in several files and added more instantiated point types, but there were still errors, so I removed that commit from this PR. Maybe I will have another look at it some other time.

**Comment by mvieth** [comment]
Closing this for now due to merge conflicts

**Pull request closed without merging**
