### PR TITLE
Update `pcl_find_boost` to allow compilation with Boost 1.73 and 1.72

### PR DESCRIPTION
**Pull request by UnaNancyOwen**
Add 1.72.0 and 1.73.0

### CODE REVIEW

**Comment by jspricke** [comment]
Is this necessary, still? (just asking)

**Comment by UnaNancyOwen** [comment]
@jspricke Yes, it is necessary when users are using an older version of CMake that can't find newer version of Boost by default. Users aren't always using a latest version of CMake.

**Comment by jspricke** [comment]
Maybe we should increase the required cmake version instead, do you know which version would be needed?

**Comment by jspricke** [comment]
Looking through my FindBoost.cmake, I guess there should be a version locking between the file and the installed boost version. So this seems like a okish workaround..

**Comment by SergioRAgostinho** [comment]
We're bumping to 3.10 very soon.

**Comment by SunBlack** [comment]
Switching to a newer CMake version doesn't change anything, as they didn't have changed there anything. So In case you want to use e.g. Boost 1.72 with CMake 3.10 it is still not possible, as long we use [FindBoost](https://gitlab.kitware.com/cmake/cmake/-/blob/master/Modules/FindBoost.cmake) of CMake. So by updating `Boost_ADDITIONAL_VERSIONS` we tell CMake: We don't care if you don't know the new version, as we checked it manually that no required module is gone and we don't need a new module of Boost.

We could only try to force config mode by `find_package(Boost CONFIG)`, so we don't need this list anymore - but I think there is a reason why CMake still updates their find script instead of to deprecate it and say: use the config. But no idea why.

**Comment by kunaltyagi** [comment]
1.74 isn't released yet: https://www.boost.org/users/history/

But once it is, we'll have to make some changes

**Comment by kunaltyagi** [comment]
> Does the new header already exist under 1.72/1.73

In 1.72 it does. But not in 1.65 (18.04) so we'd need a patch sometime later

**Comment by srini196** [comment]
Has the All-In-One Windows installer been updated to support compilation with Boost1.74?

**Comment by kunaltyagi** [comment]
Unless @UnaNancyOwen took steps to include the patch from #4330, no. You should be able to manually apply the required patch if needed

**Comment by UnaNancyOwen** [comment]
@srini196 PCL 1.11.1 All-in-one Installer is built with Boost 1.74.0 (backported #4330). You can use Boost 1.74.0. For more information, Please see [my build notes](https://gist.github.com/UnaNancyOwen/59319050d53c137ca8f3#file-pcl1-11-1-md).

**Comment by OgreTransporter** [comment]
For information only: On next Wednesday boost 1.75 will be published. FindBoost from CMake does not work with this version!

**Comment by kunaltyagi** [comment]
I really don't love this part of CMake 😆

**Pull request merged**
