### PR TITLE
fixed linemod func memory leak issue

### PR DESCRIPTION
**Pull request by BlazingForests**

### CODE REVIEW

**Comment by jspricke** [comment]
+1

**Comment by taketwo** [comment]
While we are at it, why not fixing a similar memory leak in `matchTemplates()`?

**Comment by BlazingForests** [comment]
Because a matter of time, I only modify and tested the the ```detectTemplatesSemiScaleInvariant``` function.

**Comment by jspricke** [comment]
That's fine, we ca fix the other bug later. Thanks for the pull request!

**Comment by BlazingForests** [comment]
Thanks!

**Pull request merged**
