### PR TITLE
Refactor cmake find script of libusb

### PR DESCRIPTION
**Pull request by SunBlack**
Several changes to libusb:
- As seen in #4431 there is a lot of duplicated code to find libusb => removed by using always the same find script
- Add support of PkgConfig for libusb
- Rename Findlibusb-1.0 to libusb as the real name is just [libusb](https://github.com/libusb/libusb) and currently the name was sometimes usb_10 and sometimes libusb_1
- Define an imported target. I took the code of [PkgConfig](https://gitlab.kitware.com/cmake/cmake/-/blob/v3.18.4/Modules/FindPkgConfig.cmake#L256) as reference (as only new versions of CMake support aliases for target, we don't use automatically created imported target by passing IMPORTED_TARGET to `pkg_check_modules`)
- OpenNI(2) requested libusb for all non-Win32-platforms, but added the library only on MacOS, so removed the request for other platforms.
- Headers of libusb were currently added to all targets, instead of just a few targets => fixed
- Simplified calls to `find_path` and `find_library` as system directories are already by default included

Note: I have tested it by executing `pcl_ni_*` apps - they should throw an exception that they don't find any device 

Interesting detail: It seems e.g. `pcl_dinast_grabber` is currently not build, even they should. Before this MR even `cmake --build . --target pcl_dinast_grabber` didn't worked. With this MR this works (don't ask me why just calling `make` doesn't include this target). Nevertheless this app doesn't work for me, but I don't know why:
```
(gdb) run
Starting program: /home/sunblack/dev/pcl_build_clang11/bin/pcl_dinast_grabber 
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
[New Thread 0x7fffe9589700 (LWP 103452)]

Thread 1 "pcl_dinast_grab" received signal SIGSEGV, Segmentation fault.
0x00007ffff79eb7bd in libusb_claim_interface () from /lib/x86_64-linux-gnu/libusb-1.0.so.0
```

### CODE REVIEW

**Review by kunaltyagi — APPROVED** [review]

**Comment by kunaltyagi** [comment]
Nice work!

> Nevertheless this app doesn't work for me, but I don't know why:

What does the backtrace look like? (PS: does it fail in a debug build too?)

**Comment by SunBlack** [comment]
> What does the backtrace look like? (PS: does it fail in a debug build too?)

Currently not tested (even on a fresh VM the 200GB disc is nearly full after 3 builds with different compilers ;-) ). Started VS2019 this night to check for compiler errors with libusb (I believe this is not part of Azure, or?)

**Comment by SunBlack** [comment]
> What does the backtrace look like? (PS: does it fail in a debug build too?)

With debug build:
```
(gdb) run
Starting program: /home/sunblack/dev/pcl_build_debug/bin/pcl_dinast_grabber 
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
[New Thread 0x7fffea308700 (LWP 109521)]

Thread 1 "pcl_dinast_grab" received signal SIGSEGV, Segmentation fault.
0x00007fffee1757bd in libusb_claim_interface () from /lib/x86_64-linux-gnu/libusb-1.0.so.0
(gdb) stacktrace
Undefined command: "stacktrace".  Try "help".
(gdb) backtrace
#0  0x00007fffee1757bd in libusb_claim_interface () from /lib/x86_64-linux-gnu/libusb-1.0.so.0
#1  0x00007ffff77945e6 in pcl::DinastGrabber::setupDevice (this=0x7fffffffdd20, device_position=1, id_vendor=6353, id_product=5122) at /home/sunblack/dev/pcl/io/src/dinast_grabber.cpp:192
#2  0x00007ffff7793f59 in pcl::DinastGrabber::onInit (this=0x7fffffffdd20, device_position=1) at /home/sunblack/dev/pcl/io/src/dinast_grabber.cpp:107
#3  0x00007ffff7793c5f in pcl::DinastGrabber::DinastGrabber (this=0x7fffffffdd20, device_position=1) at /home/sunblack/dev/pcl/io/src/dinast_grabber.cpp:56
#4  0x0000555555590b9b in main () at /home/sunblack/dev/pcl/apps/src/dinast_grabber_example.cpp:101
(gdb) frame 0
#0  0x00007fffee1757bd in libusb_claim_interface () from /lib/x86_64-linux-gnu/libusb-1.0.so.0
(gdb) frame 1
#1  0x00007ffff77945e6 in pcl::DinastGrabber::setupDevice (this=0x7fffffffdd20, device_position=1, id_vendor=6353, id_product=5122) at /home/sunblack/dev/pcl/io/src/dinast_grabber.cpp:192
192	  if (libusb_claim_interface(device_handle_, 0) < 0)
```

**Comment by SunBlack** [comment]
Got it to compile under MSVC (needed to compile libusb myself as the precompiled didn't worked). There I get now:

image

So it seems the issue is not related to this PR.

**Comment by SunBlack** [comment]
Just to mention: I have to adjust a few further things to the CMake file after [some clarification](https://gitlab.kitware.com/cmake/cmake/-/issues/21448) - I will need a few days for it

**Comment by SunBlack** [comment]
The pkg usage is now like in the [CMake](https://cmake.org/cmake/help/v3.19/manual/cmake-developer.7.html) documentation.

An alternative would be to use `INTERFACE IMPORTED` when the PKG package is fund and only otherwise `UNKNOWN IMPORTED`, as I now need to call `find_library` even we know the result already. Last one is required as PKG just returns `lib-usb`and not `/usr/lib/x86_64-linux-gnu/libusb-1.0.so` . Therefore this don't work:

```cmake
if(PC_LIBUSB_FOUND)
  set(libusb_INCLUDE_DIR ${PC_libusb_INCLUDEDIR})
  set(libusb_LIBRARIES ${PC_libusb_LIBRARIES})
else()
  find_path(libusb_INCLUDE_DIR
    NAMES
      libusb-1.0/libusb.h
    PATHS
      ${PC_libusb_INCLUDEDIR}
  )
  find_library(libusb_LIBRARIES
    NAMES
      usb-1.0
      libusb
    PATHS
      ${PC_libusb_LIBRARY_DIRS}
  )
endif()
```

**Review by kunaltyagi — APPROVED** [review]

**Review by larshg — APPROVED** [review]

**Comment by larshg** [comment]
Is this ready to 🚀 ?

**Comment by SunBlack** [comment]
> Is this ready to 🚀 ?

For long time already

**Pull request merged**
