### PR TITLE
Add formal documentation of PCD binary_compressed format

### LINKED ISSUE #3053: Update PCD format documentation to include binary_compressed DATA format
## Context

I am trying to import pcd files directly in python without using the PCL library python bindings.
My project is too small to justify pulling the whole PCL package just to load a few files. Besides the file format seems simple and designed to facilitate interoperability outside the PCL project.

## Expected Behavior

Documentation about the PCD file format http://pointclouds.org/documentation/tutorials/pcd_file_format.php should detail how to read  DATA in binary_compressed format.
I was not able to find informations elsewhere, the source code is not easy to find and read.

The documentation should also mention that data is transposed and explain how multidimensional points are handled in that context (flattened dimensions or still n-uplets?).

## Possible Solution

Update the documentation.
Explain that data is tranposed to improve compression (does this impact WIDTH/HEIGHT?)
Briefly document the lzf format as it is not widely known.
Maybe give a simple example to read it in python.

### PR DESCRIPTION
**Pull request by mvieth**
Fixes #3053
Please tell me if I missed any important details

### CODE REVIEW

**Comment by larshg** [comment]
Maybe a comment if the cloud contains rgb data as well. If my memory is correct it is placed in end uncompressed?

**Review by kunaltyagi — COMMENTED** [review]
Is this necessary?

> This option has been around since 2011, but did not have a formal specification for a long time.

**Comment by mvieth** [comment]
> Is this necessary?
> 
> > This option has been around since 2011, but did not have a formal specification for a long time.

Not strictly necessary, but I wanted to make clear that this format is not a new addition in a recent PCL version, that it has always been part of PCD 0.7 (no new version 0.8), that there already are PCD files that use this format, that PCL's PCDReader and PCDWriter have been able to read and write this format for a long time, and that the format was just not documented here.
So remove or keep this sentence?

**Comment by mvieth** [comment]
Yes, that intro line expresses more or less the same. I removed the sentence.

**Review by larshg — APPROVED** [review]

**Pull request merged**
