### PR TITLE
address conflict between visualization and VTK head

### LINKED ISSUE #2623: PCL 1.9+ VTK 8.2 Compilation failed pcl_visualizer.cpp:3567:88:
## Your Environment

Ubuntu 18.04 LTS
GCC 4.3   VTK 8.2 
* PCL 1.9+ Latest commit 9073f63 2 days ago

## Context

I need PCL for PDAL compatibility with VTK capabilities => Compile error Message => 
```
Building CXX object visualization/CMakeFiles/pcl_visualization.dir/src/pcl_visualizer.cpp.o
/home/mbariou/WKSCOMPILE/PCL/pcl/visualization/src/pcl_visualizer.cpp: In member function ‘bool pcl::visualization::PCLVisualizer::addTextureMesh(const pcl::TextureMesh&, const string&, int)’:
/home/mbariou/WKSCOMPILE/PCL/pcl/visualization/src/pcl_visualizer.cpp:3567:88: error: invalid conversion from ‘int’ to ‘const char*’ [-fpermissive]
                                                 vtkDataObject::FIELD_ASSOCIATION_POINTS);
```

## Expected Behavior
Seems overloading problem, but not sure if bug is inside VTK (https://www.vtk.org/doc/nightly/html/vtkPolyDataMapper_8h_source.html) or PCL (pcl/visualization/src/pcl_visualizer.cpp)
After several turn around with c_str(), to_string, and stoi() I give up Help needed! 

## Code to Reproduce

LINES 3545 to 3585 pcl_visualizer.cpp:3567:88: 
```cpp
    if (tex_id == 0)
      texture->SetBlendingMode(vtkTexture::VTK_TEXTURE_BLENDING_MODE_REPLACE);
    else
      texture->SetBlendingMode(vtkTexture::VTK_TEXTURE_BLENDING_MODE_ADD);
    // add a texture coordinates array per texture
    vtkSmartPointer<vtkFloatArray> coordinates = vtkSmartPointer<vtkFloatArray>::New ();
    coordinates->SetNumberOfComponents (2);
    std::stringstream ss; ss << "TCoords" << tex_id;
    std::string this_coordinates_name = ss.str ();
    coordinates->SetName (this_coordinates_name.c_str ());

    for (std::size_t t = 0; t < mesh.tex_coordinates.size (); ++t)
      if (t == tex_id)
        for (std::size_t tc = 0; tc < mesh.tex_coordinates[t].size (); ++tc)
          coordinates->InsertNextTuple2 (mesh.tex_coordinates[t][tc][0],
                                         mesh.tex_coordinates[t][tc][1]);
      else
        for (std::size_t tc = 0; tc < mesh.tex_coordinates[t].size (); ++tc)
          coordinates->InsertNextTuple2 (-1.0, -1.0);
      
    mapper->MapDataArrayToMultiTextureAttribute(tu,
                                                this_coordinates_name.c_str (),
                                                vtkDataObject::FIELD_ASSOCIATION_POINTS);  
   
    polydata->GetPointData ()->AddArray (coordinates);
    actor->GetProperty ()->SetTexture (tu, texture);
    ++tex_id;
  }

  // set mapper
  actor->SetMapper (mapper);
  addActorToRenderer (actor, viewport);

  // Save the pointer/ID pair to the global actor map
  (*cloud_actor_map_)[id].actor = actor;

  // Save the viewpoint transformation matrix to the global actor map
  (*cloud_actor_map_)[id].viewpoint_transformation_ = transformation;

  return (true);
}
```

## Possible Solution

I make several Turn around in the code zone, a bove I failed, some help needed thanks!

**Maintainer edit:** Aesthetics

### PR DESCRIPTION
**Pull request by greenbrettmichael**
error in vtk/rendering/core introduced by https://github.com/Kitware/VTK/commit/bbc96ed3bb95dde45f5fd4e7f932929fe5c667bd

Closes #2623

### CODE REVIEW

**Comment by greenbrettmichael** [comment]
appveyor appears to have timed out during the build process

**Comment by taketwo** [comment]
Hi, the lines that you are changing have quite a history, please refer to #2291, #2311, and #2322. As you can see, we have been bouncing between different version checks for a while. I would like to avoid a situation that we merge a commit that fixes the problem for you, but breaks builds for others. Please check especially the last thread that I referenced. We need to know a specific released VTK version where the API changed.

**Comment by marcel-bariou** [comment]
> @taketwo @SergioRAgostinho ...Hi, the lines that you are changing have quite a history, please refer to #2291, #2311, and #2322. As you can see, we have been bouncing between different version checks for a while ....

Ubuntu 18.04 LTS
GCC 4.3 VTK 8.2 with     PCL 1.9+ Latest commit 9073f63 2018/11/14
I pickup the 2612 change #ii..#else ..#endif, after code line 3563 and I apply it to the previous commit, it works perfectly thanks ! : 
> 

> #if VTK_MAJOR_VERSION >= 8 && VTK_MINOR_VERSION >= 2
>     mapper->MapDataArrayToMultiTextureAttribute(mesh.tex_materials[tex_id].tex_name.c_str(),
>       this_coordinates_name.c_str(),
>       vtkDataObject::FIELD_ASSOCIATION_POINTS);
> #else
>     mapper->MapDataArrayToMultiTextureAttribute(tu,
>                                                 this_coordinates_name.c_str (),
>                                                 vtkDataObject::FIELD_ASSOCIATION_POINTS);
>     this_coordinates_name.c_str(),
>     vtkDataObject::FIELD_ASSOCIATION_POINTS);
> #endif
>    

    polydata->GetPointData ()->AddArray (coordinates);
    actor->GetProperty ()->SetTexture (tu, texture);
    ++tex_id;
  }

**Comment by greenbrettmichael** [comment]
@taketwo 

the API changes mapper->MapDataArrayToMultiTextureAttribute to take a string, whereas SetTexture remains an integer. This prevents the approach given by the previous define from working. This was changed on VTK commit Kitware/VTK@bbc96ed 10 months ago.

This change is encorporated into the upcoming release https://blog.kitware.com/vtk-8-2-0-rc1-ready-for-testing/ . The previous define would have never activated as VTK has not release a version 9, so this change is safe from breaking users with previous versions.

**Comment by taketwo** [comment]
Thanks for investigating. I just have a minor suggestion then, can we keep the `#if`/`#else` stuff at the same place as it is now, only update the version check:

```cpp
#if (VTK_MAJOR_VERSION == 8 && VTK_MINOR_VERSION >= 2) || VTK_MAJOR_VERSION > 8
  const char *tu = mesh.tex_materials[tex_id].tex_name.c_str ();
#else
  int tu = vtkProperty::VTK_TEXTURE_UNIT_0 + tex_id;
#endif
```

**Comment by marcel-bariou** [comment]
Thanks I will look, let me a day

**Comment by greenbrettmichael** [comment]
@taketwo I agree that is more aesthetically pleasing and nicer to the commit history. However line 3570 requires int tu in all VTK versions
`actor->GetProperty ()->SetTexture (tu, texture);`
As a compromise, how about:
```
#if (VTK_MAJOR_VERSION == 8 && VTK_MINOR_VERSION >= 2) || VTK_MAJOR_VERSION > 8
  const char *tu = mesh.tex_materials[tex_id].tex_name.c_str ();
#else
  int tu = vtkProperty::VTK_TEXTURE_UNIT_0 + tex_id;
#endif
int tuID = vtkProperty::VTK_TEXTURE_UNIT_0 + tex_id;
...
mapper->MapDataArrayToMultiTextureAttribute(tu,
  this_coordinates_name.c_str(),
  vtkDataObject::FIELD_ASSOCIATION_POINTS);
polydata->GetPointData ()->AddArray (coordinates);
actor->GetProperty ()->SetTexture (tuID, texture);
```

I hope that I am not coming off as a pedant, I have more contributions to make!

**Comment by greenbrettmichael** [comment]
@taketwo  I concede that I was mistaken. I have pushed the requested change. This builds for me

**Pull request merged**
