### PR TITLE
Fix warning C4005: 'M_PI_4': macro redefinition

### PR DESCRIPTION
**Pull request by SunBlack**

### CODE REVIEW

**Comment by SunBlack** [comment]
@UnaNancyOwen: Can you reproduce compile issue on Azure? This changes works fine on my machine :/.

**Comment by SunBlack** [comment]
I took a further look into this issue. `corecrt_math_defines.h` is located in `C:\Program Files (x86)\Windows Kits\10\Include\10.0.17763.0\ucrt`. I assume [this](https://github.com/Microsoft/azure-pipelines-image-generation/blob/master/images/win/Vs2017-Server2016-Readme.md) image is used on Azure, so Microsoft.VisualStudio.Component.Windows10SDK.17763 is installed.

Conclusion: I have no idea why it fails :(.

**Comment by taketwo** [comment]
But speaking of the original problem that you are trying to solve, do I understand right that in your environment for some reason `M_PI` is undefined (thus compiler gets past ` #ifndef M_PI` guard), but `M_PI_4` is defined? This sounds quite strange. Can it be a symptom of some other issue?

**Comment by SunBlack** [comment]
@taketwo Check output of Azure Windows build. If I search for `macro redefinition` there, I got 600 hits, so it's not just my system,

**Comment by UnaNancyOwen** [comment]
I think the cause of this problem is header include order.
<code>iostream</code> header seems to include <code>cmath</code> in dependencies.
Therefor, We need to define <code>_USE_MATH_DEFINES</code> before include <code>iostream</code>.
https://github.com/PointCloudLibrary/pcl/blob/master/common/include/pcl/pcl_macros.h#L68-L74
```patch
+#ifndef _USE_MATH_DEFINES
+#define _USE_MATH_DEFINES
+#endif
#include <iostream>
#include <cstdarg>
#include <cstdio>
-#ifndef _USE_MATH_DEFINES
-#define _USE_MATH_DEFINES
-#endif
#include <cmath>
```
In the simple case, this is fix this problem.
However, I don't know whether this problem will be solved by this.
(It is possible that these headers include cmath. It has not been investigated yet.
https://github.com/PointCloudLibrary/pcl/blob/master/common/include/pcl/pcl_macros.h#L39-L41)
Please try it.

> Conclusion: I have no idea why it fails :(.

Sorry, I don't know why include fails.

**Comment by UnaNancyOwen** [comment]
Hmmm, <code>cstdlib</code> is include <code>cmath.h</code>.
We need to define <code>_USE_MATH_DEFINES</code> before include <code>cstdlib</code>.
https://github.com/PointCloudLibrary/pcl/blob/master/common/include/pcl/pcl_macros.h#L41
```patch
#include <pcl/pcl_config.h>
#include <boost/cstdint.hpp>
+#ifndef _USE_MATH_DEFINES
+#define _USE_MATH_DEFINES
+#endif
#include <cstdlib>
```
```patch
#include <iostream>
#include <cstdarg>
#include <cstdio>
-#ifndef _USE_MATH_DEFINES
-#define _USE_MATH_DEFINES
-#endif
#include <cmath>
```

**Comment by taketwo** [comment]
> Check output of Azure Windows build. If I search for macro redefinition there, I got 600 hits, so it's not just my system

OK, here are the messages:

```
C:\Program Files (x86)\Windows Kits\10\Include\10.0.14393.0\ucrt\math.h(1005): warning C4005: 'M_E': macro redefinition (compiling source file D:\a\1\s\sample_consensus\src\sac_model_circle.cpp) [D:\a\build\sample_consensus\pcl_sample_consensus.vcxproj]
  D:\a\1\s\common\include\pcl/pcl_macros.h(81): note: see previous definition of 'M_E' (compiling source file D:\a\1\s\sample_consensus\src\sac_model_circle.cpp)
```

The way I interpret them is that by the time the compiler gets to process `math.h`, the `M_E` macro has been defined already from `pcl_macros.h`. Which means, therefore, that inside our `#ifndef`ed block with constants we should _undefine_ `_USE_MATH_DEFINES`.

**Comment by SunBlack** [comment]
> (It is possible that these headers include cmath. It has not been investigated yet.
> https://github.com/PointCloudLibrary/pcl/blob/master/common/include/pcl/pcl_macros.h#L39-L41)

They do. `/showIncludes` is a really helpful option to check this :).

> > Conclusion: I have no idea why it fails :(.
> 
> Sorry, I don't know why include fails.

I know now why: `math.h` looks really different between different Windows SDK versions. So latest (10.0.17134.0) hast defined `M_PI` in `corecrt_math_defines.h`, which will be included from `math.h`. In 10.0.14393.0, which will be used by Azure pipeline, `corecrt_math_defines.h` doesn't exists. Instead `M_PI` is directly defined in `math.h`. So my hope to can just include constants without any other method, doesn't work. My conclusion from this: We could include `math.h`, but then we have some more functions in global namespace (as it will be done via 3rd-Party code already, like FLANN, it wouldn't hurt much) or we continue copy&paste these constants and just make sure to prevent this warning.

> The way I interpret them is that by the time the compiler gets to process `math.h`, the `M_E` macro has been defined already from `pcl_macros.h`. Which means, therefore, that inside our `#ifndef`ed block with constants we should _undefine_ `_USE_MATH_DEFINES`.

At the time 3rd-party code include `math.h` again with `_USE_MATH_DEFINES`, we will getting this issue back. So we should define `_MATH_DEFINES_DEFINED` instead.

**Pull request merged**
