### PR TITLE
Fix reflectivity parameters parsing in loadOBJFile

### PR DESCRIPTION
**Pull request by SergioRAgostinho**
There was a bug, attempting to make a reassignment to a reference, on the reflectivity parameters parsing stage.
I also added support to the "Tr" tag, used by meshlab, which apparently is simply the complement of the "d" dissolve parameter.

### CODE REVIEW

**Comment by stefanbuettner** [comment]
Hey Sérgio,

was this reassignment error a compilation error? 'Cause this rgb value is not used anywhere, is it?

Don't know anything about this *Tr* tag. Is there any documentation in Meshlab, which mtl-format it supports? Would be nice to have a link to the mtl-format specification PCL supports (or is working towards supporting) in the MTL reader documentation, wouldn't it.
Wikipedia links to this one, for example: http://paulbourke.net/dataformats/mtl/.

Cheers,
Stefan

**Comment by SergioRAgostinho** [comment]
> was this reassignment error a compilation error? 'Cause this rgb value is not used anywhere, is it?

It was not a compilation error. Just the underlying logic was messed up. The rgb value is used [here](https://github.com/SergioRAgostinho/pcl/blob/55a33a1a546a2d39787871f1bcd5aa6ea2367042/io/src/obj_io.cpp#L235) and [here](https://github.com/SergioRAgostinho/pcl/blob/55a33a1a546a2d39787871f1bcd5aa6ea2367042/io/src/obj_io.cpp#L246). I remember I bumped on this bug while working with a specific file, and noticed the material parameters were messed up.

> Don't know anything about this Tr tag. Is there any documentation in Meshlab, which mtl-format it supports? Would be nice to have a link to the mtl-format specification PCL supports (or is working towards supporting) in the MTL reader documentation, wouldn't it.
Wikipedia links to this one, for example: http://paulbourke.net/dataformats/mtl/.

True. For the Tr tag I took the description from [wikipedia](https://en.wikipedia.org/wiki/Wavefront_.obj_file#Basic_materials), but there's no reference to an actual standard.

**Comment by stefanbuettner** [comment]
True, but don't these functions just fill that local rgb variable based on the contents of `st`? And afterwards `rgb`is not used anywhere else.

**Comment by SergioRAgostinho** [comment]
You're right. Let me have a look tonight to see if I find my offending case :)

**Comment by SergioRAgostinho** [comment]
Just figured out what we were overlooking in our discussion. So notice that in my fix, ```rgb``` is actually a pointer and depending on the material tag, it gets assigned a different address, e.g. to ```tex_Ka```, ```tex_Kd``` or  ```tex_Ks```. Then in  ```fillRGBfromXYZ``` and ```fillRGBfromRGB```, rgb is passed by reference, so I'm actually changing ```tex_Ka```, ```tex_Kd``` or  ```tex_Ks```, respectively.

**Comment by jspricke** [comment]
I will add some comments in line. As a side note, please put different fixes in separate commits, makes them easier to review ;).

**Comment by jspricke** [comment]
Must have been the weather conditions, all good. Thanks!

**Pull request merged**
