### PR TITLE
Refactor AgastDetector7_12s_computeCornerScore

### PR DESCRIPTION
**Pull request by SunBlack**
Had yesterday again a day full of updating dependencies, so I had again time to be a masochist ;). As last time I used [this code](https://github.com/PointCloudLibrary/pcl/pull/2657#issuecomment-442884061) to verify I didn't changed behavior.

Most changes are done with help of regular expressions. I'm happy that this exists.

Just in case you want to have fun: My favorite regexe to search for specific code snippets
```
if \([^\n]*\)\s*return \((?:\([^\(\)]*\) && )*(\([^\(\)]*\))(?: && \([^\(\)]*\))*\);\s*else\s*return \((:?\([^\(\)]*\) && )*?\1(?: && \([^\(\)]*\))\);
```
```
  else\n    (\s*)return false;\n\1else\n\1  return false;
```

### CODE REVIEW

**Comment by SergioRAgostinho** [comment]
Don't forget to rebase this against the current master. We already pushed the fix that gets rid of these out of space errors in the Windows CI.

**Comment by SunBlack** [comment]
? This PR is basing on latest commit in master.

**Comment by SunBlack** [comment]
As currently clang-format will be applied to whole source: Is it possible to merge this PR before? I don't believe I can rebase this as it touches to many lines :/

**Comment by taketwo** [comment]
It'll take some time until we reach the `keypoints` module with formatting. But yes, I will try to review this soon.

**Pull request merged**
