### PR TITLE
[tools] Adds `pcl_filters` to the libraries linked to `linemod_detection`

### LINKED ISSUE #4082: [windows] symbol not found: `filters::Convolution<RGB,RGB>::convolveOne{Row,Col}Dense()`
**Describe the bug**

pcl_linemod_detection and pcl_train_linemod_template are failed build on Windows.  

```
------ ビルド開始: プロジェクト: pcl_linemod_detection, 構成: Release x64 ------
Building Custom Rule C:/pcl-1.11.0/tools/CMakeLists.txt
linemod_detection.cpp
C:\pcl-1.11.0\tools\linemod_detection.cpp(117,1): warning C4996: 'pcl::PointCloud<pcl::PointXYZRGBA>::mapping_': rewrite your code to avoid using this protected field (It will be removed in PCL 1.12)
linemod_detection.obj : error LNK2001: 外部シンボル ""private: struct pcl::RGB __cdecl pcl::filters::Convolution<struct pcl::RGB,struct pcl::RGB>::convolveOneColDense(int,int)" (?convolveOneColDense@?$Convolution@URGB@pcl@@U12@@filters@pcl@@AEAA?AURGB@3@HH@Z)" は未解決です。
linemod_detection.obj : error LNK2001: 外部シンボル ""private: struct pcl::RGB __cdecl pcl::filters::Convolution<struct pcl::RGB,struct pcl::RGB>::convolveOneRowDense(int,int)" (?convolveOneRowDense@?$Convolution@URGB@pcl@@U12@@filters@pcl@@AEAA?AURGB@3@HH@Z)" は未解決です。
C:\pcl-1.11.0\build\bin\pcl_linemod_detection.exe : fatal error LNK1120: 2 件の未解決の外部参照
プロジェクト "pcl_linemod_detection.vcxproj" のビルドが終了しました -- 失敗。
```
```
------ ビルド開始: プロジェクト: pcl_train_linemod_template, 構成: Release x64 ------
Building Custom Rule C:/pcl-1.11.0/tools/CMakeLists.txt
train_linemod_template.cpp
C:\pcl-1.11.0\tools\train_linemod_template.cpp(227,1): warning C4996: 'pcl::PointCloud<pcl::PointXYZRGBA>::mapping_': rewrite your code to avoid using this protected field (It will be removed in PCL 1.12)
train_linemod_template.obj : error LNK2001: 外部シンボル ""private: struct pcl::RGB __cdecl pcl::filters::Convolution<struct pcl::RGB,struct pcl::RGB>::convolveOneColDense(int,int)" (?convolveOneColDense@?$Convolution@URGB@pcl@@U12@@filters@pcl@@AEAA?AURGB@3@HH@Z)" は未解決です。
train_linemod_template.obj : error LNK2001: 外部シンボル ""private: struct pcl::RGB __cdecl pcl::filters::Convolution<struct pcl::RGB,struct pcl::RGB>::convolveOneRowDense(int,int)" (?convolveOneRowDense@?$Convolution@URGB@pcl@@U12@@filters@pcl@@AEAA?AURGB@3@HH@Z)" は未解決です。
C:\pcl-1.11.0\build\bin\pcl_train_linemod_template.exe : fatal error LNK1120: 2 件の未解決の外部参照
プロジェクト "pcl_train_linemod_template.vcxproj" のビルドが終了しました -- 失敗。
```

**To Reproduce**
Build PCL with enable BUILD_tools on Windows.

**Your Environment (please complete the following information):**

 - OS: Windows 10
 - Compiler: Visual Studio 2019 (x64)
 - PCL Version: PCL 1.11.0

### PR DESCRIPTION
**Pull request by kunaltyagi**
Fixes #4082

### CODE REVIEW

**Comment by kunaltyagi** [comment]
@UnaNancyOwen Can you confirm this resolves the issue?

Why didn't our CI catch this? Do we not build tools on Ubuntu and MacOS CI?

**Comment by SunBlack** [comment]
Sad news: Exactly the same fix I tried 1 hour ago and it didn't helped :-(

**Comment by kunaltyagi** [comment]
Same errors? If they are in EN or different in content, could you post them here please. I got the just in JP, but I might have missed something

**Comment by SunBlack** [comment]
Here current result of the ALL_BUILD

image

**Comment by kunaltyagi** [comment]
You're getting errors in `pcl_convolve`? That's weird because that part shouldn't be throwing errors.

**Comment by SunBlack** [comment]
> EDIT:
> Can you test #3971 to verify that it compiles for your setup because that is the root cause of the error. Any solution needs to work on that diff

#3971 is already in master, so what I should test?

When I compile 609f9ac752a7e1bb2bf3f145a3b2dd61b03d39db (last commit before #3791 was merged) I get 
image

**Comment by kunaltyagi** [comment]
Thank, that helped to identify that moving the template to src wasn't the cause.

Closing the PR because it doesn't address the root cause and I can't do anything else (because I'm not on debugging on windows)

**Comment by UnaNancyOwen** [comment]
I already tried it but this didn't solve the problem.
We should be consider building tools in CI.
(I'm not so sure if it have a history of being passed over because it takes time to build it.)

**Comment by kunaltyagi** [comment]
>  consider building tools in CI

This will be after Windows docker is ready since VTK installation takes a very long time using vcpkg. Would it be possible to collaborate with @larshg in developing and testing the Dockerfile for windows docker?

**Pull request closed without merging**
