### PR TITLE
Remove non-free lena-grayscale.png

### PR DESCRIPTION
**Pull request by jspricke**
cf. https://lintian.debian.org/tags/license-problem-non-free-img-lenna.html

### CODE REVIEW

**Comment by jspricke** [comment]
as far as I've found, this image is used nowhere.

**Comment by SergioRAgostinho** [comment]
Did our CI workers got downgraded or something? it did not finish building the project under 2 hours...

**Comment by taketwo** [comment]
As far as I can see, in the last run Travis was not able to pick up pre-compiled VTK, Flann, etc. from cache and needed to recompile them.

**Comment by taketwo** [comment]
I can not find any details about when and why Travis invalidates caches, but let's assume it happened because there was not activity in the master branch for the last two months.

In the last couple of runs all the dependencies were successfully rebuilt, but since these were "pull request runs", the cache was not uploaded to the cloud. So I will merge this one to make sure that the dependencies are rebuilt and cached again.

**Comment by SergioRAgostinho** [comment]
I was gonna say to merge #1677 instead. I wanted to see if this broke any of the tests. I find it strange that we had an unused image in the repo.

**Comment by taketwo** [comment]
Too late :) But `ag` reveals no references to this image by name. I can't imagine that there is a test case somewhere which constructs the filename by concatenating parts.

**Pull request merged**
