### PR TITLE
wrap QMatrix in namespace pcl

### PR DESCRIPTION
**Pull request by maz-1**
fixes conflict with QtGui. Resolves https://github.com/PointCloudLibrary/pcl/issues/4857

### CODE REVIEW

**Comment by larshg** [comment]
Need to fix format to clang style, see here for required changes https://dev.azure.com/PointCloudLibrary/pcl/_build/results?buildId=19641&view=logs&jobId=84ba2080-ade3-55e3-f209-94ce73f9d406&j=84ba2080-ade3-55e3-f209-94ce73f9d406&t=9838d42f-a715-5615-242f-7e73bf03078b

Click show diff.

**Review by mvieth — APPROVED** [review]
Thank you!

**Review by kunaltyagi — APPROVED** [review]
Probably also wrap the Kernel class 😆

**Comment by jspricke** [comment]
@kunaltyagi  Why is this flagged ABI break?
As far I can see this is an internal class.
Note that we can't have ABI breaks in patch releases as they don't bump the Soname, so either this should not have been in 1.12.1 or this is not an ABI break?

**Comment by kunaltyagi** [comment]
Yeah, I also thought there would be no ABI break, however, the tooling used (.github/generate_abi_reports.sh) verified the following:
* changing the arguments from unused to used impacted the registers they were being loaded to

This would have resulted in ill-formed programs post linkage. Thanks to @mvieth for figuring this out.

**Comment by mvieth** [comment]
Here is the full report for the ml module:
[compat_report_ml_1.12.1.zip](https://github.com/PointCloudLibrary/pcl/files/7775708/compat_report_ml_1.12.1.zip)

**Pull request merged**
