### PR TITLE
fix: wrong position and scale of context items when resizing ImageViewer (vtk6)

### PR DESCRIPTION
**Pull request by mdkus**
#1081 ...new patch as discussed.

### CODE REVIEW

**Comment by taketwo** [comment]
Hmmm, I have problems compiling this with _vtk6.1_:

```
/media/Workspace/Libraries/pcl/visualization/include/pcl/visualization/vtk/pcl_context_item.h:44:10: fatal error: 'vtkOpenGLContextActor.h' file not found
#include <vtkOpenGLContextActor.h>
```

Apparently, this file is not a part of the _vtk_ package (at least on Arch):

```
$ pacman -Ql vtk | grep "vtkOpenGLContext.*"
vtk /usr/include/vtk-6.1/vtkOpenGLContextBufferId.h
vtk /usr/include/vtk-6.1/vtkOpenGLContextDevice2D.h
vtk /usr/include/vtk-6.1/vtkOpenGLContextDevice3D.
```

**Comment by mdkus** [comment]
Ah yes, 'vtkOpenGLContextActor' was introduced with vtk6.2. Older versions should derive from 'vtkContextActor'...I'll send a correction...

**Comment by taketwo** [comment]
@mdkus there is no need to close this request and open a new one. Just add more commits to and push, they will automatically appear here.

**Comment by mdkus** [comment]
@taketwo unfortunately I've deleted my pcl fork in the meantime. So I can't reopen this. I think the only chance is a new pull request then?

**Pull request closed without merging**
