### PR TITLE
Disable tools build in CI.

### PR DESCRIPTION
**Pull request by SergioRAgostinho**
Disable the building of tools in the CI, 'till they get properly refactored (somehow )

### CODE REVIEW

**Comment by frozar** [comment]
Sad news...

**Comment by frozar** [comment]
I send a mail to the Travis CI support recently (it was to report a bug in their interface). They answer me:
> We have increased the maximum build time to 70 minutes for the repository PointCloudLibrary/pcl, so you will run less into false negatives.

It's really a great news, and I think that we can enable again the building of tools. What do you think about it?

PS: if you'd like read the emails, just give me your mail address on IRC (or send email at fabien.rozar@gmail.com)

**Comment by taketwo** [comment]
Fabien, that's indeed great news, thanks for reaching out to them. We should have tried this "social engineering" approach instead of "workarounds hacking" much earlier :laughing:

I've restarted [one the old jobs](https://travis-ci.org/PointCloudLibrary/pcl/jobs/278424383) for tools, let's see if it succeeds. And with this new limit we can also try merge together some of the extended test jobs to avoid superfluous library re-compilation, e.g. `test-ext-1` and `test-ext-2`.

**Comment by frozar** [comment]
@taketwo : Yes, definitely it's a great news :smile: 

If you'd like the rework the exist test, hope to you, I cannot spend too much time to develop PCL. As you can see, I open a pull request for the build of tools, and I'll look closely at the build status.

**Comment by frozar** [comment]
@taketwo : the old job you launched previously passed the build successfully: Champagne!

**Comment by SergioRAgostinho** [comment]
OMG!!!!! Good job @frozar ! Btw, why not enable apps then as well? :wink: (It's just uncommenting the other one)

**Comment by frozar** [comment]
I didn't uncomment it because I didn't know if these tests work or not. Hope to you to try them locally, check if everything is alright (ideally), and propose a pull request ;-)

**Pull request merged**
