### PR TITLE
Remove Deprecated Code for 1.15.0 release

### LINKED ISSUE #6039: Remove deprecated code for the 1.15.0 release
The full list of deprecated classes/functions/headers (for deprecated headers, please delete the file):
```
apps/in_hand_scanner/include/pcl/apps/in_hand_scanner/boost.h:PCL_DEPRECATED_HEADER(1, 15, "Please include the needed boost headers directly.")
apps/in_hand_scanner/include/pcl/apps/in_hand_scanner/eigen.h:PCL_DEPRECATED_HEADER(1, 15, "Please include the needed eigen headers directly.")
common/include/pcl/make_shared.h:PCL_DEPRECATED_HEADER(1, 15, "Use <pcl/memory.h> instead.")
common/include/pcl/point_traits.h:PCL_DEPRECATED_HEADER(1, 15, "Use <pcl/type_traits.h> instead.")
common/include/pcl/common/boost.h:PCL_DEPRECATED_HEADER(1, 15, "Please include the needed boost headers directly.")
features/include/pcl/features/boost.h:PCL_DEPRECATED_HEADER(1, 15, "Please include the needed boost headers directly.")
features/include/pcl/features/eigen.h:PCL_DEPRECATED_HEADER(1, 15, "Please include the needed eigen headers directly.")
filters/include/pcl/filters/boost.h:PCL_DEPRECATED_HEADER(1, 15, "Please include the needed boost headers directly.")
geometry/include/pcl/geometry/eigen.h:PCL_DEPRECATED_HEADER(1, 15, "Please include the needed eigen headers directly.")
gpu/utils/include/pcl/gpu/utils/device/static_check.hpp:PCL_DEPRECATED_HEADER(1, 15, "pcl::device::Static will be removed at PCL release 1.15");
gpu/utils/include/pcl/gpu/utils/device/static_check.hpp:struct [[deprecated("This class will be replaced at PCL release 1.15  by "
io/include/pcl/io/boost.h:PCL_DEPRECATED_HEADER(1, 15, "Please include the needed boost headers directly.")
io/include/pcl/io/io.h:PCL_DEPRECATED_HEADER(1, 15, "Please include pcl/common/io.h directly.")
io/include/pcl/io/eigen.h:PCL_DEPRECATED_HEADER(1, 15, "Please include the needed eigen headers directly.")
keypoints/include/pcl/keypoints/uniform_sampling.h:PCL_DEPRECATED_HEADER(1, 15, "UniformSampling is not a Keypoint anymore, use <pcl/filters/uniform_sampling.h> instead.")
octree/include/pcl/octree/boost.h:PCL_DEPRECATED_HEADER(1, 15, "Please include the needed boost headers directly.")
recognition/include/pcl/recognition/auxiliary.h:PCL_DEPRECATED_HEADER(1, 15, "Please use <pcl/recognition/ransac_based/auxiliary.h> instead")
recognition/include/pcl/recognition/model_library.h:PCL_DEPRECATED_HEADER(1, 15, "Please use <pcl/recognition/ransac_based/model_library.h> instead")
recognition/include/pcl/recognition/rigid_transform_space.h:PCL_DEPRECATED_HEADER(1, 15, "Please use <pcl/recognition/ransac_based/rigid_transform_space.h> instead")
recognition/include/pcl/recognition/voxel_structure.h:PCL_DEPRECATED_HEADER(1, 15, "Please use <pcl/recognition/ransac_based/voxel_structure.h> instead")
recognition/include/pcl/recognition/hypothesis.h:PCL_DEPRECATED_HEADER(1, 15, "Please use <pcl/recognition/ransac_based/hypothesis.h> instead")
recognition/include/pcl/recognition/orr_graph.h:PCL_DEPRECATED_HEADER(1, 15, "Please use <pcl/recognition/ransac_based/orr_graph.h> instead")
recognition/include/pcl/recognition/simple_octree.h:PCL_DEPRECATED_HEADER(1, 15, "Please use <pcl/recognition/ransac_based/simple_octree.h> instead")
recognition/include/pcl/recognition/boost.h:PCL_DEPRECATED_HEADER(1, 15, "Please include the needed boost headers directly.")
recognition/include/pcl/recognition/obj_rec_ransac.h:PCL_DEPRECATED_HEADER(1, 15, "Please use <pcl/recognition/ransac_based/obj_rec_ransac.h> instead")
recognition/include/pcl/recognition/orr_octree_zprojection.h:PCL_DEPRECATED_HEADER(1, 15, "Please use <pcl/recognition/ransac_based/orr_octree_zprojection.h> instead")
recognition/include/pcl/recognition/impl/voxel_structure.hpp:PCL_DEPRECATED_HEADER(1, 15, "Please use <pcl/recognition/impl/ransac_based/voxel_structure.hpp> instead")
recognition/include/pcl/recognition/impl/simple_octree.hpp:PCL_DEPRECATED_HEADER(1, 15, "Please use <pcl/recognition/impl/ransac_based/simple_octree.hpp> instead")
recognition/include/pcl/recognition/impl/line_rgbd.hpp:PCL_DEPRECATED_HEADER(1, 15, "Please use <pcl/recognition/impl/linemod/line_rgbd.hpp> instead")
recognition/include/pcl/recognition/line_rgbd.h:PCL_DEPRECATED_HEADER(1, 15, "Please use <pcl/recognition/linemod/line_rgbd.h> instead")
recognition/include/pcl/recognition/trimmed_icp.h:PCL_DEPRECATED_HEADER(1, 15, "Please use <pcl/recognition/ransac_based/trimmed_icp.h> instead")
recognition/include/pcl/recognition/orr_octree.h:PCL_DEPRECATED_HEADER(1, 15, "Please use <pcl/recognition/ransac_based/orr_octree.h> instead")
recognition/include/pcl/recognition/bvh.h:PCL_DEPRECATED_HEADER(1, 15, "Please use <pcl/recognition/ransac_based/bvh.h> instead")
registration/include/pcl/registration/ndt.h:  PCL_DEPRECATED(1, 15, "Parameter `transform` is not required")
registration/include/pcl/registration/boost.h:PCL_DEPRECATED_HEADER(1, 15, "Please include the needed boost headers directly.")
registration/include/pcl/registration/impl/correspondence_rejection_trimmed.hpp:PCL_DEPRECATED_HEADER(1, 15, "")
registration/include/pcl/registration/impl/correspondence_rejection_distance.hpp:PCL_DEPRECATED_HEADER(1, 15, "")
registration/include/pcl/registration/impl/correspondence_rejection_median_distance.hpp:PCL_DEPRECATED_HEADER(1, 15, "")
registration/include/pcl/registration/impl/correspondence_rejection_surface_normal.hpp:PCL_DEPRECATED_HEADER(1, 15, "")
registration/include/pcl/registration/impl/correspondence_rejection_organized_boundary.hpp:PCL_DEPRECATED_HEADER(1, 15, "")
registration/include/pcl/registration/impl/correspondence_rejection_var_trimmed.hpp:PCL_DEPRECATED_HEADER(1, 15, "")
registration/include/pcl/registration/impl/correspondence_rejection_one_to_one.hpp:PCL_DEPRECATED_HEADER(1, 15, "")
registration/include/pcl/registration/transforms.h:PCL_DEPRECATED_HEADER(1, 15, "Please include pcl/common/transforms.h directly.")
registration/include/pcl/registration/eigen.h:PCL_DEPRECATED_HEADER(1, 15, "Please include the needed eigen headers directly.")
sample_consensus/include/pcl/sample_consensus/boost.h:PCL_DEPRECATED_HEADER(1, 15, "Please include the needed boost headers directly.")
sample_consensus/include/pcl/sample_consensus/eigen.h:PCL_DEPRECATED_HEADER(1, 15, "Please include the needed eigen headers directly.")
segmentation/include/pcl/segmentation/boost.h:PCL_DEPRECATED_HEADER(1, 15, "Please include the needed boost headers directly.")
surface/include/pcl/surface/boost.h:PCL_DEPRECATED_HEADER(1, 15, "Please include the needed boost headers directly.")
surface/include/pcl/surface/mls.h:    PCL_DEPRECATED(1, 15, "use calculatePrincipalCurvatures() instead")
surface/include/pcl/surface/eigen.h:PCL_DEPRECATED_HEADER(1, 15, "Please include the needed eigen headers directly.")
tracking/include/pcl/tracking/pyramidal_klt.h:  PCL_DEPRECATED(1, 15, "use getStatusOfPointsToTrack instead")
visualization/include/pcl/visualization/pcl_visualizer.h:        PCL_DEPRECATED(1,15,"updateCamera will be removed, as it does nothing.")
visualization/include/pcl/visualization/vtk.h:PCL_DEPRECATED_HEADER(1, 15, "Use required vtk includes instead.")
visualization/include/pcl/visualization/eigen.h:PCL_DEPRECATED_HEADER(1, 15, "Please include the needed eigen headers directly.")
```

### PR DESCRIPTION
**Pull request by Shayril**
Fixes #6039

### CODE REVIEW

**Comment by larshg** [comment]
Looking good - however you need to remove them for the CMakelists.txt as well, ad it cant find them now they where removed.
Ie. here https://github.com/PointCloudLibrary/pcl/blob/5373884dc7221afeb1488850f0040db816a22d30/apps/in_hand_scanner/CMakeLists.txt#L21

**Comment by larshg** [comment]
Some of the files you deleted, shouldn't be deleted. Ie. visualization/include/pcl/visualization/pcl_visualizer.h.
Only a method inside the class are deprecated, not then entire file.
There are multiple occurence like this, ie. mls.h.

**Review by mvieth — APPROVED** [review]
Looks good, thanks!

**Review by larshg — APPROVED** [review]

**Comment by larshg** [comment]
Thank you @Shayril :+1:

**Pull request merged**
