### PR TITLE
Begin using of summary.

### PR DESCRIPTION
**Pull request by larshg**

### CODE REVIEW

**Comment by larshg** [comment]
@kunaltyagi yes, I released this. But this one should be from my own repository 👍

**Comment by larshg** [comment]
Currently print like this for windows:

-- Enabled Features:
-- The following features have been enabled:

 * c++14, is enabled
 * COMPILER, is Visual studio
 * CORE_COUNT, Core count is 2
 * OpenMP, is enabled

-- The following OPTIONAL packages have been found:

 * OpenMP, is enabled
 * flann (required version >= 1.7.0)
 * PkgConfig
 * Qhull

-- The following REQUIRED packages have been found:

 * Threads
 * Eigen (required version >= 3.1)
 * FLANN (required version >= 1.7.0)
 * Boost (required version >= 1.55.0)
 * OpenGL
 * GTestSource

-- The following OPTIONAL packages have not been found:

 * ClangFormat (required version >= 10)
 * libusb-1.0
 * OpenNI
 * OpenNI2
 * Ensenso
 * davidSDK
 * DSSDK
 * RSSDK
 * realsense2
 * RSSDK2
 * ZLIB
 * PNG
 * CUDA (required version >= 7.5)
 * Qt5
 * VTK

**Comment by kunaltyagi** [comment]
Can we make this ON by default? The user needs to provide -DWITH_SUMMARY=OFF to not see this

**Comment by larshg** [comment]
Gonna close this, as the feature summary provided by cmake, seems to have little to no "customization", so everything would end up under features (in some order).
Seeing as how OpenCV has it implemented, we should maybe go for a more own controlled printing summary:
https://github.com/opencv/opencv/blob/master/CMakeLists.txt#L970-L1604

**Pull request closed without merging**
