### PR TITLE
Hotfix for the new doc CI

### PR DESCRIPTION
**Pull request by kunaltyagi**
Update for #4691

### CODE REVIEW

**Comment by ueqri** [comment]
It's my fault for causing this trouble by modifying the single line in code editor online without too much check, I'm sincerely sorry to bring the mistake. And thanks for your hotfix. I will check the codes more carefully at any time in the further developments and ensure this doesn't happen again.

**Comment by kunaltyagi** [comment]
It's alright @ueqri , everyone has pushed hot-fixes because we aren't computers ourselves.

**Comment by kunaltyagi** [comment]
Merging because I need to verify doc pipeline soon

**Comment by ueqri** [comment]
Thank you very much, I'd be online to help monitor the behaviors of the new pipeline.

**Comment by ueqri** [comment]
As [Azure Dashboard](https://dev.azure.com/PointCloudLibrary/pcl/_build?view=runs) shows, the new docs pipeline seems to work well for push/PR of code changes:grinning:. To test doc changes, I could fix some small typo in `doc/` I've found before. Or, do you have another recommendation for testing? I'm pleased to do it.:blush:

**Comment by kunaltyagi** [comment]
Typos or minor fixes will be fine :)

**Pull request merged**
