### PR TITLE
Remove unused `NCVPyramid`

### PR DESCRIPTION
**Pull request by SunBlack**
Found this class which has the notice `Attention Work in progress!` since 2012. As everything is within `#if 0` and the file is not mentioned in any CMakeList, so it was never part of the install step, we can remove the file directly.

### CODE REVIEW

**Comment by mvieth** [comment]
Does the class/do the files cause any immediate problems? Otherwise I see no reason to delete them. If we keep them, someone might find them useful one day as a starting point, or even make the class fully functional (slim chances for the latter, I know :smile:)

> the file is not mentioned in any CMakeList, so it was never part of the install step

This is not quite true, the files are covered by globbing expressions: https://github.com/PointCloudLibrary/pcl/blob/master/gpu/people/CMakeLists.txt

**Comment by SunBlack** [comment]
Ah damn: Things you shouldn't do: Using `file(GLOB...)`, so we need to check if the files is getting installed and if yes thing about to keep the file or to deprecate it. The thing about `#if 0` is, that this code which you will always see during refactoring and is not checked by the compiler, so this is code you usually keep via code snippets or git history. But maybe on the current position it is more visible.

**Comment by mvieth** [comment]
I tested and yes, NCVPyramid.hpp is installed as a header file, and NCVPyramid.cu is part of libpcl_gpu_people.so

> so this is code you usually keep via code snippets or git history. But maybe on the current position it is more visible

I agree: If the files are deleted, I would pretty much consider them lost. Even they can theoretically be recovered using git, you would have to _know_ they were there ...

**Comment by mvieth** [comment]
@SunBlack How should we proceed here? Are you okay with keeping the files unchanged (and closing this pull request)?

**Comment by SunBlack** [comment]
In principle, yes, the question would be whether we want to discuss somewhere in general how to deal with such a code. Unfortunately, I haven't had a moment to test whether the code compiles when it is reactivated.

**Comment by mvieth** [comment]
> the question would be whether we want to discuss somewhere in general how to deal with such a code. 

You mean code that is not checked by the compiler, because it is commented out or in a `#if 0 ... #endif`? I would say it makes sense to keep such code if it might still be useful, e.g. a class or feature that is not yet finished, and to remove such code if e.g. it has been replaced by something else. If someone reactivates such code, they will have to make sure it compiles and is up to coding standards, otherwise their pull request won't be merged. That means that we should automate code checks (compiler warnings, clang-tidy, ...) as much as possible.
If you would like a broader discussion about such "deactivated" code, feel free to open an issue of course :smile:

**Pull request closed without merging**
