### PR TITLE
Some improvements to gpu/segmentation

### PR DESCRIPTION
**Pull request by mvieth**
- move implementation of economical_download to hpp file, fixes https://github.com/PointCloudLibrary/pcl/issues/5791
- add necessary template parameter in example
- const reference in for loop to avoid copies

### CODE REVIEW

**Comment by larshg** [comment]
Alternatively we could add PCL_EXPORTS in front of the economical_download and keep the implementation in the cpp file.

For the example, you could also just include:
#include <pcl/gpu/containers/device_array.h>
#include <pcl/gpu/segmentation/gpu_extract_clusters.h>

and not the .hpp files.

But if one needs the hpp files, the EXPORT is still required, so we should add it.

Last thing for the example, I added after the reading of the point cloud:

pcl::Indices nanVals;
pcl::removeNaNFromPointCloud(*cloud_filtered, *cloud_filtered, nanVals);

Or it (Kdtree with radius search) bailed on me, due to the point cloud containing nan values.

**Comment by mvieth** [comment]
> Alternatively we could add PCL_EXPORTS in front of the economical_download and keep the implementation in the cpp file.

I was considering that, but since `economical_download` is used only in gpu_extract_clusters.hpp and is also quite short, it made more sense to me to move it to gpu_extract_clusters.hpp. However if you like the PCL_EXPORTS solution better, I would also be fine with that.
 
> Last thing for the example, I added after the reading of the point cloud:
> 
> pcl::Indices nanVals; pcl::removeNaNFromPointCloud(*cloud_filtered, *cloud_filtered, nanVals);
> 
> Or it (Kdtree with radius search) bailed on me, due to the point cloud containing nan values.

Makes sense, I will add it. I guess I didn't have this problem because I didn't use a point cloud with nans

**Comment by larshg** [comment]
I guess it slows down downstream compiling, if they include the .hpp file (which shouldn't be need I guess, unless they run with no-precompile?
But yeah, it might be negligible so :+1:

**Review by larshg — DISMISSED** [review]

**Comment by mvieth** [comment]
You are right, I haven't considered that including the .hpp file is necessary unless PCL_EXPORTS is used. So I added PCL_EXPORTS

**Review by larshg — APPROVED** [review]

**Pull request merged**
