### PR TITLE
call cmake 'install targets' only on successful targets; fix copying header files with PCL_NO_PRECOMPILE

### PR DESCRIPTION
**Pull request by PhDittmann**
If you compile with `PCL_NO_PRECOMPILE`, several PCL components just don't have target files, which ends in errors. 

LinkErrors

When you run the INSTALL target, copying target files (lib/dll/a/o/...) fails of course. The issue is, that the header files are not copied, although the component became a header only component.

Includes

By adding the check `if(EXISTS $<TARGET_FILE:${_name}>)` the error does not affect copying the header files:

IncludeWithCheck

### CODE REVIEW

**Comment by larshg** [comment]
Hmm, I cannot reproduce this. The image about the errors shows that link.exe failed for some reason - could it be that it just didn't finished compiled/linking?

I have run with at least some of the libraries that are on the output of your image, both as dynamic and static libraries, but both times there are either dlls or lib files to copy.

What you also need to remember, is to run VS as administrator, else it doesn't have access to Program files(86).

**Comment by larshg** [comment]
I don't think its the right solution, due to targets like surface and search, will produce some libs and dll files, however it fails to link in kdtree, which should become a header only project.

I'm though unsure, how we can ensure this except for some manual flag set in CmakeLists, so we add it as a utility project rather than a dynamic / static library.

**Comment by PhDittmann** [comment]
For clarification, that's the cmake command I used:
```
cmake -DBUILD_tools=OFF -DWITH_QT=OFF -DWITH_VTK=OFF -DPCL_NO_PRECOMPILE=ON -DPCL_SHARED_LIBS=OFF -DCMAKE_INSTALL_PREFIX="install"
-DBOOST_ROOT=
-DQHULL_INCLUDE_DIRS= -DQHUL_LIBRARIES=
-DFLANN_INCLUDE_DIR= -DFLANN_LIBRARY_DEBUG_SHARED= -DFLANN_LIBRARY_DEBUG_STATIC= -DFLANN_LIBRARY_SHARED= -DFLANN_LIBRARY_STATIC=
```

I don't see a conflict with what you're saying. If the PCL component produces a library, then it still will be copied.

I also thought about introducing a manual flag, but I think it's harder to maintain then checking, if a lib came out.

**Comment by kunaltyagi** [comment]
Thoughts on `add_library(<name> INTERFACE)` for PCL_NO_PRECOMPILE?

**Comment by mvieth** [comment]
Is this a Windows-only problem? I just tried to build and install PCL with `PCL_NO_PRECOMPILE` on Ubuntu, and there weren't any errors. There are the same libraries as for a normal build (e.g. also libpcl_kdtree.so), only smaller. And I can't find any CMake commands causing that these library files are not generated. Does the compiler decide to not create any library file at all if it would practically be empty?

**Comment by larshg** [comment]
Yes I think so. If there are no classes/methods that has PCL_EXPORT infront of it, there won't be generated any .lib files. However depedant projects expect there to be a .lib file and therefore fail to link those missing .libs. Resulting in no .libs being produced.

Linux on the other hand, exports everything afaik.

**Pull request closed without merging**
