### PR TITLE
[doc] Add dependency graph via Doxygen

### LINKED ISSUE #4047: [doc] Add dependency graphs to documentation
**Is your feature request related to a problem? Please describe.**

I'm always frustrated when I can't see updated dependency graphs in the documentation, showing the actual dependencies between modules as parsed by Doxygen. (yeah right)

**Context**

Provide an updated view on dependencies not requiring delving into CMakeLists.txts or [using old images available online](https://www.researchgate.net/figure/Point-Cloud-Library-PCL-dependency-graph_fig20_284142470).

**Expected behavior**

The documentation available at https://pointcloudlibrary.github.io/documentation/modules.html could include a generated graph from the code.

**Current Behavior**

There is no graph available in the modules inside that webpage.

**Describe the solution you'd like**

There is a graph available for each module inside that webpage. Generated via Doxygen to make it "easy" as it should be available thanks to the [GROUP_GRAPHS](http://www.doxygen.nl/manual/config.html#cfg_group_graphs) configuration option which is currently enabled as well in our doxyfile.

**Describe alternatives you've considered**

It's a nice-to-have, not anything mandatory, so no other alternatives yet.

**Additional context**

This issue template is really in depth.

### PR DESCRIPTION
**Pull request by aPonza**
Tracks my progress on #4047. Currently doesn't work yet as it doesn't produce the expected output despite everything running as it should.

The expected output is what can be found [here](http://doxygen.10944.n7.nabble.com/Help-with-GROUP-GRAPHS-Option-td2756.html) (be mindful to extract directly the contents of the html folder as doing otherwise causes weird permission issues on my pc). What I'm currently seeing is a lack of what the attached groups.tar.gz has as /group__group1.png ... group__group4.png and I don't understand why yet.

Closes #4047

### CODE REVIEW

**Comment by aPonza** [comment]
Hmm, I'm not su inside Azure? Should I run the update-alternatives in the Dockerfile?

**Comment by divmadan** [comment]
For getting rid of transitivity, I used `cd build && tred pcl.dot | dot -T png > pcl.png` to process the `.dot` fil, resulting into a much cleaner graph.. 
We can change that info for the [wiki page info](https://github.com/PointCloudLibrary/pcl/wiki/FAQ_devel#current) you linked in the issue, on top of any changes that has to be done in the source files.
pcl

**Comment by kunaltyagi** [comment]
What do the colors (red, green) represent?

**Comment by aPonza** [comment]
Nice job, didn't seem like it would be cut down by much, but it is!

The zip I posted here holds a legend (which should come in our doc build as well, except it doesn't):
graph_legend

**Comment by SergioRAgostinho** [comment]
Are the plans to generate this image on the fly and host it on doxygen? If yes, could you update the url in https://pointcloudlibrary.github.io/about/ to point that one, so it gets updated automatically.

Second "nice to have" request: is it possible to have colors which are more vibrant? The color scheme for the image on the website looks better than the current one. :x

**Comment by divmadan** [comment]
> What do the colors (red, green) represent?

Manually set in the `.dot` file

```
  "examples" [style="filled" fillcolor="#D40000" shape="box"];
```

```
  "recognition" [style="filled" fillcolor="#008000" shape="box"];
```

```
...
```

**Comment by aPonza** [comment]
> Are the plans to generate this image on the fly and host it on doxygen?

This image should already be generated by doxygen right now with the modifications already in this PR, but it isn't. All the custom code to create pcl.dot shouldn't be necessary since the graph would be the output of `[common]` maybe minus the transitivity issues which Divyanshu solved (supposing the .dot product is there after a doc build).

If this PR works, I'm expecting another stage after compilation which creates the cleaned graph and pushes it to the website. An alternative would be keeping the current machinery and just opening another PR to deal with this one thing leaving that code in place.

**Comment by aPonza** [comment]
I found out:
- the graph we probably want is called collaboration graph;
- creating docs from the source code at the end of [this page](http://www.doxygen.nl/manual/grouping.html), running with a vanilla Doxyfile save for `HAVE_DOT = YES` generates said graphs for that cpp;
- having `QUIET = NO` helps debugging, of course, and through that I saw I can manage to get more graphs done by dot (up to 8714 from the 5k we currently generate, not that it's necessarily a positive, but I was hoping some of these would be the ones) by `HIDE_UNDOC_RELATIONS   = NO`, removing the layout file from doc/doxygen/ (has some references to collaboration graphs which might get set to don't show) but ultimately don't seem to give me anything I want;
- there really isn't much in the diff from a default-values-Doxyfile, and in fact I went with an almost default configuration and have seen no change in the modules, even though provoked the 8k images top I reached; (the file I used is [doxyfile.in.txt](https://github.com/PointCloudLibrary/pcl/files/4589906/doxyfile.in.txt) the config I used is a `doxygen -u doxyfile.in` on PCL's own doxyfile.in with manually changed what seemed changeable from a `doxygen -g`-generated-Doxyfile values;
- I updated the layout to reflect the most recent `doxygen -l` output even though it doesn't seem to change much at all, kept all the old "no" configurations; I'm not committing this because it removes some references to images which aren't actually displayed;
- tried https://stackoverflow.com/q/9822888/9926122 to no avail.

Not much to write home about, just to keep track of what I found and will forget.

**Comment by aPonza** [comment]
I just force pushed the removal of commits due to #4124, this isn't closed but I can't reopen at the moment due to zero actual progress.

**Pull request closed without merging**
