### PR TITLE
[Test] Add test to visualizer

### PR DESCRIPTION
**Pull request by larshg**

### CODE REVIEW

**Comment by kunaltyagi** [comment]
For running tests on the CI, will something like virtual frame buffer help?

**Comment by larshg** [comment]
I have no idea. I don't know what virtual frame buffer is :smile:

**Comment by kunaltyagi** [comment]
Oh, sorry about that. It basically emulates a desktop (without GPU). More [info at wikipedia](https://en.wikipedia.org/wiki/Xvfb)

**Comment by larshg** [comment]
That might work - though I'm unaware how  enable it on our CI's?

**Comment by kunaltyagi** [comment]
🤔 Perhaps add it to the Dockerfile and somehow launch the tests using it. I'll check if I can get some time now that my calendar seems to be opening up again 😄

**Comment by mvieth** [comment]
The test only verifies that there is no segfault, right?
Currently the visualization tests are not run on any of the Azure jobs, are they?

**Comment by larshg** [comment]
Yes and yes.

**Review by mvieth — APPROVED** [review]
Alright, the new test looks good, but we should really work on getting the visualization tests running on the CIs.

**Comment by larshg** [comment]
Created a new issue about using VFB so its not forgotten 😄

**Review by kunaltyagi — APPROVED** [review]

**Pull request merged**
