### PR TITLE
Enable Dockerfile to choose a cuda image as base image

### LINKED ISSUE #3575: Create a GPU CI job
## Your Environment

* Operating System and version: CI, default cuda version
* Compiler: nvcc
* PCL Version: HEAD

## Context
Current CI fails to take into account GPU compilation.

## Possible Solution
* adding a GPU CI job
* enabling GPU modules in CI using a gpu enabled base image

### PR DESCRIPTION
**Pull request by kunaltyagi**
Fixes #3575

### CODE REVIEW

**Comment by taketwo** [comment]
Is there a specific reason why you removed Ubuntu version parametrization? This allows building `env` images for different releases without Dockerfile modification. I'd prefer we keep it this way. And I'd even suggest you to additionally parametrize CUDA version.

**Comment by kunaltyagi** [comment]
There's no specific reason. I just modified to get it working on my setup.

**Comment by taketwo** [comment]
Thanks, looks better :+1:

Further thoughts:
1. I am not sure if we want to "unconditionally" switch to CUDA-based images. I think we may want to have separate "env" images, with and without CUDA.
2. The Dockerfile is for Ubuntu (it uses `apt-get`), so why having configurable `OS_NAME`?

**Comment by kunaltyagi** [comment]
> I am not sure if we want to "unconditionally" switch to CUDA-based images.

I don't see a negative (except the size) so I can create an arg for that.

**Comment by taketwo** [comment]
> I don't see a negative (except the size)

Another problem is that CUDA images are available only for a limited number of Ubuntu distros. For example, there is none for 19.10 (that we use on CI).

**Comment by taketwo** [comment]
Wow, I was puzzled about how exactly you were going to implement conditional base image selection. Kudos for utilizing this Bash magic.

I've pushed the newly generated `env:16.04` to Dockerhub already, so we can experiment with enabling CUDA in the CI pipeline. By the way, with this change our `env:16.04` image increased in size from 2.22 to 3.5 Gb.

Unrelated to this PR: I'm shocked about the list of packages that get installed on 19.10:

```
The following NEW packages will be installed:
  accountsservice acl adwaita-icon-theme apg apport apport-symptoms aptdaemon
  aptdaemon-data aspell aspell-en at-spi2-core autoconf automake autotools-dev
  avahi-daemon avahi-utils bind9-host binutils binutils-common
  binutils-x86-64-linux-gnu bluez bolt bsdmainutils bubblewrap build-essential
  ca-certificates cheese-common cmake cmake-data colord colord-data cpp cpp-9
  cracklib-runtime crda cups-pk-helper cython3 dbus dbus-user-session dbus-x11
  dconf-cli dconf-gsettings-backend dconf-service default-libmysqlclient-dev
  desktop-file-utils dh-python dictionaries-common dirmngr distro-info-data
  dmsetup dns-root-data dnsmasq-base dpkg-dev emacsen-common enchant
  evolution-data-server evolution-data-server-common fakeroot file fontconfig
  fontconfig-config fonts-dejavu-core fprintd freeglut3 g++ g++-9 gcc gcc-9
  gcr gdal-data gdm3 geoclue-2.0 geoip-database gettext-base gfortran
  gfortran-9 gir1.2-accountsservice-1.0 gir1.2-atk-1.0 gir1.2-atspi-2.0
  gir1.2-freedesktop gir1.2-gck-1 gir1.2-gcr-3 gir1.2-gdesktopenums-3.0
  gir1.2-gdkpixbuf-2.0 gir1.2-gdm-1.0 gir1.2-geoclue-2.0 gir1.2-glib-2.0
  gir1.2-gnomebluetooth-1.0 gir1.2-gnomedesktop-3.0 gir1.2-gtk-3.0
  gir1.2-gweather-3.0 gir1.2-ibus-1.0 gir1.2-json-1.0 gir1.2-mutter-5
  gir1.2-nm-1.0 gir1.2-nma-1.0 gir1.2-notify-0.7 gir1.2-packagekitglib-1.0
  gir1.2-pango-1.0 gir1.2-polkit-1.0 gir1.2-rsvg-2.0 gir1.2-secret-1
  gir1.2-soup-2.4 gir1.2-upowerglib-1.0 gir1.2-vte-2.91 gjs gkbd-capplet
  glib-networking glib-networking-common glib-networking-services
  gnome-control-center gnome-control-center-data gnome-control-center-faces
  gnome-desktop3-data gnome-keyring gnome-keyring-pkcs11 gnome-online-accounts
  gnome-session-bin gnome-session-common gnome-settings-daemon
  gnome-settings-daemon-common gnome-shell gnome-shell-common
  gnome-startup-applications gnome-user-docs gnupg gnupg-l10n gnupg-utils
  googletest gpg gpg-agent gpg-wks-client gpg-wks-server gpgconf gpgsm
  groff-base gsettings-desktop-schemas gstreamer1.0-clutter-3.0
  gstreamer1.0-gl gstreamer1.0-plugins-base gstreamer1.0-plugins-good
  gstreamer1.0-pulseaudio gstreamer1.0-x gtk-update-icon-cache hdf5-helpers
  hicolor-icon-theme humanity-icon-theme hunspell-en-us i965-va-driver ibus
  ibus-data ibverbs-providers icu-devtools iio-sensor-proxy im-config
  intel-media-va-driver ippusbxd iptables iso-codes iw keyboard-configuration
  kmod krb5-locales language-selector-common language-selector-gnome libaa1
  libaacs0 libaccountsservice0 libaec-dev libaec0 libalgorithm-diff-perl
  libalgorithm-diff-xs-perl libalgorithm-merge-perl libaom0 libapparmor1
  libappindicator3-1 libappstream4 libarchive13 libargon2-1 libarmadillo-dev
  libarmadillo9 libarpack2 libarpack2-dev libasan5 libasn1-8-heimdal
  libasound2 libasound2-data libasound2-plugins libaspell15 libassuan0
  libasyncns0 libatk-bridge2.0-0 libatk1.0-0 libatk1.0-data libatomic1
  libatspi2.0-0 libavahi-client3 libavahi-common-data libavahi-common3
  libavahi-core7 libavahi-glib1 libavc1394-0 libavcodec-dev libavcodec58
  libavformat-dev libavformat58 libavutil-dev libavutil56 libbdplus0
  libbind9-161 libbinutils libblas-dev libblas3 libbluetooth3 libbluray2
  libboost-date-time-dev libboost-date-time1.67-dev libboost-date-time1.67.0
  libboost-dev libboost-filesystem-dev libboost-filesystem1.67-dev
  libboost-filesystem1.67.0 libboost-iostreams-dev libboost-iostreams1.67-dev
  libboost-iostreams1.67.0 libboost-regex1.67-dev libboost-regex1.67.0
  libboost-serialization1.67-dev libboost-serialization1.67.0
  libboost-system1.67-dev libboost-system1.67.0 libboost-thread1.67.0
  libboost1.67-dev libbrotli1 libbsd0 libc-dev-bin libc6-dev libcaca0
  libcaf-openmpi-3 libcairo-gobject2 libcairo2 libcamel-1.2-62
  libcanberra-gtk3-0 libcanberra-gtk3-module libcanberra-pulse libcanberra0
  libcap2 libcap2-bin libcc1-0 libcdparanoia0 libcharls-dev libcharls2
  libcheese-gtk25 libcheese8 libchromaprint1 libclang1-8 libclutter-1.0-0
  libclutter-1.0-common libclutter-gst-3.0-0 libclutter-gtk-1.0-0
  libcoarrays-dev libcoarrays-openmpi-dev libcodec2-0.8.1 libcogl-common
  libcogl-pango20 libcogl-path20 libcogl20 libcolord-gtk1 libcolord2
  libcolorhug2 libcrack2 libcroco3 libcryptsetup12 libcups2 libcurl3-gnutls
  libcurl4 libcurl4-gnutls-dev libdaemon0 libdap-dev libdap25 libdapclient6v5
  libdapserver7v5 libdatrie1 libdbus-1-3 libdbus-glib-1-2 libdbusmenu-glib4
  libdbusmenu-gtk3-4 libdconf1 libdevmapper1.02.1 libdns1104
  libdouble-conversion3 libdpkg-perl libdrm-amdgpu1 libdrm-common libdrm-dev
  libdrm-intel1 libdrm-nouveau2 libdrm-radeon1 libdrm2 libdv4
  libebackend-1.2-10 libebook-1.2-20 libebook-contacts-1.2-3 libecal-2.0-1
  libedata-book-1.2-26 libedata-cal-2.0-1 libedataserver-1.2-24
  libedataserverui-1.2-2 libedit2 libegl-mesa0 libegl1 libeigen3-dev libelf1
  libenchant1c2a libepoxy0 libepsilon-dev libepsilon1 libevdev2 libevent-2.1-6
  libevent-core-2.1-6 libevent-pthreads-2.1-6 libexif12 libexpat1
  libexpat1-dev libfabric1 libfakeroot libfile-fcntllock-perl libflac8
  libflann-dev libflann1.9 libfontconfig1 libfontconfig1-dev libfontenc1
  libfprint0 libfreetype6 libfreetype6-dev libfreexl-dev libfreexl1
  libfribidi0 libfyba-dev libfyba0 libgbm1 libgcc-9-dev libgck-1-0
  libgcr-base-3-1 libgcr-ui-3-1 libgd3 libgdal-dev libgdal20 libgdata-common
  libgdata22 libgdbm-compat4 libgdbm6 libgdk-pixbuf2.0-0 libgdk-pixbuf2.0-bin
  libgdk-pixbuf2.0-common libgdm1 libgee-0.8-2 libgeoclue-2-0 libgeocode-glib0
  libgeoip1 libgeos-3.7.2 libgeos-c1v5 libgeos-dev libgeotiff-dev libgeotiff2
  libgfortran-9-dev libgfortran5 libgif-dev libgif7 libgirepository-1.0-1
  libgjs0g libgl1 libgl1-mesa-dev libgl1-mesa-dri libgl2ps-dev libgl2ps1.4
  libglapi-mesa libgles1 libgles2 libglew-dev libglew2.1 libglib2.0-0
  libglib2.0-bin libglib2.0-data libglu1-mesa libglu1-mesa-dev
  libglvnd-core-dev libglvnd-dev libglvnd0 libglx-mesa0 libglx0 libgme0
  libgnome-autoar-0-0 libgnome-bluetooth13 libgnome-desktop-3-18
  libgnomekbd-common libgnomekbd8 libgoa-1.0-0b libgoa-1.0-common
  libgoa-backend-1.0-1 libgomp1 libgphoto2-6 libgphoto2-l10n libgphoto2-port12
  libgpm2 libgraphene-1.0-0 libgraphite2-3 libgsm1 libgsound0 libgssapi-krb5-2
  libgssapi3-heimdal libgssdp-1.2-0 libgstreamer-gl1.0-0
  libgstreamer-plugins-base1.0-0 libgstreamer-plugins-good1.0-0
  libgstreamer1.0-0 libgtest-dev libgtk-3-0 libgtk-3-bin libgtk-3-common
  libgtop-2.0-11 libgtop2-common libgudev-1.0-0 libgupnp-1.2-0
  libgupnp-av-1.0-2 libgupnp-dlna-2.0-3 libgusb2 libgweather-3-15
  libgweather-common libharfbuzz-icu0 libharfbuzz0b libhcrypto4-heimdal
  libhdf4-0-alt libhdf4-alt-dev libhdf5-103 libhdf5-cpp-103 libhdf5-dev
  libhdf5-mpi-dev libhdf5-openmpi-103 libhdf5-openmpi-dev libheimbase1-heimdal
  libheimntlm0-heimdal libhunspell-1.7-0 libhwloc-dev libhwloc-plugins
  libhwloc5 libhx509-5-heimdal libhyphen0 libibus-1.0-5 libibverbs-dev
  libibverbs1 libical3 libice-dev libice6 libicu-dev libicu63 libidn11
  libiec61883-0 libieee1284-3 libigdgmm11 libimobiledevice6 libinput-bin
  libinput10 libip4tc2 libip6tc2 libiptc0 libisc1100 libisccc161 libisccfg163
  libisl21 libitm1 libjack-jackd2-0 libjansson4 libjavascriptcoregtk-4.0-18
  libjbig-dev libjbig0 libjpeg-dev libjpeg-turbo8 libjpeg-turbo8-dev libjpeg8
  libjpeg8-dev libjson-c-dev libjson-c4 libjson-glib-1.0-0
  libjson-glib-1.0-common libjsoncpp-dev libjsoncpp1 libk5crypto3 libkeyutils1
  libkml-dev libkmlbase1 libkmlconvenience1 libkmldom1 libkmlengine1
  libkmlregionator1 libkmlxsd1 libkmod2 libkrb5-26-heimdal libkrb5-3
  libkrb5support0 libksba8 liblapack-dev liblapack3 liblcms2-2 libldap-2.4-2
  libldap-common libldb1 libllvm8 libllvm9 liblmdb0 liblocale-gettext-perl
  liblsan0 libltdl-dev libltdl7 liblwres161 liblz4-dev liblzma-dev
  libmagic-mgc libmagic1 libmbim-glib4 libmbim-proxy libmediaart-2.0-0
  libminizip-dev libminizip1 libmm-glib0 libmnl0 libmozjs-60-0 libmp3lame0
  libmpc3 libmpdec2 libmpfr6 libmpg123-0 libmtdev1 libmutter-5-0
  libmysqlclient-dev libmysqlclient21 libndp0 libnetcdf-c++4
  libnetcdf-cxx-legacy-dev libnetcdf-dev libnetcdf13 libnetfilter-conntrack3
  libnewt0.52 libnfnetlink0 libnftnl11 libnghttp2-14 libnl-3-200 libnl-3-dev
  libnl-genl-3-200 libnl-route-3-200 libnl-route-3-dev libnm0 libnma0
  libnotify4 libnpth0 libnspr4 libnss-mdns libnss-systemd libnss3 libnuma-dev
  libnuma1 liboauth0 libodbc1 libogdi-dev libogdi4.1 libogg-dev libogg0
  libopengl0 libopenjp2-7 libopenjp2-7-dev libopenmpi-dev libopenmpi3
  libopenmpt0 libopenni-dev libopenni-sensor-pointclouds0 libopenni0
  libopenni2-0 libopenni2-dev libopus0 liborc-0.4-0 libpackagekit-glib2-18
  libpam-cap libpam-fprintd libpam-gnome-keyring libpam-systemd libpango-1.0-0
  libpangocairo-1.0-0 libpangoft2-1.0-0 libpangoxft-1.0-0 libpcap0.8 libpci3
  libpciaccess0 libpcre16-3 libpcre2-16-0 libpcre3-dev libpcre32-3
  libpcrecpp0v5 libpcsclite1 libperl5.28 libphonenumber7 libpipeline1
  libpixman-1-0 libplist3 libpmix2 libpng-dev libpng-tools libpng16-16
  libpolkit-agent-1-0 libpolkit-gobject-1-0 libpoppler-dev
  libpoppler-private-dev libpoppler90 libpopt0 libpq-dev libpq5 libproj-dev
  libproj13 libprotobuf17 libproxy1v5 libpsl5 libpsm-infinipath1 libpsm2-2
  libpthread-stubs0-dev libpulse-mainloop-glib0 libpulse0 libpulsedsp
  libpwquality-common libpwquality1 libpython3-dev libpython3-stdlib
  libpython3.7 libpython3.7-dev libpython3.7-minimal libpython3.7-stdlib
  libqhull-dev libqhull-r7 libqhull7 libqmi-glib5 libqmi-proxy
  libqt5concurrent5 libqt5core5a libqt5dbus5 libqt5designer5
  libqt5designercomponents5 libqt5gui5 libqt5help5 libqt5network5
  libqt5opengl5 libqt5opengl5-dev libqt5positioning5 libqt5printsupport5
  libqt5qml5 libqt5quick5 libqt5quickparticles5 libqt5quickshapes5
  libqt5quicktest5 libqt5quickwidgets5 libqt5sensors5 libqt5sql5
  libqt5sql5-sqlite libqt5svg5 libqt5test5 libqt5webchannel5 libqt5webkit5
  libqt5webkit5-dev libqt5widgets5 libqt5x11extras5 libqt5xml5 libquadmath0
  libraw1394-11 librdmacm1 libreadline8 librest-0.7-0 librhash0
  libroken18-heimdal librsvg2-2 librsvg2-common librtmp1 librygel-core-2.6-2
  librygel-db-2.6-2 librygel-renderer-2.6-2 librygel-server-2.6-2
  libsamplerate0 libsane libsane-common libsasl2-2 libsasl2-modules
  libsasl2-modules-db libsbc1 libsecret-1-0 libsecret-common libsensors-config
  libsensors5 libshine3 libshout3 libsigsegv2 libslang2 libsm-dev libsm6
  libsmbclient libsnapd-glib1 libsnappy1v5 libsndfile1 libsnmp-base libsnmp30
  libsodium23 libsoup-gnome2.4-1 libsoup2.4-1 libsoxr0 libspatialite-dev
  libspatialite7 libspeex1 libspeexdsp1 libsqlite3-0 libsqlite3-dev libssh-4
  libssh-gcrypt-4 libssl-dev libssl1.1 libstartup-notification0
  libstdc++-9-dev libstemmer0d libsuperlu-dev libsuperlu5 libswresample-dev
  libswresample3 libswscale-dev libswscale5 libsz2 libtag1v5 libtag1v5-vanilla
  libtalloc2 libtcl8.6 libtdb1 libteamdctl0 libtevent0 libtext-iconv-perl
  libthai-data libthai0 libtheora-dev libtheora0 libtiff-dev libtiff5
  libtiffxx5 libtinyxml2.6.2v5 libtk8.6 libtool libtsan0 libtwolame0 libubsan1
  libuchardet0 libudisks2-0 libunwind8 libupower-glib3 liburiparser-dev
  liburiparser1 libusb-1.0-0 libusb-1.0-0-dev libusb-1.0-doc libusbmuxd4
  libutempter0 libuv1 libv4l-0 libv4lconvert0 libva-drm2 libva-x11-2 libva2
  libvdpau1 libvisual-0.4-0 libvorbis0a libvorbisenc2 libvorbisfile3 libvpx6
  libvte-2.91-0 libvte-2.91-common libvtk7-dev libvtk7-java libvtk7-jni
  libvtk7-qt-dev libvtk7.1 libvtk7.1-qt libvulkan-dev libvulkan1 libwacom-bin
  libwacom-common libwacom2 libwavpack1 libwayland-client0 libwayland-cursor0
  libwayland-egl1 libwayland-server0 libwbclient0 libwebkit2gtk-4.0-37
  libwebp-dev libwebp6 libwebpdemux2 libwebpmux3 libwebrtc-audio-processing1
  libwhoopsie-preferences0 libwhoopsie0 libwind0-heimdal libwoff1 libwrap0
  libx11-6 libx11-data libx11-dev libx11-xcb-dev libx11-xcb1 libx264-155
  libx265-176 libxatracker2 libxau-dev libxau6 libxaw7 libxcb-dri2-0
  libxcb-dri2-0-dev libxcb-dri3-0 libxcb-dri3-dev libxcb-glx0 libxcb-glx0-dev
  libxcb-icccm4 libxcb-image0 libxcb-keysyms1 libxcb-present-dev
  libxcb-present0 libxcb-randr0 libxcb-randr0-dev libxcb-render-util0
  libxcb-render0 libxcb-render0-dev libxcb-res0 libxcb-shape0
  libxcb-shape0-dev libxcb-shm0 libxcb-sync-dev libxcb-sync1 libxcb-util1
  libxcb-xfixes0 libxcb-xfixes0-dev libxcb-xinerama0 libxcb-xinput0
  libxcb-xkb1 libxcb-xv0 libxcb1 libxcb1-dev libxcomposite1 libxcursor1
  libxdamage-dev libxdamage1 libxdmcp-dev libxdmcp6 libxerces-c-dev
  libxerces-c3.2 libxext-dev libxext6 libxfixes-dev libxfixes3 libxfont2
  libxft-dev libxft2 libxi6 libxinerama1 libxkbcommon-x11-0 libxkbcommon0
  libxkbfile1 libxklavier16 libxml2 libxml2-dev libxmu6 libxmuu1 libxpm4
  libxrandr2 libxrender-dev libxrender1 libxshmfence-dev libxshmfence1
  libxslt1.1 libxss-dev libxss1 libxt-dev libxt6 libxtables12 libxtst6 libxv1
  libxvidcore4 libxvmc1 libxxf86dga1 libxxf86vm-dev libxxf86vm1 libyaml-0-2
  libyelp0 libzstd-dev libzvbi-common libzvbi0 linux-libc-dev lsb-release m4
  make man-db manpages manpages-dev mesa-common-dev mesa-va-drivers
  mesa-vdpau-drivers mesa-vulkan-drivers mime-support
  mobile-broadband-provider-info modemmanager mousetweaks mpi-default-bin
  mpi-default-dev mutter mutter-common mysql-common netbase network-manager
  network-manager-gnome network-manager-pptp networkd-dispatcher
  ocl-icd-libopencl1 odbcinst odbcinst1debian2 openmpi-bin openmpi-common
  openni-utils openssh-client openssl p11-kit p11-kit-modules packagekit
  packagekit-tools patch perl perl-modules-5.28 pinentry-curses
  pinentry-gnome3 pkg-config policykit-1 poppler-data ppp pptp-linux proj-bin
  proj-data publicsuffix pulseaudio pulseaudio-module-bluetooth
  pulseaudio-utils python-apt-common python3 python3-apport python3-apt
  python3-aptdaemon python3-aptdaemon.gtk3widgets python3-asn1crypto
  python3-attr python3-autobahn python3-automat python3-blinker python3-cairo
  python3-cbor python3-certifi python3-cffi-backend python3-chardet
  python3-click python3-colorama python3-constantly python3-cryptography
  python3-cups python3-cupshelpers python3-dbus python3-defer python3-dev
  python3-distro python3-distutils python3-entrypoints python3-gi
  python3-httplib2 python3-hyperlink python3-idna python3-incremental
  python3-jwt python3-keyring python3-launchpadlib python3-lazr.restfulclient
  python3-lazr.uri python3-lib2to3 python3-lz4 python3-macaroonbakery
  python3-minimal python3-mpi4py python3-nacl python3-oauthlib python3-openssl
  python3-pkg-resources python3-png python3-problem-report python3-protobuf
  python3-pyasn1 python3-pyasn1-modules python3-pymacaroons python3-pyqrcode
  python3-requests python3-requests-unixsocket python3-rfc3339
  python3-secretstorage python3-service-identity python3-simplejson
  python3-six python3-snappy python3-systemd python3-talloc python3-trie
  python3-twisted python3-twisted-bin python3-txaio python3-tz
  python3-u-msgpack python3-ubjson python3-urllib3 python3-vtk7
  python3-wadllib python3-wsaccel python3-zope.interface python3.7
  python3.7-dev python3.7-minimal qdoc-qt5 qhelpgenerator-qt5 qt5-assistant
  qt5-gtk-platformtheme qt5-qmake qt5-qmake-bin qt5-qmltooling-plugins
  qtattributionsscanner-qt5 qtbase5-dev qtbase5-dev-tools qtchooser
  qtdeclarative5-dev qtdeclarative5-dev-tools qttools5-dev qttools5-dev-tools
  qttools5-private-dev qttranslations5-l10n readline-common rtkit rygel
  samba-libs sane-utils session-migration shared-mime-info
  sound-theme-freedesktop switcheroo-control system-config-printer
  system-config-printer-common system-config-printer-udev systemd systemd-sysv
  tcl tcl-dev tcl-vtk7 tcl8.6 tcl8.6-dev tk tk-dev tk8.6 tk8.6-dev tzdata
  ubuntu-docs ubuntu-mono ubuntu-session ubuntu-system-service
  ubuntu-wallpapers ubuntu-wallpapers-eoan ucf udev unixodbc-dev unzip
  update-inetd upower usb-modeswitch usb-modeswitch-data usbmuxd uuid-dev
  va-driver-all vdpau-driver-all vtk7 wamerican wget whoopsie-preferences
  wireless-regdb wpasupplicant x11-common x11-utils x11-xkb-utils
  x11-xserver-utils x11proto-core-dev x11proto-damage-dev x11proto-dev
  x11proto-fixes-dev x11proto-scrnsaver-dev x11proto-xext-dev
  x11proto-xf86vidmode-dev xauth xbitmaps xdg-dbus-proxy xdg-user-dirs
  xfonts-base xfonts-encodings xfonts-utils xkb-data xorg-sgml-doctools
  xserver-common xserver-xephyr xserver-xorg xserver-xorg-core
  xserver-xorg-input-all xserver-xorg-input-libinput xserver-xorg-input-wacom
  xserver-xorg-legacy xserver-xorg-video-all xserver-xorg-video-amdgpu
  xserver-xorg-video-ati xserver-xorg-video-fbdev xserver-xorg-video-intel
  xserver-xorg-video-nouveau xserver-xorg-video-qxl xserver-xorg-video-radeon
  xserver-xorg-video-vesa xserver-xorg-video-vmware xterm xtrans-dev xwayland
  xz-utils yaru-theme-gnome-shell yelp yelp-xsl zenity zenity-common
  zlib1g-dev
```

`evolution-data-server`? `yelp`? `network-manager-gnome`? What?!

**Comment by kunaltyagi** [comment]
> I'm shocked about the list of packages that get installed on 19.10

That's both sad and hilarious at the same time.

> image increased in size from 2.22 to 3.5 Gb

Expected. CUDA has 2 big layers, about 700MB (Mb?) each, so that's about right

**Comment by taketwo** [comment]
Sorry, correction, I've only started to push. It will take forever to finish.

**Comment by kunaltyagi** [comment]
No issues, none at all

**Pull request merged**
