### PR TITLE
Silent CMake warnings about quoted variables

### PR DESCRIPTION
**Pull request by VictorLamoine**
To globally fix #1095

### CODE REVIEW

**Comment by taketwo** [comment]
I think it should go into it's own `if` clause. Further, a small comment would be nice. Finally, what about adding back quotes removed in #1095?

**Comment by VictorLamoine** [comment]
Ok for the own `if` and comment.

I see no points in adding back the quotes; I don't know why they changed this  behavior but maybe one day it will be forbidden to quote the variables.

**Comment by taketwo** [comment]
Ok

**Comment by VictorLamoine** [comment]
Done

**Comment by taketwo** [comment]
Thanks!

**Pull request merged**
