### PR TITLE
Drop code for MSVC 2013 and below

### PR DESCRIPTION
**Pull request by SunBlack**

### CODE REVIEW

**Comment by SunBlack** [comment]
> What do you think about this file? Do you think `MSVC_2010_FIX` is still necessary?
> https://github.com/PointCloudLibrary/pcl/blob/pcl-1.9.1/surface/include/pcl/surface/3rdparty/poisson4/binary_node.h

No idea. This code is enabled for all platform, so it's not MSVC specific and we don't touch 3rdParty code so I don't really care about this ;).

**Comment by UnaNancyOwen** [comment]
@SunBlack Thanks!

**Comment by SunBlack** [comment]
Other question is if we really still need `GTEST_USE_OWN_TR1_TUPLE` - current googletest code seems not to use this define anymore. But I think this is something for another MR.

**Comment by UnaNancyOwen** [comment]
> current googletest code seems not to use this define anymore. 

Are googletests that are not using <code>GTEST_USE_OWN_TR1_TUPLE</code> already released?
If not released, I think that it should not yet remove.

**Comment by SunBlack** [comment]
Moved discussion about this into separate issue (#2824)

**Pull request merged**
