### PR TITLE
Remove WIN32 or replace with _WIN32

### LINKED ISSUE #3670: WIN32 instead of _WIN32 used in PCL
## Your Environment

* Operating System and version: Windows
* PCL Version: HEAD

## Context
Accidentally `WIN32` and `WIN64` has been used for Windows OS detection instead of `_WIN32` and `_WIN64` (notice the underscore)

## Possible Solution
* Replacement of `WIN32` with `_WIN32`
* Compile test
* Behavior verification

### PR DESCRIPTION
**Pull request by larshg**
Fixes #3670.

### CODE REVIEW

**Comment by larshg** [comment]
I haven't modified 3. party files. Should we do this?

**Comment by larshg** [comment]
its defined in the "default" values, so it might be a default from CMake. So we have to manually remove it maybe.
https://github.com/PointCloudLibrary/pcl/blob/14de3bea4869ac66f48e6815de9ae0402552a59d/CMakeLists.txt#L66

I'll have a look at it, next time.

**Comment by kunaltyagi** [comment]
Searching `CMAKE_CXX_FLAGS_DEFAULT` shows no such variable in CMake (and PCL as one of the top results)

**Comment by SergioRAgostinho** [comment]
> Are we still defining `WIN32` in CMake? Would it be a behavior change if we stop defining that?

Technically we could break user code if the user followed the same bad practice as "we did". I'm tempted to strip it out as pray.

**Comment by larshg** [comment]
Its rather troublesome to remove some of the default flags, but its doable. See this [SO](https://stackoverflow.com/questions/45995784/how-to-set-compiler-options-with-cmake-in-visual-studio-2017/46000520#46000520) about changing /w3 to /w4.
Even if we remove it from PCL, if people use CMake to generate their projects, they will still have WIN32 defined.

**Pull request merged**
