### PR TITLE
Refactor visualizer and point type conversion, fix numerous warnings

### PR DESCRIPTION
**Pull request by denix56**
This pull request aimed at fixing warnings, adding generic function for point and pointcloud conversion, improving the performance of the PCL Visualizer
If you have any additional propositions, especially about visualizer, please let me know.

### CODE REVIEW

**Comment by SergioRAgostinho** [comment]
Some pointers:
-  Your PRs need to be clean compared to master. If you want to have the lastest changes from master, you need to rebase your commit with master, not merge it.
- Don't change indentation on code which you didn't specifically change. Otherwise running `git blame` will become useless.
- One PR for each topic, otherwise reviewing is cumbersome and (even) slow(er).

**Comment by denix56** [comment]
@SergioRAgostinho ok, I got it. I fixed indention, and become more familiar with git rebase :)

**Comment by denix56** [comment]
Should I close this pull request and split it in multiples ones?

**Comment by SergioRAgostinho** [comment]
Leave this open for now, and open the multiple ones which will act as a replacement. Don't forget to make clean changes over HEAD, so no merge commits or commits from PRs pending to be merged to master.

**Pull request closed without merging**
