### PR TITLE
Reverts #1084

### PR DESCRIPTION
**Pull request by jspricke**

### CODE REVIEW

**Comment by jspricke** [comment]
As discussed with @gedikli this reverts #1084 and adds a comment.

**Comment by taketwo** [comment]
@soyersoyer FYI

**Comment by soyersoyer** [comment]
Could you explain why is it necessary?

What I think:
At the time when the destructor's lock.unlock() unlocks the mutex, the running thread maybe 
* running some code between lines 125-129
* waiting at line 133
* waiting at line 141/143

The first case, after locking the mutex, it checks the quit_ and ends the loop.
The second case, the destructor wakes up the thread (with the cv's notify), so the thread can check the quit_ and break
The third case is the same as the second.

**Comment by gedikli** [comment]
The revert was for the original pull request:
https://github.com/soyersoyer/pcl/blob/6c02167896df2aa1a4bb933edb3653ca68f43b78/common/src/time_trigger.cpp
... and that's clearly wrong.

thread1: 72-74
thread2: 130-131
thread1: 75
thread2: 132
thread1: 77

Thus thread1 fired the notification before thread2 got into the wait state -> misses it and will wait afterwards forever.
thread1 tries to join thread2 and waits forever.

But by adding the if(quit_) after the wait call, this should behave correct again: https://github.com/PointCloudLibrary/pcl/blob/049a36a169292a844127ca438ad41317098d2d39/common/src/time_trigger.cpp

-Suat

**Comment by gedikli** [comment]
I would propose to use your version with ALL the changes: 
https://github.com/PointCloudLibrary/pcl/blob/049a36a169292a844127ca438ad41317098d2d39/common/src/time_trigger.cpp
with or without lock.unlock before notify_all.

Since this solves another race condition i found right now in my initial implementation:
https://github.com/PointCloudLibrary/pcl/blob/c1022f646479d7a45d51af878f7e38642a96255c/common/src/time_trigger.cpp
thread2 129
thread1: 72-77
thread2: 130-132
Similar issue as described above: thread1 is at line 77 and waits thread2 to finish
thread2 misses the notification and then waits without checking whether the object is about to be destroyed -> need to check quit_ before wait and within lock.
@soyersoyer : #1084 + if(quit_ within lock before wait) together should solve this problem without introducing a new race condition.
-Suat

**Pull request merged**
