### PR TITLE
Kinect2Grabber with example

### PR DESCRIPTION
**Pull request by giacomodabisias**
This is a grabber for the kinect v2. Since libfreenect2 is still in development I created a preliminary version of the grabber with an example as app instead of inserting it in IO. The grabber produces 512x424 clouds, but I am planning to create clouds of dynamic dimensions. The support for it is already available in the code, but I have to make some fixes. The cloud is already registered, if the correct calibration is provided. There is the possibility to calibrate the kinectv2 using the grabber, by providing a set or depth/rgb images. I add also my own calibration files even if the grabber supports calibration.

### CODE REVIEW

**Comment by aurelw** [comment]
Any news/progress on this?

**Comment by giacomodabisias** [comment]
I added cuda support for the registration and cloud creation, but I have currently no time to adapt the grabber to the pcl interface. There is a minor problem also with the distortion which I will fix soon. I made the depth->rob registration, but I have an alignment problem with the rgb-> depth registration (this would remove some shadows). I added an interface to obtain organized clouds and one for cloud with non Nans.  If anyone is interested in working on it or helping integrating it let me know; you are more than welcome

**Comment by aurelw** [comment]
I can help with on integrating it. And also with calibration issues, but I guess you are already in very deep on this subject. I can do the dirty work with the interface. As I mentioned before, imho it would be good to have as much as possible of the calibration handled by libfreenect2.

Personally, I am involved in a project where I would need a libfreenect2 grabber soon (with working RGB registration). I am also currently looking for a job and at 2/4 companies I have visited so far I would need to create a libfreenect2 grabber anyways ;)

**Comment by giacomodabisias** [comment]
Ok perfect, we can work in it :) . Contact me at giacomo(dot)dabisias(at)gmail(dot)com.

**Comment by giacomodabisias** [comment]
Hi,
Is there any news?

**Comment by giacomodabisias** [comment]
I think we can close since there is #1410

**Pull request closed without merging**
