### PR TITLE
Use `emplace_back` instead of `push_back`

### PR DESCRIPTION
**Pull request by DIlkhush00**

### CODE REVIEW

**Comment by DIlkhush00** [comment]
@larshg  @mvieth , I am not sure but did the build fail because of the spacing between the `emplace_back` and it's opening bracket `(` ?

**Comment by larshg** [comment]
> @larshg @mvieth , I am not sure but did the build fail because of the spacing between the `emplace_back` and it's opening bracket `(` ?

Yes, its our code format that rejects it. So you need to remove the spaces.

**Comment by larshg** [comment]
You can use the patch generated here: https://dev.azure.com/PointCloudLibrary/pcl/_build/results?buildId=24754&view=artifacts&pathAsName=false&type=publishedArtifacts

**Comment by DIlkhush00** [comment]
Thanks, I shall correct them in all places

**Comment by mvieth** [comment]
@DIlkhush00 There are unfortunately still a few formatting issues left, see: https://dev.azure.com/PointCloudLibrary/pcl/_build/results?buildId=24755&view=logs&j=84ba2080-ade3-55e3-f209-94ce73f9d406&t=9838d42f-a715-5615-242f-7e73bf03078b (so just a different indentation)

**Comment by DIlkhush00** [comment]
Fixed. I hope everything's good now 🙂

**Comment by larshg** [comment]
Looks good 👍

**Review by mvieth — APPROVED** [review]
Thanks!

**Pull request merged**
