### PR TITLE
[CMAKE] Tiny useless change.

### PR DESCRIPTION
**Pull request by frozar**
The only purpose of this merge request is to test the Travis check against the current master branch.

### CODE REVIEW

**Comment by frozar** [comment]
@taketwo : I'm pretty sad. On this merge request, you can see that Travis check doesn't pass, even on the current master branch. In [the Travis documentation](https://docs.travis-ci.com/user/customizing-the-build#Build-Timeouts), they say that a job have 50 min to run. Recent, I'm pretty sure that something has change on the amazon server where the jobs are executed, and the `build-tools` job takes a bit longer, just enough to timeout.

What do you think about it? And what should be done?

**Comment by taketwo** [comment]
We had a lot of troubles with this time limit in the past, and we have tried different approaches to circumvent this problem. Lately, @SergioRAgostinho was experimenting with using _ccache_ (#1892), however if I understand correctly, this did not bring much of an improvement. So right now it's not clear what should be done and I'm afraid we will have to live with this for a while.

**Comment by frozar** [comment]
Ok, I see that it's not a new problem. I close this useless merge request...

**Comment by SergioRAgostinho** [comment]
If you want to work on it I suggest creating a Travis account and running the ci tests on your local fork. That way we won't get flooded with all the test commits (I had really a lot till I got things going).

**Comment by frozar** [comment]
Thank for the advice. In fact, I don't want to work on it, but keep a functionnal continous integration system is pretty useful ^^'

**Pull request closed without merging**
