### PR TITLE
Adding CUDA and GPU modules to CI

### LINKED ISSUE #3575: Create a GPU CI job
## Your Environment

* Operating System and version: CI, default cuda version
* Compiler: nvcc
* PCL Version: HEAD

## Context
Current CI fails to take into account GPU compilation.

## Possible Solution
* adding a GPU CI job
* enabling GPU modules in CI using a gpu enabled base image

### PR DESCRIPTION
**Pull request by kunaltyagi**
Actually closes #3575

### CODE REVIEW

**Comment by kunaltyagi** [comment]
CUDA 9 throws error asking for a C++14 flag. That's never been an issue

**Comment by taketwo** [comment]
Maybe has something to do with the ancient CMake version?

**Comment by kunaltyagi** [comment]
That wasn't an issue before. Did adding nvcc make it an issue? Maybe the old nvcc doesn't support c++14.

**Comment by taketwo** [comment]
What if we put this on hold until 20.04 is released? nVidia will certainly distribute a CUDA Docker image for it. Then we'll replace our 19-10 job with 20-04/CUDA job.

**Comment by kunaltyagi** [comment]
This shows that PCL doesn't support CUDA 9 on 16.04 at least. Is there a supported platform list where we can update this info?

BTW, 16.04 has [cuda 7.5](https://packages.ubuntu.com/xenial/nvidia-cuda-dev) so that basically means we dont support GPU on 16.04 (unless we move to a cuda version high enough)

**Comment by taketwo** [comment]
> Is there a supported platform list where we can update this info?

Unfortunately, there is none. I wanted to include a list of minimum required versions in the release notes but forgot. It should be possible to put together such a list by grepping for `Bump .* version`" items in the changelog.

> BTW, 16.04 has cuda 7.5 

Does anyone install CUDA SDK from `apt-get` :laughing: 

> This shows that PCL doesn't support CUDA 9 on 16.04 at least

I wouldn't rule this out completely. Maybe it's possible to get it to work with `-DCUDA_HOST_COMPILER=...` as you suggested.

**Comment by taketwo** [comment]
OK, how about a new 18-04/CUDA10 job? (Temporary until 20.04)

**Comment by kunaltyagi** [comment]
> how about a new 18-04/CUDA10 job? (Temporary until 20.04)

Does it mean that we replace
1. 18.04 with 20.04 or
2. 18.04 and 16.04 with 20.04?

Just clarifying I'm ok with the suggestion.

**Comment by taketwo** [comment]
I mean that until the next Ubuntu release we have:
 * Ubuntu 16.04
 * Ubuntu 18.04/CUDA
 * Ubuntu 19.10

After the release we have:
 * Ubuntu 16.04
 * Ubuntu 20.04/CUDA

Generally, the idea is to have two Ubuntu jobs. One with the baseline release and one with the most up-to-date.

**Comment by SunBlack** [comment]
> OK, how about a new 18-04/CUDA10 job? (Temporary until 20.04)

Bad idea. I'm currently trying it, but I get
```
In file included from /home/sunblack/dev/pcl/common/include/pcl/pcl_macros.h:75:
/usr/include/eigen3/Eigen/Core:42:14: fatal error: 'math_functions.hpp' file not found
    #include <math_functions.hpp>
             ^~~~~~~~~~~~~~~~~~~~
```

This is fixed with [this commit](https://bitbucket.org/eigen/eigen/commits/034b6c3e101792a3cc3ccabd9bfaddcabe85bb58). This fixed is included since eigen 3.3.6 - but Ubuntu 18.04 [just has 3.3.4, during 19.04 already has 3.3.7](https://packages.ubuntu.com/search?suite=all&section=all&arch=any&keywords=libeigen3-dev&searchon=names). So we should use an older CUDA version on 16.04/18.04 build.

**Comment by taketwo** [comment]
So Ubuntu 20.04/CUDA will be problematic as well due to compiler version?

**Comment by kunaltyagi** [comment]
I think the issue is `CMake + GCC + CUDA`. I use a recent CMake (3.16) which can use older nvcc (the one with cuda 10.1) (since cuda lags behind everyone else) for cu files and gcc (9.2) for cpp files. This isn't possible for old cmake IIRC.

**Comment by SunBlack** [comment]
Do you know how CMake then bypass the check within `/usr/local/cuda-10.2/include/crt/host_config.h`?

**Comment by kunaltyagi** [comment]
It might be CMake inserting the flag `--compiler-bindir` to nvcc or something similar (like the `CUDA_HOST_COMPILER` option) to use 2 different gcc (since I have to provide the older gcc to CMake using the host compiler option and it discovers the latest gcc for normal compilation)

**Comment by kunaltyagi** [comment]
I'm using this [setup for cmake](https://gist.github.com/kunaltyagi/31f1c0d2c8b31afba424888274801fab)

This might explain why I miss some compile errors as well as how I can compile cuda stuff... :laughing:

**Pull request closed without merging**
