### PR TITLE
Remove explicit setting of CM0074 policy to NEW

### PR DESCRIPTION
**Pull request by shrijitsingh99**
Expanding upon #2671 
Couldn't quite understand why this was needed:
https://github.com/PointCloudLibrary/pcl/blob/8bcde6f06c94d401fc33d695eb8eac15194538c1/PCLConfig.cmake.in#L20

### CODE REVIEW

**Comment by kunaltyagi** [comment]
There's another PR working on Boost. Can't link it here

**Comment by shrijitsingh99** [comment]
> There's another PR working on Boost. Can't link it now

I had mistakenly modified the Boost dependency. Removed it.

**Comment by kunaltyagi** [comment]
> Couldn't quite understand why this was needed:

CMake considers `<module>_ROOT` variables to be used to find the CMake module called `<module>`. By hiding them with a `PCL_` prefix, 
1. we can prevent name clashes since we can assume nobody but PCL will make a module called `PCL_surface`
2. BUT other people can release modules called `surface` to find which
3. CMake will search for `surface_ROOT` and due to our 'new' naming, there will not be any confusions between `surface_ROOT` and `PCL_surface_ROOT`

**Comment by SergioRAgostinho** [comment]
> Couldn't quite understand why this was needed:

Recent versions of cmake we're at some point spewing the warning claiming that policy was not set. This [comment](https://github.com/PointCloudLibrary/pcl/pull/2671#discussion_r238203614) clarifies under which situations it is emitted. 

If you're using CMake >= 3.12 and no warning related the policy is being emitted, then it might mean that it is no longer required. Try this both for pcl and a downstream project with a cmake_minimum_required < 3.12, while using a CMake version >= 3.12.

**Comment by shrijitsingh99** [comment]
>     2. BUT other people can release modules called `surface` to find which
> 
>     3. CMake will search for `surface_ROOT` and due to our 'new' naming, there will not be any confusions between `surface_ROOT` and `PCL_surface_ROOT`

Still slightly confused. We use `BOOST_ROOT` to help CMake discover the Boost module. in `all_in`one_installer` mode. 
So why create something like `PCL_BOOST_ROOT`, what would be its purpose?

**Comment by shrijitsingh99** [comment]
I checked it out, didn't notice any CMake warnings on setting minimum version to 3.0

**Comment by kunaltyagi** [comment]
@SergioRAgostinho I'm not comfortable merging PR with CMake changes. PTAL

**Comment by SergioRAgostinho** [comment]
> I checked it out, didn't notice any CMake warnings on setting minimum version to 3.0

We might have removed the previous usage of `*_ROOT` in most finder scripts. I still see them being set in PCLConfig for PCL_ALL_IN_ONE_INSTALLER code. I would be more comfortable unsetting the policy once all situations in which  a `*_ROOT` variable is set are removed from the code base.

**Comment by kunaltyagi** [comment]
Maybe @larshg can help review the CMake code so there's more confidence in merging this

**Comment by larshg** [comment]
As I can see it, Package_ROOT variables are still used in various find scripts. And the policy is first available from 3.12. I couldn't find any information if it has been removed in later Cmake versions, but I don't get any warnings not setting the policy, running Cmake 3.19.1.
But most dependencies are also found with config files now or with find_package.

However, I don't see any reason not to keep it as it just allow CMake to look in package_ROOT directories if they are defined.
We could however remove all the XX_ROOT variables, but first when CMake 3.12 are required. If we remove the paths now, all old CMake versions that doesn't know the policy, would go with the old behavior and won't automatically look in package_ROOT folders and eventually lead to dependencies not being found.

I would close this one for now.

**Comment by kunaltyagi** [comment]
Will reopen if there's interest by original author post 3.12 requirement

**Pull request closed without merging**
