### PR TITLE
Fix potential memory problems in GICP and IncrementalRegistration

### PR DESCRIPTION
**Pull request by themightyoarfish**
The aligned operator new is surely missing due to `base_transformation_` member possibly being of type `Matrix4f`.

About the aligned vector I'm not so sure, but the `MatricesVector` which is vector of Matrix3d uses it, so either that can go away or should be used consistently.

Added the operator also to classes derived from those needing it. Never really sure about that one, but back when I tested this, this requirement seemed to be infectuious and leaving it out from child classes would fail, even though they only inherited the base class' members with alignment requirements.

### CODE REVIEW

**Comment by mvieth** [comment]
> The aligned operator new is surely missing due to `base_transformation_` member possibly being of type `Matrix4f`.

`Registration` (in registration.h), a parent class of GICP, already has the macro, which should probably suffice. Still, adding the macro to GICP shouldn't hurt, so I am okay with it (either it's necessary or it replaces the one from `Registration`).

> About the aligned vector I'm not so sure, but the `MatricesVector` which is vector of Matrix3d uses it, so either that can go away or should be used consistently.

Since it is `Matrix3d` there shouldn't be alignment problems (not a [fixed-size vectorizable object](https://eigen.tuxfamily.org/dox/group__TopicFixedSizeVectorizable.html)). I would prefer to keep `mahalanobis_` and `MatricesVector` unchanged unless we actually find a problem with it.

> Added the operator also to classes derived from those needing it. Never really sure about that one, but back when I tested this, this requirement seemed to be infectuious and leaving it out from child classes would fail, even though they only inherited the base class' members with alignment requirements.

Based on this explanation, I understand that you added it to GICP6D, but why did you also add it to icp_nl, incremental_registration, and joint_icp? They don't inherit from GICP?

**Comment by themightyoarfish** [comment]
They don't inherit from GIPC, but from other classes that have aligned members (such as plain icp), depending on the scalar template type.

**Comment by themightyoarfish** [comment]
I've removed the change to the `mahalanobis_` type, but in my opinion this will always raise questions to every reader that comes across the inconsistency.

**Comment by mvieth** [comment]
Closing and reopening to rerun checks ...

**Comment by mvieth** [comment]
> They don't inherit from gicp, but from other classes that have aligned members (such as plain icp), depending on the scalar template type.

I still don't fully understand what you mean. Yes, icp_nl and joint_icp inherit from icp, but icp itself doesn't have the aligned-operator-new macro and doesn't seem to have fixed-size vectorizable objects?

**Comment by themightyoarfish** [comment]
ICP inherits from `Registration`, which has both of those. Assuming it's transitive, all child classes would need to have it. I find it hard to believe that this is necessary, if it weren't for an experiment I made some time back where I tested this (with my own code, not PCL). Unfortunately, you never know if it's your code change or just randomness when alignment problems go away after a change.

**Comment by mvieth** [comment]
> ICP inherits from `Registration`, which has both of those. Assuming it's transitive, all child classes would need to have it. I find it hard to believe that this is necessary, if it weren't for an experiment I made some time back where I tested this (with my own code, not PCL). Unfortunately, you never know if it's your code change or just randomness when alignment problems go away after a change.

To be honest, I would rather not make a change based on the guess that adding the macro _might_ have fixed a problem in a similar situation. I don't recall anyone having alignment problems in subclasses of `Registration`. And I also can't imagine that a class inherits the need to have the macro because of a fixed-size vectorizable object in a parent class, but does not inherit the macro itself. If you have something reproducible, or at least "close to reproducible", we can see further, but otherwise I would prefer to only add the macro in classes which have a fixed-size vectorizable object themselves (i.e., in gicp.h and incremental_registration.h).

**Comment by themightyoarfish** [comment]
Well I understand that, the issue is that these issues are never reliably reproducible. Nowadays I'm tending towards simply using it by default in any new classes, as I've wasted too many of my days hunting down memory alignment problems.

**Comment by themightyoarfish** [comment]
The question for me, which I haven't found an answer to yet, is how derived classes are actually instantiated by the compiler. If it starts with reserving a chunk of memory that fits all the derived and base class members and then starts instantiating base classes in that chunk, there's no guarantee that base class alignment is respected, unless the derived class overloads its `operator new` accordingly.

**Comment by themightyoarfish** [comment]
I tried to investigate some more, and contrary to my earlier experience, an aligned `operator new()` for a base class does seem to make derived instances aligned as well, as can be tested with the below code by adding or removing the macro from `A`. 

I wondered earlier about the mechanism, but I suppose if derived class does not override `operator new()`, it will just inherit the base class function.

```
#define EIGEN_MAX_ALIGN_BYTES 32
#include <Eigen/Core>
#include <cstdint>
#include <vector>
#include <iostream>

class A {
  /* public: */
  /*   EIGEN_MAKE_ALIGNED_OPERATOR_NEW; */
};

class B : public A {};

bool is_aligned(const std::uintptr_t p) { return !(p % EIGEN_MAX_ALIGN_BYTES); }

int main(int argc, char *argv[]) {
  for (int i = 0; i < 1000000; ++i) {
    auto cp = new B;
    if (!is_aligned(reinterpret_cast<std::uintptr_t>(cp))) {
      std::cout << "Not aligned!" << std::endl;
      exit(1);
    }
  }
  return 0;
}
// clang++ -std=c++14 -o test test.cpp -I include/eigen3/ -DEIGEN_MAX_ALIGN_BYTES=32 && ./test
```

**Comment by themightyoarfish** [comment]
I have rewritten this branch to only add the macro to the two classes with `Matrix4` members.
GICP shouldn't need it, as it's inherited from `Registration`, but I believe it provides clarity to the reader, since it has another `Matrix4` member that would required the macro, if `Registration` did not already have it.

**Review by mvieth — APPROVED** [review]
Thank you for investigating!
So to summarise: GICP needs the macro because of the `base_transformation_` member, and `IncrementalRegistration` needs the macro because of the `delta_transform_` and `abs_transform_` members.

**Pull request merged**
