### PR TITLE
Revert "Fixes issue #1414"

### PR DESCRIPTION
**Pull request by SergioRAgostinho**
Mac compilation is failing on clang because of the removal of the darwin check. 

@taketwo  Please merge with urgency because ALL mac user will be prevented from compiling the nightly build. I should have just removed the line with the -Wl. Having an empty conditional branch feels weird.

### CODE REVIEW

**Comment by aledalgrande** [comment]
Install of HEAD version from Homebrew is failing because of this I think. +1

**Comment by taketwo** [comment]
Oops, indeed we changed the logic of the `if/else` statements. But why reverting instead of applying a proper fix which addresses the original problem as well? Basically we need to modify the final `else()` clause to be applied if compiler is not _clang_.

```cmake
if(WIN32 AND MSVC)
    # ...
elseif(...)
    # ... other special cases
elseif(NOT CMAKE_CXX_COMPILER_ID STREQUAL "Clang")
  set_target_properties(${_name} PROPERTIES LINK_FLAGS -Wl,--as-needed)
endif()
```

**Comment by jspricke** [comment]
@taketwo I don't like adding inverted checks (i.e., all except one compiler), because we are not sure if it will actually work for all others and if not the check will be a mess. So I really like the solution of having different cases for different systems.

@SergioRAgostinho whats the exact error you get? Are the cmake defaults wrong or do we break them somewhere?

**Comment by SergioRAgostinho** [comment]
@taketwo I "panicked" once I realised I had broken HEAD for Mac. The revert was to have a quick fix while we discussed a proper way to solve it. 

@jspricke The error is that ld does not recognize the "--as-needed" option and that errors out preventing you from linking any target. We cannot pass "--as-needed" to (apple-)ld, regardless if the compiler is clang or gcc. Only (gnu-)ld supports it. 

Sorry for this.

**Comment by jspricke** [comment]
So it's the final `else` we should remove! Also I would propose to remove all of those `set_target_properties` and set `CMAKE_SHARED_LINKER_FLAGS` in the `CMakeLists.txt` instead. I can prepare a pull request later, if no one wants to jump in.

**Comment by taketwo** [comment]
@jspricke +1. I can test on Windows once that's done.

**Comment by SergioRAgostinho** [comment]
@jspricke Please do. I can support for testing on Mac.

I think it's save to close this PR then. My apologies Mac users!

**Pull request closed without merging**
