### PR TITLE
Remove FZ-API

### PR DESCRIPTION
**Pull request by SunBlack**
Solves #2701

### CODE REVIEW

**Comment by taketwo** [comment]
As suggested in https://github.com/PointCloudLibrary/pcl/issues/2701#issuecomment-452367059, let's keep the grabber header around. Remove everything and just put a error pragma with an explanation what happened and perhaps a link to the GitHub issue where we discussed the removal. If somebody is affected indeed, this will be helpful.

**Comment by SunBlack** [comment]
Can you explain, who you want to have implemented this error pragma?

E.g. for io/CMakeLists.txt:
```
if(WITH_FZAPI)
  message(FATAL_ERROR "FZ-API is not anymore supported and removed.").
endif()
```
Or keep most things in CMake and have
following class:

io/include/pcl/io/fotonic_grabber.h:
```
#pragma once

#error FZ-API is not anymore supported and removed.

//file end
```

**Comment by taketwo** [comment]
I meant something similar to your second code snippet. However I'm not sure what you mean by "keep most things in CMake". I think it's fine to remove everything related to FZ from CMake and unconditionally install this header with `#error`.

The problem with the first option is that all our grabbers are `ON` by default. So hypothetical FZAPI user probably did not need to specify `WITH_FZAPI` explicitly.

**Comment by SunBlack** [comment]
I added a commit to add error pragma as discussion based. Commits should squashed before merge.

> The problem with the first option is that all our grabbers are ON by default. So hypothetical FZAPI user probably did not need to specify WITH_FZAPI explicitly.

Can we change default to OFF for this plugin?

@jspricke What do you think about the way error pragma is implemented?

**Comment by taketwo** [comment]
> Can we change default to OFF for this plugin?

I think we should remove it entirely, i.e. including this line: https://github.com/PointCloudLibrary/pcl/blob/a023a4ff41d2b01605d478cb731bbd57e3a59142/CMakeLists.txt#L314

**Comment by jspricke** [comment]
If we remove all the sources, there is no need to add a `#error`, people will find that out themself ;). My proposal was rather to leave the sources in and only add the `#error` so if someone wants to maintain it, he can send a patch fixing bugs in the code and removing the `#error`.

**Comment by taketwo** [comment]
> If we remove all the sources, there is no need to add a `#error`, people will find that out themself ;).

Sure, they will find out themselves that the file is missing. But to understand why they will need to first check their CMake configuration to see if there is a mistake, then check Git history to find the commit that removed it, then find the PR/issue on GitHub with explanation. I think it would be nice if we spare them some time, by providing a pointer.

@SunBlack was eager to wipe out the sources for the following reasons:

> This is like dead code: Mostly you don't care about it. But in case you are refactoring things (like we are currently doing. e.g. by partially replacing boost by std or CMake refactoring), you will always see this code and think short about it, before you see, it is dead code (e.g. if i search for a keyword with a general text search). So you spent even for dead code a bit time.

> In case someone is enabling warning as errors (e.g. before submitting sth.) he needs always to disable everything with FZ-API, because we cannot fix compiler warnings there as long we don't see them. So whoever is still using this will have pain in the ass with this unmaintained code.

So if we are not removing the code, we can as well go through a proper deprecation procedure.

**Comment by SunBlack** [comment]
So compared with current master:
- Remove app/optronic_viewer files
- Add #pragma error to fotonic_grabber.h
?

**Comment by taketwo** [comment]
This is what I would do:
* remove optronic_viewer
* remove CMake options and finder scripts for FZAPI
* remove all source files related to fotonic grabber except to "fotonic_grabber.h" header
  * install this header unconditionally
  * empty the header
  * add error pragma

**Comment by SunBlack** [comment]
New try. Hope this time everything is okay.

**Pull request merged**
