### PR TITLE
Initialize all members in `SupervoxelClustering::VoxelData`

### LINKED ISSUE #3369: Weird compiler warning in segmentation module
I'm compiling with normal flags, GCC 9.1 (Linux) and am looking at the following warning:
```c++
segmentation/include/pcl/segmentation/supervoxel_clustering.h: In member function ‘void pcl::octree::OctreePointCloudAdjacencyContainer<PointInT, DataT>::reset() [with PointInT = pcl::PointXYZRGBA; DataT = pcl::SupervoxelClustering<pcl::PointXYZRGBA>::VoxelData]’:
segmentation/include/pcl/segmentation/supervoxel_clustering.h:134:13: warning: ‘*((void*)&<anonymous> +52)’ is used uninitialized in this function [-Wuninitialized]
  134 |       class VoxelData
      |             ^~~~~~~~~
```

This is a class inside another class, which ideally should not trip up compilers.

### PR DESCRIPTION
**Pull request by kunaltyagi**
Fixes #3369.

### CODE REVIEW

**Comment by taketwo** [comment]
Thanks!

Side note: we have some maintainers scripts to automate release preparation. In particular, we have a script that generates a changelog by putting together titles of merged PRs. Thus to get a sensible changelog, it's better if a PR title either describes the bug that it fixes or generally the topic of the PR. And the cross-reference to the GitHub issue should go to the description.

**Comment by kunaltyagi** [comment]
Got the two points. I'll try and stick by them 🤞

**Comment by taketwo** [comment]
Hm, did you try to compile with this change? It gives `-Wreorder` now.

**Comment by kunaltyagi** [comment]
> Hm, did you try to compile with this change?

I was waiting for the CI. My PC was compiling GCC trunk (because of the weird warning with GCC 9.1)

**Pull request merged**
