### PR TITLE
Reduce code duplication

### PR DESCRIPTION
**Pull request by larshg**

### CODE REVIEW

**Comment by mvieth** [comment]
I am a bit confused (probably because I don't know much about VTK): [the documentation says](https://vtk.org/doc/nightly/html/classvtkCellArray.html#ac4ac40720a7e280ef854d5692be7d763) that `SetNumberOfCells()` has no effect. Or is that only true for the newest version of VTK?

**Comment by larshg** [comment]
Its only left for the previous versions. https://vtk.org/doc/release/7.1/html/classvtkCellArray.html#ac4ac40720a7e280ef854d5692be7d763

VtkCellArray has had some serious refactoring. So we can encapsulate it to only be compiled with versions before 9.0.

Thanks looking into it 😄

**Comment by larshg** [comment]
I'm gonna leave as is. Since the VTK PR #4536 will make it use a new method and in that one I'll encapsulate all the Non-V2 versions and only keep the V2 versions of the respective methods?

**Review by kunaltyagi — APPROVED** [review]
The changeset LGTM. Please feel free to merge as (and when) needed 😄

**Comment by larshg** [comment]
#4262 includes this one - I'll rebase when this get merged.

**Review by mvieth — APPROVED** [review]

**Pull request merged**
