### PR TITLE
loadplyfile may parse the header error

### PR DESCRIPTION
**Pull request by sofu456**
the iostream may be fail state with the last ingore in the end of the file in linux.

### CODE REVIEW

**Comment by taketwo** [comment]
Thanks! Could you please post a short file that causes trouble on `master` and is parsed correctly with your patch?

**Comment by sofu456** [comment]
> Thanks! Could you please post a short file that causes trouble on `master` and is parsed correctly with your patch?


[tmp.ply.txt](https://github.com/PointCloudLibrary/pcl/files/3640516/tmp.ply.txt)

**Comment by taketwo** [comment]
The last line of the file you posted is:

```
509.09079 -291.39304 -1129.5593 212 234 
```

The value of the `blue` field is missing. Therefore the line is not valid. In turn, this invalidates the entire file. The current `master` fails with a "parse error" message. Your patch makes it silently swallow the invalid file. I don't think this is desirable behavior.

Could you perhaps explain your use-case and why you think the PLY reader should behave in the way you proposed?

**Comment by sofu456** [comment]
> The last line of the file you posted is:
> 
> ```
> 509.09079 -291.39304 -1129.5593 212 234 
> ```
> 
> The value of the `blue` field is missing. Therefore the line is not valid. In turn, this invalidates the entire file. The current `master` fails with a "parse error" message. Your patch makes it silently swallow the invalid file. I don't think this is desirable behavior.
> 
> Could you perhaps explain your use-case and why you think the PLY reader should behave in the way you proposed?

maybe this cause this error, but i use the meshlab can open this file. so i think pcl can improve the fault tolerance. corlor or position loss may replace by default

**Comment by sofu456** [comment]
> The last line of the file you posted is:
> 
> ```
> 509.09079 -291.39304 -1129.5593 212 234 
> ```
> 
> The value of the `blue` field is missing. Therefore the line is not valid. In turn, this invalidates the entire file. The current `master` fails with a "parse error" message. Your patch makes it silently swallow the invalid file. I don't think this is desirable behavior.
> 
> Could you perhaps explain your use-case and why you think the PLY reader should behave in the way you proposed?

i just find the istream will cause a fail in the end of the file.and this file is generate by zed depth camera. and another file that do not loss the color in the end of the file . you can check it 

[point_cloud_PLY_18024_1242_24-09-2019-15-15-56.zip](https://github.com/PointCloudLibrary/pcl/files/3655593/point_cloud_PLY_18024_1242_24-09-2019-15-15-56.zip)

**Comment by jasjuang** [comment]
@sofu456 I just checked out your point_cloud_PLY_18024_1242_24-09-2019-15-15-56.zip and it's case 2 of the failure scenario that I filed here https://github.com/PointCloudLibrary/pcl/issues/3487. If you can take a look and show me how to resolve cases 3 and 4 I will greatly appreciate it.

**Pull request closed without merging**
