### PR TITLE
Add compound CMake target for examples, tools, apps.

### LINKED ISSUE #2511: Create high level CMake targets for examples, apps and tools
The idea is to be able to be quickly instantiate building these targets with a single command e.g.:

Building all possible examples taking into consideration all third party dependencies which were met.
```
make examples
```

### PR DESCRIPTION
**Pull request by SergioRAgostinho**
Closes #2511

### CODE REVIEW

**Comment by SergioRAgostinho** [comment]
:+1: Sounds valuable. I'm not exactly using an IDE so it would be nice to get some visual input on how things get organized in the end. Are you using one @SunBlack? If positive, can you post a screenshot on how it looks on your IDE?

I'm have to say I'm not really fond of this particular string `PCL_Compound_Targets` but  I need to have a sense of how things look in the different IDEs before having a good suggestion.

Windows people @UnaNancyOwen @claudiofantacci,  can any of you also post a screenshot of how the PCL project structure looks in VS?

**Comment by SunBlack** [comment]
I don't have all dependencies on my home PC, so I can't create a screenshot of your branch. But it looks like [this](https://dogfeatherdesign.com/wp-content/uploads/2015/11/visual_studio_3.jpg) after this.

I don't like `PCL_Compound_Targets`, too, but I have a better idea now:

```
foreach(target ${PCL_APPS_ALL_TARGETS})
    set_target_properties(target PROPERTIES FOLDER "Apps")
endforeach()
set_target_properties(${SUBSYS_NAME} PROPERTIES FOLDER "Apps")
```
Similar for both other groups.

**Comment by SergioRAgostinho** [comment]
Let me collect all variants here:
- For the Sublime Text 2 (make) generator, it's fine as it is as it imports make targets names
- For VS, seems like the folder names should be all upper case.
- XCode - tbd

**Comment by SunBlack** [comment]
> * For VS, seems like the folder names should be all upper case.

It doesn't matter. I prefer `Examples`, `Apps` and `Tools` as folder name.

The only thing: Custom targets are written in uppercase in CMake by default (`ZERO_CHECK`, `INSTALL`, `ALL_BUILD`), So I would prefer targets `ALL_APPS`, `ALL_TOOLS` and `ALL_EXAMPLES` (even if `make apps` looks better than `make ALL_APPS`), so it is more clear that this is a custom target and no library or executable only target.

**Comment by UnaNancyOwen** [comment]
2018-12-02_23h37_54

**Comment by SunBlack** [comment]
Well I didn't knew there is already an option to enable folder: `USE_PROJECT_FOLDERS`. But it seems there is no folder for e.g. apps.

image

**Comment by SergioRAgostinho** [comment]
I think I'll open a separate PR to beautify things and  restrict this one to just adding the new targets.

**Comment by SergioRAgostinho** [comment]
That was a nasty rebase. :shipit:

**Comment by SergioRAgostinho** [comment]
Seems to be working again. Good for review.

**Comment by taketwo** [comment]
Thanks! Could you please add a brief summary in the PR description, so that clicking on the changelog item will give necessary information to those who are interested?

**Pull request merged**
