### PR TITLE
Convert pcl::int_t to std::int_t

### PR DESCRIPTION
**Pull request by kunaltyagi**
Reduces another dependency on boost satisfied by C++14

### CODE REVIEW

**Comment by taketwo** [comment]
There seem to be a problem with my suggestion, we get warnings of this form:

```
/__w/1/s/common/include/pcl/Vertices.h:19:17: warning: 'using uint32_t = uint32_t' is deprecated: use std::uint32_t instead [-Wdeprecated-declarations]
     std::vector<uint32_t> vertices;
```

Not sure what is the best course of action. Do we want to force people to always use `std::` prefix? If so, we should also use inside the library, right?

**Comment by kunaltyagi** [comment]
>  we should also use inside the library, right

Yes. I'll fix those

**Comment by kunaltyagi** [comment]
Fixing by using the following script (not exactly, modified)
````
for type in uint8_t int8_t .... int_fast16_t; do
  for file in grep "[ <(]$type" * -nrl; do
    # had an issue with capture gp in sed
    sed -i "s/ $type/ std::$type/g" $file
    sed -i "s/<$type/[std::$type/g" $file
    sed -i "s/($type/(std::$type/g" $file
    sed -i 's/std::std::/std::/g' $file
  done
done
````
The change in the last commit will be large. I should have used clang-tidy, but I realized too late.

**Comment by kunaltyagi** [comment]
PTAL. No more deprecation warning regarding `pcl::u*int_.*_t`

**Comment by taketwo** [comment]
Thanks, looks good! One thing on my mind though is the deprecation message. As it stands, we get

```
warning: ‘using uint8_t = uint8_t’ is deprecated: use std::uint8_t instead [-Wdeprecated-declarations]
```

which is confusing. What do you think about deviating from our usual template and stating explicitly instead of what `std::uint8_t` should be used? Something like:

```
warning: ‘using uint8_t = uint8_t’ is deprecated: use std::uint8_t instead of pcl::uint8_t [-Wdeprecated-declarations]
```

**Comment by kunaltyagi** [comment]
Sure. That's a good idea actually. Users who use `using namespace pcl` will see this weird message since the deprecation is in the namespace

**Comment by SunBlack** [comment]
Just to mention: I'm getting now an compile issue since this PR:

```
[ 27%] Building CXX object surface/CMakeFiles/pcl_surface.dir/src/gp3.cpp.o
/media/sf_pcl/gpu/surface/src/internal.h(47): error: qualified name is not allowed

/media/sf_pcl/gpu/surface/src/internal.h(52): error: namespace "std" has no member "uint64_type"

/media/sf_pcl/gpu/surface/src/cuda/device.h(74): error: namespace "std" has no member "uint64_type"

/media/sf_pcl/gpu/surface/src/cuda/convex_hull.cu(69): error: namespace "std" has no member "uint64_type"

/media/sf_pcl/gpu/surface/src/cuda/convex_hull.cu(69): error: class "pcl::device::Static<<error-constant>>" has no member "check"

/media/sf_pcl/gpu/surface/src/cuda/convex_hull.cu(265): error: namespace "std" has no member "uint64_type"

/media/sf_pcl/gpu/surface/src/cuda/convex_hull.cu(317): error: namespace "std" has no member "uint64_type"

/media/sf_pcl/gpu/surface/src/cuda/convex_hull.cu(323): error: namespace "std" has no member "uint64_type"

/media/sf_pcl/gpu/surface/src/cuda/convex_hull.cu(337): error: namespace "std" has no member "uint64_type"

/media/sf_pcl/gpu/surface/src/cuda/convex_hull.cu(349): error: no instance of overloaded function "thrust::sort_by_key" matches the argument list
            argument types are: (thrust::device_ptr<<error-type>>, <error-type>, thrust::device_ptr<int>)

/media/sf_pcl/gpu/surface/src/cuda/convex_hull.cu(362): error: namespace "std" has no member "uint64_type"

/media/sf_pcl/gpu/surface/src/cuda/convex_hull.cu(374): error: namespace "std" has no member "uint64_type"

/media/sf_pcl/gpu/surface/src/cuda/convex_hull.cu(375): error: namespace "std" has no member "uint64_type"

/media/sf_pcl/gpu/surface/src/cuda/convex_hull.cu(591): error: namespace "std" has no member "uint64_type"

/media/sf_pcl/gpu/surface/src/cuda/convex_hull.cu(616): error: namespace "std" has no member "uint64_type"

/media/sf_pcl/gpu/surface/src/cuda/convex_hull.cu(692): error: namespace "std" has no member "uint64_type"

/media/sf_pcl/gpu/surface/src/cuda/convex_hull.cu(734): error: namespace "std" has no member "uint64_type"

/media/sf_pcl/gpu/surface/src/cuda/convex_hull.cu(735): error: namespace "std" has no member "uint64_type"

18 errors detected in the compilation of "/tmp/tmpxft_00005dbe_00000000-15_convex_hull.compute_75.cpp1.ii".
CMake Error at pcl_gpu_surface_generated_convex_hull.cu.o.RelWithDebInfo.cmake:279 (message):
  Error generating file
```

**Comment by kunaltyagi** [comment]
I see. I probably missed the gpu module compilation (along with CI) since I'm using clang not gcc. It might just be a missing header. I'll send a patch ASAP. Sorry

**Comment by SunBlack** [comment]
I'm using clang6 to build the PCL ;-). I have already fixed it locally, just waiting until build is fully completed, to be sure there are no further compile issues.

It seems you didn't used best search & replace pattern, as this doesn't look as valid code^^:
https://github.com/PointCloudLibrary/pcl/blob/72a0c4f04150004b327f6b59258ec8aab6eb6c32/gpu/surface/src/convex_hull.cpp#L77

**Comment by kunaltyagi** [comment]
> didn't used best search & replace pattern

Yeah. I used `uint64_t` since my sed threw up when I tried to incorporate `\b`. I thought I'd catch all compilation issues but apparently not. All the errors are in gpu with `uint64_type` and that further led to them passing through.

> I'm using clang6 to build the PCL ;-). I have already fixed it locally

Oh, thanks a lot. Really sorry. I have clang-9 and gcc-9 and cuda doesn't like that. I switched to cuda-gcc (nvcc + gcc-8) and just started on the compilation issues, but got sidetracked by 
```
/usr/bin/ld: /usr/lib/libboost_regex.so: undefined reference to `std::__cxx11::basic_stringstream<char, std::char_traits<char>, std::allocator<char> >::basic_stringstream()@GLIBCXX_3.4.26'
```

**Comment by SunBlack** [comment]
> Yeah. I used `uint64_t` since my sed threw up when I tried to incorporate `\b`.

Oh you are really using sed? I'm using it on our build server, but I don't really like it. You don't get a hint, that sed e.g. doesn't know `\d`, so I had to use `[0-9]` instead. But perl on command line isn't much better (in case you have multiline regular expressions). Don't want to know how much hours I spend in last time for this both tools for an easy task...

**Pull request merged**
