### PR TITLE
Move functions from pcd_io.hpp to pcd_io.cpp to make compile faster

### PR DESCRIPTION
**Pull request by mvieth**
The header file pcd_io.h is used often (included over 300 times), and pcd_io.h always includes pcd_io.hpp, which is currently 871 lines long. This is a test whether compiling is faster when functions are moved from pcd_io.hpp to pcd_io.cpp (and then only compiled once). I will also try to move `writeASCII` and `writeBinary`

### CODE REVIEW

**Comment by larshg** [comment]
This seems to be difficult to verify on the CI's with varying CPU resources?
Should we do it locally and see if we could get volunteers?

**Comment by mvieth** [comment]
> This seems to be difficult to verify on the CI's with varying CPU resources?
> Should we do it locally and see if we could get volunteers?

I hope that the improvement will be large enough that we can still see it on the CIs, despite the varying resources. But I can also do it locally on my Ubuntu with GCC, maybe also with CLANG. If I see an improvement there, I think we can safely assume that all compilers and systems will benefit from it.

**Comment by larshg** [comment]
I tried these changes, however they doesn't seem to have much impact. And even though I thought my laptop would give somewhat equal results, there is quite a variance to the individual projects build times.

I wonder if the compiler figures out how many places it requires the code and then just "copy" already compiled code, hence they relatively small reduction in compile time.

Runtime without these changes: 26m 21s.
WithoutChanges

Runtime with these changes: 26m 10s.
WithChanges

**Comment by mvieth** [comment]
I also did some tests and got very similar results. When building with these changes, the build time was just a few seconds less than the current master (total build time around 30 minutes). It also does not seem to do much for dependant projects: I tested with the pcd_write tutorial, and there was no significant difference.
So it seems like this PR is a dead end. It does not seem to reduce build time, and I don't see any other benefits from these changes, so I am considering closing this PR. However, I have a new lead: pcl/io/boost.h includes many boost headers, and is itself included by many other files, e.g. file_io.h and pcd_io.hpp. I am currently working on a new PR to improve this.

**Comment by kunaltyagi** [comment]
Close this PR? Or let ir remain for now?

**Comment by mvieth** [comment]
Yes, I am going to close this for now. The changes don't seem to reduce the build time (significantly). They do reduce the line count and unify the versions with and without indices for writeASCII and writeBinary, but there are probably better ways to achieve that.

**Pull request closed without merging**
