### PR TITLE
[TRAVIS] assert() function should be functionnal.

### PR DESCRIPTION
**Pull request by frozar**
Try to enable `assert()` check function to Travis jobs.

### CODE REVIEW

**Comment by taketwo** [comment]
Good idea.

However, this does not seem to have any effect, the Travis test job succeeds without triggering an assertion.

**Comment by taketwo** [comment]
Reason: when CMake puts together the final compiler command, `CMAKE_CXX_FLAGS` come before `CMAKE_CXX_FLAGS_RELWITHDEBINFO`. The latter contains `-DNDEBUG`, which sets non-debug mode again.

Looking at the whole Travis config, it seems a bit misleading to me. We set some flags explicitly using `CMAKE_CXX_FLAGS` variable. But then the build mode is implicitly `RelWithDebInfo`, so corresponding flags are picked up in addition. What if we reuse the already existing "Maintainer" mode for Travis builds, updating its corresponding default flags to what we use on Travis? @SergioRAgostinho

**Comment by frozar** [comment]
I let you manage it.

**Comment by SergioRAgostinho** [comment]
>  What if we reuse the already existing "Maintainer" mode for Travis builds, updating its corresponding default flags to what we use on Travis? @SergioRAgostinho.

I think Maintainer mode will require some additional work before it is functional again, nevertheless it's intended purpose is exactly this. Nevertheless, removing the explicit flags and setting Debug will get your asserts running immediately. I do remember bumping into a Travis bug related to KVM and SSE flags so you might need to disable them entirely.

**Comment by taketwo** [comment]
> removing the explicit flags and setting Debug will get your asserts running immediately

Yes, but in Debug mode we will be compiling without optimization. I think it's better to test in optimized mode to catch bugs resulting from undefined behavior.

So what's the conclusion then?

**Comment by jspricke** [comment]
I vote for Release mode (don't see a reason for RelWithDebInfo) and removing the DNDEBUG

**Comment by SergioRAgostinho** [comment]
> I vote for Release mode (don't see a reason for RelWithDebInfo) and removing the DNDEBUG

You mean just for Travis right? Because NDEBUG must be defined in a normal Release build.

This is how I originally though the different build types were:
- Debug - Flags less strict than Wall Wextra, symbols and assertions
- Maintainer - A (somehow) stricter version of Debug
- Release - Optimized, no symbols, SSE

What about creating a CI build type?

**Comment by taketwo** [comment]
> (don't see a reason for RelWithDebInfo)

Should we also change this in the CMakeLists.txt? I.e. default to Release if user did not specify build type?

> I vote for Release mode and removing the DNDEBUG

Well, when it comes to the actual compiler flags, Release mode is nothing else but `-O3 -NDEBUG`, removing the latter leaves us with only optimization. Setting Release and then manipulating the flags to remove half of the implied flags looks weird.

At the same time, on Travis we currently set `-Wall -Wextra -Wabi -O2` additional flags. What about just changing the Maintainer mode to `-Wall -Wextra -Wabi -O2`?

**Comment by jspricke** [comment]
+1 for adopting the maintainer mode and renaming it.

**Comment by SergioRAgostinho** [comment]
> Should we also change this in the CMakeLists.txt? I.e. default to Release if user did not specify build type?

I would leave it as it is.

> +1 for adopting the maintainer mode and renaming it

That's probably the best to do. I personally don't use Maintainer mode at all.

**Comment by taketwo** [comment]
So, updated list:

- Debug - Flags less strict than Wall Wextra, symbols and assertions
- Release - Optimized, no symbols, SSE
- Maintainer/CI - Optimized, no symbols, all warnings (+extra, +abi), assertions

**Comment by frozar** [comment]
Also in the `.trvais.sh` script, for the different build configuration, the `CMAKE_BUILD_TYPE` variable is never specified. Will you change it or keep it like that? (It this variable is explicitly specified, it's easier to understand what's happen on Travis.)

**Comment by SergioRAgostinho** [comment]
> -  Debug - Flags less strict than Wall Wextra, symbols and assertions
> -  Release - Optimized, no symbols, SSE
> -  Maintainer/CI - Optimized, no symbols, all warnings (+extra, +abi), assertions

We night need to include SSE under Debug as well.

> Will you change it or keep it like that? (It this variable is explicitly specified, it's easier to understand what's happen on Travis.)

We're gonna address it using CMAKE_BUILD_TYPEs, so in theory we will only set that variable and stop setting explicit flags.

**Comment by frozar** [comment]
In fact, the CMAKE_C_FLAGS and CMAKE_CXX_FLAGS were set in the `.travis.sh` because of [this condition](https://github.com/PointCloudLibrary/pcl/blob/master/.travis.sh#L13).

**Comment by SergioRAgostinho** [comment]
I'm closing this since we're gonna adopt an entire new strategy for it. Please reopen if I missed something.

**Pull request closed without merging**
