### PR TITLE
Rename IncrementalICP IncrementalRegistration

### PR DESCRIPTION
**Pull request by jspricke**

### CODE REVIEW

**Comment by jspricke** [comment]
As discussed in #1426

**Comment by taketwo** [comment]
I was wondering if we need two separate classes for "incremental" and "meta" registration. The only difference is whether a full cloud is accumulated or not. This could be controlled just with a switch. What do you think?

**Comment by SergioRAgostinho** [comment]
I'm ok with having separate class entities for incremental and meta registration. 

Nevertheless, what I think it would be actually sexy to have is to use them in "similar" to what it's done in ```NormalEstimation.setSearchMethod()```, but something called ```setRegistrationStrategy()```. Both incremental and meta would derive from a ```RegistrationStrategy``` base class, and any class derived from ```Registration```would have access to it, and further accumulation strategies. 

Ps: I really think the prefix meta gives no clue whatsoever on the matching strategy applied.

**Comment by taketwo** [comment]
> Ps: I really think the prefix meta gives no clue whatsoever on the matching strategy applied.

Exactly. And from what I see the code doing, I would rather call it "incremental".

**Comment by SergioRAgostinho** [comment]
Ignore my last comment, I should've looked before writing. You're right @taketwo, it's too similar to be worth and entire new class. Switch should be more than enough.

**Comment by jspricke** [comment]
We discussed the name over here and it's in use since at least since ten years in various papers.
Regarding putting both in one class, I think it's semantically sufficiently different to have two classes.
If no one objects, I will merge #1426 this evening.

**Comment by SergioRAgostinho** [comment]
:+1:

**Comment by taketwo** [comment]
Leaving aside semantics, the diff between the source code of these classes is very small.

**Comment by taketwo** [comment]
But anyway, I'm fine with having two classes.

**Pull request merged**
