### PR TITLE
Add new gtest path

### PR DESCRIPTION
**Pull request by jspricke**

### CODE REVIEW

**Comment by jspricke** [comment]
needed for at least Debian stretch, as the sources are now in the googletest package. I would propose to  cherry pick it into the RC as well, if you agree.

**Comment by SergioRAgostinho** [comment]
Sure.

Can we merge straight from master, to merge all potential hotfixes into the RC branch, or do are we gonna need to cherry pick every single one?

**Comment by jspricke** [comment]
I've just pushed it ;).

**Comment by taketwo** [comment]
Jochen, you pushed what exactly? From what I can see, there is nothing new on the `rc` branch since I tagged.

**Comment by jspricke** [comment]
oups, pushed to my fork, fixed now. Thanks for the heads up :)

**Pull request merged**
