### PR TITLE
Update required FLANN

### PR DESCRIPTION
**Pull request by larshg**

### CODE REVIEW

**Comment by mvieth** [comment]
Any reason to update this? Requiring the newer version seems to be fine since 1.9.1 was released in 2016 and even Ubuntu 18.04 uses it, just wondering if there is a reason why older versions don't work any more.

**Comment by kunaltyagi** [comment]
Makes sense to update it since we can't test on it anymore, and most people would be able to get required flann on our supported platforms.

**Comment by larshg** [comment]
Alternatively to requiring it, we could add a warning if we detect "unsupported" versions, that we don't test with on CI's. So we remove all requirements from any library, but print a warning if we detect versions out of CI's scopes?

**Comment by kunaltyagi** [comment]
Since we don't know if we accidentally break a behavior(even compile time, eg: with Boost) on non-CI versions, I doubt the effort in making a CMake function to replace find_package(REQUIRED) with find_package(MIN_RECOMMENDED) would be worth it.

**Comment by larshg** [comment]
> Any reason to update this? Requiring the newer version seems to be fine since 1.9.1 was released in 2016 and even Ubuntu 18.04 uses it, just wondering if there is a reason why older versions don't work any more.

I'm also targeting 18.04 with default installed packages as minimum requirements.

**Review by mvieth — APPROVED** [review]

**Review by kunaltyagi — APPROVED** [review]

**Pull request merged**
