### PR TITLE
Fix several WIN32 macro check problem in cuda module.

### PR DESCRIPTION
**Pull request by ShiningPluto**
It is obvious that no one care about the CUDA part of PCL!

### CODE REVIEW

**Comment by SergioRAgostinho** [comment]
@taketwo Based on [this](http://www.boost.org/doc/libs/1_61_0/libs/predef/doc/html/predef/reference/boost_os_operating_system_macros.html#predef.reference.boost_os_operating_system_macros.boost_os_windows) seems true. But looking at our [pcl_macros.h](https://github.com/PointCloudLibrary/pcl/blob/master/common/include/pcl/pcl_macros.h#L278), I see both definitions being used. Should we suggest to change to 
```c++
#if defined WIN32 || defined _WIN32
```

?

**Comment by taketwo** [comment]
Usage of these macros in `pcl_macros.h` is inconsistent, see e.g. lines 172 and 180. Unfortunately, I'm not a Windows user, so can not comment on which one is the preferred.

**Comment by SergioRAgostinho** [comment]
From what I'm seeing [here](http://stackoverflow.com/questions/662084/whats-the-difference-between-the-win32-and-win32-defines-in-c) and [here](http://stackoverflow.com/a/5080453) I'm more convinced that ```_WIN32``` is the standard way of doing it and ```WIN32``` is something that normally also works because 
1. The user included some windows headers which defined it
2. MSVC also appears to add it although it's not exactly a standard

@UnaNancyOwen any relevant comments you might give us on this discussion?

Nevertheless, I have the feeling this should be good to merge.

**Comment by UnaNancyOwen** [comment]
It is correct that @SergioRAgostinho said.
[Microsoft-specific predefined macros | MSDN Library](https://msdn.microsoft.com/en-us/library/b0084kay.aspx#Anchor_2)

```cpp
#include <iostream>

int main()
{
    // Defined as 1 when include header that WIN32 is defined (such as windows.h), or set define WIN32 in preprocessor definition.
    // "WIN32" is user-defined flags.
    std::cout << "WIN32 : ";
#ifdef WIN32
    std::cout << "Defined" << std::endl;
#else
    std::cout << "Undefined" << std::endl;
#endif

    // Defined as 1 when compilation target is 32-bit ARM, 64-bit ARM, x86, or x64.
    // "_WIN32" is compiler-defined flags.
    // That is, _WIN32 is always defined by compiler when using MSVC.
    std::cout << "_WIN32 : ";
#ifdef _WIN32
    std::cout << "Defined" << std::endl;
#else
    std::cout << "Undefined" << std::endl;
#endif

    return 0;
}
```

MSVC output is following.
```
WIN32 : Undefined
_WIN32 : Defined
```

**Comment by SergioRAgostinho** [comment]
Super nice explanation. Thanks @UnaNancyOwen

**Pull request merged**
