### PR TITLE
Remove unnecessary includes [common, io]

### PR DESCRIPTION
**Pull request by SunBlack**
Changes are done by [IncludeToolbox (Trial and Error Include Removal)](https://marketplace.visualstudio.com/items?itemName=Wumpf.IncludeToolbox). It is less aggressiv then [iwyu](https://include-what-you-use.org), so it should not have this much side effects (as it touches only cpp files, because remove includes in header files mostly causes include errors in other header/cpp files).

### CODE REVIEW

**Comment by jasjuang** [comment]
This is awesome. Thanks for showing me the existence of this tool!

**Comment by kunaltyagi** [comment]
Is there a way to automate this? Then the CI can be run instead of as manual cron job

**Comment by taketwo** [comment]
This approach does not fully convince me. As @SunBlack noted, it does not take care of header files. Imagine the following situation:
 * "a.h" includes header "x.h", although `X` is not used there;
 * "a.cpp" also includes header "x.h" and `X` is used there.

The right thing to do is to remove "x.h" include from the header file, but keep it in the implementation file. What will IncludeToolbox do? Remove the include from the implementation file.

If we could assume that the includes in all our header files are in perfect shape, then this would be helpful. Without this assumption, however, we are risking doing the wrong thing.

**Comment by taketwo** [comment]
#3545 supersedes this.

**Pull request closed without merging**
