### PR TITLE
[Benchmarks] Add approximate_voxel_grid and voxel_grid benchmarks

### PR DESCRIPTION
**Pull request by larshg**

### CODE REVIEW

**Review by mvieth — APPROVED** [review]

**Comment by larshg** [comment]
Should we make them selectable which to build, so you dont have to build all benchmarks, when you have to compare only a subset of algorithms?

**Comment by mvieth** [comment]
> Should we make them selectable which to build, so you dont have to build all benchmarks, when you have to compare only a subset of algorithms?

I think when running `cmake --build . -- run_benchmark_features_normal_3d` (for example), only that one benchmark is built. Adding any selection logic is in my opinion overkill right now, since we only have 2 benchmarks currently and I don't expect that we have many more benchmarks very soon. I think if there is ever the point that we want to make them selectable, it should still be fairly easy to do that.

**Comment by larshg** [comment]
> 
> 
> > Should we make them selectable which to build, so you dont have to build all benchmarks, when you have to compare only a subset of algorithms?
> 
> I think when running `cmake --build . -- run_benchmark_features_normal_3d` (for example), only that one benchmark is built. Adding any selection logic is in my opinion overkill right now, since we only have 2 benchmarks currently and I don't expect that we have many more benchmarks very soon. I think if there is ever the point that we want to make them selectable, it should still be fairly easy to do that.

This is true. In VS its a bit different, but one can select the single project that one wants to build/run and just run that one. So lets just keep it like this. However, often its best to be foresigted and implement things the right way from the start 😄

I do believe there are some more benchmarks that would be nice to have, like Passthrough/cropbox vs a Functer filter version, Octree vs GPU octree (how large does the cloud / queries have to be before it makes sense to switch), Euclidian clustering vs GPU Euclidian clustering - just to name some of the comparison I would like to see.

**Comment by kunaltyagi** [comment]
> Passthrough/cropbox vs a Functer filter version

Code is present in the issue, just need to make a PR of that. #4247

**Review by kunaltyagi — APPROVED** [review]

**Pull request merged**
