### PR TITLE
Fixes incorrect return value of pcl converter

### LINKED ISSUE #1851: Converter exits with -1 but exit code 0 expected, because conversion works without error
:warning: This is a issue tracker, please use our mailing list for questions: www.pcl-users.org. :warning: 

## Your Environment

PCL 1.8.0

## Expected Behavior
Expected that the converter ends with exit code 0, but instead exits with -1

## Current Behavior
converter exits with -1 in case of successfull conversion

## Possible Solution
line 273 if condition wrong, has to be negiated
see https://github.com/PointCloudLibrary/pcl/blob/master/io/tools/converter.cpp#L273

## Code to Reproduce
convert a ply to a binary pcd without faces

## Context
converting a ply to a binary pcd without faces

### PR DESCRIPTION
**Pull request by SergioRAgostinho**
Fixes #1851. Credits to @pclbel .

### CODE REVIEW

**Comment by taketwo** [comment]
BTW any idea why your topic branch ended up in the main PCL repo?

**Comment by SergioRAgostinho** [comment]
I edited the file on GitHub and submitted the PR on the spot. I though the process was exactly the same...

**Comment by SergioRAgostinho** [comment]
I'm confused... What exactly is the "topic branch"?

I did manually add topics "pcl, computer-visio, etc..." to the repo, but I thought that's a github specific search related functionality. This commit is innocent.

**Comment by SergioRAgostinho** [comment]
I understand what you mean now! I made the edit on pcl's GitHub page, instead than doing on mine... Apologies. I'll delete it right away.

I got confused with the word "topic".

**Comment by taketwo** [comment]
Sorry didn't mean to confuse you :)

**Pull request merged**
