### PR TITLE
Fixed MSVC openmp compatibility

### PR DESCRIPTION
**Pull request by mdering**
By changing this array to a vector, i introduced a bug in all versions of OpenMP, since private variables are not copied. I changed this to firstprivate. This fixes the issue, as well as finally providing this with MSVC compatibility.

### CODE REVIEW

**Comment by jspricke** [comment]
Hi mdering, I'm not sure I get what this is about. Can you give some more insights? Thanks!

**Comment by mdering** [comment]
Yeah, I did a terrible job here :) In a [previous pull request](https://github.com/PointCloudLibrary/pcl/pull/1222) I made a change to hopefully alleviate problems with MSVC and openMP 2.0 which is the latest version it supports, but in doing so I broke the openMP functionality altogether. This new pull request fixes it.

**Comment by jspricke** [comment]
I guess you mean #1214 ;). Still, `size()` should be unsigned, so I'm I get your patch.

**Comment by mdering** [comment]
crap, I think i've crossed some wires, I'm going to close this and re-submit because these are the wrong changes (although these changes are needed by MSVC as well, I want to put more thought into it)

**Comment by jspricke** [comment]
No need to close, just force push your changes into the branch ;). Also, I would suggest to use feature branches.

**Pull request closed without merging**
