### PR TITLE
[registration] reactivate registration visualizer in icp

### PR DESCRIPTION
**Pull request by keineahnung2345**
Please check commit message for details.

### CODE REVIEW

**Comment by mvieth** [comment]
Do you think it would make sense to add a destructor to the RegistrationVisualizer which calls stopDisplay? (Assuming it is safe to call stopDisplay twice)

**Comment by keineahnung2345** [comment]
Then just rename `stopDisplay` to `~RegistrationVisualizer`? Otherwise the two functions would have the same effect.

**Comment by mvieth** [comment]
> Then just rename `stopDisplay` to `~RegistrationVisualizer`? Otherwise the two functions would have the same effect.

We can't simply remove (rename) `stopDisplay` because we want to keep the API stable. Adding a destructor which calls `stopDisplay` would be for convenience, and to avoid errors if a user forgets to call `stopDisplay`

**Comment by keineahnung2345** [comment]
I've pushed the commit. Also tested that whether `stopDisplay` is called explicitly, the program will always return 0.

**Comment by keineahnung2345** [comment]
@mvieth Also doing one iteration everytime after user presses space would be good, like `viewer.registerKeyboardCallback(&keyboardEventOccurred, (void*)NULL);` in https://github.com/PointCloudLibrary/pcl/issues/5180, but in that case viewer and icp should be in the same thread, any ideas?

**Review by mvieth — DISMISSED** [review]
Looks good, thank you!

**Comment by keineahnung2345** [comment]
Sorry, find a bug: in my revision, `update_visualizer_` will be called in `registerVisualizationCallback`, so `first_update_flag_ = false;` should be run before `registration.registerVisualizationCallback (this->update_visualizer_);`.

**Review by mvieth — APPROVED** [review]

**Pull request merged**
