### PR TITLE
Enable C++ 14 flags

### PR DESCRIPTION
**Pull request by SergioRAgostinho**
This pull request enables C++14 flag for the library, effectively making a C++14 supporting compiler an official requirement. If desired, the user may request to build the library with even newer standard by passing e.g. `-DCMAKE_CXX_STANDARD=17` option to CMake.

Note that the flag is not exported to `PCLConfig.cmake`. This means that downstream projects linking against PCL have to **explicitly set the flag**. This is done to support e.g. using PCL built with C++14 together with downstream projects built with C++17.

### CODE REVIEW

**Comment by taketwo** [comment]
We had one more item on the "switching on c++14" list:
 * Add a #error in one of main headers to check if 14 is activated, this is to solve the last item mentioned here: https://github.com/PointCloudLibrary/pcl/pull/2382#issuecomment-407353426

It turned out this may be problematic on MSVC: https://github.com/PointCloudLibrary/pcl/pull/2382#issuecomment-437152538. However, I think it will still be helpful if we have such thing working for at least Ubuntu/macOS.

**Comment by taketwo** [comment]
Thanks Sérgio. I have updated the PR summary to describe what's going on in more detail.

**Comment by SunBlack** [comment]
Maybe we should force VS 2015 as minimum requirement - depends on which C++ [features](https://github.com/MicrosoftDocs/cpp-docs/blob/master/docs/visual-cpp-language-conformance.md) you want to use.

**Comment by taketwo** [comment]
Aren't we implicitly forcing this by setting `CMAKE_CXX_STANDARD_REQUIRED` to `ON`?

**Comment by SunBlack** [comment]
Never tried if this checks works, but we have implemented this just in root CMakeLists of PCL and not in PCLConfig.cmake. For installed PCL, check in `pcl_config.h.in` was introduced - but MSVC version check is excluded there. We could check for `_MSC_VER < 1900` (see [here](https://en.wikipedia.org/wiki/Microsoft_Visual_C%2B%2B#Internal_version_numbering)), but with this check we don't know if it is 15.3 and below or higher (this check would be nice for e.g. #2694). But better than nothing.

**Comment by taketwo** [comment]
I see your point. I don't really have an opinion here though, I'm not a Windows user. Maybe we wait some time and see how many people show up and file issues. If there are only few, perhaps we don't need this check.

**Comment by jasjuang** [comment]
I am a bit late to the party. In order to not having downstream projects linking against PCL having to explicitly set the c++14 flag, it's a better idea to use something like

```
target_compile_features(${PROJECT_NAME} PUBLIC cxx_std_14)
```

so when the downstream target link against pcl targets the c++14 flags will be propagated along with it.

**Comment by SergioRAgostinho** [comment]
So the idea would be declare that in PCLConfig.cmake somewhere around here
https://github.com/PointCloudLibrary/pcl/blob/master/PCLConfig.cmake.in#L588-L627
when we declare the imported targets.

**Comment by jasjuang** [comment]
Manually setting it in `PCLConfig.cmake` will work too.

**Pull request merged**
